### ISSUE TITLE
Try: Smoother block selection transitions

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1000]
Note: This issue is a placeholder for future exploration.

## Problem

Currently, changing focus between blocks is very abrupt. There are no transitions, other than immediate snapping.

## Proposal

Let’s try to experiment with ways that enable smooth transitions (dimensions, fading of borders, etc) so the experience feels more fluid.

Just to explore a bit, I spent some time this week playing around in codepen, and put together this quick prototype: https://codepen.io/iamthomasbishop/full/byRJKp

**Comment by SiobhyB** [comment]
Closing as block selection was iterated on since this issue's creation, and is no longer as abrupt as it once was. As this issue is almost 5 years old, any further improvements would likely be best driven via newer issues.
