### ISSUE TITLE
[Android] Crash on undo on v1.5.0

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1001]
Steps to reproduce:

1. Run the demo app
2. Put the caret at the end of the "Hello world" paragraph block
3. Type in one character
4. Tap on "undo"
5. 💥  with:
```
Error while updating property 'text' of a view managed by: RCTAztecView

null

setSpan (13 ... 13) ends beyond length 12
```

**Comment by koke** [comment]
Is this ready to close?

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/1002
