### ISSUE TITLE
[Android] Video block - There is a split second before the placeholder/uploading state shows

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1005]
This issue is opened to track the issue on comment: https://github.com/wordpress-mobile/gutenberg-mobile/pull/979#issuecomment-493500639

Quote:

`there is a split second before the placeholder/uploading state shows, where the inner block collapses. Can we make sure the placeholder shows immediately, so there isn't a jump`

**Comment by SergioEstevao** [comment]
I tested this on the current version for Android (1.29) and I no longer see this "jump" so I'm closing this one.
