### ISSUE TITLE
Do we need to pass className or wrapperClassName?

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#102]
Relevant to https://github.com/WordPress/gutenberg/pull/8774#discussion_r209172486 and https://github.com/WordPress/gutenberg/pull/8774#discussion_r209172883.

Even though [a commit removed](https://github.com/WordPress/gutenberg/pull/8774#discussion_r209172883) the passing down of those, we should revisit, probably when we start applying proper styling to the components.

**Comment by SergioEstevao** [comment]
I think that with the work being done for [implementing global styles in RN](https://github.com/WordPress/gutenberg/pull/21637#event-3255155543) this issue is being addressed
