### ISSUE TITLE
Backspace does not outdent nested list item on android

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#1027]
**Description:**
Pressing backspace when the caret is at the beginning of a nested list item does not "outdent" the list item. Rather, it merges the list item to the preceding list item.

**Steps to reproduce:**
1. Create a nested list
2. Place caret at the start of an indented list item
3. Press [Backspace]

**Expected behavior:**
The indented list item should outdent one level with each press of [Backspace], and only merge with the preceding item after it is fully outdented.

**Screencast:**
<img src="https://user-images.githubusercontent.com/8507675/58224339-b647c500-7d60-11e9-9d07-2cbc5b20c2a0.gif" width="360">

**Actual behavior:**
The indented list item immediately merges with the preceding list item.

**Screencast:**
<img src="https://user-images.githubusercontent.com/8507675/58224962-2a836800-7d63-11e9-925e-9c9d748db3ff.gif" width="360">

**Comment by mkevins** [comment]
One approach to implement outdent behavior for Android is to follow [the implementation used for iOS](https://github.com/wordpress-mobile/gutenberg-mobile/pull/991/files#diff-ad68d1bf3bf68556db4be6e6215573adR282) which emits the [Backspace] event to JS, delegating the nested list item behavior to `gutenberg` code.

I began implementing this on Android, however, the changes are non-trivial to implement. On Android, the logic determining whether or not to emit a [Backspace] event to JS is conditioned in several places, across several projects / repositories. [Here is the line that emits the event to JS](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java#L404).

Here are the places which currently condition on this:

When the caret is at the beginning of the block with no selection:
https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java#L393

When the `onBackspace` property is truthy (across the bridge) and the `isTextChangedListenerDisabled` flag is false:
https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java#L105
`onBackspace` property:
https://github.com/WordPress/gutenberg/blob/1a20e15a615ecb344cfb0dd8b614982910240909/packages/block-editor/src/components/rich-text/index.native.js#L859

_and_:

When the content is either [empty](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java#L107), or [equal to the empty html tag for the current block type](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java#L111):

Also, the interface method will not be called from Aztec unless several conditions are met within the `InputFilter`:
https://github.com/wordpress-mobile/AztecEditor-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt#L501

It would be nice to have many (or _all_) of these conditions in one place, however, refactoring to accomplish that may require a good deal of time / care to ensure that the changes do not cause regressions in other areas.

I have pushed some experimental branches to begin the process of exploring what changes would be necessary:

https://github.com/wordpress-mobile/AztecEditor-Android/tree/experimental/fix-backspace-outdent-on-nested-lists
https://github.com/wordpress-mobile/gutenberg-mobile/tree/experimental/fix-backspace-outdent-on-nested-lists

The current state of these branches does fix the outdent issue, however, may result in other regressions. With some effort, there may be a way to refactor the conditions to selectively alter the behavior only for nested lists, and I suspect this should also involve extensive testing to prevent regressions in Aztec. :wave: @daniloercoli  @hypest wdyt?

**Comment by daniloercoli** [comment]
> One approach to implement outdent behavior for Android is to follow the implementation used for iOS which emits the [Backspace] event to JS, delegating the nested list item behavior to gutenberg code.

I've the fear that the current Android behaviour will bite us in the near future, when other blocks will be ported to mobile gb. I think we can migrate much of the GB.mobile logic to the wrapper, and keep here in Aztec only the bare minimum of it.  (Consider that Backspace.key detection is also used in Aztec to remove styles).

I can take a deeper look tomorrow, and assign this issue to me.

**Comment by SergioEstevao** [comment]
@mchowning when you work on Aztec for mentions to support the @ detection you probably can also check if it's possible to send the backspace press on other situations?

**Comment by SiobhyB** [comment]
Confirmed that this was fixed somewhere down the line! 🎉  I tested using a Pixel 6 and the latest version (24.1) and a backspace worked to outdent a nested list item.
