### ISSUE TITLE
[Quote Block] Tapping on the left side of the block moves the caret to another RichText powered block

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#1047]
Tapping on the left side of the block, where is the quote block visual marker, moves the caret to another RichText powered block. 
It usually moves the caret to the top most RichText powered block.

See the video here: https://cloudup.com/ctvkLzIJe-W

**Comment by SergioEstevao** [comment]
Just tested this on iOS and Android and is no longer happening.
