### ISSUE TITLE
Allow linking to existing content within blocks

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#1058]
Gutenberg on WordPress.com allows linking to existing content (posts/pages already created on the site) within blocks.
By tapping the link icon, users are able to search for existing posts or pages and link to them.

<img width="893" alt="Screen Shot 2019-06-02 at 4 15 57 PM" src="https://user-images.githubusercontent.com/15107387/58761896-b9f1fd80-8551-11e9-813d-9ca765c886cc.png">

This is also the case within the classic editor in iOS:
![IMG_1739](https://user-images.githubusercontent.com/15107387/58761929-2f5dce00-8552-11e9-9930-b9157bd09b84.PNG)

However, in Gutenberg mobile, we lack the ability to search for internal content. Instead we only have the ability to paste a URL.

![IMG_1738](https://user-images.githubusercontent.com/15107387/58761931-34228200-8552-11e9-88fb-f6362614858b.PNG)

It would be very helpful to be able to link to existing content. User report in #2057785-z, but had another request earlier today for Android (https://github.com/wordpress-mobile/WordPress-Android/issues/4388)

**Comment by tbradsha** [comment]
Requested in 16570204-hc.

**Comment by maxme** [comment]
Fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/2484
