### ISSUE TITLE
File Block

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#1059]
Add support for File Block.
Calypso's File Block can be seen here: https://en.support.wordpress.com/wordpress-editor/blocks/file-block/

This came up in #2079388-zen where the user requests the ability to upload PDFs on Android. There's also a related issue in Android with nearly 50 comments: https://github.com/wordpress-mobile/WordPress-Android/issues/4842

**Comment by iamthomasbishop** [comment]
Data note for when we figure out where to propose this: the file block is consistently in the top 15 in terms of usage data on WPcom.

**Comment by SergioEstevao** [comment]
@maxme  this could a nice block to add to our supported list.

**Comment by maxme** [comment]
@SergioEstevao porting `core/file` to mobile is in our plans for this year.

**Comment by jd-alexander** [comment]
I will be closing this issue since the File block has been built and shipped.
