### ISSUE TITLE
AndroidX migration

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1062]
Android's support library is phased out and replaced by [AndroidX](https://developer.android.com/jetpack/androidx). The effort to migrate in the main WP app is underway https://github.com/wordpress-mobile/WordPress-Android/issues/9209 and it would be best if gutenberg-mobile migrates soon.

React Native v0.60 is scheduled to add support for AndroidX so, we should try it out and see if there are any blockers to overcome. At the time of writing, [v0.60.0 RC0](https://github.com/facebook/react-native/releases/tag/v0.60.0-rc.0) is out so, we can give it a try.

**Comment by marecar3** [comment]
Done with this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1112
