### ISSUE TITLE
[iOS] Video block has black background when upload is in progress or upload has failed

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#1066]
When a video is in progress or upload has failed, video block has a black background.

It is a regression caused by this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1046

<img width="317" alt="Screen Shot 2019-06-04 at 12 46 41" src="https://user-images.githubusercontent.com/28219092/58915312-b8aa0780-86ee-11e9-9ffd-3b923c0b5a53.png">

<img width="328" alt="Screen Shot 2019-06-04 at 12 47 28" src="https://user-images.githubusercontent.com/28219092/58915313-b8aa0780-86ee-11e9-9bb3-f799e0496a1f.png">

**Comment by pinarol** [comment]
@iamthomasbishop setting the background color of the video somehow can lead to a crash on android. so it was reverted by this PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/1046

Right now we are only setting the background to black on iOS but it causes difference between platforms:

Android (video doesn't have a background color so the container view's color is visible instead):

![Screenshot_1559726002](https://user-images.githubusercontent.com/5032900/58945130-f446df00-878b-11e9-9a65-9572b89238f0.png)

Portrait video:

![Screenshot_1559727413](https://user-images.githubusercontent.com/5032900/58946902-8b616600-878f-11e9-875b-acfd597d6603.png)


iOS (video has black background):

![Simulator Screen Shot - iPhone Xʀ - 2019-06-05 at 12 15 19](https://user-images.githubusercontent.com/5032900/58945149-fc068380-878b-11e9-8b01-1db026082fe7.png)

Portrait video:

![Simulator Screen Shot - iPhone Xʀ - 2019-06-05 at 12 43 15](https://user-images.githubusercontent.com/5032900/58946895-856b8500-878f-11e9-826b-2de350c0b336.png)

Just wanted know if you are OK with this.

Maybe it'd be better to equalize platforms and remove black background from iOS also? wdyt? 

We can play with container view's background color also but it is a reusable view between image/video blocks and I am a bit afraid to bring more side effects at last moment.

**Comment by koke** [comment]
What if we set the background color on the [container view](https://github.com/WordPress/gutenberg/blob/4d5998d7b8558c94c6030d167111c11f92c5b46a/packages/block-library/src/video/edit.native.js#L213)?

**Comment by pinarol** [comment]
@koke I think it is doable but my hesitation was:

> We can play with container view's background color also but it is a reusable view between image/video blocks and I am a bit afraid to bring more side effects at last moment.

(referring to media-upload-progress view)

**Comment by pinarol** [comment]
I might have a safe fix, let me try it out and write here, until then you can ignore my question @iamthomasbishop

**Comment by pinarol** [comment]
Ok I think I am able to solve this without effecting other blocks, l'll get it tested by others also. You can ignore my question @iamthomasbishop for now, sorry for the confusion. We'll have black background for both platforms when the video is loaded. I hope nothing else comes up in the tests.
