### ISSUE TITLE
Caption stops being centered when text styling (bold/italic) is applied

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1070]
Image caption should stay centered even when bold/italic is applied to the text.

Steps to reproduce:
1. Select an image block from the demo content in the demo app
2. Add some text in the caption. Notice that the text is centered as expected.
3. Select all caption text and tap on the "Bold" toolbar button
4. Notice that the text moved to the far left, which is not expected

**Comment by etoledom** [comment]
Related: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1113

**Comment by mkevins** [comment]
> Related: #1113:
> The image caption field on Android is centered when is empty and the user add a new caption, but when switching to html mode and back, the field is not centered anymore.

This also happens on WordPress Android when switching to preview mode and back to visual mode, updating the post, or leaving the post and re-opening it.
