### ISSUE TITLE
[Android] Pressing enter on the title creates a <br> tag

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#1078]
To reproduce:

1. Create a new post
2. Write a title and press enter
3. Write some other content
4. Close the editor

On the post list, you can see a `<br>` at the end of the post title.

![bugreport](https://user-images.githubusercontent.com/8739/58957800-b2289800-87a1-11e9-9ffb-66eec87728fd.gif)

**Comment by daniloercoli** [comment]
I guess it a regression of https://github.com/WordPress/gutenberg/pull/15944 cc @SergioEstevao 

I also noticed that `onReplace` of `post-tile` is being called from [RichText->onSplit](https://github.com/WordPress/gutenberg/blob/aa7b15494c73460fdf17d9c010b651bedca13708/packages/block-editor/src/components/rich-text/index.native.js#L234) with `blocks` = `[ undefined, undefined ]`.

**Comment by SergioEstevao** [comment]
> I guess it a regression of WordPress/gutenberg#15944 cc @SergioEstevao
> I also noticed that onReplace of post-tile is being called from RichText->onSplit with blocks = [ undefined, undefined ].

the parameters shouldn't make any difference because we are only using the calling of the method to intercept the Enter press.

if the PR above was the reason, I suggest we change the approach to have a specific prop called `interceptEnter` in order to avoid this issues, instead of using `onSplit` and `onReplace`.

**Comment by mkevins** [comment]
I tried these steps to reproduce on WP-Android develop (1cbefeb) and actually observed that I was able to add newlines to the title :thinking: .

**Screencast:**
<img src="https://user-images.githubusercontent.com/8507675/59082477-9d313d80-8936-11e9-8437-9633b733217a.gif" width="360">
