### ISSUE TITLE
Regression: Paragraph block is half-visible after split

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#1091]
It seems that there is a regression when `Paragraph block` is split into two blocks, the first paragraph block is half-visible for a second.

The same problem is when two Paragraph blocks get merged, a newly created block is half-visible for a moment.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/28219092/59068173-7a911d00-8881-11e9-9bed-1efb43d00234.gif)

**Comment by hypest** [comment]
Not happening anymore after we have improved the layout delay with https://github.com/wordpress-mobile/gutenberg-mobile/pull/1076.
