### ISSUE TITLE
Pasting content into the title field crashes the app

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#1092]
Steps to reproduce:

1. Copy some text from a web page or an existing post in the app.
1. Open any post or start a new post.
1. Paste the copied content int the post title field.

<strong>Result:</strong> the app crashes every time I try to paste content using "Paste" or "Paste as Plain Text" into the title field. 

<img src="https://user-images.githubusercontent.com/1119271/59072566-49641d00-8880-11e9-804b-a7f710f0bdc6.png" width="270" alt="Screenshot_20190606-172328">
<sup>Tested with WPAndroid alpha-172 (12.6 alpha) on Pixel 3 Android 9 using a self-hosted site running WP 5.2.1 with no active plugins `devoted-dragonfly.jurassic.ninja` and also with a WP.com free site `madefortesting823.wordpress.com`.</sup>

**Comment by marecar3** [comment]
WPAndroid with v1.6.1 has this fix.
PR: https://github.com/WordPress/gutenberg/pull/16037
