### ISSUE TITLE
Paste into Title may result in empty text

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#1099]
Noticed that pasting a simple 1-line text on Android may result in empty title.

Steps to repro:
- Start the demo app
- Tap on the Title block
- Paste some simple text (better 1 line text)
- Notice that the text is not added to the title
Video: https://cloudup.com/cnMErcD-Ese

Tested on current develop `909ddae3b707a569f78286996239461cbf97fa4d` on Android 7.1

**Comment by etoledom** [comment]
Also happens on iOS
