### ISSUE TITLE
[Quote] Tapping return at end of block doesn't create new block

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1104]
Note: I'm running a custom version of WPiOS, built off of develop (iOS 12.4, iPhone Xs Max). I haven't tried a build w/ Quote on Android yet.

## Steps to reproduce

* Select a Quote block with some text
* Go to end of block's contents
* Tap enter

## Expected Behavior

I expect a new block to be created, just like happens on other RichText blocks.

**Comment by SergioEstevao** [comment]
@iamthomasbishop this is not the way GB web work. We will need to open a ticket there if we want to change this behaviour.

**Comment by iamthomasbishop** [comment]
Fair enough. I think it's worth doing, but maybe not urgent. 

Also, maybe this is only at the end of the citation field - if you have a quote but no citation, tapping return should continue to the citation field. Then another return in the citation would create a new block.

**Comment by SergioEstevao** [comment]
Fixed by this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2352
