### ISSUE TITLE
[Block Library/Inserter] Order blocks based on usage stats or content type

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1105]
As we've built out the set of block types that we currently have, we've just added them to the grid. Here's what that currently looks like:

![image](https://user-images.githubusercontent.com/1200432/59135877-49c6eb80-8946-11e9-8cf5-362b66bcd437.jpeg)

The Block Library UI (aka Inserter) itself will need a restructure as soon as we have more than ~12-15 blocks. For now, we should consider organizing them, either by how commonly used they are or by type:

### Order based on the last usage data I've seen

1. Paragraph
2. Image
3. Heading
4. List
5. Video
6. Separator
7. Quote
8. Read More
9. Page Break

### Group them roughly by type (text, media, other)

1. Paragraph
2. Heading
3. List
4. Quote
5. Image
6. Video
7. Separator
8. Read More
9. Page Break

My preference would be to take the second approach (group by content type), but I'm open to other suggestions.

**Comment by hypest** [comment]
I'd personally vote for deterministic versus dynamic ordering, unless is a mild one and not aggressively adapt to the block usage. I'm generally sensitive and confused when things troll :trollface: my muscle memory and make me have to _look_ to find them 😃.

**Comment by iamthomasbishop** [comment]
> I'm generally sensitive and confused when things troll

Totally agree with you on this point – what I meant was we might order based on most commonly used blocks amongst _all users_ – nothing clever 😄

**Comment by iamthomasbishop** [comment]
Another note: I lean towards the second approach above because it would mean less change over time – If we iterate the order of blocks over time as the usage stats change, that'd get annoying to users. Also, considering we might soon want to re-think the library bottom sheet to scale better anyhow, we might want to keep any changes here to the simplest.

**Comment by iamthomasbishop** [comment]
@hypest are we already doing this on the latest Android beta? I just pulled up WPAndroid 12.8 beta and after I add a block on the canvas, that block goes to first in my list on the bottom sheet – it's not this way on WPiOS 12.7 – it's a static list (which as discussed above maybe makes most sense).

**Comment by hypest** [comment]
> @hypest are we already doing this on the latest GB beta? I just pulled up WPAndroid 12.8 beta and after I add a block on the canvas, that block goes to first in my list on the bottom sheet – it's not this way on WPiOS 12.7 – it's a static list (which as discussed above maybe makes most sense).

I think I noticed it too. Probably a web side feature that automagically sees its way to mobile too as we are using more and more of the web side components.

**Comment by iamthomasbishop** [comment]
Ahh, interesting. This mechanism could come in handy if/when we need to show the most common/recent block types in the toolbar, which was part of [this proposal](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1020).

**Comment by hypest** [comment]
Closing this as it's functionality already in place.
