### ISSUE TITLE
Android: List bullet color

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1111]
This is the current state of list style on Android:

![Screenshot_20190610-192928](https://user-images.githubusercontent.com/9772967/59214195-e0014880-8bb6-11e9-882c-edeed04d5bbd.png)

The bullets color should be black matching iOS and web.

cc @iamthomasbishop

**Comment by SiobhyB** [comment]
I verified that the bullet points are now black on Android, so going ahead to close this issue.
