### ISSUE TITLE
Android Image caption is not centered

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1113]
The image caption field on Android is centered when is empty and the user add a new caption, but when switching to html mode and back, the field is not centered anymore.

It is also not centered when loading an Image Block that already has a caption.

![Screenshot_20190611-094652](https://user-images.githubusercontent.com/9772967/59253412-71f86800-8c2e-11e9-9bc8-3ecf7723cd56.png)

**Steps on example app:**

- Add this snippet to the initial html:
```html
<!-- wp:image {"align":"center"} -->
<div class="wp-block-image"><figure class="aligncenter"><img src="https://cldup.com/cXyG__fTLN.jpg" alt="Beautiful landscape"/><figcaption>Give it a try.<br> Press the "wide" button on the image toolbar.</figcaption></figure></div>
<!-- /wp:image -->
```
- Run the example app.
- Check that the image caption field is not centered.

**Comment by mchowning** [comment]
Closing. This was fixed by #1243.
