### ISSUE TITLE
[iOS] Quote block inserts wrong p tags inside cite tags.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1121]
This is an snippet from `gutenberg-mobile` on iOS:
```html
<!-- wp:quote -->
<blockquote class="wp-block-quote">
    <p>Line 1</p>
    <p>Line 2</p>
    <p>Line 3</p>
    <cite>
        <p>Cite line 1</p>
        Cite line 2<br>
        Cite line 3
    </cite>
</blockquote>
<!-- /wp:quote -->
```

This is the same example from gutenberg web:

```html
<!-- wp:quote -->
<blockquote class="wp-block-quote">
    <p>Line 1</p>
    <p>Line 2</p>
    <p>Line 3</p>
    <cite>
        Quote line 1<br>
        Quote line 2<br>
        Quote line 3
    </cite>
</blockquote>
<!-- /wp:quote -->
```

Note that on iOS, the first cite line has `p` tags (`<p>Cite line 1</p>`)

**Comment by hypest** [comment]
Do we know if this causes any side effects? For example, does it produce any invalidation errors, or perhaps marking the post as modified if open&close without user action?

**Comment by etoledom** [comment]
> does it produce any invalidation errors

No invalidation errors 🎉 

> or perhaps marking the post as modified if open&close without user action?

On my tests it doesn't affect this either.
I have seen this behavior happening _sometimes_ but it doesn't seem that Quote block is responsible.

**Comment by SergioEstevao** [comment]
This no longer happens on iOS, so I'm closing this issue.
