### ISSUE TITLE
Toolbar remembers scroll position even if its contents change

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#1132]
To reproduce this:

1. Insert a list
2. Scroll the toolbar to the end so the bold/italic options are visible
3. Press enter twice or focus on a paragraph block
4. The toolbar still has the same offset, even if it has less items inside it

![bugreport](https://user-images.githubusercontent.com/8739/59501737-73c76300-8e9c-11e9-886e-43963260113f.gif)

**Comment by hypest** [comment]
Duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/934 perhaps?

**Comment by koke** [comment]
Yep, looks the same :)
