### ISSUE TITLE
Caret position remains at start after pasting

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1136]
The caret position remains at start after I paste. Happens only on empty blocks. I am not fully aligned with the design decisions there but I'd expect the caret appear at the end instead.

![caretPaste](https://user-images.githubusercontent.com/5032900/59507528-edb71680-8eb3-11e9-8966-7e78390f2a8c.gif)

Detected while testing https://github.com/wordpress-mobile/WordPress-iOS/pull/11885

**Comment by hypest** [comment]
Closing as it seems duplicate of #828 . I will add a pointer to this ticket though and update to reflect that it's an issue on both platforms.
