### ISSUE TITLE
Align init-html content with Gutenberg changes in heading block style

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#1141]
There are some changes in heading block style that were introduced by the latest [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/16035) 

which resulted in a `red screen` in `gutenberg-mobile` demo application.

![error](https://user-images.githubusercontent.com/28219092/59546603-7eb2df80-8efe-11e9-9e5d-489ce62f0486.png)

**Comment by Tug** [comment]
Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/1143
