### ISSUE TITLE
It's too easy to accidentally delete blocks

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1146]
## Problem

Currently, it's too easy to accidentally delete blocks on the canvas, mainly because the `delete` (trash) icon on the inline toolbar is often docked right next to the `hide keyboard` button.

_Note: this is especially a problem on iOS because our "scroll-to" positioning is "smarter" than Android. Most often when a block is focused (unless it's a tall block), it gets nicely docked above the Quick Toolbar._

![image](https://user-images.githubusercontent.com/1200432/59631476-8dbbac80-910d-11e9-9395-5ce1da9b0dd8.jpeg)

## Potential Fixes

A few approaches we could take:

1. Implement the `•••` menu in place of the `remove block` icon (which we were eventually going to) and place the `remove block` option in the subsequent sheet.

2. Force the scroll position to about ~24px higher to limit accidental taps. This would leave some whitespace between the two toolbars.

3. Add a confirmation dialog that shows when removing a block from the canvas.

## Data

To inform the approach we take, it would be useful to see some data on how often the `remove block` button is used.

**Comment by hypest** [comment]
With undo/redo available and in a prominent place, I'd assume that accidental deletion can be annoying but not a substantial problem. For the same reason, adding more steps to the deletion flow feels too cautious.

I don't think we have usage data in place but I'd be inclined to close this ticket as "wontfix" and re-open if we get more user data. WDYT @iamthomasbishop ?

**Comment by iamthomasbishop** [comment]
> adding more steps to the deletion flow feels too cautious.

@hypest Probably right. Either of the first 2 solutions would be preferred, and perhaps even both of them should be considered.

**Comment by mchowning** [comment]
@akirk ran into this exact issue, but for him it was the result of trying to fix a typo that was near the trash can icon.

**Comment by iamthomasbishop** [comment]
@mchowning We're considering changing the `trash` icon to the long-term preferred `•••` along with the work we're tackling w/ the "collapsed" version of the inline toolbar [over here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2180) — we still need to figure out what is going to be housed in that menu, but I think it's safe to say that that solution would probably solve this issue, because you'd be accidentally tapping on the `•••` menu instead of removing a block. // cc @lukewalczak

**Comment by lukewalczak** [comment]
I think we can close that issue since remove option is reachable via ellipsis button in toolbar.
