### ISSUE TITLE
Videos added from media library don't load in the editor

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#1151]
1. Start a new block editor post in the app.
2. Add a video block.
3. Add a video from the site's media library.

Expected: The video will load in the editor with a play button.
Actual: All I see in the editor is a black rectangle.

The video was added to the post as expected (it loads when I view the actual post) but it never shows up in the editor. Videos I uploaded from the device or captured directly while in the editor appeared as expected, so the only issue seems to be with videos added from the media library.

![image](https://user-images.githubusercontent.com/8658164/59705467-52e17380-91f6-11e9-969a-84a09dd0c6b5.png)

Tested on iPhone XS, iOS 12.3.1, WPiOS 12.7.0.20190617

**Comment by pinarol** [comment]
Hey @rachelmcr 👋 

Is that happening every time? This blankness is about video not getting ready to play, as far as I know it was returning to normal after some updates on the post. But I know that it is annoying, so we already did some changes to make this better, for now I can suggest trying it again on the next release.

A bit detail on the issue:

The thing is, we are waiting for that "ready to play" state to show the play button. In the next release we changed this, it'll show the play button no matter what and tapping it will open the full screen player, user will see some loading indications there. Also I think it will re-trigger buffering and fix the preview also. After that we might even need to do some more work to show the loading indication on the thumbnail as well, but it is hard to tell without trying the new version.

**Comment by rachelmcr** [comment]
> Is that happening every time? This blankness is about video not getting ready to play, as far as I know it was returning to normal after some updates on the post.

Yes, it's happening every time with different videos from my media library (including some small test videos that are only about 2 seconds long and 5 MB). I tried waiting, adding more content, saving the post, exiting and reopening the editor ... the videos never load or change.

It sounds like the next release will work better for me, but as it is the video block _looks_ broken inside the editor when I add a video from my media library.

**Comment by pinarol** [comment]
hey @rachelmcr 👋thanks for the extra info. I forgot to ask, is that happening on Atomic sites also? I think you are trying with a Premium site right?

**Comment by rachelmcr** [comment]
I tested again and I see this issue on all WordPress.com Simple sites, regardless of plan. Other sites (WordPress.com Atomic, Jetpack, self-hosted) work as expected.

**Comment by designsimply** [comment]
I tested today with 13.5-rc-1 (apk) on Pixel 3 Android 10 and on 13.5.0.0 beta (TestFlight) on iPhone 6S iOS 13.2 and found that I could see videos load with a play button in the block editor when added from the WordPress Media Library on a WordPress.com Premium site.

<img src="https://user-images.githubusercontent.com/1119271/67516935-c4c34100-f65e-11e9-895e-54ef9513d4e3.png" width="270" alt="Screenshot_20191024-130116"> <img src="https://user-images.githubusercontent.com/1119271/67518640-6b5d1100-f662-11e9-9df9-dd9bd177b89b.PNG" width="270" alt="IMG_3262">
<sup>Tested with WPAndroid 13.4-rc-1 on Pixel 3 Android 10 and WPiOS 13.5.0.0 beta (TestFlight) on iPhone 6S iOS 13.2.</sup>

**Comment by rachelmcr** [comment]
This is still an issue for me on a private WordPress.com Simple site in 13.5.0.20191021, on iPhone XS, iOS 13.1.3:

<img src="https://user-images.githubusercontent.com/8658164/67528386-417f0b00-f6b1-11e9-9869-496d48ad80d4.PNG" width="50%">

Although I do see a play button on the video now, when I tap it the video never loads:

<img src="https://user-images.githubusercontent.com/8658164/67528399-493eaf80-f6b1-11e9-893a-2bca85c80ed0.PNG" width="50%">

But I also tested on a public site, and the video loaded there as expected.

Reopening because this is still an issue in some cases (and I confirmed that it works as expected in a browser on the private site).

**Comment by rezzap** [comment]
I'm replicating this issue on both Android and iOS after a report from a user in Samsung Galaxy Tab A for both Premium plan site and free plan site.

![Screenshot_20200314-080958_WordPress](https://user-images.githubusercontent.com/10325627/76678039-6a565d00-65cc-11ea-924e-15a2e206d769.jpg)

![Image from iOS (2)](https://user-images.githubusercontent.com/10325627/76678265-5b70aa00-65ce-11ea-9c4a-2ddd173a463f.png)


They also reported and it's being replicated that the media library thumbnails for videos show blank. 

![Screenshot_20200314-081025_WordPress](https://user-images.githubusercontent.com/10325627/76678048-88bc5880-65cc-11ea-8579-cc88d6041575.jpg)

Replicated on Samsung Galaxy Tab A SM-T510, Android 9, WP app 14.4-rc-1
iPhone X MQAD2B/A iOS 13.3.1 WordPress app 14.3
User report in 2776496-zen

Also replicating the same behaviour in the published post as reported in #1909 and I'm not sure if this is related or not.

**Comment by ceyhun** [comment]
I was able to reproduce as well using a free .com site.
On Android 14.5, Play Store version. Closing, saving and re-opening the draft didn't change anything.
On iOS 14.6, App Store version. Closing, saving and re-opening the draft fixed it!

**Comment by SiobhyB** [comment]
As of 2024, this is only an issue for private sites, which is captured in https://github.com/wordpress-mobile/gutenberg-mobile/issues/5497. I'll go ahead to close this one.
