### ISSUE TITLE
Quote Block: Undo and Redo consistently don’t work on first line

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#1158]
When pressing the Undo button in the first line of a Quote Block, an extra line is added and it’s no longer possible to press Redo.
However, subsequent lines are able to Undo and Redo without any issues, even though an extra line is added.

See video for a better sense of this:

![quoteblock](https://user-images.githubusercontent.com/15107387/59768544-381e0600-92ad-11e9-880e-6129dbf4ce51.gif)

**To reproduce:**
1. Start a new post
2. Add a Quote Block
3. Type a line, then undo. Note that you cannot redo.
4. Type a line, then another line. Note that you can undo and redo.
5. Now undo again, removing the first line, and not that you can no longer redo.

The extra line being added is referenced here:
https://github.com/wordpress-mobile/gutenberg-mobile/pull/1129#issuecomment-502210091

I tested this on iOS but it’s also mentioned for Android here: https://wp.me/p5T066-Tx

Tested on iPhone SE, (iOS 12.2) running WPiOS 12.7

**Comment by SergioEstevao** [comment]
This is solved on develop and it will be deployed on version 1.8.0

**Comment by hypest** [comment]
Verified not happening on v1.8 of the block editor. Closing.
