### ISSUE TITLE
Links: Undo doesn’t work for links that open in a new tab.

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#1160]
**Expected:**
After adding any link, tapping “Undo” would undo the addition of the link.

**Actual:**
After adding a link which is set to “open in a new tap”, the Undo button does nothing and Redo button is greyed out.

Works in Paragraph, Header, List, Quote blocks.

**To reproduce:**
1. Create a new post
2. Add a paragraph block, type some text.
3. Add a link and set it to “Open in a new tab”.
4. Tap Undo and find it does nothing.

**Video:**
![quoteblocklink](https://user-images.githubusercontent.com/15107387/59776038-cf3d8a80-92ba-11e9-8895-71b5a546d868.gif)

**Tested on iPhone SE, (iOS 12.2) running WPiOS 12.7**

**Comment by hypest** [comment]
This seems related to #1161, especially if that one is about state not being set correctly.

**Comment by designsimply** [comment]
Closed https://github.com/wordpress-mobile/gutenberg-mobile/issues/2495 as a duplicate and adding some additional notes from that issue. /hat tip @mchowning 

> Observe that no matter how many times you slowly tap the undo button, the link remains. If you tap the undo button a bunch of times very quickly, however, it is possible to remove the link.

> Additional context
> I wonder if there might be some connection between this and #2091

**Comment by SiobhyB** [comment]
Tested and confirmed undo now works as expected in this scenario, I believe it was fixed as part of https://github.com/WordPress/gutenberg/pull/50460.
