### ISSUE TITLE
Refine "Add new block" indicator style

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1166]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/1200432/59795972-1cf9c900-92a2-11e9-97d9-8fc662deec10.png">

Requested Changes:

* Text color: `$gray`
* Font-family: system `sans-serif`
* Font-size: `14px`
* Text-transform: `uppercase`

**Comment by ceyhun** [comment]
Current
-- 
<img width="584" alt="current" src="https://user-images.githubusercontent.com/1845482/76550116-e304ce80-6491-11ea-85f1-e9c94e5cbaa6.png">


Proposed
--
Light
<img width="584" alt="14-gray-margin-no-bold" src="https://user-images.githubusercontent.com/1845482/76550115-e26c3800-6491-11ea-8cde-def87907f9b2.png">
Dark
<img width="584" alt="14-gray-margin-no-bold-dark-mode" src="https://user-images.githubusercontent.com/1845482/76550112-e0a27480-6491-11ea-9190-0f7962f5c671.png">

```scss
font-size: 14px;
color: $gray; // dark mode: $gray-20
margin: 0 8px; // left and right
```

@iamthomasbishop I made the changes with these variable and it looks like this now. What do you think?

**Comment by iamthomasbishop** [comment]
Looks great!
