### ISSUE TITLE
Video Block doesn't continue upload after losing and restoring network connection

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/gutenberg-mobile#1173]
This specifically happens if the user tries to save a draft offline while the post contains a video block on iOS. This also leads to some data loss if there's other content in the post. 

Steps to reproduce
1. Create a post with some content
2. Add a video block and try to add a video
3. before the upload completes switch to Airplane mode
4. Try to save the post as a draft

At this point you should see a white space where the video block should be

![IMG_0046](https://user-images.githubusercontent.com/6520461/60063917-45c7f700-96c4-11e9-89ce-3ef2fd9e8dba.PNG)

5. Turn off airplane mode and connect to the network 
6. Try to save the post as a draft

At this point, you should see something like this,

![IMG_0047](https://user-images.githubusercontent.com/6520461/60063930-5b3d2100-96c4-11e9-838f-97d91cb47a01.PNG) with the HTML matching up with this

Both these screenshots are from the same post, and the content shown in the first one was replaced with older content in the post the save completed. 

The preview shows something completely different,

![IMG_0050](https://user-images.githubusercontent.com/6520461/60064068-d9012c80-96c4-11e9-81e0-3725f2528d14.PNG)

and on the web it lines up with the preview

![Screen Shot 2019-06-24 at 9 14 21 PM](https://user-images.githubusercontent.com/6520461/60064136-15cd2380-96c5-11e9-8928-e0ea6cfe3eed.png)

The video also wasn't uploaded properly and does not play on web or mobile.

**Comment by pinarol** [comment]
hey @JavonDavis 👋  Could you also switch to the html mode and add the html output here? That'll be some useful info when debugging.

**Comment by JavonDavis** [comment]
> with the HTML matching up with this

@pinarol I had mentioned it here but luckily I did take a screenshot too 😄 

![IMG_0051](https://user-images.githubusercontent.com/6520461/60101168-e2b87d80-9720-11e9-9058-b10126395971.PNG)
