### ISSUE TITLE
Track unsupported blocks from the apps

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1174]
We have some data on how many published blocks there are of each type on WordPress.com, which is a nice proxy, but it’d be better to know exactly what are users encountering as unsupported in the apps

**Comment by hypest** [comment]
As far as I understand, #1199 enables sending the list of unsupported blocks found but, the WP client apps don't yet log that list somewhere, right?

If so, let's reopen the ticket to work in another iteration and probably send the list to Tracks. Alternatively let's open a new ticket to track that effort.

**Comment by daniloercoli** [comment]
In https://github.com/wordpress-mobile/gutenberg-mobile/pull/1199 we've added the ability to GB to report the list of unsupported blocks found in the currently loaded post.

We need to process (maybe count instances of each unsupported block) and send the info up to Tracks. We need to brainstorm a way on how to bump this info in Tracks to be easily query-able in funnels.

**Comment by daniloercoli** [comment]
Android implementation just merged https://github.com/wordpress-mobile/WordPress-Android/pull/10237.

iOS merged days ago https://github.com/wordpress-mobile/WordPress-iOS/pull/12150
