### ISSUE TITLE
[Try] Improve editor loading experience

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1179]
## Problem

Sometimes the editor can take some time to load, and when the content is loaded, it enters pretty jarringly. This is especially strong on iOS when posts have a lot of content.

## Context

At the moment, on Android we're showing a spinner, like so:

![image](https://user-images.githubusercontent.com/1200432/60137843-d9093700-976d-11e9-973c-572a8ab55ac1.png)

...whereas on iOS, we're showing nothing.

![IMG_4018](https://user-images.githubusercontent.com/1200432/60138011-69e01280-976e-11e9-8edd-da9f7008e82f.png)

This is especially jarring on iOS with long posts.

## Proposal

Let's improve the experience of a post as it's loading by either:

* Showing a progress spinner or similar on iOS – like we do on Android. This at least tells me something is in progress.

* Even better, we could show skeleton elements in place of the title and body. That would look something like this:

<img width="2079" alt="image" src="https://user-images.githubusercontent.com/1200432/60138157-eb37a500-976e-11e9-818f-af6d7b451a78.png">

If we were to take a skeleton-loader approach, we should reference other places in the apps that follow this pattern, and ensure we are able to show this elegantly, to limit flashes of content.

**Comment by etoledom** [comment]
@iamthomasbishop - I've been playing a bit with this today and this is what I could come with:

![ghost](https://user-images.githubusercontent.com/9772967/84180392-ba3ba780-aa87-11ea-8ed2-2d751f0c2847.gif)


It's the same effect used on the other parts of the app. On iPad it uses readable content layout so it's centred too.

I'm planning a PR soon after cleaning up the code. Please let me know if it's good enough or you would like some changes in advance.

**Comment by iamthomasbishop** [comment]
@etoledom Wow, that’s awesome! The title/content looks and feels _really_ nice. Is it possible to also add a “fake” block toolbar with some skeleton buttons? If so, I can provide an updated design that more appropriately matches the current block toolbar.

**Comment by etoledom** [comment]
> Is it possible to also add a “fake” block toolbar with some skeleton buttons?

It's difficult to imagine it, but as a wild guess I'd say could get quite complicated.
