### ISSUE TITLE
[iOS] Quick photo post - App crashes when adding a photo from device picker

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#1190]
Test case:
1. In the iOS hold finger on WPiOS app icon
2. Choose: New Photo Post
3. Image device picker will show up
4. Choose an image from the picker 

![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/28219092/60618154-6f0f1400-9da3-11e9-88c9-287bb6899662.gif)

Error screen:
![Image from iOS](https://user-images.githubusercontent.com/28219092/60618175-7fbf8a00-9da3-11e9-9a51-68e1bd0a0b76.jpg)

Result: App crashes

**Comment by hypest** [comment]
Is this related to #860 ?

**Comment by etoledom** [comment]
@hypest - They are different issues.

What is referred on #860 is sharing from another app.
This ticket is about the 3D Touch short-cut from the Home Screen.
