### ISSUE TITLE
Unwanted scroll back to selected block

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1192]
### Description
On Android, if you select a block and then quickly scroll away from that block, I am seeing the scroll position reset back to the selected block after a short delay. On the demo app, this appears to happen on any fling, even if the selected block is not changed (i.e., you can do it over and over again by repeatedly flinging, as shown in the gif of the demo app). I did not observe this issue when testing on iOS.

FWIW, I observed slightly different behavior between the WPAndroid and Gutenberg demo apps. Both are discussed below.

#### Steps To Reproduce
1. Create a post with more content than will fit on the screen.
2. Add a block to the bottom of the post (I use a list block in the gif below)
3. Select a block **other than** the block at the bottom of the post
4. In quick succession:
    a. Select the list block at the bottom of the post; and
    b. Scroll the post up so that the list block goes off the bottom of the screen.
5. Observe that the list will scroll back to the selected list block.

This gif shows the behavior with a VanillaDebug build from the WPAndroid develop branch (65eb044257):

![scroll-reset_without-metro mp4](https://user-images.githubusercontent.com/4656348/60626128-c7501100-9db7-11e9-9441-3f7e5843d2a1.gif)

### Gutenberg Demo app

The behavior is substantially worse on the demo app (29b1e147) though since it seems to reset the scroll over and over again. This might be due to the larger post sample in the demo app or maybe the bundler being attached (debugger was _not_ attached).

#### Steps to Reproduce

1. Create a post with more content than will fit on the screen.
2. Add a block to the bottom of the post (I use a list block in the gif below)
3 . Select the block at the bottom of the post
4. Wait a bit if you feel like it
5. Fling scroll to (or close to) the top of the post (note that in the gif, the third time I flung I did not fling all the way to the top of the post)
6. Observe that the list will scroll back to the selected list block.
7. Once the scroll back to the selected block completes, go back to Step 5 and repeat.

![device-2019-07-03-175144 mp4](https://user-images.githubusercontent.com/4656348/60627196-53176c80-9dbb-11e9-92bc-b7c853465704.gif)

**Comment by geriux** [comment]
This was fixed in https://github.com/WordPress/gutenberg/pull/59833
