### ISSUE TITLE
[iOS]: Video block won't refresh UI after finishing uploading

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1204]
The video block UI won't show completion if while uploading, the user loose connection, try to save as draft, get back the network connection.

Following these steps to reproduce this issue:

- On WPiOS, create a new Post
- Add a video block
- Add a video from camera roll
- While is uploading, turn off networking to make the upload fail
- When the retry UI is visible, Save as Draft from the contextual menu (...)
- Restore networking and wait until the upload is completed
- You will see a toast message saying `Post draft uploaded`
- The video block UI won't refresh to show the uploaded video

![video](https://user-images.githubusercontent.com/9772967/60784946-64f96680-a151-11e9-865f-695f709ba8bf.png)

**Comment by hypest** [comment]
Not sure if you're actively working on this one @etoledom , if so, better to move the ticket to the "In Progress" column in the project board, otherwise let's un-assign the ticket. Thanks!

**Comment by etoledom** [comment]
After some investigation, It seems like this issue is a side-effect of https://github.com/wordpress-mobile/WordPress-iOS/issues/12282 .

**Comment by hypest** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/issues/12282 looks fixed now so, I'm wondering if this issue is still valid. Can you check @etoledom ?
