### ISSUE TITLE
Allow Selecting Text Color in Blocks with Text

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#1212]
Users have asked for the ability to change the color of text on posts and pages for a long time. Not just "all text on the page", which can be set at the theme level - they want to make _one phrase red_ or emphasize certain words in a text.

Gutenberg core is considering allowing this in text blocks:
https://github.com/WordPress/gutenberg/issues/15899

And we should too.

Here are a few places this has come up before:
https://wp.me/p4a5px-1Uf
https://wp.me/p77Llu-5Sn
https://github.com/wordpress-mobile/AztecEditor-Android/issues/819
https://github.com/wordpress-mobile/WordPress-iOS/issues/12074#issuecomment-509319825

**Comment by rachelmcr** [comment]
Another user asked about how to change the text color in 2290521-zen.

**Comment by designsimply** [comment]
This came up in an app review: 

> Why I can't change text's color? 
> 
> <sup>3-star app review by بلو بوب. M - 6/13, 8:49 PM - WPAndroid 14.9 Xiaomi MI6 Android 9</sup>

**Comment by designsimply** [comment]
This came up in another app review:

> I would request the developer team to please add the font size and colour customizer for selected text in post. These features are missed and awaited a lot by many around the globe.
> 
> <sup>4-star app review by Chandrayan Chakraborty - Jun 16, 2020 at 4:53 AM - WPAndroid 15.1-rc-1 Vivo Y53 Androic 6.0</sup>

**Comment by designsimply** [comment]
Note: you can change colors for selected text in the Gutenberg editor as of WordPress 5.4. ([gutenberg/16014](https://github.com/WordPress/gutenberg/pull/16014#pullrequestreview-354627103), announced [here](https://wordpress.org/news/2020/03/adderley/))

**Comment by designsimply** [comment]
This came up in beta tester feedback during the 15.7 release:

> The app is great, but it lacks some features that should have become intuitive in the blogging process: […]  Shading behind the text

<sup>4-star review - Sep 18, 2020 at 11:28 PM - Galaxy On Nxt, WPAndroid 15.7-rc-3, Android 7.0</sup>
<sup>(internal reference: play-store-feedbackid=gp:AOqpTOFwoqUWzFnguYgKjf8J7PtrHbtwz2PdvUIgV_1lrD-OKnxA1b1ZMZt6_sYj9ncV7uZMSlJJ4OaC8x1xG2V6)</sup>

**Comment by reginabally** [comment]
Shared in app review on WPAndroid 15.8.1.

> I've been happily blogging on WP for a few years and thought I'd try editing on the Block Editor in the App, but many of the functions don't seem to be available which are available on the web version. ie. Text colour, justify, add image etc. Sadly finding that quite restrictive & frustrating, as I'm trying to like the Block editor. Is the App only for rough drafts?

**Comment by designsimply** [comment]
> Why is there no text coloring paragraph .. This is not present in the application itself .. and only exists when entering it from the browser
> 
> <sup>1-star beta tester feedback - Dec 15, 2020, 07:02 - Samsung Galaxy J7 V - Android 7.0 - WPAndroid 16.3-rc-2 - Arabic</sup>

<sup>(internal reference: play-store-previewId=gp%3AAOqpTOH2dMydCrGTXQncnRPNt80mMZ34UJ0NAiwQ0KPd-QbYlHHQIxVf2p3KMIJUfGmHJ3W3QANkJOxi8D3Q3spn&corpus=BETA_FEEDBACK)</sup>

**Comment by rezzap** [comment]
> Very lite app and useful one.only need some improvement like changing text color and the ability to resize text .

4 star app review (internal link: https://play.google.com/console/u/0/developer/7957760354032996428/app/4973361825681449040/user-feedback/review-details?reviewId=gp%3AAOqpTOHLoTPa_66lZBHW7EvAx8bspkXvfPEH066IKzsZQVJrGmh_eaj1rggQGIgcrWDjzgohpD4OcdeMgb0G2g&corpus=PUBLIC_REVIEWS)

**Comment by rezzap** [comment]
> Please add option for changing font color 

3 star beta tester feedback (internal link: https://play.google.com/console/u/0/developer/7957760354032996428/app/4973361825681449040/user-feedback/beta-feedback-details?reviewId=gp%3AAOqpTOGsfO5xpQxwErWB4BOj7gcQhc_DSaqfWjQQ0AAVOLM2XhvF4Yom8ehkNawvxYLD5OAB5NT6v0NzXeyeNODM&corpus=BETA_FEEDBACK)

**Comment by reginabally** [comment]
> Its different from the website.. Why i cant set the font color? Its so different

1-star app review (https://play.google.com/console/u/0/developers/7957760354032996428/app/4973361825681449040/user-feedback/review-details?reviewId=gp%3AAOqpTOGouzo7pwaGh6nciQhMtbGyoGCLPTgi9YmX910QGv0iQskh1c8MPW0sYXPQcNrRJ1UPNRsafr2gVCuUCw&corpus=PUBLIC_REVIEWS)

**Comment by reginabally** [comment]
> I'm using the app for 5 months the only issue is that there is an option to write in colors just black

4-star app review (https://play.google.com/console/u/0/developers/7957760354032996428/app/4973361825681449040/user-feedback/review-details?reviewId=gp%3AAOqpTOHmJEpcAAsRNgGw4VfEedkofEGBBwnOtjibda7sigeUylwXhiqGC5qhYy6Pi7ofKNMUoxUPbgkQ1zFuYA&corpus=PUBLIC_REVIEWS)

**Comment by ceyhun** [comment]
Another user that isn't able to use classic editor anymore because of its deprecation said they need it because of the lack of this feature 3929672-zen.

**Comment by guarani** [comment]
This came up in another App Store review:

> I was wondering if we would be able eventually to add colour in our text, because on my laptop I can, but on the app, I can’t.

**Comment by thehenrybyrd** [comment]
Noting that there is now an initial implementation in core Gutenberg in https://github.com/WordPress/gutenberg/pull/16014.

**Comment by reginabally** [comment]
Another request in 4091121-zd-woothemes
