### ISSUE TITLE
[iOS] Underline in links spans the whole line

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1218]
Links seem to have their underline expand full width.

First reported by @elibud in Slack.

See the screenshot below:

![File](https://user-images.githubusercontent.com/1032913/61056623-61d5d300-a3fc-11e9-9b69-012d0ef0dea3.jpg)

**Comment by SergioEstevao** [comment]
I've debugged this a bit and track down when this happen:

- It looks that any links that contain a `&nbsp;` character in the middle will have this problem.

For example:
```
<ol>
  <li>Hello <a href="www.apple.com" target="" rel="noopener">Apple is&nbsp;great</a></li>
</ol>
```

**Comment by SergioEstevao** [comment]
This needs to be fixed in the Aztec-iOS project.

**Comment by etoledom** [comment]
Fixed via https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1271
