### ISSUE TITLE
Video block caption retains format toolbar options from previously selected block

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1220]
The caption for the video block shows the format options of the previously selected block. For example, if the previously selected block was a paragraph block, then the video caption shows (non-functional) rich text editing options. If the post's title was previously selected, then the video caption will not show rich text editing options.

I observed this behavior on both platforms.

![Screen Capture on 2019-07-11 at 14-46-23](https://user-images.githubusercontent.com/4656348/61077303-1e736880-a3ec-11e9-9913-20beb16e7875.gif)

### Test Scenario
1. Start with a video block with an empty caption (when the video block is selected you will see the "Write caption..." placeholder text)
2. Select the video block's caption.
3. **Observe that the caption _does not have_ rich text editing options in the format toolbar**
4. Add some text to the caption (so that it can be directly selected from a different block without having to first select the video block)
5. Select a paragraph block
6. Select the video caption
7. **Observe that the caption now _has_ rich text editing options**
8. Select the post's title
9. Select the video caption
10. **Observe that the caption now _does not have_ rich text editing options**

**Comment by marecar3** [comment]
This can be reproduced also on WPiOS Internal **v12.8**

**Comment by mchowning** [comment]
Thanks for taking care of this @Tug . Your fix works great!  🎉
