### ISSUE TITLE
Virtual keyboard dismisses when focus moves from image/video caption to paragraph

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1221]
Steps to reproduce:

1. Run the demo app
2. Tap on the image (or video) block to select it
3. Tap in its caption. The virtual keyboard should come up.
4. Tap in a paragraph or heading block
5. Notice the virtual keyboard becoming dismissed while the focus and caret is in the paragraph block

**Comment by mchowning** [comment]
Also observed this in v1.8.0 (6025fe9a).

I did observe that the issue did not always occur (most of these tests were with an image caption, but video captions appeared to behave similarly):

### Switching away from image with _empty_ caption

Scenario | Frequency of Issue Occurring
---- | ----
Image had no caption, and no text added to caption | Always
Image had caption, caption was entirely deleted, switched to other block after deleting the caption | **Usually**


### Switching away from image with _non-empty_ caption

Scenario | Frequency of Issue Occurring
---- | ----
Had no caption, and text added to caption | Never
Had caption, and caption was not changed | Never
Had caption, caption was entirely deleted, text was added back to caption (all done while not losing focus on the caption) | **Infrequently**

The fact that having a caption avoids the issue entirely _unless_ you delete and re-add the caption was pretty surprising to me. 🤔 Seems like I haven't really isolated the behavior well. 

**I also observed the keyboard-dismiss-behavior _sometimes_ when returning to the caption (heading selected with keyboard open, tap on non-empty caption, keyboard dismisses).**

**Comment by mchowning** [comment]
A bit of additional info for whoever picks this up (in case it's not me): the issue appears to be related to the fact that we do not render the component for an empty caption if the image/video block is not selected. Changing it so that the caption component always renders, even if it's empty, prevents the keyboard from dismissing.
