### ISSUE TITLE
[Android] Video block - cannot preview posts with video blocks from the editor

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#1235]
Steps to reproduce:

1. Create a new post.
1. Add a video block using the "Take a Video" option.
1. Add at least one other block.
1. Save or publish the post.
1. From the block editor, go to More > Preview.

<strong>Result:</strong> preview is completely blank, the content area is an empty white screen. ([3m23s](https://cloudup.com/cljoa-TzoBr))

**Note:** There's a brief flash of content before the editor preview goes blank, but it lasts less than a second. ([screenshot](https://user-images.githubusercontent.com/1119271/61495109-424b2700-a975-11e9-9198-a31e48fd7876.png))

**Note:** Webviews (tapping "View" from the Post List) work but they are also missing a poster image and the default doesn't look nice. ([screenshot](https://user-images.githubusercontent.com/1119271/61495133-5131d980-a975-11e9-8cbd-2c900b319acf.png))

<img src="https://user-images.githubusercontent.com/1119271/61495072-26478580-a975-11e9-9dfb-f2e7d865b7eb.png" width="270" alt="preview-with-video-block-is-blank">
<sup>Tested with WPAndroid alpha-181 (12.9 alpha) on Pixel 3 Android 9.</sup>

<sub>h/t @JavonDavis for testing this in 12.9 beta testing (internal reference: p5T066-Wo-p2#comment-3235).</sub>

**Comment by designsimply** [comment]
Note: when I try the "Choose from device" option, then the poster image in the editor works and I can see the extra large placeholder poster image of a circle with a triangle in it the editor preview that @JavonDavis reported.

<img src="https://user-images.githubusercontent.com/1119271/61496052-4593e200-a978-11e9-89e4-f2e2d36a0019.png" width="200" alt="Screenshot_20190718-161102"> <img src="https://user-images.githubusercontent.com/1119271/61496054-4593e200-a978-11e9-9ee4-594f902bec18.png" width="200" alt="Screenshot_20190718-161116"> <img src="https://user-images.githubusercontent.com/1119271/61496055-4593e200-a978-11e9-98f6-dd4a21bd1265.png" width="200" alt="Screenshot_20190718-161123">

Aha! and when I tested the "Take a Video" option when adding a video block a 2nd time, the poster image worked (maybe that's a timing issue?) but I noticed that the video block and everything below it are still missing from the editor preview.

<img src="https://user-images.githubusercontent.com/1119271/61496202-b9ce8580-a978-11e9-91da-f48b58e54509.png" width="200" alt="Screenshot_20190718-161254"> <img src="https://user-images.githubusercontent.com/1119271/61496402-58f37d00-a979-11e9-911b-d9bac3c4fb8b.png" width="200" alt="Screenshot_20190718-162516"> <img src="https://user-images.githubusercontent.com/1119271/61496401-58f37d00-a979-11e9-8111-175a2f7cb718.png" width="200" alt="Screenshot_20190718-162524">

<sup>Tested with WPAndroid alpha-181 (12.9 alpha) on Pixel 3 Android 9.</sup>

**Comment by hypest** [comment]
I think we can park this ticket since:

1. The preview functionality is actually not part of the editor per se. It's handled by the parent app (WPAndroid) code.
2. The preview feature itself is on its way out: https://github.com/wordpress-mobile/WordPress-Android/issues/9729

WDYT @designsimply ?

**Comment by marecar3** [comment]
Hey @designsimply @hypest I have tested on WPiOS and it seems that video preview isn't working there as it was stuck 3-4 times with "loading..." state or no state at all, just blank surface (instead of video)

When I have compared WPAndroid Gutenberg with WPAndroid Aztec, Aztec is just showing a plain text without video.

If we are going to move away from the preview feature, maybe it's a good option to park this one.

**Comment by designsimply** [comment]
I always think of previews as part of the editor! My mistake. Let's move this to `WordPress-Android` in that case, but I believe the bug still stands and is more broken in the block editor previews where videos and content below them completely missing compared to the Aztec editor previews where a video placeholder is shown and no other content is missing.

https://github.com/wordpress-mobile/WordPress-Android/issues/10257

> The preview feature itself is on its way out: wordpress-mobile/WordPress-Android/9729

The 9729 issue specifically mentions local previews in the context of offline editing. My understanding is that we will still have previews though and that videos should work in those previews or at least show a placeholder of some kind.

**Comment by designsimply** [comment]
<blockquote>I have tested on WPiOS and it seems that video preview isn't working there as it was stuck 3-4 times with "loading..." state or no state at all, just blank surface (instead of video)</blockquote>

I am testing WPiOS 12.9 beta today and will cover this flow and make a new issue if needed. Thanks for catching that @marecar3 !
