### ISSUE TITLE
YellowBox Warning: componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/gutenberg-mobile#1242]
There is currently a warning showing on the gutenberg mobile demo app:

> Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

![Screenshot_1563871613](https://user-images.githubusercontent.com/40213/61702654-7a20e880-ad40-11e9-9055-cdd3cdf27b6d.png)

It's due to at least one of our dependencies:

![Screenshot_1563874106](https://user-images.githubusercontent.com/40213/61702671-8147f680-ad40-11e9-84fa-c126174f8754.png)

I couldn't find any occurrences of `componentWillReceiveProps` in our code, so I think updating the dependencies would be enough to fix this.

**Comment by maxme** [comment]
I tried to upgrade `react-native-modal` to latest revision (v11.1.0). Doing this removes the warning, but there is another warning when the bottom sheet animation starts:

![Screenshot_1563875473](https://user-images.githubusercontent.com/40213/61702582-59589300-ad40-11e9-9e4c-6e316462b035.png)

This one comes from a `react-native-modal` dependency: `react-native-animatable` and is not fixed yet:


https://github.com/oblador/react-native-animatable/issues/180#issuecomment-513271224

**Comment by maxme** [comment]
In the meantime, one can hide this warning by ignoring this warning in `src/index.js`:

```diff
diff --git a/src/index.js b/src/index.js
index b0554c0f..684d0bc3 100644
--- a/src/index.js
+++ b/src/index.js
@@ -77,7 +77,7 @@ export class RootComponent extends React.Component {

 export function registerApp() {
        // Disable require circle warnings showing up in the app (they will still be visible in the console)
-       YellowBox.ignoreWarnings( [ 'Require cycle:' ] );
+       YellowBox.ignoreWarnings( [ 'Require cycle:', 'componentWillReceiveProps'] );
```

**Comment by hypest** [comment]
Not seeing the YellowBox anymore, at least on 7495fbf3. Closing but let's reopen if it comes back.

**Comment by mchowning** [comment]
I just commented out [this line](https://github.com/wordpress-mobile/gutenberg-mobile/blob/3d10d026ea0175ba6ffc94345546704056662365/src/index.js#L99): 

```
console.disableYellowBox = true;
```

and loaded the editor to this 😱 

![all_the_warnings mp4](https://user-images.githubusercontent.com/4656348/84407083-5d033b80-abd8-11ea-919d-0caa1c1da40a.gif)


I'm thinking maybe we should keep this one open 🙂 (there are some `componentWillReceiveProps` deprecation warnings in there), and probably add new issues for the other warnings too. WDYT @hypest ?

**Comment by hypest** [comment]
Yes, let's re-open.

Also, wondering if [the 0.62.x upgrade](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1823) has the same issues reported.

**Comment by geriux** [comment]
Closing since there are no `componentWillReceiveProps` references anymore.
