### ISSUE TITLE
Add rich text styling to video block captions

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1244]
Currently video block captions only permit plain text styling. I believe we should add rich text styling for these captions [like we did for image blocks](https://github.com/wordpress-mobile/gutenberg-mobile/issues/574). Aztec has this capability.

Image (rich text) | Video (plain text)
--- | ---
![image](https://user-images.githubusercontent.com/4656348/61812368-5a0d2a00-ae11-11e9-86ba-997855029ffa.png) | ![video](https://user-images.githubusercontent.com/4656348/61812382-5ed1de00-ae11-11e9-9402-d3dfd9684005.png)

**Comment by hypest** [comment]
There's formatting support in all captions for some time now and at least on WPAndroid v15.0-rc-3 is working OK for image and video blocks. Closing this ticket.
