### ISSUE TITLE
CustomImageLoader is interrupting the symbolicate request on Haul

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1256]
Root cause analysis can be found [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1250) 
We'll need to update `CustomImageLoader.canLoadImageURL` to address the symbolicating issue

**Comment by SergioEstevao** [comment]
@pinarol is this still an issue?

**Comment by pinarol** [comment]
This problem was only manifesting itself with the usage of Haul but the [root cause analysis](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1250#issuecomment-516761920) showed that [canLoadImageURL](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/ios/CustomImageLoader.swift#L9-#L11) can return true for requests that has nothing to do with image loading. So I believe it'd be good to improve that condition to avoid any potential problems in the future, even if we don't use Haul at all.

**Comment by chipsnyder** [comment]
The reason for this change seems to be tied to the HAUL exploration. Since that is no longer on the radar I'm going to close this and we can reopen it later if needed.
