### ISSUE TITLE
Add missing heading levels

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1261]
Even though Gutenberg mobile renders them already, user has no way to set H4, H5, H6 via the editor UI. Let's add the missing functionality.

**Comment by iamthomasbishop** [comment]
@SergioEstevao I think I'd like to start using collapsed groups/dropdowns for this type of thing, but until we have those, let's just display the heading levels inline on the toolbar. Example:

![image](https://user-images.githubusercontent.com/1200432/65458930-5ba89d80-de14-11e9-8334-57716b1c2f56.jpeg)
