### ISSUE TITLE
[Android] Cannot select text across multiple blocks

### ISSUE THREAD

**Issue by KokkieH** [wordpress-mobile/gutenberg-mobile#1287]
#### To replicate

1. Add text to two or more paragraph blocks
2. Try to select text across multiple blocks

#### What I expected

For the multiple blocks to be selected in full, as happens in the web editor.

#### What happened

I can only select text from the current block. Tapping the Select All option also only selects text from the current block.

#### App and device info

User who reported this is on v 12.9 on Android 5

Replicated v13.0-rc-3 on Android 9

Reported in https://en.forums.wordpress.com/topic/wordpress-android-app-3/

**Comment by hypest** [comment]
Thanks for reporting @KokkieH ! I will close this ticket in favor of #1257 which is basically the same issue.

**Comment by KokkieH** [comment]
Ah, missed that one. Will follow along there instead, thanks!
