### ISSUE TITLE
Gallery: Cross Platform Tiles Component

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1302]
We should add a high level gallery tiles component to replace the `<ul/>` usage in the gallery block. I think it is ok to create a dummy GalleryImage implementation on mobile side just to use for test purposes until the [real implementation](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1301) is ready.

This component would take the image component, column count, and alignment from outside. The style on the other hand would be contained by the inner implementation. This is my first impression of the component but if better possibilities come up during implementation we can just update the description or add comment.

**Comment by mkevins** [comment]
For the first iteration of mobile Gallery block, we will use a semi-cross-platform approach. This allows us to share _some_ of the logic with the web implementation, with minimal changes to the web implementation. The `Tiles` component will only be used for the mobile implementation, and the original draft PR for that component has been superseded by this PR: https://github.com/WordPress/gutenberg/pull/18130.

**Comment by mkevins** [comment]
Resolved by: https://github.com/WordPress/gutenberg/pull/18130
