### ISSUE TITLE
Crash on HTML mode

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1303]
There's a crash when switching to HTML mode.

On the example app, it's triggered when trying to edit the HTML content (the iOS example app has the UI to switch to HTML mode)

On WPiOS, it's triggered just by switching to HTML mode.

This is the error:

![IMG_2962](https://user-images.githubusercontent.com/9772967/63325901-5777f480-c32b-11e9-91ed-c2f241cce89e.jpeg)

**Comment by hypest** [comment]
Fixed by #1305
