### ISSUE TITLE
Editing block on Mobile loses Ordered List Settings

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1304]
In [gutenberg#15113](https://github.com/WordPress/gutenberg/pull/15113) the web side added settings for changing the start number in an ordered list and reversing the ordered list. Unfortunately, these changes broke mobile because they used components mobile had not implemented. That was fixed in [gutenberg#17070](https://github.com/WordPress/gutenberg/pull/17070), but we have not implemented those additional settings, so any changes on mobile will override (and lose) those settings from web. See [this comment](https://github.com/WordPress/gutenberg/pull/17070#pullrequestreview-276950939) for additional info.

**Comment by mchowning** [comment]
We may have the same issue with respect to the color of a list separator block added from web as a result of https://github.com/wordpress-mobile/gutenberg-mobile/pull/1308

**Comment by hypest** [comment]
So, if I understand this ticket correctly, editing on mobile a _post_ that has one of those list settings not currently supported on mobile will result in loosing content details?

**Comment by mchowning** [comment]
>So, if I understand this ticket correctly, editing on mobile a post that has one of those list settings not currently supported on mobile will result in losing content details?

That is the concern @hypest . @etoledom raised this concern when we were fixing a crash on mobile, and because we were in the middle of trying to get the release out I did not have time to fully investigate the issue, so I made this ticket to track it. 

The separator block color was added in gutenberg [6.3.0](https://github.com/WordPress/gutenberg/releases/tag/v6.3.0) and the reverse and start number settings for list blocks were added in [6.4.0](https://github.com/WordPress/gutenberg/releases/tag/v6.4.0). It looks like my site on WP.com is still using gutenberg 6.2.0, so it's not super easy to verify this issue at this time.

**Comment by hypest** [comment]
Let's split this into 2 tickets:

1. Make sure we don't alter the body of the post. So, if those options are used, the mobile editor needs to keep them.
2. Display/rendering of the list when those options are in effect

**Comment by SergioEstevao** [comment]
I'm implementing support for displaying start and reversed properties in Aztec iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1242

**Comment by SergioEstevao** [comment]
For the record, even before implementing the necessary changes in Aztec, we were not losing the reversed and save attributes because of Aztec. 
I think the problem at the time was that our version of Gutenberg master was behind and not saving the new attributes at all.
