### ISSUE TITLE
Inner Blocks - Navigating Upward in the hierarchy

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1315]
User should be able to navigate upward in the hierarchy.

Please take a look at the [prototype](https://href.li/?https://www.figma.com/proto/SptxS8feaNYtWUzoeNM4qI/Nested-Blocks-i2?node-id=2%3A9167&viewport=-1433%2C80%2C1&scaling=min-zoom) to get a sense of how it should behave.

User should be able to navigate upward in the hierarchy by tapping the Up button inside the floating toolbar.

<img width="492" alt="Screen Shot 2019-08-22 at 21 28 04" src="https://user-images.githubusercontent.com/5032900/63539901-c15aee80-c523-11e9-964e-b2a5da9758a7.png">

**Comment by pinarol** [comment]
Linking [this comment](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1344#issuecomment-527663856) here since it contains relevant discussion.

Especially this part:

```
Considering the upcoming work to implement a hierarchy navigation toolbar, I think we should go one of two routes. Either:

- Slim down the additional margins to ~4-8px left/right (this would lessen the problem, but not fix it)
- Remove the additional margins completely (this would mean all blocks – nested or not – would be full-width, but wouldn't provide as much a visual cue of hierarchy)

If there are other suggestions, I'm all ears.

```

Hard to tell before using, I think we can do both and compare as an experiment 🤔

**Comment by jbinda** [comment]
Hello 👋 

What should be correct order during navigating to the top ?
Let's say I have below structure:

`

    
    
        
            
            
        

    

        
            
             **current selection
        

`

the order of the selections will be:
_wp:heading_g2_ **->** _wp:group2_root_ **->** _wp:video_root_ **->** _wp:heading_g1_ **->** _wp:image_g1_ **->** _wp:group1_root_ **->** _wp:heading_root_ **->** _wp:image_root_ 

is that correct ?

**Comment by pinarol** [comment]
Navigating upward is necessary only in case the block has inner blocks, we expect navigation upward would set the focus to the block’s parent. The order would be just: 
paragraph_g2 -> group2
If I understand the example right, group2 doesn’t have a parent so there’s nowhere else to navigate in upwards direction at that point.

**Comment by jbinda** [comment]
Ok, thanks - I will raise an PR soon and let you
