### ISSUE TITLE
Inner Blocks - Navigating with the Document Outline view

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1320]
Document Outline view is displayed once the user taps the breadcrumb on the [Floating Toolbar](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1317). This is for navigating inside a complex hierarchy. 

The scroll position should be arranged programmatically to make the selected block visible in the viewport. Please take a look at the [prototype](https://href.li/?https://www.figma.com/proto/SptxS8feaNYtWUzoeNM4qI/Nested-Blocks-i2?node-id=2%3A9167&viewport=-1433%2C80%2C1&scaling=min-zoom) to get a sense of how it should behave.

This uses the existing Bottom Sheet component, we should be setting indentations to better visualize the hierarchy. 

<img width="580" alt="Screen Shot 2019-08-22 at 22 51 10" src="https://user-images.githubusercontent.com/5032900/63545142-6c24da00-c52f-11e9-8bd5-74a30ed81a02.png">

For most of the blocks it shows the title of the block, for text based blocks it shows a hint about the contained text.

**Comment by pinarol** [comment]
There's a possibility we can de-prioritize this a bit, let's talk before starting the implementation.

**Comment by dratwas** [comment]
@pinarol 
I already started the implementation but I'm in early phase.
What I did is:
- show list of all block inside BottomSheet (not styled properly yet)
- select correct block when clicked in the document outline
- hide BottomSheet

What is left:
- mark which block is selected in the document outline
- scroll to the selected block inside document outline and after a click on an item inside
