### ISSUE TITLE
Add Size options to Image Block

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#1329]
See Parent issue #1263

The gutenberg-mobile editor should allow users to update Image Size options the same way that they can in the Aztec Editor. 

Size options should be added to the existing image options BottomSheet menu. Selecting Size should lead to a second BottomSheet menu that lets the user change the size. 

This first implementation will not alter the presentation of the Image in the editor based on its image size, as that feature is currently implemented in the Aztec Editor on iOS but not Android, so it is a slightly lower priority. 

![image](https://user-images.githubusercontent.com/1103838/63741147-9f75aa80-c848-11e9-80b5-b9ad401cae6f.png)

**Comment by hypest** [comment]
I haven't closely followed the conversation about the design side of the feature so, allow me to ask, what do you think about the nested bottomsheet here @iamthomasbishop?

**Comment by iamthomasbishop** [comment]
Nested sheets for settings – especially on iOS – would be huge. That was an original proposal but it's going to require some additional effort, so in the meantime we decided to open a second sheet where necessary.
