### ISSUE TITLE
Crash on the latest master on gutenberg repo

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1332]
Following crash occurs when we update gutenberg hash to point to master.

<img width="344" alt="Screen Shot 2019-08-23 at 12 02 32" src="https://user-images.githubusercontent.com/5032900/63786950-ab6e7480-c8fb-11e9-9f61-673b53cd8074.png">

It looks like [this PR](https://github.com/WordPress/gutenberg/pull/16932) caused this regression.

**Comment by etoledom** [comment]
We have this PR with a partial fix: https://github.com/WordPress/gutenberg/pull/17228

It solves the error referenced on this ticket, but it exposes an underlying problem given the nature of the changes from https://github.com/WordPress/gutenberg/pull/16932

WIP.
