### ISSUE TITLE
Multiple bugs on rotate with modal open in WordPress Android (Android API 28, Pie v9.0 only)

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#1333]
Related to [WordPress Android Issue #10227](https://github.com/wordpress-mobile/WordPress-Android/issues/10227)

## Expected: 
Opened modals remain open on rotate, just like they do in WordPress iOS, and WordPress Android on API version < 28. 

## Actual:
In WordPress Android, with a device running Pie (API 28/v9.0) , open modals on rotate will close, the editor may jump to focus on the wrong block, buttons for opening modals may stop working, and double rotations will crash (crash issue covered in WordPress Android Issue [#10227](https://github.com/wordpress-mobile/WordPress-Android/issues/10227)).

![crash-api-28](https://user-images.githubusercontent.com/1103838/63823469-d3180980-c908-11e9-89b3-6b731ff4c8dd.gif)

## Build numbers / Devices Tested
Tested using WordPress Android develop [78f11d9](https://github.com/wordpress-mobile/WordPress-Android/commit/78f11d983139a0ba283a1caaaef998b67221550a) and gutenberg-mobile release/1.11.0 branch and the Play Store beta build (13.2-rc-1). Verified on Samsung S10 API 28 and emulator Pixel 3 on API 28. 
Verified issue does NOT exist on Samsung Galaxy Tab 3 API 26, and with emulator of Google Pixel on API 27, 26, and 21 (Min supported for WordPress Android)

## Steps to reproduce: 
1. Open WordPress Android on a device running Pie (API 28/v9.0) and start editing a post in the block editor
2. Open a modal from Block Inserter, new Image/Video Block, or Image Options gear button
3. Rotate the phone and observe that modal closes, focus shifts to different blocks, and button used to open modal may no longer be working.
4. (optional) If you rotate a second time you will see a crash (4th step fixed by Android PR [#10383](https://github.com/wordpress-mobile/WordPress-Android/pull/10383#issuecomment-521123642))

Hopefully the issues here can all be fixed from addressing the same root cause of [#10227](https://github.com/wordpress-mobile/WordPress-Android/issues/10227), but for now #10227 (the crash on double rotate) has a fix (Android [PR #10383](https://github.com/wordpress-mobile/WordPress-Android/pull/10383#issuecomment-521123642)) and the rest of the behaviors on rotate do not. The fixes for this issue should be coordinated in tandem with [Android PR #10383](https://github.com/wordpress-mobile/WordPress-Android/pull/10383#issuecomment-521123642).

The ideal functionality would be to keep modals open on rotate, how they behave on WordPress iOS and the gutenberg-mobile Android example app. However, if there is no short term fix for keeping modals open on rotate, we should at least fix the crash issue, the incorrect focus issue, and the deactivated buttons issue.

**Comment by SergioEstevao** [comment]
@cameronvoell is this still an open issue? I could not reproduce on my device.

**Comment by cameronvoell** [comment]
> @cameronvoell is this still an open issue? I could not reproduce on my device.

Closed via https://github.com/wordpress-mobile/WordPress-Android/pull/10383.
