### ISSUE TITLE
 Image Options - Link To (including "open in new window")

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#1337]
See Parent issue #1263 

We'd like to add the "Link to" Image options that are available in the Aztec Editor, but not the Gutenberg mobile editor, specifically including the "open in new window" option. 

Sketch from design:
![image](https://user-images.githubusercontent.com/1103838/63998255-89b8ed00-cab5-11e9-9c32-bfcffe902aa2.png)

**Comment by cameronvoell** [comment]
In addition to reaching Aztec parity, it [was proposed to scope out the work to see how much extra time it would take to add the "Link To existing content" option](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1285#issuecomment-526127598). While implementing "open in new tab", I'll spend a bit of time to see if I can get a work/time estimate for linking to existing content as well.

**Comment by etoledom** [comment]
"Open in new window" was added via https://github.com/wordpress-mobile/gutenberg-mobile/pull/1394

If this is enough for V2, should we close this ticket?
cc @hypest

**Comment by hypest** [comment]
Thanks for the nudge @etoledom , closing as "done".

By the way, there's already #1058 for tracking the "link to existing content" feature.
