### ISSUE TITLE
Media & Text block needs update with new prop names of MediaPlaceholder and MediaUpload

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1338]
Media & Text block is [merged](https://github.com/WordPress/gutenberg/pull/16305/files) to `rnmobile/master` recently but since it is merged at the same time with [unify props PR](https://github.com/WordPress/gutenberg/pull/17145) it missed to use the new prop names. We need a small PR to fix Media & Text block to use new prop names of MediaUpload & MediaPlaceholder.

**Comment by pinarol** [comment]
Could someone do a quick PR for this? @dratwas @lukewalczak ?

**Comment by pinarol** [comment]
cc @geriux : You might find Media & Text block is not working on the latest `rnmobile/master`

**Comment by lukewalczak** [comment]
Will handle it!

**Comment by lukewalczak** [comment]
[PR](https://github.com/WordPress/gutenberg/pull/17268) is ready.

**Comment by pinarol** [comment]
Merged https://github.com/WordPress/gutenberg/pull/17268
