### ISSUE TITLE
[Android] Multiple media selection adds only one image/video block

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1346]
Current behavior:

- Add an image/video block
- Add multiple images/videos from WordPress media library
- Only 1 image/video block is added

Expected behavior:

- Add an image/video block
- Add multiple images/videos from WordPress media library
- Multiple image/video blocks are added with the selected images/videos

Root cause analysis

It looks like we are having a side effect of a [recently merged PR](https://github.com/WordPress/gutenberg/pull/16677/files). The code that subscribes for mediaAppend events are moved and since inserter menu is not rendered after we pick the media it won't be able to listen. We can try moving this subscription back to its old place as a solution, or anywhere more suitable which won't be unmounted along the way.

This is only observable via WordPress Android app because WordPress iOS app doesn't let multiple selection on WordPress media library currently.

**Comment by etoledom** [comment]
This also seems to be the cause of an issue on WPiOS, where the Force Touch app shortcut doesn't work properly selecting "New Photo Post".

Steps:
- Force Touch on the WPiOS app icon.
- Select `New Photo Post` shortcut.
- Make sure Gutenberg was opened as the editor.
- Select an Image.
- 💥 No image block was appended.

![Force_touch_bug](https://user-images.githubusercontent.com/9772967/64186219-c5b1d080-ce6e-11e9-88b4-4c751b85cac7.gif)
