### ISSUE TITLE
Heading Block loses style after hitting backspace until empty and typing again

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#1355]
Steps:

1. Add a header block with some text. 
2. Remove all the text in a Heading block
3. The placeholder text should appear again
4. Start typing in the block
5. The styling should be there and the toolbar updated

![rpreplay_final1567654665 mp4](https://user-images.githubusercontent.com/1103838/64311653-c1161680-cf59-11e9-89b8-45b09d0b9751.gif)

**Comment by cameronvoell** [comment]
I noticed this would have been caught in test steps of this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/739 , so this is probably a regression.

**Comment by SergioEstevao** [comment]
@cameronvoell do you mind test again with the latest develop. I don't think this is no longer happening in iOS.
