### ISSUE TITLE
Mobile unit tests are failing on Gutenberg CI

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1356]
The JS mobile unit tests are currently failing on the Gutenberg CI with the multiple instances of this error:

```
FAIL ../../packages/rich-text/src/component/test/index.native.js
  ● Test suite failed to run
    Cannot find module 'Platform' from 'react-native-implementation.js'

    However, Jest was able to find:
    	'../index.js'
    	'../index.native.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      4 | import { StyleSheet, TouchableOpacity, Text, View, Platform } from 'react-native';
      5 | 
    > 6 | const isAndroid = Platform.OS === 'android';
        |                   ^
      7 | const marginBottom = isAndroid ? -0.5 : 0;
      8 | const marginLeft = -3;
      9 | 
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:229:17)
      at Object.require [as Platform] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:325:12)
      at Object.Platform (packages/components/src/button/index.native.js:6:19)
```

Example: [Travis Job failing](https://travis-ci.com/WordPress/gutenberg/jobs/230992153), on [this PR](https://github.com/WordPress/gutenberg/pull/17309)

The Travis job is set to "This job is allowed to fail." so it doesn't block the PRs but, we need to fix this in order to move to the next steps.

**Comment by hypest** [comment]
Following up on our weekly hangout yesterday, let's put this ticket back into the "Open Beta" project column and un-assign people from it. We'll get back to it very soon.

**Comment by hypest** [comment]
👋 @JavonDavis , can you have a look when you get the chance?

Here's a recent PR that the mobile Jest tests on Gutenberg fail: [PR](https://github.com/WordPress/gutenberg/pull/17989), the [Travis job page](https://github.com/WordPress/gutenberg/runs/263580534), and [the failing log line in Travis](https://travis-ci.com/WordPress/gutenberg/jobs/246579938#L653).

**Comment by JavonDavis** [comment]
@hypest sure I can take a look at this!

**Comment by hypest** [comment]
I think I managed to replicate the issue by running the (Gutenberg side) tests on an Ubuntu VM locally. Opened https://github.com/WordPress/gutenberg/pull/18378 in an attempt to fix this.

**Comment by JavonDavis** [comment]
> I think I managed to replicate the issue by running the (Gutenberg side) tests on an Ubuntu VM locally. Opened WordPress/gutenberg#18378 in an attempt to fix this.

Interesting 🤔@hypest thanks for getting to that for me 🙇 I just hadn't gotten a chance to really look into it as yet! I'll give the PR a go 👍
