### ISSUE TITLE
Introduce grouping in the Block Settings Inspector

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1384]
We are about to complete [refactoring Block Settings](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1341) in a cross platform manner. Next step is introducing the grouping behavior similar to web. We had some discussions around the issue but I think we don't have a clear conclusion yet. Inviting @iamthomasbishop into conversation at this point.

From technical side of view, considering that this component will be cross platform, it'd be beneficial to keep things similar to web which displays settings inside a single page as a tree structure. But we can always explore other options, I just wanted to mention the technical aspect of it.

**Comment by iamthomasbishop** [comment]
In previous discussions, it seemed like there was some agreement around taking a super simple approach for a v1, and building beyond that in the near future. I believe something along these lines is what we discussed doing for v1:

* Replicate the organization/grouping structure that the web offers, into sections – each with a title
* On the web, each section is collapsible in accordion format. The accordion format doesn't work great on mobile, so we should simply expand the sections

This is a quick mock of what it might look like (on iOS, but we'd substitute native Android components for the stepper, switch, etc.

<img width="692" alt="Screen Shot 2019-09-25 at 4 23 05 PM" src="https://user-images.githubusercontent.com/1200432/65641177-b7f4f400-dfb1-11e9-896c-a4b891d8c318.png">

## Future

In the long-term, there were a couple of options that seemed desireable:

### Nesting

Similar to iOS' native navigation nesting, we would allow the user to go down into sub-pages in a sheet. Personally, I think this sort of thing will become necessary soon as we add more complex controls, such as sliders, color pickers, etc.

![img_0574](https://user-images.githubusercontent.com/1200432/65641528-a19b6800-dfb2-11e9-82de-1eb0d5ed33f7.jpeg)

### Tabs

Each section would become a tab (in paragraph block, tabs would be **Text**, **Color**, and **Advanced**.

![image](https://user-images.githubusercontent.com/1200432/65641402-3f426780-dfb2-11e9-806f-bc79992b71ba.png)

**Comment by jbinda** [comment]
As first thought grouping in Settings BottomSheet can be achieved nicely using PanelBody component

**Comment by pinarol** [comment]
Correct @jbinda we'll be using PanelBody for this 👍
