### ISSUE TITLE
Crash: null is not an object (evaluating '_this.scrollViewRef.props)

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#1390]
While testing #1361 I came across one crash that seems unrelated to it (also reproduced on current develop).

To reproduce:

- Create a new post
- Insert an image and upload a photo from the device
- When it uploads, insert a media-text block
- Remove both blocks
- Dismiss the keyboard (or insert a video block)
- Crash

**Comment by koke** [comment]
When I delete the media-text block, I'm seeing this in Chrome devtools:

```
TypeError: Cannot read property 'name' of null
    at index.native.js:150
    at Object.mapSelect [as current] (index.js:54)
    at onStoreChange (index.js:127)
    at index.js:154
    at registry.js:56
    at Array.forEach (<anonymous>)
    at globalListener (registry.js:56)
    at index.js:85
    at dispatch (createStore.js:186)
    at index.js:24
```

![Screen Shot 2019-09-27 at 11 56 35](https://user-images.githubusercontent.com/8739/65760798-f3143600-e11d-11e9-9954-7f0acaa5a045.png)

**Comment by koke** [comment]
The crash happens on [KeyboardAwareFlatList](https://github.com/WordPress/gutenberg/blob/a5b1b2e271a55a7474bdd803df490871252a2d39/packages/components/src/mobile/keyboard-aware-flat-list/index.ios.js#L33). There's a `setTimeout` and when it executes, `this.scrollViewRef` is `null`

**Comment by pinarol** [comment]
Makes sense, before the inner blocks there were no case like scrollViewRef being null because the only KeyboardAwareFlatList was the main one.
