### ISSUE TITLE
[iOS] List block: Bullet overlaps placeholder in dark mode

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#1391]
When adding a new list block in dark mode, the bullet overlaps the block placeholder:

<img src="https://user-images.githubusercontent.com/8658164/65767083-b992f900-e124-11e9-8aed-35d4633304e9.png" width="50%">

This only happens in dark mode; I don't see any issue in light mode.

Tested on iPhone XS, iOS 13.1, WPiOS 13.3.0.20190926

**Comment by rachelmcr** [comment]
cc @etoledom

**Comment by etoledom** [comment]
Thank you for this report @rachelmcr 

We were talking about this with @SergioEstevao , I didn't notice previously that this only happens on Dark Mode. That's a good lead!
