### ISSUE TITLE
Paragraph/Break tag inconsistencies in quote blocks

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1396]
There is inconsistency in how Android and iOS handle new lines in quote blocks.

### Web

As a starting point, it's worth looking at how the web handles quote blocks. For the quote (top) part of the block, paragraph tags are used for each line. For the cite (bottom) part of the block, there are no paragraph tags, only break tags.

```
<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>Line 1</p><p>Line 2</p><p>Line 3</p>
<cite>Line 1<br>Line 2<br>Line 3</cite></blockquote>
<!-- /wp:quote -->
```

![Screen Shot 2019-10-01 at 11 15 18 AM](https://user-images.githubusercontent.com/4656348/65975555-c8d3b880-e43c-11e9-9a4d-d81799ae787b.png)

### Android

On Android, for both the quote portion and the citation portion, pressing the enter key adds a new break tag, with the quote portion being wrapped in a single paragraph tag. 

```
<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>Line 1<br>Line 2<br>Line 3</p>
<cite>Line 1<br>Line 2<br>Line 3</cite></blockquote>
<!-- /wp:quote -->

```

![Screen Shot 2019-10-01 at 11 00 04 AM](https://user-images.githubusercontent.com/4656348/65974397-e3a52d80-e43a-11e9-937f-92cad7e665c2.png) 

### iOS

On iOS, the quote part of the block uses paragraph tags for each new line like the web. For the `cite` portion, the first line is wrapped in a paragraph tag and any subsequent lines are separated by break tags.

```
<!-- wp:quote -->
<blockquote class="wp-block-quote">
<p>Line 1</p><p>Line 2</p><p>Line 3</p>
<cite><p>Line 1</p>Line 2<br>Line 3<br>Line 4<br></cite></blockquote>
<!-- /wp:quote -->
```

 This creates some inconsistency in how the lines are spaced.

![Screen Shot 2019-10-01 at 11 00 59 AM](https://user-images.githubusercontent.com/4656348/65974404-e7d14b00-e43a-11e9-88d2-35044b2af44d.png)

This ends up looking especially odd if the block is saved and viewed on the web _**editor**_ because the first line of the cite section is not sized appropriately:

![Screen Shot 2019-10-01 at 11 18 18 AM](https://user-images.githubusercontent.com/4656348/65976089-9ffff300-e43d-11e9-9d90-2a357c922c0e.png)

The text size is fixed if you _**Preview**_ the post on web, although the line spacing remains off:

![Screen Shot 2019-10-01 at 11 20 45 AM](https://user-images.githubusercontent.com/4656348/65976100-a3937a00-e43d-11e9-8020-b0e0d67828b5.png)

### Expected behavior

At a minimum, iOS should have consistent spacing for new lines in the cite section of the quote block (i.e., not have different spacing between lines 1 & 2 as compared to the spacing between lines 2 & 3).

Ideally, web/Android/iOS should all generate the same html.

### Test Environment
This was tested on the release candidate branches for 1.14.0. (WPiOS -> 6b22a1fea4 and WPAndroid -> d588d154e3). iOS was tested on an iPhone Xs simulator (13.0). Android was using a physical Pixel (10.0).

Somewhat related quote block Issue: [[iOS] `<br>` tags are converted to `<br />` on WPiOS HTML mode](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1138)

**Comment by mchowning** [comment]
A similar issue [also appears to be occurring with pullquote blocks](https://github.com/WordPress/gutenberg/issues/29862).

**Comment by SiobhyB** [comment]
Closing as this is no longer an issue now that the quote block uses inner blocks.
