### ISSUE TITLE
Heading block Hx (level) buttons won't change icon color when active.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1398]
### Expected behavior
The icon color of Hx (level) toolbar buttons on Heading block should be white when the button is active.

### Actual behavior
 They stay the same color when inactive.

![Hx](https://user-images.githubusercontent.com/9772967/66036337-423adc00-e50d-11e9-9a26-5e835dfbc494.png)

### Steps to reproduce the behavior

- Add a Heading block.
- Check the Heading Level buttons on the toolbar.

**Comment by marecar3** [comment]
It seems that we need to support the new heading icon on gb-mobile side: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/heading/heading-level-icon.js or to examine options on how to pass style to SVG.

**Comment by marecar3** [comment]
Fixed in: https://github.com/WordPress/gutenberg/pull/17747
