### ISSUE TITLE
Heading block: H5-H6 not always working properly

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1399]
On new Heading blocks, pressing H5 or H6 won't change the Heading level.
This seems to be a visual issue, since changing to HTML mode, the h6 is properly represented.

To reproduce:
- Run Gutenberg on iOS example app or WPiOS.
- Create a new Heading block.
- Select the H5 or H6 
- Check that the placeholder won't change size.
- Write some text.
- Check that the text size has not changed to represent the new Heading level.
- Select other Heading levels, the text won't change size.

![H5-6](https://user-images.githubusercontent.com/9772967/66037808-c0e54880-e510-11e9-89d1-3dbcd24893ac.gif)

**Comment by marecar3** [comment]
Resolved. Closing this one.

**Comment by etoledom** [comment]
Fixed via https://github.com/WordPress/gutenberg/pull/17710
