### ISSUE TITLE
Improve empty editor area height 

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#1408]
As long as there is any visible whitespace it would be tappable. The 80px of padding is useful when there is more content that can fit on the screen to ensure some extra whitespace at the end.

Currently how it's working:
![empty_editor_area](https://user-images.githubusercontent.com/28219092/66206654-fcb71400-e6b0-11e9-8ffc-42b642bad93e.gif)

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/1200.
