### ISSUE TITLE
Gallery block - semi cross platform approach

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1416]
We can still have single edit.js and share @wordpress/components imports with web. But since we don't have an approved approach for replacing the web elements yet let's re-think about x-platform tiles, image subtasks. Especially if we think we won't be able to use the x-platform image component without the rest of the primitives let's re-think about the ideal next steps.

This issue is just for documenting the next steps, doesn't mean that we'll track the whole work with this, we should create new development subtasks if needed.

#### Some steps:
- [x] Make sure it works with existing content (i.e. open a post that was created on web)
- [x] Choosing media from WordPress Media Library
- [ ] Choosing media from device (i.e. uploading media) tracked here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1610

**Comment by mkevins** [comment]
## Description

This tracks the first iteration for a semi-cross-platform Gallery block. I have opened smaller PRs with smaller changesets to facilitate more focused discussion around the components used.

The `gutenberg` PRs for this feature have been rebased into a hierarchy described below. [This "top level" PR](https://github.com/WordPress/gutenberg/pull/18265) can be used to test the aggregate changeset and integration of components within these related PRs.

## Sibling PRs from other repositories
gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1498
WordPress-Android: https://github.com/wordpress-mobile/WordPress-Android/pull/10703

## PR Hierarchy

- ### GalleryImage: https://github.com/WordPress/gutenberg/pull/18155

  - #### Gallery Button: https://github.com/WordPress/gutenberg/pull/18264 
    This has been merged into `GalleryImage` PR for review there.

- ### :heavy_check_mark: Tiles: https://github.com/WordPress/gutenberg/pull/18130

- ### :construction: Native Gallery: https://github.com/WordPress/gutenberg/pull/18176

  - #### MediaPlaceholder: https://github.com/WordPress/gutenberg/pull/18262
    This has been merged into the Native Gallery PR for review there.

- ### Extract Gallery: https://github.com/WordPress/gutenberg/pull/18265

**Comment by pinarol** [comment]
I am closing this since upload is tracked here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1610
