### ISSUE TITLE
Proposal: Long-press on inserter to show options for "add above" and "add below"

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1433]
Long-pressing on the inserter button (`(+)` on the quick toolbar) should show options to `Add Block Before` and `Add Block After` the currently selected block. If there is no selection these options could be `Add to beginning` and `Add to end`. On iOS, this could be an `ActionSheet` and Android a `BottomSheet`.

Example:

![IMG_0645](https://user-images.githubusercontent.com/1200432/66610762-39d44800-eb82-11e9-952f-2b925d035b22.jpeg)

Note: I think we could expand on this pattern in the future, but I've found myself wanting to do add blocks before the selected one quite often, especially now that we have InnerBlocks.

We might also want to add these options to the `•••` menu on the inline toolbar when we get a chance, similar to web.

**Comment by hypest** [comment]
Aha, I'm not sure how discoverable the long-press will be but, let's go with the proposal, starting with the long-press alone.

The inline toolbar menu can be done in a separate step.

**Comment by iamthomasbishop** [comment]
> I'm not sure how discoverable the long-press will be

I have a feeling it'll be more expected than it seems on the surface (similar to the "empty space at the end of the post" expectation), but considering it's additive at this point, I think it's a good starting point. In the long-run maybe we have a bunch of options, here are a few:

* Show a "floating tip" of sorts
* Add as part of a more comprehensive on-boarding flow 
* Trigger a "tip" after you insert your first block as an explainer

> The inline toolbar menu can be done in a separate step.

Sounds good 👍  I was assuming we wouldn't work on that for a while (until we have that `•••` menu).

**Comment by ceyhun** [comment]
Hello everyone, I'll be working on this 🛠
