### ISSUE TITLE
Media & Text icon shows wrong color in dark mode

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#1441]
![Simulator Screen Shot - iPhone 11 - 2019-10-11 at 15 40 10](https://user-images.githubusercontent.com/8739/66656009-6f8a3700-ec3d-11e9-8a15-de619a2be112.png)

**Comment by etoledom** [comment]
Fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/1443
