### ISSUE TITLE
Focus loop when rotating the device

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#1446]
I've found an issue on the Android side that happens when rotating the device and the caret is in a Paragraph block.

Steps to replicate:
- Start the editor in Portrait orientation on a post with some Paragraph blocks in it
- Set the caret in one of those Paragraph, and let the keyboard show on the screen
- Rotate the device to landscape
- See the issue on the screen
- The caret/focus jumps between paragraph blocks, until stops in one of the blocks

Note: There were few test cases where the editor went into a loop, and needed to go back to posts list.

I made a video of it here:  https://cloudup.com/cOOErAZN87W

- Tested on devices running Android 7.1 and Android 9
- Tested on app version `13.3` downloaded from the Google Store

**Comment by hypest** [comment]
Probably related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1343 too.

**Comment by daniloercoli** [comment]
Yes, I think it's the same issue already reported before. We may need to test this a bit more, since i found some few (random) cases where the editor started a loop and never stopped, until i tapped Back many times to go back to posts list.

**Comment by mchowning** [comment]
I cannot reproduce this issue. The other misplaced-focus-on-rotation issue (#1343) was also closed recently as no longer reproducible, so it appears that these focus issues may have been fixed as a part of some other cleanup.
