### ISSUE TITLE
[iOS] Image not added to post when using iOS home screen shortcut for "New Photo Post"

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1447]
When using the quick action shortcut from the app icon (long-press/3D touch on the app icon), the media picker launches appropriately, but the chosen image isn't actually added to the canvas. There have been [other issues](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1190) related to 3D touch crashing this flow (cc @etoledom), but I'm not seeing a crash here – it's just that the upload isn't happening after a image is chosen. 

Video:

![RPReplay_Final1571089297-edit 2019-10-14 16_48_47](https://user-images.githubusercontent.com/1200432/66785337-8f6e6480-eea2-11e9-868f-267cd1ce93a9.gif)

**Comment by etoledom** [comment]
Thank you for reporting this @iamthomasbishop !
The fix for this issue is coming on WPiOS 13.5 ✅ 

Fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/1383

**Comment by iamthomasbishop** [comment]
Yayyy, thank you! 👏
