### ISSUE TITLE
BottomSheet - change style of RangeCell component

### ISSUE THREAD

**Issue by jbinda** [wordpress-mobile/gutenberg-mobile#1448]
According to discussion [here](https://github.com/WordPress/gutenberg/pull/17282) we need to adjust Slider style before shipping it.

**Comment by pinarol** [comment]
Let's also add Accessibility improvements as stated by @etoledom in this [comment](https://github.com/WordPress/gutenberg/pull/17896#pullrequestreview-305065808).
