### ISSUE TITLE
Image Block Size Options -  UX Production Ready

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#1452]
This is a follow up to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1329 incorporating feedback from https://github.com/WordPress/gutenberg/pull/17245

- [x] Verify Image Size Options UI updates image URL's accordingly
- [x] Update Constant references to re-use size options from existing web code (Thumbnail, Full Size, etc): https://github.com/WordPress/gutenberg/pull/17245/files#r334790181
- [x] Close Bottom Sheet menu before submenu is opened, reopen initial menu when submenu is closed: https://github.com/WordPress/gutenberg/pull/17245#pullrequestreview-301932626

**Comment by cameronvoell** [comment]
@iamthomasbishop I could use your feedback on a simpler approach I am trying out for Image Size Selection (related to comment here: https://mobilegutenberg.wordpress.com/2019/11/27/modal-ui-for-block-settings-weaving-the-best-path-forward/#comment-1580). As you can see in the video below, a line of buttons in the BottomSheet makes the user require one less navigation step, and it lets them quickly switch between sizes and get visual feedback:

![image-size-buttons](https://user-images.githubusercontent.com/1103838/70217379-e7348980-16f5-11ea-98fb-6cdc21be7fa1.gif)

However it's not obvious what icons we would use for buttons. One idea I had came from the documentation for Inspector Controls which shows Paragraph Blocks with buttons for S, M, L, XL:

![image](https://user-images.githubusercontent.com/1103838/70218660-3e3b5e00-16f8-11ea-801b-ff1fe67f6f99.png)

 Perhaps we could do something like that with letters, and it would be clear enough for users if we showed the selected size description in the BottomSheet row (thumbnail, medium, full size, etc) combined with the visual feedback the user sees of the image changing. See letter combinations I was experimenting with below:

![image](https://user-images.githubusercontent.com/1103838/70218708-5b702c80-16f8-11ea-90ca-e2acae66b888.png)

One note is that if we go this route, I will also have buttons retain selected state similarly how they do elsewhere (alignment, heading size selection). I apologize the implementation I have so far is a bit rough, but refining the code ended up more time consuming than I expected, so I figured getting feedback now would probably be wise.

**Comment by iamthomasbishop** [comment]
Thanks for the update, @cameronvoell ! I have a few thoughts.

I'm not sold on the approaches shown above. I don't think either are very clear – the first with the icons is confusing to me (maybe it's just the icons being used?), and in the second the single-letter buttons would confuse me. Beyond that, neither feel native on either platform. With that, I have a couple of suggestions that may simplify, not in any specific order.

### Option 1

On the right side of the cell, only show the current size. Tapping on the cell simply cycles to the next image size. For example if `Small` is the current size, tapping on the cell would change it to `Medium`. We might want to provide a button to reset in this case, perhaps simply add some sort of icon-button for this on the right side of the cell. The downside to this is that it'd require multiple taps, although it's a benefit that you can see what is happening on the canvas.

### Option 2

Display a native UI element – like a Dialog on Android, and perhaps something like an ActionSheet or Picker on iOS. I'm not sure if we are able to provide totally separate native components for an interaction like this, but it may make sense and minimize what we have to build/maintain. Although I'm guessing the iOS ones I mentioned may run into the same problem w/ regards to swapping the sheet in and out.

I might have other suggestions brewing, so I'll drop additional comments if the inspiration strikes 😄

**Comment by cameronvoell** [comment]
Your **Option 1** reminded me of one other style I was trying with up and down arrows for modifying the size. Let me know if you prefer a variant of up and down arrows or if just tapping the size and cycling like you said might be preferred:
![up-down-arrows-image-size](https://user-images.githubusercontent.com/1103838/70257622-7ade7800-173f-11ea-8fb9-65d7bd892ee9.gif)

**Comment by cameronvoell** [comment]
> Option 1
On the right side of the cell, only show the current size. Tapping on the cell simply cycles to the next image size. For example if Small is the current size, tapping on the cell would change it to Medium. We might want to provide a button to reset in this case, perhaps simply add some sort of icon-button for this on the right side of the cell. The downside to this is that it'd require multiple taps, although it's a benefit that you can see what is happening on the canvas.

Hey @iamthomasbishop you can try a build with **Option 1** without the reset button here: (build number 18404.) https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs

Let me know if you think this is an improvement to the second BottomSheet opening over the first like we had before (I think it is!), and is acceptable for releasing Image Size Settings when all networking issues are ready.

**Comment by iamthomasbishop** [comment]
This should work for now, until we have a better standardized selection method built. One thing I noticed is that there is a small bit of empty space on the right side of the cell, maybe 4-8px.

**Comment by iamthomasbishop** [comment]
One more tiny thing: can we make the value label white to match other non-placeholder text labels?

**Comment by cameronvoell** [comment]
@iamthomasbishop See updated with your suggestions here: https://github.com/wordpress-mobile/WordPress-iOS/pull/13052 . There should be a link to a downloadable build soon as well.

**Comment by SergioEstevao** [comment]
@cameronvoell is this work still ongoing, or it's all done now?

**Comment by cameronvoell** [comment]
> @cameronvoell is this work still ongoing, or it's all done now?

All done! Closed via https://github.com/WordPress/gutenberg/pull/19232. I'll go ahead and close this one out.
