### ISSUE TITLE
Images with links that open new tabs do not have rel values when published from mobile

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1458]
## Summary

In my testing, when publishing a post from mobile that will open in a new tab, the resulting link in the published post does not have any `rel` values:

```
<a href="alink.com" target="_blank">
```

whereas publishing a post from web does have "noopener" and "noreferrer" rel values, even if the user inputs no rel values when editing the image link (can only add custom rel values from the web currently):

```
<a href="alink.com" target="_blank" rel="noopener noreferrer">
```

## Background

This issue began occurring because of a recent change that the web side made to stop displaying "noopener" and "noreferrer" rel attributes to the user ([issue](https://github.com/WordPress/gutenberg/issues/15915) [PR](https://github.com/WordPress/gutenberg/pull/17398)). In particular, the addition of "noopener" and "noreferrer" rel attributes [was removed from image blocks](https://github.com/WordPress/gutenberg/pull/17398/files#diff-2ebb49409e6d6a7bdb21daf2c54abc2cL29). The reason behind this change according to the [related issue](https://github.com/WordPress/gutenberg/issues/15915) was just to avoid _displaying_ these two rel values to the user. This fix appears to work fine on web in my testing because a post published from web has those values in the html for the relevant link, but when a post is published from mobile I'm not seeing those rel values in the html of the published post.
 
## Needs Verification

The behavior I am observing seems very odd because, in my testing, both mobile and web are saving the same attributes for the block (and even have the same output from the `save` function), but they're resulting in a different output in the published post. This makes me suspicious that there could be an issue with my testing (although I've reproduced this issue multiple times). If someone else has trouble reproducing this issue, then it seems very possible that there may just be something weird going on with my testing setup.

**Comment by hypest** [comment]
Maybe those attributes are added by the backend (WordPress) itself. Perhaps @donmhico or @jorgefilipecosta can verify.

**Comment by hypest** [comment]
Is this still occurring? If yes, can we add steps to reproduce? Thanks!

**Comment by mchowning** [comment]
I cannot reproduce this issue on WPAndroid alpha-234, so closing.
