### ISSUE TITLE
Final set of templates for MVP

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#1468]
During the development of the Templates MVP we will have the two templates defined in #1462. By the time we are ready to launch, we expect to have more supported blocks, which will unlock more and better templates.

The final set of templates is not decided yet, adding this issue as a placeholder

**Comment by pinarol** [comment]
@iamthomasbishop I think it is time to start making some real templates as we are mostly clear about what blocks will be available until the end of January. 

We have 3 **recently available** blocks:

Media-Text
Gallery
Spacer

We have 3 **upcoming** until the end of January:

Button
Column
Group

But just for minimizing the risk I recommend preparing a small set of basic templates with what we already have first.

But it is still a good idea to prepare a few more that can include: Buttons, Column, Group. 

Our planned deadline for the 1st iteration of SPTs is end of January 2020. So let's talk about our possibilities for what we can provide for the 1st iteration.
