### ISSUE TITLE
Update wording on the "Block editor enabled" dialog

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/gutenberg-mobile#1480]
The current string is nudging people to switch back to Classic. The message should be more neutral, current message:

```
You're currently using the block editor to create new pages. Want to use the classic editor by default? Head to Site Settings.
```

There was some back and forth about this on this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10254

Note that I opened the ticket in `wordpress-mobile/gutenberg-mobile`, but the string must be changed in each app repo.

**Comment by maxme** [comment]
We will probably remove that dialog completely after v2 release.

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/10678, https://github.com/wordpress-mobile/WordPress-iOS/pull/12761.
