### ISSUE TITLE
E2E tests failing locally 

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/gutenberg-mobile#1482]
The UI tests are having trouble detecting html content locally and keeps returning `html-view-content` which causes all the tests using that to fail. This is probably related to XCode 11 since on CI everything seems to still work fine.

**Comment by rachelmcr** [comment]
I took a quick look at the tests locally and I see those iOS failures. It looks like the tests find the HTML text view correctly but are returning the text view's accessibility label (`html-view-content`) instead of its value (the HTML content).

**Comment by geriux** [comment]
Closing since E2E tests are now running locally without any issues.
