### ISSUE TITLE
Block Picker: Layout is messed up/not all blocks appear on screen after rotating device

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#1491]
If you open the block picker and then rotate the device, the block picker layout is messed up. Not all blocks appear on screen and there's no way to navigate to them. The only solution is to close the block picker and reopen it.

### Steps to reproduce

1. With the device in portrait mode, start a new post.
2. Open the block picker.
3. Rotate the device to landscape. Note that the blocks don't use the full width of the screen and not all blocks fit on screen.
4. Close the block picker and reopen it.
5. Rotate the device to portrait. Note that some blocks don't appear on screen.

In addition, rotating the device with the block picker open on Android makes the keyboard appear. This doesn't cause any issues once the keyboard is closed, but it does interfere with viewing/interacting with the block picker.

### Screenshots

iOS - rotating portrait to landscape:

![2019-10-24 08 51 28](https://user-images.githubusercontent.com/8658164/67472169-9c304c80-f648-11e9-91d2-ffa5f6319ac7.png)
![2019-10-24 08 51 31](https://user-images.githubusercontent.com/8658164/67472170-9c304c80-f648-11e9-887b-887e2f47b9f0.png)

iOS - rotating landscape to portrait (8 blocks instead of 10):

<img src="https://user-images.githubusercontent.com/8658164/67472197-ab16ff00-f648-11e9-85db-7dd2c3d0e945.png" width="50%">

Android - rotating portrait to landscape:

![Screenshot_20191024-101938](https://user-images.githubusercontent.com/8658164/67472341-dc8fca80-f648-11e9-96ba-5860514f6a35.png)

Android - rotating landscape to portrait:

<img src="https://user-images.githubusercontent.com/8658164/67472348-df8abb00-f648-11e9-8a9d-a238961e865b.png" width="50%">

Tested on:

* WordPress iOS 13.5.0.20191021, iPhone XS, iOS 13.1.4
* WordPress Android alpha-192, moto e5 play, Android 8.1.0

**Comment by hypest** [comment]
> In addition, rotating the device with the block picker open on Android makes the keyboard appear. This doesn't cause any issues once the keyboard is closed, but it does interfere with viewing/interacting with the block picker.

I think that's covered in https://github.com/wordpress-mobile/gutenberg-mobile/issues/1333

**Comment by designsimply** [comment]
Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/1495. Props @etoledom. 🎉
