### ISSUE TITLE
Media & Text - Image url is inserted into videos if post is closed/reopened during the upload

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1508]
Detected during testing #1503.
Also reproducible @ 9f4afd6 develop
Tested with iPhone 8 plus, iOS 13.1

Reality:

- Add media & text block, tap placeholder and choose Choose from device
- Select a video
- Start upload but before it finishes close the post by selecting Update Post
- Re-open the post before upload finishes
- Wait until upload finishes
- Video is shown as blank
- Switch to html editor
- An image url is seen instead of the video url, and that image url is the cover url of the video
- Lastly, when you open the WPMedia library you can see that cover urls are uploaded there unintentionally:

<img width="433" alt="Screen Shot 2019-10-28 at 21 21 50" src="https://user-images.githubusercontent.com/5032900/67705923-f9b9f580-f9c8-11e9-81fb-c1e1e4ca7f8c.png">

Expected:

- Add media & text block, tap placeholder and choose Choose from device
- Select a video
- Start upload but before it finishes close the post by selecting Update Post
- Re-open the post before upload finishes
- Wait until upload finishes
- Verify that video is shown properly
- Switch to html editor
- Verify that video url should be seen
- Lastly, verify that cover picture of video is not uploaded to WPMedia library

**Comment by etoledom** [comment]
Fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/1506
