### ISSUE TITLE
Media & Text - Block validation error occurs if media upload finishes when the post is closed

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1509]
Detected during testing https://github.com/wordpress-mobile/gutenberg-mobile/pull/1503.
Also reproducible @ 9f4afd6424481c786e00c692e225d6fc3e105386 `develop` 
Tested with iPhone 8 plus, iOS 13.1

- Add media & text block, tap placeholder and choose Choose from device
- Start upload but before it finishes close the post by selecting Update Post
- Wait until the upload finishes
- Re-open the post and you'll see:

<img width="425" alt="Screen Shot 2019-10-28 at 15 24 52" src="https://user-images.githubusercontent.com/5032900/67678489-c90d9800-f997-11e9-8167-8c3adf52dd74.png">

- Switch to html mode, meda-text is still showing the upload id:

<img width="435" alt="Screen Shot 2019-10-29 at 11 09 33" src="https://user-images.githubusercontent.com/5032900/67751394-17777100-fa42-11e9-81da-40a5b577d30c.png">

![mediaTextUpload2](https://user-images.githubusercontent.com/5032900/67678546-e80c2a00-f997-11e9-9ea9-b129544364d8.gif)

Expected: 
- Add media & text block, tap placeholder and choose Choose from device
- Start upload but before it finishes close the post by selecting Update Post
- Wait until the upload finishes
- Re-open the post 
- Verify that no red screen occurs
- Switch to html mode
- Verify that the mediaId is correct(usually a shorter and a positive number)

**Comment by koke** [comment]
Tested on WPAndroid develop with 1.15.1 and could reproduce the issue.

**Comment by etoledom** [comment]
Fixed via https://github.com/wordpress-mobile/WordPress-iOS/pull/12797 and https://github.com/wordpress-mobile/WordPress-Android/pull/10710
