### ISSUE TITLE
BR tags in Quote block are removed in Android

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#1518]
Found a problem with the Quote block where BR tags in the middle of the content are removed when opening the block on mobile. 

![Screenshot 2019-10-30 at 17 16 44](https://user-images.githubusercontent.com/518232/67876971-11b08700-fb39-11e9-8599-bf96b1fdeaa6.png)

The HTML code of the block is the following:
```
<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>This is a quote block that has BR tags in the middle of it<br><br><br><br><br><br></p><p>The empty lines are above</p></blockquote>
<!-- /wp:quote -->
```

If you open it on mobile, the block is displayed without those BR tags, and modifying one part of the post (even if it's on another block) will result in HTML sent to the server without those "BR tags".

**Comment by designsimply** [comment]
We received a report in https://github.com/wordpress-mobile/WordPress-Android/issues/11031 (moved to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1727) that this problem happens for code blocks as well.

**Comment by hypest** [comment]
Can't replicate the "removal" part of this issue. The empty lines are not displayed in the mobile block editor indeed, but the content still has them even after adding/editing a secondary paragraph block. Tested on WPAndroid v15.0-rc-3, Pixel 2XL Android 10.
