### ISSUE TITLE
[Android] Extra backspace in paragraph blocks with formatting

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1524]
On Android only, removing formatted text from a paragraph block can get you to a state where there is no formatting and no placeholder appearing. You have to press backspace an extra time to get the placeholder to appear.

#### Steps

1. Add a paragraph block with some text
2. Apply formatting to all the text 
3. press the backspace key once for each character in the text
4. Observe that the paragraph block is empty, with no formatting active, and without the placeholder appearing (if you check the html at this point, you will see that it is `<p></p>`, and that when you return from the html view the placeholder will be showing)
5. Press backspace again
6. Observe the placeholder text appear

![android_extra_backspace mp4](https://user-images.githubusercontent.com/4656348/67950412-e45aec00-fbbf-11e9-93dd-840e5a84cf42.gif)

**Comment by hypest** [comment]
Confirmed still happening on WPAndroid v15.0-rc-3.

**Comment by mchowning** [comment]
If the rich text view is in the state where the placeholder is not showing, typing the `@` character will not trigger the mentions UI. Instead, you have to tap the backspace key an extra time (so that the placeholder shows up) and then the `@` character will trigger the @-mentions.

Thanks to @designsimply for raising this. :bow:
