### ISSUE TITLE
Refine background/icon of image block transitional state

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1544]
While reviewing [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/12834), I noticed something that's been bugging me about the image block in general – the icon that sits over the background during upload progress is way too large and the wrong color. It looks like this:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/1200432/68231963-aeec3f00-ffc1-11e9-84de-4840aa265dbb.png">

It looks like the Video block has the "proper" styling, which IIRC is:

* Background: good as-is (same as global placeholder background, which IIRC is `gray-light` from [Colors Archive](https://dotcombrand.wordpress.com/colors-archive/) in `light mode` and `gray 90` from [Color Studio](https://color-studio.blog) in `dark mode`)
* Icon size: 32x32
* Icon color (`light mode`): `gray-lighten-20` from [Colors Archive](https://dotcombrand.wordpress.com/colors-archive/)
* Icon color (`dark mode`): `gray-70` from [Color Studio](https://color-studio.blog)

Which looks like this:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1200432/68232230-40f44780-ffc2-11e9-814a-caab610745bf.png">

## Tasks

- [ ] Apply above styling to image block upload state placeholder
- [ ] Cross-reference other blocks that have this sort of "in between" state/background, to ensure we are matching the above styling?

**Comment by cameronvoell** [comment]
Adding a note here that there is another issue in this feature that may be able to be tackled simultaneously - incorrect loading bar position: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1641

**Comment by iamthomasbishop** [comment]
Thanks, @cameronvoell!
