### ISSUE TITLE
Deleting text and updating paragraph alignment fails to update cursor alignment

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1545]
## Summary

This is an iOS-specific bug that @SergioEstevao caught with the [recent introduction of alignment for paragraph blocks](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1489). If you select a paragraph block with text in it, delete the text in that block, and update the alignment for the text in that block, the placeholder's alignment will be updated, but the cursor itself will not update.

## To Reproduce

Step # | Step | Info
--- | --- | ---
1a | (Alternative a) Load a post with a paragraph block that already has text | The text can be either aligned or unaligned. The bug will not occur if you load a post with an empty paragraph block.
1b | (Alternative b) Create a new block, add text to it, and then deselect and reselect that block. | Focus must leave the block in question, if you remain focused on the block the whole time then the bug will not appear.
2 | Delete all the text from the paragraph block | The bug appears regardless of whether you change the alignment before deleting all the text in the block
3 | Update the alignment of the empty block | The block must be empty, if you delete all the text and add any text back, then the bug does not appear.

## Expected behavior
Updating the alignment for a paragraph block should always update the alignment of the cursor and placeholder (if the placehodler is visible).

![](https://user-images.githubusercontent.com/651601/67718924-b65f8700-f9c8-11e9-9a3d-6111b67bf8fd.gif)

**Smartphone:**
 - Device: iPhone Xr, 11
 - OS: iOS 13.1, 13.2

**Comment by SergioEstevao** [comment]
I think this issue was sorted by these PRs:

- https://github.com/wordpress-mobile/gutenberg-mobile/pull/1541
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/1517

Both of them refresh the content when deleting all the content and force relayout so they improve the refresh of cursor position.

**Comment by SergioEstevao** [comment]
I can no longer reproduce this on release 1.17 branch so I'm closing this.
