### ISSUE TITLE
Pexels/device media library: Deleting inserted image before the post's online crashes the app

### ISSUE THREAD

**Issue by arunsathiya** [wordpress-mobile/gutenberg-mobile#1549]
**Describe the bug**

When I attempt to delete an image added from Pexels or from the device media library, before that post is saved online, the app crashes. 

**To Reproduce**

- Get the WordPress Android 13.6-rc-1 version of the app.
- Add an image block.
- Add an image from Pexels or from the device media library.
- While that post is still locally saved (not uploaded online), delete that image block

**Expected behavior**

The image block is removed without crashing the app.

**Screenshots**

![Screenshot_20191106-200536](https://user-images.githubusercontent.com/18581859/68309057-e1865c80-00d3-11ea-884b-f388cd0cd314.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android 9
 - Version: WordPress Android 13.6-rc-1

**Additional context**

I found that this does not happen only for Pexels. This happens for images added from the device media library (not site media library) as well.

**Comment by designsimply** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/10491 and noting there is a fix incoming (props @marecar3 🎉) which we should see show up in 13.7.
