### ISSUE TITLE
Deleting image blocks before the post's online refreshes the app once and uploads the post

### ISSUE THREAD

**Issue by arunsathiya** [wordpress-mobile/gutenberg-mobile#1551]
**Describe the bug**

When an image from the site media library is added to an image block, deleting that block (before the post is uploaded online), refreshes the app once and then post starts uploading online. During the brief period where the app refreshes itself, a white screen is seen.

**To Reproduce**

- Add an image block.
- Add an image to it from the site media library. (Do not add from Pexels or device media library, which has a different issue https://github.com/wordpress-mobile/gutenberg-mobile/issues/1549)
- Delete that block, before the block gets uploaded online.

**Expected behavior**

The block is deleted.

**What happens instead**

The app refreshes itself, for a few seconds, and the view with site controls (pages, posts etc) appears again. The post can be also be seen to be uploading online at this stage.

**Screenshots**

NA

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android 9
 - Version: WordPress Android 13.6-rc-1

**Additional context**

Different issue with Pexels/site media library - https://github.com/wordpress-mobile/gutenberg-mobile/issues/1549

**Comment by hypest** [comment]
> and the view with site controls (pages, posts etc) appears again

If I understand this correctly, that's the screen before the the editor itself? If yes, then that means the editor actually crashed and reloaded on its own. I'd file that as a crash.

Does the issue still happen?

**Comment by arunsathiya** [comment]
>If I understand this correctly, that's the screen before the the editor itself? 

That is correct, yes. 

>Does the issue still happen?

I cannot reproduce this anymore though! 😀This is on WordPress for Android - version 14.9.

Marking this issue as closed.
