### ISSUE TITLE
Media-Text: Image gets out of the bounds intermittently

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1554]
**Describe the bug**

Image is getting out of the bounds of media-text block in a certain scenario.

**To Reproduce**

1. Start a new post
2. Add media-text block
3. Enter some text into media-text, keep keyboard open
4. Tap media placeholder and insert image from WP media library
5. Wait until image is downloaded
6. Tap on the image

Result: Image gets out of the bounds of media-text

**Expected behavior**

Image position shouldn't change

**Screenshots**

<img width="250" alt="Screen Shot 2019-11-07 at 10 59 35" src="https://user-images.githubusercontent.com/5032900/68370504-b3ddf980-014d-11ea-8b82-806cdf53af78.png">

![mediaTextLayout2](https://user-images.githubusercontent.com/5032900/68370547-cb1ce700-014d-11ea-9ac8-ac1fae14faf9.gif)

**Smartphone (please complete the following information):**

 - Device: iPhone 8 Plus simulator
 - OS: iOS 13.1
- Reproducible on gutenberg-mobile/develop e49f509e94af72e5c5533afc2902a9eda3573375

I tried it on WPAndroid as well but couldn't reproduce.

**Comment by lukewalczak** [comment]
I think it's fixed within https://github.com/WordPress/gutenberg/pull/18300. Could you please test it?

**Comment by lukewalczak** [comment]
ios | android
--- | ---
![image_mt_ios](https://user-images.githubusercontent.com/22746080/68477696-5ff71180-022e-11ea-87b8-82ad82b1b8e0.gif) | ![image_mt](https://user-images.githubusercontent.com/22746080/68477701-61c0d500-022e-11ea-9ae5-e74008374d9c.gif)

**Comment by lukewalczak** [comment]
Closed via PR https://github.com/WordPress/gutenberg/pull/18300.
