### ISSUE TITLE
Stepper component

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1562]
We need a Stepper component to represent controls that has ≤ 6 or 8 options. At the moment, we'll use this to manage columns setting on Gallery and Columns blocks replacing the Slider there.

**Describe the solution you'd like**

Stepper should look different on both platforms:

@iamthomasbishop Could you provide designs with size, color, etc info as well as the dark mode version?  

<img width="276" alt="66678029-95f5a580-ec30-11e9-9256-0bcb69c2cd6f-1" src="https://user-images.githubusercontent.com/5032900/68485166-d35d4b00-024f-11ea-9617-e5d52e7db64e.png">

**Additional context**

We had a discussion about using the native Stepper on iOS but then we agreed on implementing this fully on RN side since we are only planning to use this for controls that has ≤ 6 or 8 options currently.

**Comment by pinarol** [comment]
@lukewalczak could you share the callstack library that provides the Stepper component? We can use it if it fits our needs or get inspiration from it.

**Comment by lukewalczak** [comment]
Sure! I would suggest looking at the [Stepper](https://github.com/callstack/react-native-ios-kit/blob/master/src/components/Stepper.js) logic, especially in the context of "autorepeating" behaviour.

**Comment by geriux** [comment]
Hey @iamthomasbishop 👋 could you please share design specs for this component? Colors, Dark mode styles, etc.

Thanks!

**Comment by lukewalczak** [comment]
Hey @geriux! You can find a design details on [Zeplin](https://app.zeplin.io/project/5bfecbea71ce881122eadd2f/screen/5dcdccecab1ef03b2a05bd55)

**Comment by geriux** [comment]
> Hey @geriux! You can find a design details on [Zeplin](https://app.zeplin.io/project/5bfecbea71ce881122eadd2f/screen/5dcdccecab1ef03b2a05bd55)

Awesome, thank you!!
