### ISSUE TITLE
Editor close button unresponsive until editor fully loads

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#1567]
**Describe the bug**

While waiting for the editor to load in either WPiOS or WPAndroid, the close button is unresponsive. (It can be tapped, but it doesn't do anything.)

**To Reproduce**
1. Go to My Sites > Blog Posts.
2. Start a new post or open an existing post. (This issue may be more evident when opening an existing post with a lot of content, per https://github.com/wordpress-mobile/gutenberg-mobile/issues/1179.)
3. Before the editor finishes loading, try to close it.

Result: Until the editor fully loads (title, content, format bar) the close button doesn't do anything.

**Expected behavior**

I expect to always be able to close the editor, once the button becomes tappable.

**Screenshots**

Example of WPiOS when the close button is tappable but doesn't do anything:

<img src="https://user-images.githubusercontent.com/8658164/68600702-e4e66300-049a-11ea-90d4-e140f02c3960.jpg" width="50%">

**Smartphone (please complete the following information):**
 - Device: Multiple, including iPhone XS and moto e5 play
 - OS: Multiple, including iOS 13.2 and Android 8.1
 - Version: WPiOS and WPAndroid 13.6 betas

**Additional context**

Originally observed while working on UI tests for WPiOS.

**Comment by hypest** [comment]
Issue doesn't happen on WPAndroid v15.0-rc-3 for Android. The editor closes immediately if "Back" is pressed while loading a long post.

OTOH, the issue still happens for v15.0 (TestFlight version) of WPiOS so, I'll mark this ticket as iOS only.

**Comment by SiobhyB** [comment]
I was no longer able to reproduce on 24.2 of the iOS app.
