### ISSUE TITLE
Build on iOS fails silently if Carthage is not installed

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#157]
I ran `yarn run iOS` on a new machine and I got an unrelated error. It took me a while to scroll back and see the `carthage: command not found`.

We should fail early if any of the required tools are missing

**Comment by hypest** [comment]
Hey @diegoreymendez , any idea how to go about for this one?

**Comment by koke** [comment]
I think I’d start by replacing all the `;` with `&` in npm scripts (see [Exiting](https://docs.npmjs.com/misc/scripts#exiting)). I’m not sure if that’ll work for pushd/popd or we might have to move some things to their own shell scripts.
