### ISSUE TITLE
Basic video alignment options

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#1573]
The video block should have the same alignment options as the image block, discussed in https://github.com/wordpress-mobile/gutenberg-mobile/issues/198.

![Screenshot 2019-11-13 09 38 12](https://user-images.githubusercontent.com/8658164/68751334-52100a80-05f9-11ea-870f-31d460af598b.png)

Basic alignment options (left, right, center) were implemented for the image block in https://github.com/WordPress/gutenberg/pull/17962 and https://github.com/wordpress-mobile/gutenberg-mobile/pull/1460.

Raised by a beta tester using WPAndroid 13.6-rc-1.

**Comment by hypest** [comment]
Tested on WPAndroid v15.0-rc-3 (but it's been there for a while, not sure exactly since when), basic alignment controls (left/center/right) are available for the video block as well so, closing this ticket.
