### ISSUE TITLE
[i18n] Sending wrong strings for translation 

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1586]
**Describe the bug**
We are exporting string for translations from unit tests. This is a problem since the `@wordpress/i18n` module has some translation strings on unit tests meant just to test the library:

https://github.com/WordPress/gutenberg/blob/ff6afdad160f73b88eba3b427ad2fd15c87fc9a0/packages/i18n/src/test/index.js#L101

We capture them for translation:

https://github.com/wordpress-mobile/gutenberg-mobile/blob/52c89f1e2e2310985e04186da43986ee97681b58/bundle/ios/GutenbergNativeTranslations.swift#L83

And they get translated:

https://translate.wordpress.org/projects/apps/ios/dev/ru/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=8643644&filters%5Btranslation_id%5D=67652791

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/1624/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R80-R81. Closing this ticket.
