### ISSUE TITLE
Dynamic system background colors inherited from Aztec cause RichText/Canvas backgrounds to clash

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1591]
Our RichText components (using Aztec) inherit dynamic `systemBackground` colors on iOS – which is great – but unfortunately, our canvas background does not have that ability. This is fine and dandy until you go into multi-tasking modes, where there becomes a clash of fill colors between the RichText instances' backgrounds and our canvas background. It looks like this:

![IMG_0667](https://user-images.githubusercontent.com/1200432/69083870-9b50c780-0a08-11ea-9748-7e2296ccb6fa.jpeg)

Note: this isn't noticeable in single-app mode because our background color (`black`) is the same as iOS `systemBackground`.

**To Reproduce**
0. Switch iPad to Dark Mode
1. Make sure app is in multi-tasking/split-screen mode
2. Open a post or page w/ any RichText block on it (Paragraph, Heading, etc)
3. See mis-match between black background and RichText fill

## Proposal

I'm open to suggestions, but it seems like the best (and most flexible) solution would be to remove the background fill altogether from the Aztec component either by:

* Removing on our end by manually overriding the behavior 
* Making the change on Aztec so that there is no fill (or a transparent fill). 

We're soon going to introduce background colors on blocks like Media & Text, Cover, Button, etc. so maybe it makes sense to go fully transparent at the source (Aztec).

**Device:**
 - iPad Pro 10.5"
 - OS: iOS 13.3b1
 - Version WPiOS 13.7b

**Comment by SergioEstevao** [comment]
For the record we could also set the canvas color to be the system background color. We just need to set the color on top background view we have in RN.

What is the color you want to use for the background in dark mode? pure black?

**Comment by iamthomasbishop** [comment]
> For the record we could also set the canvas color to be the system background color.

That's amazing, I did not know that! Let's do that for starters (set the canvas background to use the dynamic system background color). I think doing that will remove the mismatch between the canvas and RichText, but I think we can make this bullet-proof for the aforementioned examples by removing the background fill altogether from RichText.

**Comment by hypest** [comment]
👋 @SergioEstevao can you plan to work on this in the first opportunity? I'll assign you the ticket in the meantime, cool?

**Comment by SergioEstevao** [comment]
@iamthomasbishop I've been testing this today and it looks it no longer happens can you confirm it ?

**Comment by iamthomasbishop** [comment]
@sergioestevao I can also confirm that it is not happening on iPad using iOS 13.4 beta, but it’d be good to double check 13.3 (unless you already have).

**Comment by SergioEstevao** [comment]
I tested on 13.1.2 release of iOS.

**Comment by SergioEstevao** [comment]
This got solved by this change: https://github.com/WordPress/gutenberg/pull/19722/files#diff-412d95d265a95fcbe366a4b879d184a3R6

Now all RichText components have a transparent background so this is no longer a problem.
