### ISSUE TITLE
[iOS] Flash of double-spaced content while loading the post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#1596]
**Describe the bug**

While the post content is loading (when first opening the editor or when updating a post), I see a flash of double-spaced content. This is most obvious on a post with more content.

**To Reproduce**
1. Create a new post.
2. Add at least ~200 words of text (more content may help see the issue more clearly).
3. Save the post as a draft.
4. Tap "Update" to update the post content.
5. Watch as the spacing changes in the content while the post is being saved.

**Expected behavior**

I expect the post to be saved/updated with no visual change to the content in the editor.

**Screenshots**

Screencast here: https://cloudup.com/c8ebVYIPQDp

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 13.2.3
 - Version: WPiOS 13.6 and 13.7.0.20191118

**Comment by hypest** [comment]
👋 @rachelmcr , I wonder, does this still happen on recent app versions?

**Comment by rachelmcr** [comment]
I'm not seeing this anymore (tested in 15.0.0.20200611 beta but I also haven't recalled seeing it while dogfooding in any recent versions); closing as resolved.
