### ISSUE TITLE
Support for inline css coloring

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1603]
Aztec supports collored text via inline CSS styles so, for Aztec parity the block editor could support it too.

Edit: Aztec (Android) supports _rendering_ the styled text via `style="color:hex-or-default-color-name"`.

**Comment by SergioEstevao** [comment]
@hypest  Are we talking just displaying the colors? or have user interface to set the colors?

For displaying iOS can show the color if they are set using ```style={color:0xFF0000}``` but not if they refer to CSS defined colors.

**Comment by hypest** [comment]
Tried surrounding a single word in a Paragraph block with `<span style="color:red">word</span>` and works OK in gutenberg-mobile for Android (and WPAndroid) but not on iOS (demo app nor WPiOS). I'll mark this as iOS only.

> @hypest Are we talking just displaying the colors? or have user interface to set the colors?

I'll update the ticket description to denote that we're referring to just rendering the color, not having a UI for it (Gutenberg-web doesn't have a UI for individual text coloring inside a paragraph either).

**Comment by SergioEstevao** [comment]
@hypest 'red'  doesn't work in iOS

'''<span style="color:red">word</span>'''

but this works fine:

```
style={color:#FF0000}
```

I can add support for standard colors in HTML to Aztec to allow the 'red', 'blue' and others...

**Comment by SergioEstevao** [comment]
@hypest does Android support all of this: https://www.w3schools.com/colors/colors_names.asp ?

**Comment by hypest** [comment]
> I can add support for standard colors in HTML to Aztec to allow the 'red', 'blue' and others...

Yeap, let's go that route to align the platforms.

**Comment by hypest** [comment]
> @hypest does Android support all of this: https://www.w3schools.com/colors/colors_names.asp ?

Here are the names supported in Aztec Android: https://github.com/wordpress-mobile/AztecEditor-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/util/ColorConverter.kt#L31

**Comment by hypest** [comment]
Fixed by https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1243
