### ISSUE TITLE
Allow media within media & text block to be selected

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1607]
It's confusing that you can't select the media part of the Media & Text block but you _can_ select the other side's blocks. The result of this is that you don't get the associated controls and interactions that a "normal" image or video block would offer. In other words, I would expect the media side to act as InnerBlocks of the Media & Text block.

**To Reproduce**
1. Select a Media & Text block with an image on one side and some text block on the other side
2. Try tapping on the image part
3. Notice nothing happens, the Media & Text block ("parent") remains selected
4. Try selecting text on the other side
5. Notice that this works as you'd expect it to (as a "child" of the Media & Text block)

**Example**

![image](https://user-images.githubusercontent.com/1200432/69362598-6d5fc300-0c54-11ea-8c58-05f59b8eaf35.jpeg)

**Comment by hypest** [comment]
👋 @pinarol , can this one perhaps be moved to a GutenPages project?

**Comment by pinarol** [comment]
> 👋 @pinarol , can this one perhaps be moved to a GutenPages project?

Yeah let's take care of this inside GutenPages. @hypest

**Comment by koke** [comment]
> I would expect the media side to act as InnerBlocks of the Media & Text block

That would be interesting, but I wouldn't try to fake it just for mobile. We can explore what it'd take to make media-text use inner blocks, but I think we might hit some limitations of the format. For the media part, we'd have two options:
- Use a template lock to limit contents to one children, but then you can only lock it to either an image or a video block
- Don't use a template lock and allow only image/video as the children, but then you can't limit it to one child only.

It would also seem interesting to explore how to implement cardinality constraints on InnerBlocks, so you can specify a maximum of 1 child. That could also help with the issues we were discussing around columns and the insert/remove behavior when the number of items is constrained.
