### ISSUE TITLE
Adding an emoji in title adds an opening <strong> tag, resulting in entire body text being bold

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1613]
When adding an emoji to the title, an opening `<strong>` Tag is added  (no closing tag), result is that the entire body of the post is set in bold. Not sure if this is also happening on Android, as I don’t have my Android device on me to test atm.

**To Reproduce**
1. Add a post title with an emoji to a post or page
2. Save
3. Go to posts/page list, see `<strong>` Tag is added on title
4. Preview post, see body text is all bold

**Screenshots**

![03134E7F-00D7-40E0-A634-22796D83F08F](https://user-images.githubusercontent.com/1200432/69481299-c3a83f80-0dd5-11ea-9b0c-0a809723c03a.jpeg)
![08A802EB-B4BB-4B8A-AF1B-2BC2F98680EF](https://user-images.githubusercontent.com/1200432/69481301-c3a83f80-0dd5-11ea-83a7-d23ed8626340.jpeg)
![D5F28418-31F6-4E35-BED4-827C3719AB07](https://user-images.githubusercontent.com/1200432/69481302-c440d600-0dd5-11ea-86c4-0f5e2875b79d.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.1
 - Version: 13.7 internal beta

**Comment by SergioEstevao** [comment]
Fixed on release 1.23 of GB
