### ISSUE TITLE
Add separator between list-type and indentation controls on List block toolbar

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1614]
There should be a section separator (vertical line) between the list-type and indentation controls on the List block toolbar.

![5DCA000F-38E3-4D9D-9097-FFD6C18C46A4](https://user-images.githubusercontent.com/1200432/69483416-ceba9a00-0dec-11ea-9199-96832e9712d2.jpeg)

**Comment by SergioEstevao** [comment]
@iamthomasbishop I don't see this separator on the web, do we want to make this divergence in the native code?

**Comment by iamthomasbishop** [comment]
Oh wow, for some reason I thought the web had a separator there 🤔 I had expected a separator there because they seem like separate functions – the list-type is almost like a style variation, whereas the indent/outdent is an inline control for the content itself. 

I'm tempted to add a separator there out of principle, but I understand if we don't want to move away from Core for the sake of principle 😄 

@maxme – Do you have any opinion on this?

**Comment by hypest** [comment]
> I understand if we don't want to move away from Core for the sake of principle

Sounds more like a case where touching base with designer(s) on the web side would be the next step I'd propose. We can add the separator for both platforms easily (I think) if there's consensus. I personally don't have an opinion about whether to have the separator or not in this case.

**Comment by maxme** [comment]
I agree with @hypest - I'd prefer to add a separator for both Web and mobile or keep the current design without it.

**Comment by iamthomasbishop** [comment]
Ok, sounds good. We can close this one for now.
