### ISSUE TITLE
"Use Block Editor" toggle getting out of sync

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1632]
### Describe the bug
On Android, the "Use Block Editor" toggle frequently gets out of sync and/or toggles on its own.

### To Reproduce
1. Observe "Use Block Editor" toggle set to on
2. Tap the toggle two times very quickly
3. Observe that the toggle update to "off" and back to "on" as you would expect when you tapped it
4. Observe that after about 1 second the toggle switched back to "off" with no user interaction.

Here is a video of me following those steps (it's hard to tell in the video, but I tapped the toggle two times): https://cloudup.com/cAJgGu0ZnCP

### Expected behavior
The toggle should (1) switch once for each time the user taps it and (2) accurately reflect the preference state on the backend.

### Smartphone
 - Device: Pixel
 - OS: Android 10
- Gutenberg-mobile hash: 27486217

### Additional context
Looking at the Charles logs, the backend call for the first toggle's call is taking ~700ms, whereas the second call is taking ~150ms. I wonder if this issue might be related to the responses coming back out of order because the first call takes longer than the second. Interestingly, when I check iOS (which does not seem to have these problems with the toggle state as best I can tell), I am consistently seeing the opposite pattern: on iOS the first call is quicker at around 150ms and the second call is longer at ~700ms.

**Comment by mchowning** [comment]
I have [proposed a fix for a different "Use Block Editor" toggle issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1633#issuecomment-559304017), that I believe would also likely resolve this issue.

**Comment by mchowning** [comment]
A somewhat related issue I've noticed: frequently on a fresh install if I log into the app and immediately open a post I will get the Aztec Editor instead of gutenberg. Backing out and checking the toggle will show that the block editor is toggled on in the site settings. If I then go back to the editor again, the gutenberg editor usually loads. It seems that it is defaulting to Aztec until it gets the http call response back.

**Comment by guarani** [comment]
Noting that as we remove the editor preference switch (https://github.com/wordpress-mobile/gutenberg-mobile/issues/3092) – something we're first addressing on Simple sites, then Atomic, etc – this issue will become less impactful.

**Comment by SiobhyB** [comment]
Closing as the toggle was fixed in May, 2022, as part of https://github.com/wordpress-mobile/WordPress-Android/pull/16517. I also removed the `[Pri] High` label to reflect the fact the toggle is now only available to a relatively low percentage of our users.
