### ISSUE TITLE
Refactor Caption component to make it available for Gallery tiles

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1639]
We have a Caption component used by Image, Video blocks but it is assuming that Caption is put on block level. So we weren't able to use it from Gallery tiles. Let's divide that component into 2 and make the UI part available for individual tiles of Gallery.

In theory we can rename the current one as BlockCaption and extract the UI part into a component named Caption. Image, Video blocks can use BlockCaption while tiles use Caption.

Otherwise we'll need to duplicate fixes like [this](https://github.com/WordPress/gutenberg/pull/18818) in gallery tiles.

**Comment by pinarol** [comment]
@geriux Gallery PRs aren't merged yet, so we are using [this PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1498) branch to test it. You can collaborate with @mkevins about Gallery.

**Comment by iamthomasbishop** [comment]
@pinarol would it make sense to solve this issue (https://github.com/wordpress-mobile/WordPress-iOS/issues/13063) on our end GB while we are doing this refactoring of the caption component? Or is it better solved at the Aztec level?

// hat tip @designsimply for finding the issue! Perhaps also related to this one? https://github.com/wordpress-mobile/gutenberg-mobile/issues/1609

**Comment by pinarol** [comment]
🧐 That looks like a very different issue which will require us to touch different parts of the code. So better be handled separately. @iamthomasbishop

**Comment by iamthomasbishop** [comment]
Ok, fair enough. Thanks for confirming!
