### ISSUE TITLE
Incorrect Loading bar position on Image Block

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#1641]
**Description**
While uploading an image on the image block, the loading bar sometimes appear on the bottom of the image instead of the top where it should be. 

**To Reproduce**
1. Add an image block in the block editor
2. Click add image => Choose from device => Pick a large picture
3. Observe during image upload, loading bar is seen on the bottom of the image block. 

**Expected behavior**
Loading bar should appear at the top of the image block during image upload. See video block for correct behavior. 

**Screenshots**
![Screenshot_20191202-134847_WordPress](https://user-images.githubusercontent.com/1103838/69999676-0d97d080-150e-11ea-9859-673b1e6ca6b0.jpg)

**Comment by SergioEstevao** [comment]
@cameronvoell Is this still happening to you? I couldn't reproduce it?
