### ISSUE TITLE
Tapping on a different block when text is selected shifts focus multiple times

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1643]
## Describe the bug
On Android, when changing focus from a paragraph block with selected text to a different paragraph block, the focus shifts between the two blocks more times than it should (i.e. 2 or 3 times instead of just once)

## To Reproduce

1. Create two paragraph blocks containing text
2. Select some text in block 1
3. Tap on block 2
4. Observe the focus shift from block 1 to block 2, then back to block 1, and possibly even back to block 2 again (in the video below, the focus only shifts 2 times, to block 2 and back to block 1).

![selection-cursor-jump-android mov](https://user-images.githubusercontent.com/4656348/70069841-75a6ef00-15c0-11ea-81bb-7ba87588a0da.gif)

## Expected behavior
When selecting a new block the focus should only shift one time to the newly selected block.

## Smartphone
Pixel, Android 10, 1.17.0

**Comment by geriux** [comment]
This was already addressed when we fixed not hiding the keyboard when changing focus between text-based blocks.
