### ISSUE TITLE
[Spacer block] Refine "reset" button UX

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1644]
Now that the Spacer block is included, I've been testing and have found that one thing didn't translate well in practice – the `Reset` button behavior. I expected a tap on this button to _reset the value to the default_ (100px), _not to the value that was applied when opening the sheet_. I believe this is what the behavior was on the web previously (which oddly enough I'm not seeing on the web, but I'm almost positive it was there at some point 🤔). A couple of routes we could go – in order of preference:

1. Change the behavior of the `Reset` button so that when tapped, it changes the value to the default (100px) – might also want to change the label to `Default` or `Reset to Default`
2. Remove the `Reset` button from the Slider title row, add a button row at the bottom of the sheet, titled `Reset to Default` – [example mock](https://cloudup.com/c2Wzw37luhv)
3. Keep the behavior of the `Reset` button, but change the label to say `Undo`
4. Remove the button altogether, considering web no longer has the button

Tested on:
 - Device: iPhone 11 Pro
 - OS: iOS 13.2.3
 - Version: WPiOS 13.8 TestFlight beta

cc @lukewalczak @pinarol

**Comment by lukewalczak** [comment]
I think the best option is to reset the value to the default (100px) and keep the `Reset` label or change to `Default`. Actually `Reset to Default` can be too long and on the largest font (_accessibility_) may take too much space.

Scenario with changing the label for `Undo` sounds also good, but I'm afraid of losing some kind of consistency with other cases where we have `Reset` button e.g reset button within setting `Button` block border radius.

However, if we want to be really coherent with the web, where there is no button (I'm also surprised 😮) we can remove it.

**Comment by iamthomasbishop** [comment]
> Actually Reset to Default can be too long and on the largest font (accessibility) may take too much space.

Glad you mentioned this, I was also worried about translations. Let's go with `Default`, which is clearer in context than `Reset` (if I weren't familiar with this feature, I would wonder "reset to what?" especially if I hadn't changed anything.

> However, if we want to be really coherent with the web, where there is no button (I'm also surprised 😮) we can remove it.

I thought I was going crazy, I _know_ I saw this at some point 😆 I think it's a nice feature to have so considering we already have it built, `Default` is probably a better label. 

I'd like to get some more feedback on this before making a change // cc @pinarol @koke @hypest does changing the `Reset` button to `Default` make more sense?

**Comment by koke** [comment]
I'm fine with either option, although I'd probably just take it away, since I don't thing the default value is meaningful enough to have a button dedicated to go back to it. After all, since there's nothing else to a spacer, it's relatively easy to remove and add a new one if you want the default value for some reason.

**Comment by iamthomasbishop** [comment]
Fair points, @koke. I'm okay with removing the button – we can always put it back if need be, as IIRC that is built into the Slider component itself.

**Comment by pinarol** [comment]
If we want the button to always revert to the same value, I think Default would makes more sense.

But I am fine with removing it as well 👍
