### ISSUE TITLE
[Heading Block] When heading block has bold text as link, text shadow of bold text extends beyond link text

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1654]
**Describe the bug**
When a heading block has bold text that is also a link, the text shadow of the bold text extends beyond the link text.

**To Reproduce**
1. Add a heading block
2. Select a word, make it bold
3. Apply a link to the same word
4. See the text shadow of the base text shadow extend beyond the link

**Screenshots**

(regular weight link text)
![9FA0195B-45B6-4C2D-B217-06344D30A1F8](https://user-images.githubusercontent.com/1200432/70289537-ab9fcb00-179a-11ea-81bc-67044a6dfff6.jpeg)

(bold link text)
![7D54D00C-769E-43EC-95C3-EB0AA2C0D597](https://user-images.githubusercontent.com/1200432/70289538-ab9fcb00-179a-11ea-95f6-4601edc5d53b.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.2.3
 - WPiOS 13.8b

**Comment by iamthomasbishop** [comment]
@pinarol  Do you think this is related to the text shadow trick we applied to simulate bolding on heading blocks?

**Comment by pinarol** [comment]
wow good catch @iamthomasbishop ! not sure I would ever notice that.

> Do you think this is related to the text shadow trick we applied to simulate bolding on heading blocks? 

It is highly possible, this needs forther investigation but if we can set the shadow color to be same as link color I believe we can fix this.

**Comment by iamthomasbishop** [comment]
> wow good catch @iamthomasbishop ! not sure I would ever notice that.

I hadn't noticed it until now because I rarely add links to headings! Glad I stumbled onto it 😄 

> if we can set the shadow color to be same as link color I believe we can fix this.

Good to hear! 🙌
