### ISSUE TITLE
Scroll to new block indicator when adding block

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1672]
When I tap the Inserter toggle (`(+)` icon) and the block library bottom sheet opens, I expect the canvas to scroll to where the new block is being added (to the `Add Block Here` indicator). This is especially confusing when a block is at the end of the post and it gets hidden behind the bottom sheet.

## Current UX

![https://user-images.githubusercontent.com/1200432/70573581-de194180-1b67-11ea-9c3c-8a7fe8740092.gif](https://user-images.githubusercontent.com/1200432/70573581-de194180-1b67-11ea-9c3c-8a7fe8740092.gif)

## Proposal

Scroll the canvas so that the `Add Block Here` indicator is on the top half of the screen, at least above the bottom sheet.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/1200432/70574901-d313e080-1b6a-11ea-973f-279dde736a6f.png">

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro, Google Pixel 4
- OS: iOS 13.2.3, Android 10
- Version: WPiOS/WPAndroid 13.8b

-------

Note: this issue is part of the [Nov/Dec 2019 Design Audit](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1671).

**Comment by hypest** [comment]
Removing the assignee as this ticket is not worked on at the time of writing.

**Comment by geriux** [comment]
Closing this since we added a functionality to scroll down to the newly added block.
