### ISSUE TITLE
Dark Mode - Android integration

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/gutenberg-mobile#1675]
We want to support dark mode for Android like it was done recently for iOS.

The work is in progress in this wpandroid branch:
https://github.com/wordpress-mobile/WordPress-Android/tree/feature/material-theme - cc @khaykov 

Some color name and value changes might be required to align with the new color system - cc @iamthomasbishop 

Related iOS Dark mode PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1309

**Comment by marecar3** [comment]
Thanks, @maxme!
