### ISSUE TITLE
Block navigation toolbar items overlap on media-text

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#1677]
**To Reproduce**
1. Insert a media-text block
2. Focus on the paragraph on the right
**Screenshots**

![Simulator Screen Shot - iPhone 11 - 2019-12-13 at 10 43 43](https://user-images.githubusercontent.com/8739/70791036-87457f00-1d96-11ea-93aa-8c68168b80b2.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 (Simulator)
 - OS: iOS 13

**Additional context**

**Comment by lukewalczak** [comment]
Hello @koke, I've checked that issue (after pulling all new changes from gutenberg) and right now on vertical mode items within `Media&Text` block are aligned one above the other, on horizontal mode I'm not able to reproduce it.

horizontal | vertical
--- | ---
![Screenshot 2019-12-17 at 11 30 20](https://user-images.githubusercontent.com/22746080/70987672-a7d84680-20c0-11ea-8611-3d340655d3f1.png) | ![Screenshot 2019-12-17 at 11 30 25](https://user-images.githubusercontent.com/22746080/70987682-ab6bcd80-20c0-11ea-99b7-830affe559f6.png)

**Comment by koke** [comment]
That seems fine now, but I'm thinking this might break in other cases where translations for the block title might be longer. When the text doesn't fit, the text should be ellipsized or cut off, but the icons should not overlap

**Comment by lukewalczak** [comment]
I've discovered that navigation `Toolbar` is a bit broken on the largest font on iOS:

* icons are overlapping
* component name goes beyond the container

vertical | horizontal
--- | ---
![Screenshot 2020-01-09 at 11 50 18](https://user-images.githubusercontent.com/22746080/72061621-8d1b7b00-32d6-11ea-9cd6-fdb15428f155.png) | ![Screenshot 2020-01-09 at 11 50 23](https://user-images.githubusercontent.com/22746080/72061623-8e4ca800-32d6-11ea-80ef-aaa27b6ec84b.png)

Currently `Toolbar` height is fixed and the value is 44px. What do you think about expanding container to fit icons along with label in two lines? Ellipsing / cutting off the label is not ideal case for a11y.

**Comment by lukewalczak** [comment]
Another solution can be changing the title `fontSize` to fit within a container.

**Comment by iamthomasbishop** [comment]
Can we set a max font-size on the label? I think it's inevitable that we'll run into issues w/ long names (esp translations), but a max size might help limit the issue.

**Comment by lukewalczak** [comment]
I'm thinking right now of kinda compromise between setting a max font-size along with ellipsing long names. What I mean is to use props called [maxFontSizeMultiplier](https://facebook.github.io/react-native/docs/text#maxfontsizemultiplier) and [ellipsizeMode](https://facebook.github.io/react-native/docs/text#ellipsizemode). It allows us to give the user a full name if it's not so long or ellipsed a bit in the wrong case.
Look at the screenshots for reference:

short | long 
--- | ---
<img width="895" alt="Screenshot 2020-01-09 at 18 11 21" src="https://user-images.githubusercontent.com/22746080/72089383-3cbf1000-330c-11ea-9426-246b631de677.png"> | <img width="895" alt="Screenshot 2020-01-09 at 18 20 58" src="https://user-images.githubusercontent.com/22746080/72089723-d7b7ea00-330c-11ea-9349-e42ac1bd4d6c.png">

**Comment by iamthomasbishop** [comment]
Ah ok. As you mentioned, not great for a11y, but I think it's okay as a start. I wonder if we do something when that's long-pressed to show a tooltip or something other thing?

Also worth mentioning that the block dev guidelines recommend short names for all block names, so if a block-maker uses a super-long name they're probably running into these types of issues in more places.
