### ISSUE TITLE
Image (alpha)

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#169]
Add support for the image block.

A lot of this was done as part of #140. We'll leave image settings for the beta but there are some remaining things that we want in the alpha:

- [X] Captions (#161)
- [ ] Alignment toolbar
![screen shot 2018-10-17 at 12 41 27](https://user-images.githubusercontent.com/8739/47082023-9cfbfa80-d20c-11e8-8c54-25ffc8e5bcb5.png)

**Comment by koke** [comment]
From @hypest:

> The Image alignment toolbar, well, I think that could use some design work to make it seem working on mobile. The setting itself will work (easily I think, it's GB side logic already in place) but tapping on those buttons will look like nothing's happening. So, i'd assume it to be 2 weeks of effort (design+implementation), assuming some trickery with padding to simulate the various alignments.

**Comment by koke** [comment]
@iamthomasbishop have you considered how to display the different alignment options on mobile (specially Centered vs Wide width vs Full width)?

**Comment by iamthomasbishop** [comment]
I think it should match up with what users expect on mobile web, which works as such on small viewports:

1. Left aligned: Image floats left, text wraps around right side
2. Center aligned: Image is centered, floats are cleared (no text wrapping, afaik)
3. Right aligned: Image floats right, text wraps around left side
4. Wide: Image is stretched to edges of content-width (full-width, less 16pt margin on both sides, iirc)
5. Full-width: Image protrudes to edge of viewport (full-bleed)

The difference is once you go up in viewport size (tablet and above) is that the wide variation should extend slightly beyond content-width 10-20%.

Here's a sketch to visualize:

![evernote snapshot 20181023 150209](https://user-images.githubusercontent.com/1200432/47387379-d339ee00-d6d4-11e8-9904-9dbb24cb15af.png)

**Comment by etoledom** [comment]
@iamthomasbishop  - This is super interesting, and scary at the same time!

This is mostly from the top of my mind (and a short search), but this kind of behavior if wrapping text around the image might be a little bit too complex, at least for the `Alpha`.

What I think @hypest meant (please correct me if I'm wrong! ), is that for most cases, when working with images from mobile, they will be wider than the phone screen (optimized for desktop), so they will take full width of the screen, not leaving space for wrapping text, unless the image is super thin.

So, thinking in most cases where the image width is bigger than the screen, when the user press the `align left/right` buttons, it won't actually make the text go around the image (since there's no space).

There's an example from Gutenberg web on mobile:
![image_gutenberg_web_mobile](https://user-images.githubusercontent.com/9772967/47430767-a804dc80-d770-11e8-9c75-7e09afe36a8f.gif)

It adds some small padding at the sides to show that the setting was changed but it doesn't really let the text go around.

I also noticed a few extra things:
- There are just 3 alignment settings.
- There's no image dimensions tools/options (just image size like Thumbnail, Medium, Large, etc...)

**Comment by koke** [comment]
Thanks for the explanation, it's really helpful. I was assuming this would be an easy one, but if it's not we can leave it out of the alpha.

> There are just 3 alignment settings.

This might be theme-dependent, I'm seeing all five in testgutenberg.com

![img_9e353d7b5470-1](https://user-images.githubusercontent.com/8739/47438558-fcc54900-d7aa-11e8-9258-8f3f98983b75.jpeg)

> There's no image dimensions tools/options (just image size like Thumbnail, Medium, Large, etc...)

I was surprised by this but they're actually limiting what's on the inspector based on screen size (I tested on web resizing the browser)

**Comment by etoledom** [comment]
The difficult part is the text wrapping around the image. If we avoid that behavior, the rest I believe would be fairly strait forward.

If that's the case, I would give it an estimation of around **half week** (two or three days).

**Comment by hypest** [comment]
> assuming some trickery with padding to simulate the various alignments

Just to add some clarity to what I had in mind, I'd expect having text around the image to be non trivial and perhaps not practical anyway. It might even give the wrong impression on what the final outcome will be. Instead, left/right alignment could just make the left/right paddings uneven even to look like the image will indeed be aligned to one side only. Center alignment would have those paddings equal.

Then, the size related options will only play with the amount of padding. Say, "center" alignment can have "50" padding, "wide" would have "20" and "full-width" would have zero.

*Note*: those paddings are only going to be a _visual clue_ while in the mobile editor, that something's going to happen with the image alignment/size. They will not correspond to actual padding in html/css.

Then again, @etoledom mentioned another thing (which I wasn't referring to earlier but have discussed it with Eduardo in DMs) where the _actual_ image size is not generally represented truthfully in the mobile editors. We will need to take that into account to represent the image here. For example, _in the future version where we're going to have the Image Inspector settings_, the user can set the image size to 25%. How is that going to look like in the editor?

**Comment by koke** [comment]
I was looking at the web and they represent the left and right floats as just slightly off center for mobile:

![img_3087](https://user-images.githubusercontent.com/8739/47484673-a0ab0500-d83c-11e8-9a54-0d6c638abf8d.PNG)

But then I turned into landscape (and I imagine any orientation on tablets) and there is wrapping around the text:

![img_3088](https://user-images.githubusercontent.com/8739/47484711-b3253e80-d83c-11e8-8436-78027cfbf3e2.PNG)

I don't think it's worth dealing with this for either the alpha or the beta. One decision I'd still like to consider is whether we:
1. Keep the alignment buttons so you can still change it, but without visually representing the outcome (afaik Aztec does this already, at least on iOS)
2. Take out the alignment toolbar altogether

**Comment by etoledom** [comment]
Good point about landscape!

I believe that for now (Alpha and maybe Beta too), replicating what Aztec does is good to go. 👍
And for what I see in Aztec, it does move the images according to the alignment setting, but it doesn't wrap the text around:

![img_4dd793cdb942-1](https://user-images.githubusercontent.com/9772967/47517541-dd87f380-d85e-11e8-9e9a-6954fc4f9d10.jpeg)

**Comment by iamthomasbishop** [comment]
Catching up on the conversation, I agree with the following sentiments:

* We should match what we have on Aztec for the initial iteration. From there, we can do our best to match how the web team is tackling image alignments

* This might've been answered already, but the available image alignment options is dependent on the theme

I should've prefaced my comment by saying "this is the ideal scenario, based on what exists on the web", so sorry if I caused any confusion!

**Comment by koke** [comment]
Thanks for all the input on this one. I've moved the remaining alignment task to #198 for the beta and I'm closing this one.
