### ISSUE TITLE
Fix "Add Media" bottom sheet in all languages

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/gutenberg-mobile#1691]
**Describe the bug**
When an item in the "Add Media" bottom sheet is too long, it overflows into the icon. This depends on the selected language.

**To Reproduce**
* Set language to Czech
* Go to a post with Gutenberg
* Add Image block
* Click on "Add Media" 
* The text in the last item overflows the icon.
 
**Expected behavior**
* The text doesn't overflow the icon. 

**Screenshots**
<img width="475" alt="Screenshot 2019-12-17 at 14 27 02" src="https://user-images.githubusercontent.com/1079756/70999442-be3ecc00-20d9-11ea-958d-7bb04d6f3a0b.png">

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android X
 - Version 29

**Comment by maxme** [comment]
Fixed via https://github.com/WordPress/gutenberg/pull/20768
