### ISSUE TITLE
Add Color picker to be used in block settings

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1692]
We need a color picker component to be used in block settings(Button, Cover etc). [Button block first iteration](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1513) will be completed soon so it is about time to make things more specific for the mobile Color picker component.
Could you drop your design proposal here @iamthomasbishop ? I believe you already had some drafts.

**Comment by pinarol** [comment]
One thing to note: It would be useful to implement the UI as a separate component and then use it in the settings rather than implementing it as a single "settings" component. In this way, we can use it in other places as well like the way on web:

<img width="785" alt="Screen Shot 2020-01-06 at 13 42 43" src="https://user-images.githubusercontent.com/5032900/71813517-daa3a800-308a-11ea-9be8-d8fa0dd6c5a4.png">

The mobile designs for Cover is not determined yet, I am just putting that as an example.

**Comment by iamthomasbishop** [comment]
There was a lot of discussion around some of the technical challenges surrounding color pickers, but here are some quick (unfinished) notes on the current state (very much open to iteration) of my mockups.

### Ideal Flow

In a perfect world, I'd like to simplify the entry point into one. So for something like a paragraph, you could have a single entry point for "background color" and one for "text color". That would look like this:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/1200432/72749359-6df6d600-3b7f-11ea-8ef0-3285c06229b3.png">

...then tapping on one of them would show you a separate color picker component (in a sheet perhaps), which ideally we'd be able to reuse for anything that needs color picking. Example:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/1200432/72749404-97176680-3b7f-11ea-866a-0c5168ea4ddc.png">

If you notice in the solid color example, you have a multi-color "wheel". That would link to a full custom color picker that would look like this, similar to what exists on the web:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/1200432/72749468-c201ba80-3b7f-11ea-8983-c11f722ce3c6.png">

### Alternate Flow

If we wanted to bring things a little closer to the initial sheet, as was discussed earlier, we would bring the colors list onto the main sheet:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1200432/72749519-e3fb3d00-3b7f-11ea-80bc-22d8970e7878.png">

This would take up a bunch more vertical space in the sheet, so I wanted to avoid doing it this way if possible. We'd also need to figure out a way to allow for both solid and gradient colors. There are a couple of proposals ([here](https://github.com/WordPress/gutenberg/pull/19582) and [here](https://github.com/WordPress/gutenberg/pull/19288#issuecomment-572477792)) in the works on core, so maybe this would simplify for us.

**Comment by pinarol** [comment]
I like the idea of having Solid/Gradient colors in the same component, it is more user friendly. Web also has them together after the latest changes, so there won't be a problem in terms of sharing the API. 

<img width="433" alt="image" src="https://user-images.githubusercontent.com/1200432/72749404-97176680-3b7f-11ea-866a-0c5168ea4ddc.png">

However, this time we need to check if we are able to put it on a separate bottom sheet and still keep the settings API same with web. 🤔 Let's first do some experiments in the code and give feedback accordingly.

**Comment by iamthomasbishop** [comment]
> I like the idea of having Solid/Gradient colors in the same component, it is more user friendly. Web also has them together after the latest changes, so there won't be a problem in terms of sharing the API.

Agreed 😄 

> However, this time we need to check if we are able to put it in a separate bottom sheet and still keep the settings API same with web. 🤔 Let's first do some experiments in the code and give feedback accordingly.

Fair enough. Related, is it possible to take advantage of recent changes on the web side, which now provides a toggle/segmented control for color format (solid, gradient)? It looks like this:

<img width="283" alt="image" src="https://user-images.githubusercontent.com/1200432/72930034-ab469980-3d20-11ea-98f0-53e0324b654d.png">

**Comment by lukewalczak** [comment]
I have some questions regarding to screenshots above, so I would like to ask:

1.  How we are going to navigate from main settings directly into color settings and how to navigate back?:
![untitled (1)](https://user-images.githubusercontent.com/22746080/75245774-b0d74980-57ce-11ea-9fa3-b967c164b696.png)

2. The same question how to navigate to/from color settings into color picker?
![untitled (2)](https://user-images.githubusercontent.com/22746080/75246050-4377e880-57cf-11ea-922d-f721d19b0166.png)
