### ISSUE TITLE
Crash when interacting with RichText (caused by Gutenberg #19117)

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1693]
### Describe the bug
Tapping on any `RichText` component results in the following javascript crash: 

```
TypeError: undefined is not an object (evaluating formatTypes.map)
```

This is due to a recent [gutenberg change](https://github.com/WordPress/gutenberg/pull/19117/files#diff-935c2255007bfc4fe3deceaaaf49dccaL81) that now requires `formatTypes` to be passed to the `FormatEdit` component as a prop.

### To Reproduce
1. Tap on any `RichText`-based block (paragraph, heading, etc.)
2. Observe crash because `formatTypes` is undefined

**Comment by hypest** [comment]
Fixed with https://github.com/WordPress/gutenberg/pull/19200
