### ISSUE TITLE
Focus loop on Rich Text

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1696]
**Describe the bug**
I am using the html snippet here:

```
<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Button</a></div>
<!-- /wp:button -->

<!-- wp:image {"id":984,"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://pinarspremiumtestsite123443.files.wordpress.com/2019/12/img_0111.jpg?w=1024" alt="" class="wp-image-984"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>Faded from</p>
<!-- /wp:paragraph -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"></div></div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Button 2</a></div>
<!-- /wp:button --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group -->

<!-- wp:media-text {"mediaId":990,"mediaType":"image"} -->
<div class="wp-block-media-text is-stacked-on-mobile"><figure class="wp-block-media-text__media"><img src="https://pinarspremiumtestsite123443.files.wordpress.com/2019/12/img_0111-1.jpg" alt="" class="wp-image-990"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"></div></div>
<!-- /wp:group -->

<!-- wp:video -->
<figure class="wp-block-video"></figure>
<!-- /wp:video -->

<!-- wp:image {"id":987,"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://pinarspremiumtestsite123443.files.wordpress.com/2019/12/img_0005-1-1.jpg?w=1024" alt="" class="wp-image-987"/></figure>
<!-- /wp:image -->

```
--->>> Make sure autocorrect is on

Select one of the sub-blocks of Group block
Add an image block in it, add some image
Add a paragraph under it
Type sth and make sure there's an autocorrect suggestion for it(if you pay attention to the gif, autocorrect kicks in and changes the text right after focus is lost)
(the text from autocorrect needs to be longer or shorter than the original text)
Tap navigation up button
Result: it is not able to change focus, the focus is stuck in paragraph

It is also reproducible on media-text, since it is already live we should fix this urgently.

**Expected behavior**
the focus shouldn't get stuck on paragraph block

![focus-loop](https://user-images.githubusercontent.com/5032900/71100656-73e74900-21c6-11ea-944d-07440cfec109.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max Simulator
 - OS: 13
 - commit: b6e5a239e46d1d094e5e6c37da0970c3944b53cc/develop 
using metro on

**Comment by pinarol** [comment]
A very similar issue can be reproduced at commit: 3ff15cd1a87f4aa6af00fc6d57f30b7985ab0969 which is before [InnerBlock enhancements](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1379) are merged. 

And it is reproducible with just an image and a paragraph block:

![focus-loop3](https://user-images.githubusercontent.com/5032900/71108269-caa74f80-21d3-11ea-9c7e-03b0a783db72.gif)

--->>> Make sure autocorrect is on

Add an image block in it, add some image
Add a paragraph under it
Type sth and make sure there's an autocorrect suggestion for it(if you pay attention to the gif, autocorrect kicks in and changes the text but it takes some trials)
Tap on the image

Result: focus loop

I think these 2 has the same root cause but we are observing a stuck focus instead of focus loop in the latest develop, the symptoms can be differentiating because of the `pointerEvents`usage introduced with  [InnerBlock enhancements](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1379).

**Comment by pinarol** [comment]
Auto correction should be turned on in order to repro it

![37963D9B-D679-43C0-990A-ED02E657BE51](https://user-images.githubusercontent.com/5032900/71118276-ca657f00-21e8-11ea-9b4c-b6f616ffa518.png)

**Comment by designsimply** [comment]
Received a report of this during 14.9 beta testing that I think is the same issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2294.

![2294](https://user-images.githubusercontent.com/1119271/82707195-cecf1180-9c38-11ea-9b8e-4df61b840a13.gif)

**Comment by designsimply** [comment]
This came up in an app review:

> I love this app. I have always dreamt of becoming a writer, and I wrote lots of books, but this app allows me to share my stories to the world. I even can write about reality without feeling sad. But there is a really annoying bug. Whenever I am on a certain paragraph and I press ‘Enter’, I go to the next paragraph, but I suddenly switch to the one before. Then it goes back to the new paragraph, and it keeps repeating. It is very annoying, because it is very hard to access a switching paragraph. The only way to fix it is to publish or update it. Can you please solve this problem? It is very buggy indeed.
> 
> <sup>3-star review by BrainHigh1234 Jun 7 | WPiOS 14.9 | Singapore</sup>

**Comment by pinarol** [comment]
@designsimply Thank you, we'll make a [new fix](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1702#issuecomment-567831623) about this but we need to [update to RN 0.62.2](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1823) for that. @marecar3 Can I ask the state on that one, any estimates about when we can expect the merge? Thanks!

**Comment by marecar3** [comment]
Hey 👋 @pinarol!

Thanks for asking. Currently, we have a blocker (random crash) in Android code which I am trying to figure out looking at a hermes stack trace. 

I will let you know when we are ok to merge it as currently, I don't have clear estimation if that's ok with you?

**Comment by pinarol** [comment]
Sure thank you @marecar3 !
