### ISSUE TITLE
App crash after block removal due to `undo` button pressing

### ISSUE THREAD

**Issue by lukewalczak** [wordpress-mobile/gutenberg-mobile#1699]
**Describe the bug**

App is crashing when pressing `undo` button is leading to block removal.

**To Reproduce**
1. Add a `Paragraph`
2. Type some characters
3. Undo these changes till the block is removed
4. See app crash

**Expected behavior**
The app mustn't crash.

**Screenshots**
![crrash](https://user-images.githubusercontent.com/22746080/71173884-2ae5d200-2264-11ea-94c8-67b70438b45c.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone X 
 - OS: 13.1

**Additional context**

Problem exists in that [line](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/inserter/menu.native.js#L176)

I think that into function `getBlock` we are passing `id` (end argument) which is referring to the component which doesn’t exist (is deleted because of `undo`)

**Comment by geriux** [comment]
Mentioning this one https://github.com/wordpress-mobile/WordPress-Android/issues/10876  since it's related
