### ISSUE TITLE
Paragraph

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#170]
Add support for the paragraph block.

Most of this is already done, but there are some remaining tasks:

- [ ] Add alignment toolbar
- [x] Strikethrough formatting from the toolbar

**Comment by koke** [comment]
From @hypest:

> alignment toolbar and strikethrough feel like a week or 1.5weeks of effort.

**Comment by diegoreymendez** [comment]
Marking strikethrough as completed since it's already working in both iOS and Android.

**Comment by koke** [comment]
Ok, at 1-1.5 weeks I think we'll leave alignment out of the alpha, and maybe of the beta as well

**Comment by koke** [comment]
We're tracking block alignment in #198
