### ISSUE TITLE
Add GIF badge to `ImageGallery`

### ISSUE THREAD

**Issue by kmdupr33** [wordpress-mobile/gutenberg-mobile#1715]
In #968, we added GIF badges to Image editors. This issue is to do the same work for Gallery Image editors. A rough picture of how the badges look are found below, but the source of truth for badge design is [here](https://zeroheight.com/226850145/p/11878e/b/793b21/i/6492732)

![image](https://user-images.githubusercontent.com/5463526/71309981-512e7d80-23dc-11ea-8717-8d18e5652c99.png)

**Comment by SiobhyB** [comment]
A badge was added to the image block in https://github.com/WordPress/gutenberg/pull/38996, so will show up for galleries too.
