### ISSUE TITLE
Analytics Not Tracking Progressive Rollout of Block Editor

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1718]
### Describe the bug
When a user is automatically opted into using the block editor as a part of the [progressive rollout](https://github.com/wordpress-mobile/WordPress-Android/pull/10752) we do not record any analytics event. 

In particular, [if you check the `wpandroid_gutenberg_enabled` event](https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=wpandroid_gutenberg_enabled&interval=day&prop=source&startdate=20191120&stat=uniques), it has not increased since the progressive rollout started, and it has no events with a source indicating the block editor was enabled as a part of the progressive rollout.

### Expected behavior
When a user is automatically opted into using the block editor as a part of the progressive rollout, we should send off a `wpandroid_gutenberg_enabled` event with a `source` value of `on_progressive_rollout`. 

We have a [`BlockEditorEnabledSource` enum with an `ON_PROGRESSIVE_ROLLOUT` value](https://github.com/wordpress-mobile/WordPress-Android/blob/af9988fb196ab47eafb5453a73f653e48bd7abdd/WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java#L73-L77), but that value appears to not be used. I believe we can get the analytics we want by adding a call along these lines to the [progressive rollout code](https://github.com/wordpress-mobile/WordPress-Android/blob/c1d90239d20609a6b073567fd16e012fac92dcea/WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java#L84):

```
AnalyticsUtils.trackWithSiteDetails(
  EDITOR_GUTENBERG_ENABLED, 
  site, 
  ON_PROGRESSIVE_ROLLOUT.asPropertyMap()
);
```

**Comment by hypest** [comment]
Not sure, can this ticket be closed or are there still any subtasks that need to be addressed?

**Comment by mchowning** [comment]
Thanks @hypest ! I believe we can close this, so I'll go ahead and do that. Please correct me if you think there's more to be done on this @maxme .
