### ISSUE TITLE
Video Block: "Play inline" setting doesn't get saved

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#1721]
Steps to reproduce:

1. Add a video block or open a post that already has one.
1. Tap the gear icon.
1. Toggle the "Play inline" setting to on.
1. Save the post and re-open it.
1. Check to see if the "Play inline" setting is still on.

**Result:** the "Play inline" setting is off after turning it on and saving then re-opening the post. ([24s](https://cloudup.com/cVEH0fr_bM3) iOS, [37s](https://cloudup.com/cLK5AgjWGh2) Android)

<img src="https://user-images.githubusercontent.com/1119271/71374622-9b4c6600-2578-11ea-9142-600e726e679d.png" height="400" alt="play-inline-setting-not-saved-wpios-13 9-beta"> <img src="https://user-images.githubusercontent.com/1119271/71375048-2aa64900-257a-11ea-90cd-26928b1216f5.png" height="400" alt="play-inline-setting-not-saved-wpandroid-13 9-beta">
<sup>Tested with WPiOS 13.9.0.0 TestFlight beta on iPhone 6S iOS 13.2.3 and WPAndroid 13.9-rc-1 on Pixel 3 Android 10.</sup>

**Comment by SergioEstevao** [comment]
I did some more testing, and it looks that locally the code is working correctly, the setting is saved and you can check that by switching to HTML mode and back.

When the post is saved to the server the it’s look the `playsinline` attribute is stripped from the video element inside the block. So the post content returned from the server no longer has the `playsinline` attributed and the setting is lost.

This only happens on WP.com sites or sites that have Jetpack active and the VideoPress option ON, on .org site the setting is kept.

I will try to investigate on the WP.com server code to see the reason for this to happen.

**Comment by hypest** [comment]
> This only happens on WP.com sites or sites that have Jetpack active and the VideoPress option ON, on .org site the setting is kept.

Interesting, does the issue also happens on Gutenberg on the web against .com sites?

**Comment by guarani** [comment]
> Interesting, does the issue also happens on Gutenberg on the web against .com sites?

The "Plays Inline" option is missing from the video block settings panel on WordPress.com.

| .com | .org |
| - | - |
| <img width="200" alt="Screen Shot 2020-04-06 at 23 10 06" src="https://user-images.githubusercontent.com/1898325/78695727-72a07000-78cc-11ea-83b1-e2e3102a013e.png"> | <img width="200" alt="Screen Shot 2020-04-06 at 23 03 43" src="https://user-images.githubusercontent.com/1898325/78695738-7a601480-78cc-11ea-8629-fe50ff74faad.png"> |

**Comment by SiobhyB** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/35637.
