### ISSUE TITLE
Paragraph tags do not show on the front-end

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#1728]
Thank you @sarahfg for the original report at https://github.com/wordpress-mobile/WordPress-Android/issues/11030!

### Steps to reproduce the behavior
1. Create a new self-hosted or Jetpack-connected WordPress site.
2. Log into the new site in the WordPress Android app.
3. Enable the block editor.
4. Create a new post or page using paragraphs.
5. Publish the post or page.
6. View the post on the front-end and check the page source to see if the paragraphs are surrounded by `p` html tags or if the paragraph tags are stripped.

##### Tested on 
Pixel 3, Android 10, WPAndroid alpha-201
Pixel 3 XL, WPAndroid 13.8
WordPress.org site with no active plugins and the theme Twenty-Twenty active.

<img src="https://user-images.githubusercontent.com/1119271/71702286-bb0b3780-2d8b-11ea-8938-7572ed7df8e8.png" width="400" alt="Screen Shot on 2020-01-01 at 10-15-16">

<sup>(internal reference: 2581137-zen)</sup>

**Comment by designsimply** [comment]
Tested and confirmed using WPAndroid 13.7+ on Pixel 3 Android 10. ([3m13s](https://cloudup.com/c5MyNgKgEu6))

<img src="https://user-images.githubusercontent.com/1119271/71703452-c5c8cb00-2d91-11ea-979a-2e0280f6435b.png" width="150" alt="Screenshot_20200102-185620"> <img src="https://user-images.githubusercontent.com/1119271/71703456-d416e700-2d91-11ea-886d-7be902c60cef.png" width="150" alt="Screenshot_20200102-185626"> <img src="https://user-images.githubusercontent.com/1119271/71703207-c4e36980-2d90-11ea-85b2-20fff5c80e6e.png" width="150" alt="paragraph-tags-missing-when-viewing-front-end"> <img src="https://user-images.githubusercontent.com/1119271/71703206-c44ad300-2d90-11ea-843e-72d4d5dcea00.png" width="150" alt="paragraph-tags-missing-when-viewing-page-source-in-chrome">

<img width="400" alt="Screen Shot 2020-01-02 at Jan 2 7 01 48 PM" src="https://user-images.githubusercontent.com/1119271/71703571-864eae80-2d92-11ea-84a3-439dbd0b12c0.png">

Note: in my testing, this problem did not happen when editing posts using the block editor on the web in WP Admin and it also did not happen when using the block editor in the app for WordPress.com simple sites. I tested with the Twenty Twenty and Twenty Nineteen themes. The paragraph tags only seems to disappear for self-hosted or Jetpack sites when using Gutenberg Mobile to save a post in WPAndroid 13.7 and above. Oddly though, paragraph tags do seem to be there when using the block editor in the app in both Visual and HTML Mode.

**Comment by maxme** [comment]
- I tried on a WordPress.com site and on a self-hosted with Jetpack, I couldn't reproduce the issue.
- I tried on a self hosted without Jetpack (running WordPress 5.3.2) and I got that problem.

**Comment by maxme** [comment]
I sniffed the network calls when publishing a post with the wpcom REST and XMLRPC APIs. The XMLRPC request sent is missing the `<p>` tags:

```xml
<member>
  <name>post_content</name>
  <value>
    <string>&lt;!-- wp:paragraph --&gt;
Test 1

&lt;!-- /wp:paragraph --&gt;

&lt;!-- wp:paragraph --&gt;
Test 2

&lt;!-- /wp:paragraph --&gt;</string>
  </value>
</member>
```

The wpcom REST request has the `<p>` tags:
```json
"content": "<!-- wp:paragraph -->
<p>Test1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Test2</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Test3</p>
<!-- /wp:paragraph -->"
```

**Comment by maxme** [comment]
I found the reason why the `<p>` tags are stripped for self hosted sites, if actually in FluxC: 

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/b42d25cd78e0c0b561c8e9c93be453deaf1f9011/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/post/PostXMLRPCClient.java#L510-L513


I'm not sure why this exists in the first place, and why this is done only for new posts (local drafts). I wrote an e2e test in FluxC: https://github.com/wordpress-mobile/WordPress-FluxC-Android/compare/issue/missing-paragraph-on-self-hosted?expand=1#diff-1ed1caf7921034d95aab63ac66820876  - also tried to dig more information from the history and I think this was imported directly from the old (5 years+) network code.

**Comment by designsimply** [comment]
I tested this in WPAndroid 14.0-rc-2 and paragraphs are now showing up properly on the front-end for published posts on a self-hosted site made with the block editor in the mobile app.

Closing as fixed. Props @maxme. 🎉
