### ISSUE TITLE
Cover block: Allow uploading image

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1739]
Depends on 

[Add Cover Block - 1st iteration](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1734)

Allow uploading image on Cover block. We should have options for uploading from device library and by capturing image from device camera.

**Comment by pinarol** [comment]
We need to add upload processors to WPiOS as well. Adding @chipsnyder for that part. Basically, we have some upload completion processors on main app that update the block content if upload completes during the time post is closed. See GutenbergImgUploadProcessor.swift
Image and Media-Text blocks are handled here but Cover is not handled. We'll need to support this for Cover as well.

**Comment by mkevins** [comment]
Auto-closed by merging the WordPress-Android processor PR, so reopening to be closed when enable-production PRs land.

**Comment by mkevins** [comment]
See: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1739#issuecomment-617589468
