### ISSUE TITLE
Cover block: Allow uploading video

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1740]
Depends on 

[Add Cover Block - 1st iteration](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1734)

Allow uploading video on Cover block. We should have options for uploading from device library and by capturing video from device camera.

**Comment by pinarol** [comment]
@chipsnyder @mkevins Could you check what's left to do to upload video to Cover? AFAIR only the upload processor is missing?

**Comment by chipsnyder** [comment]
> AFAIR only the upload processor is missing?

This is what I recall as well. I can jump on the iOS side of this.

**Comment by mkevins** [comment]
I'll certainly take a look at this for the Android side as well.
