### ISSUE TITLE
Use the REST API endpoint to resolve theme colors

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1744]
Depends on the issue: https://core.trac.wordpress.org/ticket/48798

Use the recently extended REST API endpoint added [here](https://core.trac.wordpress.org/ticket/48798) to resolve color settings

**Comment by pinarol** [comment]
**Some History**

Currently on mobile side we are not able to render theme colors in the block editor. For example, if you:
- Create a Button block in web 
- Set a theme color from color palette 
- View the same Button block on mobile
You'll see a Gray color. That's because we don't know how to resolve the theme color into real color value, so we are using a fallback color for theme colors.
Same thing is true for Cover block.

With the help of the updated `/themes` endpoint, we'll be able to get a color name-value, gradient name-value mappings.

**`/themes` Endpoint**

https://core.trac.wordpress.org/ticket/48798 was closed in favor of https://core.trac.wordpress.org/ticket/49037 . 49037 extends `/themes` endpoint to return lots of theme information including color and gradient values used in that theme.

The endpoint should be available as of WordPress 5.4 RC, but it is not released yet.

There are some instructions here about how to test it: https://wordpress.org/news/2020/03/wordpress-5-4-release-candidate/

**WPiOS/WPAndroid**

We need to:

- Add service calls to the `/themes` endpoint in parent apps
- Bootstrap the block editor with the new theme colors

I believe we can find out how other types of site data is stored and store theme colors in a similar way.

**RN side**

As far as I understand we need to change "withColors" in a way that also resolves the theme colors.

**Comment by chipsnyder** [comment]
Android side of this has merged now it'll be in 15.2 🚀
