### ISSUE TITLE
Add Latest Posts block - 1st iteration

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1746]
Would that be possible to come up with a simple 1st iteration for this? @iamthomasbishop This time I am talking about something that can also ship to prod. What I have in mind is not showing block previews but just allowing the user to change the most important block settings, wdyt?

**Comment by iamthomasbishop** [comment]
Are we talking about the "Latest Posts" block that is in core? I know there was some discussion around which block will end up being used in Core (there are a few that are on the radar), so I want to make sure our target is aligning with core.

For reference, the current Latest Posts block looks like this:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1200432/71851975-59a1dc00-309d-11ea-80f2-c294c0087ff7.png">

**Comment by pinarol** [comment]
> Are we talking about the "Latest Posts" block that is in core?

Yes, this issue is about the core one.

**Comment by lukewalczak** [comment]
Hi @iamthomasbishop , can you upload some design for that block?

**Comment by chipsnyder** [comment]
Hey, @iamthomasbishop I'm getting ready to start looking into the support for this. Do we have any designs ready for it yet?

**Comment by chipsnyder** [comment]
Chatting with @iamthomasbishop, we discussed the following:

For the canvas, we won't focus on adding any block specific editing to the canvas but instead have a basic UI with the standard controls for moving the block up and down.

For the Block settings, we'll add support for:
- Post Content
  - Excerpt / Full Post (Only shown if Post Content is toggled on)
  - Maximum Number of words (Only shown if Post Content is toggled on AND Excerpt is selected)
- Display Post Date
- Order By
- Category
- Number of Items

For "Post Content," I'll start by investigating some flows around that to see if there are any blockers around the conditional rows or if the flow feels weird.
