### ISSUE TITLE
SPTs: Add Modal template picker for SPTs (… more button)

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1748]
We need a Modal template picker once we have enough supported blocks to have a better offering of available templates.

 - The button list will be scrollable, and have a “••• More” button at the end.
 - That button will open a full screen selector with all the available templates.

Latest blueprint:

![blueprint-starter-page-templates-android-i2](https://user-images.githubusercontent.com/5032900/71825963-ee143a80-30ad-11ea-8e46-c2b25881a1e6.jpg)

**Comment by pinarol** [comment]
We need a sectioned modal layout picker since there will be multiple layouts for each category. 

And as a natural result we need to bring in thumbnail preview images. We'll be able to use the same thumbnails with .com for the layouts that we took directly from there. 

This is also a good preparation for the next phase where we'll start fetching the layouts from the back end service. 

@iamthomasbishop Could you help us on designs?

**Comment by pinarol** [comment]
Closing this in favor of new designs.

**Comment by designsimply** [comment]
Can you help point me to the latest designs posted to GitHub? I'd like to refer to them while beta testing for the 16.1 release and also refer to them in our public call for testing. cc @chipsnyder @geriux @iamthomasbishop

**Comment by chipsnyder** [comment]
@designsimply These Blueprints might be a good reference for you to use. I should add that the design of the notice for "Page Created" changed from these Blueprints to what was developed.


<details>
<summary>Blueprint Flow - iOS</summary>
<img src="https://user-images.githubusercontent.com/3384451/85329020-bce2c780-b49f-11ea-88f3-5db30c13af03.jpg" />
</details>

<details>
<summary>Blueprint Flow - Android</summary>
<img src="https://user-images.githubusercontent.com/3384451/85889853-40f7c080-b7ba-11ea-819b-21f075afc772.jpg" />
</details>
