### ISSUE TITLE
Undo is enabled on just opened post

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/gutenberg-mobile#1751]
**Describe the bug**
When I open an existing post in WPAndroid, the undo button is enabled. When I click on the undo button the content of the post gets deleted.

**To Reproduce**
1. Open an existing post in WPAndroid
2. Click on "Undo"

**Expected behavior**
Undo button is disabled when I open a post.

**Screenshots**
![undo](https://user-images.githubusercontent.com/2261188/71830797-cde17d00-30a7-11ea-8c9f-5c9dce34a313.gif)

**Comment by mchowning** [comment]
This seems like a significant issue since it could easily make a user think they've lost their post content.

**Comment by SiobhyB** [comment]
I'm no longer able to reproduce this issue on 24.0 of the Android app. If I open a post or page, both the undo and redo buttons are disabled, as expected.
