### ISSUE TITLE
App crashes when adding a photo from Free Photo Library 

### ISSUE THREAD

**Issue by lukewalczak** [wordpress-mobile/gutenberg-mobile#1760]
**Describe the bug**

The app is crashing on Android once adding a photo using the option `Free Photo Library` in both `Image` and `Media&Text` block.

**To Reproduce**
1. Open WordPress-Android app
2. Write a post
3. Add an Image / Media&Text block
4. Click on image placeholder
5. Click `Choose photo from Free Photo Library`
6. App is crashing on Android

**Expected behavior**
The app shouldn't crash and photo should be uploaded properly.

**Screenshots**

![photo_crash](https://user-images.githubusercontent.com/22746080/71974986-35680b80-3213-11ea-89ab-4ff0448cc7a5.gif)

**Smartphone (please complete the following information):**
 - Device: Simulator Pixel 2
 - OS: Android 9

**Comment by mchowning** [comment]
This should be fixed by https://github.com/wordpress-mobile/WordPress-Android/pull/11046

**Comment by lukewalczak** [comment]
Closed via: wordpress-mobile/WordPress-Android#11046
