### ISSUE TITLE
Display issue around videos on Android

### ISSUE THREAD

**Issue by Tug** [wordpress-mobile/gutenberg-mobile#1761]
**Describe the bug**

In Visual mode, vertical videos overlay their video block causing display issue, making the caption underneath hard to read and even overflowing to the toolbar and the next block.

We also lose the cover image that was previewing the video, for all type of videos. 

Those are regressions for Android as they were not present in v1.19.

**To Reproduce**
1. Add a video block
2. Upload a vertical video
3. Focus the video block
4. See the display issue, still visible even after focusing another block 

**Expected behavior**
I'd expect the video to not be displayed at all on focus

**Screenshots**
![image](https://user-images.githubusercontent.com/230230/71977828-2042ab00-321a-11ea-8e7e-c6cb6d749184.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 8
 - OS: Android 9

**Comment by hypest** [comment]
With the RN v0.61.5 upgrade now merged, can you test the issue again @Tug to see if by any chance it's back or not? Let's close the ticket if it's still not happening. Thanks!

**Comment by hypest** [comment]
Can't experience the issue with WPAndroid v15.0-rc-3 on a Pixel 2XL running Android 10. Closing but, we can reopen if the issue still happens for others.
