### ISSUE TITLE
[iOS] The Done button row in BottomSheet is all blue instead of just the button

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#1767]
The `Done` button whole row is blue  (only the button text should be blue, not the whole bar).

Visual example of problem: 

<img src="https://cldup.com/JMQoUaaJfE.jpeg">

**Note:** iOS only, also, might be an issue with `RangeControl`

**Comment by chipsnyder** [comment]
Closing this as we've updated to use a stepper now. So this issue no longer applies
