### ISSUE TITLE
Add option to change caret color in `RichText`

### ISSUE THREAD

**Issue by lukewalczak** [wordpress-mobile/gutenberg-mobile#1773]
**Is your feature request related to a problem? Please describe.**

Currently there is no option to change a caret color in `RichText` component which causes a visibility issue when background color is blue-ish.

<img width="507" alt="Screenshot 2020-01-13 at 13 14 33" src="https://user-images.githubusercontent.com/22746080/72255307-af7b0480-3606-11ea-92f7-c7bea1ca5c58.png">

**Describe the solution you'd like**

React Native `TextInput` has a prop called `selectionColor` which allows to change caret and selected text color. I think that's the way which we can follow.

**Comment by SergioEstevao** [comment]
I can tackle the iOS part of this issue.

**Comment by chipsnyder** [comment]
I'm happy to take on the Android side.

**Comment by pinarol** [comment]
great thanks! @SergioEstevao @chipsnyder 🎉

**Comment by lukewalczak** [comment]
Thank you both!
