### ISSUE TITLE
Android Add option to change caret color in `RichText` in API 29+

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#1787]
**Describe the bug**
The solution used as part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/1773 only supports API 27 and below in Android as reflection is not supported in API 28+.
Starting in API 29 there are the following supported methods that allow the cursor to be edited programmatically. 

| Link | Attribute |
| --- | --- |
| [TextView#setTextCursorDrawable](https://developer.android.com/reference/android/widget/TextView#setTextCursorDrawable(android.graphics.drawable.Drawable)) | cursor |
| [TextView.html#setTextSelectHandleLeft](https://developer.android.com/reference/android/widget/TextView.html#setTextSelectHandleLeft(android.graphics.drawable.Drawable)) | Left selector icon |
| [TextView.html#setTextSelectHandleRight](https://developer.android.com/reference/android/widget/TextView.html#setTextSelectHandleRight(android.graphics.drawable.Drawable)) | Right selector icon |
|[TextView.html#setTextSelectHandle](https://developer.android.com/reference/android/widget/TextView.html#setTextSelectHandle(android.graphics.drawable.Drawable)) | Single selector icon |

Once Aztec View is updated to target API 29 support for the cursor drawable should be added to wrap up support for `selectionColor`

**To Reproduce**
1. In Gutenberg add `selectionColor` to a component that uses RichText
2. Add that field to a page or post

**Expected behavior**
The cursor should match the `selectionColor`

**Screenshots**
Cursor Color API 29:
<img width=300 src="https://user-images.githubusercontent.com/3384451/72740272-56195500-3b73-11ea-9beb-f7bae7596750.png" />

Highlight Color API 29:
<img width=300 src="https://user-images.githubusercontent.com/3384451/72740316-721cf680-3b73-11ea-9e04-0058a4a1bf2f.png" />

**Smartphone (please complete the following information):**
 - Device: Pixel 3a emulator
 - OS: Android 10
 - Version 29

**Comment by antonis** [comment]
Closing the issue as the it seems to be fixed now. Please reopen if that is not the case.

<details>
<summary>Screenshot</summary>

|Selection|Cursor|
|---|---|
|![device-2022-01-24-121128](https://user-images.githubusercontent.com/304044/150763659-29672efb-de74-4c7a-988b-a89d71344c1b.png)|![device-2022-01-24-121424](https://user-images.githubusercontent.com/304044/150764051-272bda8d-756e-4b92-8577-c872d0b69cf5.png)|

</details>
