### ISSUE TITLE
Video block settings: Refine separators on table rows

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1796]
Separators on Video block settings don't span the width of each row. They should go from the left edge of the left label to the right edge of the right label, 16px margins on each side. Also, there shouldn't be a separator on the last row. I tested on iPhone, but I am assuming this is also the case on Android.

Note: I think this wider inset is the "default" for new rows. We might want to change the default to 16 left and 16 right (I believe it's 56 on iOS and 72 on Android to account for icons, but we aren't using icons as much as non-icon rows).

Screenshot:
![image](https://user-images.githubusercontent.com/1200432/72825240-4b76c280-3c3c-11ea-8341-dc12a4f6110d.jpeg)

**To Reproduce**
1. Add video block, upload video
2. Tap on settings cog icon to show block settings sheet
3. See issues described above

// cc @SergioEstevao @etoledom

**Comment by hypest** [comment]
👋 @ceyhun , can you have a look at this one? I'll assign it to you in the meantime and we can re-assign if needed.
