### ISSUE TITLE
Links should pre-populate based on text added

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/gutenberg-mobile#1807]
**Is your feature request related to a problem? Please describe.**

When trying to insert a text into a post, you need to know the exact URL or have it saved in your Clipboard to past it in the link URL field. 

If you do the same in the browser version, you can type to search for specific internal links that will prepopulate the fields so you don't need to remember the URL. 

**Describe the solution you'd like**

User would like the same behaviour they have in the browser available in the app. The option to type in text to search for internal links instead of knowing specific URL.

**Describe alternatives you've considered**

There are no other alternatives other than first copying the link to your clipboard before you begin writing the post so you can paste it. It's not a very easy flow. 

**Additional context**

A user reported this: 2650041-zen

**Comment by hypest** [comment]
I think this feature request is already covered in https://github.com/wordpress-mobile/gutenberg-mobile/issues/1058. Closing in favor of the older ticket.

**Comment by rezzap** [comment]
This came up again in a ticket today and on reviewing the PR I realized it's not for the same issue. 

What users are missing is the option to select from the URLs of their already posted content so they can link between posts and pages more easily without needing to know the full URL. 

See a screenshot here: 
<img width="801" alt="Image 2020-10-24 at 5 00 26 pm" src="https://user-images.githubusercontent.com/10325627/97086348-9209ab00-161a-11eb-8e3b-e9ac1e7db169.png">

Is this something we're able to support in Gutenberg? We get the request often and I wasn't able to find another report of it.

Requested in 3432896-zen
