### ISSUE TITLE
Update Shortcode design elements from design review

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#1810]
**Describe the bug**
From the design review with @iamthomasbishop:

- Top Label:
    - Use system font "sans-serif" for ios
    - Set font color to be `$gray` in light mode and `$gray-50` in dark mode
    - Increase margin between the label and input field

**Screenshots**
#### iOS
| Default | Dark mode |
|  :---: | :---:  | 
| <img width="300" alt="Placeholder-iOS" src="https://user-images.githubusercontent.com/3384451/72094646-d4a90380-32e4-11ea-8444-b867fefdca1d.png"> | <img width="300" alt="iOS Dark - Placeholder" src="https://user-images.githubusercontent.com/3384451/72096098-86e1ca80-32e7-11ea-8ddd-74e671835ef8.png"> |

| iPad Default | iPad Dark mode |
|  :---: | :---:  | 
| <img width="855" alt="iPad - Placeholder" src="https://user-images.githubusercontent.com/3384451/72097732-08872780-32eb-11ea-8ac0-3ed4c9984145.png"> | <img width="855" alt="iPad Dark - Placeholder" src="https://user-images.githubusercontent.com/3384451/72097740-0c1aae80-32eb-11ea-94f8-f1e4477d4d3b.png"> |

#### Android
| Default |
|  :---:  | 
| <img width="300" alt="Android - Placeholder" src="https://user-images.githubusercontent.com/3384451/72099936-ad0b6880-32ef-11ea-9851-2a90917bc10c.png"> |

#### iOS
| Default | Dark mode |
|  :---: | :---:  | 
| <img width="300" alt="Static-iOS" src="https://user-images.githubusercontent.com/3384451/72094868-58fb8680-32e5-11ea-8484-8ae8b1868947.png"> | <img width="300" alt="iOS Dark - Static" src="https://user-images.githubusercontent.com/3384451/72096856-19369e00-32e9-11ea-91ec-ae04d1e9a4ca.png"> |

| iPad Default | iPad Dark mode |
|  :---: | :---:  | 
| <img width="855" alt="iPad - Static" src="https://user-images.githubusercontent.com/3384451/72097845-48e6a580-32eb-11ea-870e-30670c17d0a6.png"> | <img width="855" alt="iPad Dark - Static" src="https://user-images.githubusercontent.com/3384451/72097860-4dab5980-32eb-11ea-98b4-aaf69b432a64.png"> |

#### Android
| Default |
|  :---: |
| <img width="300" alt="Android - Static" src="https://user-images.githubusercontent.com/3384451/72100262-4c306000-32f0-11ea-808f-bbd3ac54fad5.png"> |

#### iOS
| Default | Dark mode |
|  :---: | :---:  | 
| <img width="300" alt="Selected-iOS" src="https://user-images.githubusercontent.com/3384451/72094897-63b61b80-32e5-11ea-8d84-9e1047aa443a.png"> | <img width="300" alt="iOS Dark - Selected" src="https://user-images.githubusercontent.com/3384451/72096899-2a7faa80-32e9-11ea-8270-5f1830da111c.png">|

| iPad Default | iPad Dark mode |
|  :---: | :---:  | 
| <img width="855" alt="iPad - Selected" src="https://user-images.githubusercontent.com/3384451/72097920-72073600-32eb-11ea-8365-bfd292835199.png"> | <img width="855" alt="iPad Dark - Selected" src="https://user-images.githubusercontent.com/3384451/72097936-76335380-32eb-11ea-9edd-cbf8e3d20b84.png"> |

#### Android
| Default |
|  :---: |
| <img width="300" alt="Android - Selected" src="https://user-images.githubusercontent.com/3384451/72100149-1c815800-32f0-11ea-9047-73bd69c3d693.png"> |

**Additional context**
This is to make up for not performing design review before https://github.com/WordPress/gutenberg/pull/19534 was merged

**Comment by iamthomasbishop** [comment]
Thanks, Chip! To clarify by “Set font color to match $gray in light mode and $gray-50 in dark mode” I was referring to the top label (“Shortcode” above the input). I believe the placeholder text on the input was fine.

**Comment by iamthomasbishop** [comment]
> Increase margin between the label and input field

Fwiw, I think the spacing should be 4px, but it might be slightly different if the design is using a different line-height than the implementation.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/1200432/73013571-2e79f500-3dde-11ea-94db-b263a1071c47.png">
