### ISSUE TITLE
Add support for setting anchors and referring to them from links

### ISSUE THREAD

**Issue by Tug** [wordpress-mobile/gutenberg-mobile#1816]
The mobile block editor currently does not support editing the "HTML Anchor" setting of the Heading block. We should be adding this if we want to support editing anchors.

- Heading block 👉 [PR in Review](https://github.com/WordPress/gutenberg/pull/27935)
- Other blocks 👉 WordPress/gutenberg#28363

We should also fix referring to an anchor from the url field with `#my-anchor` for instance. Currently this is not supported as it's considered as an invalid url, so it won't persist.

**Comment by dcalhoun** [comment]
@iamthomasbishop I am beginning work on this issue. I had a few questions that I'd like your input on please. I plan to move forward with the presumptions I outline, but please let me know if I am mistaken. Thanks!

## Accessing Heading Anchor Controls

Do we envision accessing the controls to set the heading anchor within the toolbar atop the keyboard (i.e. matching heading level button) or a button on the block itself (i.e. adding a settings cog button)? 

My presumption is the latter, as this would align with the organization of the web interface.

<details>
<summary>Example Images</summary>
<img width="506" alt="heading-anchor-access" src="https://user-images.githubusercontent.com/438664/103315897-8e185180-49ec-11eb-830c-6dc99c2b64a9.png">

<img width="996" alt="web-control-organization" src="https://user-images.githubusercontent.com/438664/103315653-d3884f00-49eb-11eb-8b24-4916a72e4287.png">
</details>

## Organizing Heading Settings

I was provided #1385 as being relevant to this issue. Was the intention that navigating to modify the heading anchor setting would present a bottom sheet with an "Advanced" settings group leveraging the Block Settings grouping implemented within #1397? 

My presumption is yes. We would have a single "Advanced" grouping and additional sections would be added later.

<details>
<summary>Example Images</summary>
<img width="896" alt="heading-control-groupings" src="https://user-images.githubusercontent.com/438664/103316184-53fb7f80-49ed-11eb-8827-a665674df136.png">
</details>

## Modifying Heading Anchor Value

Regarding https://github.com/wordpress-mobile/gutenberg-mobile/issues/1385#issuecomment-535963076, do we want the user to edit the heading anchor value via an inline text input or some form of nested bottom sheet navigation? 

Please keep in mind that while my example images are from the link editor I'm specifically asking about _setting the value_ for the anchor, _not referencing/linking to_ the anchor.

My presumption is that we will use an inline text input for now.

<details>
<summary>Example Images</summary>
<img width="506" alt="inline-text-input" src="https://user-images.githubusercontent.com/438664/103316126-1f87c380-49ed-11eb-8c5b-972bd8b69dd1.png">
<img width="506" alt="nested-bottom-sheet" src="https://user-images.githubusercontent.com/438664/103316926-9c1ba180-49ef-11eb-8f45-98dbc5c94659.png">
</details>

**Comment by iamthomasbishop** [comment]
> Do we envision accessing the controls to set the heading anchor within the toolbar atop the keyboard (i.e. matching heading level button) or a button on the block itself (i.e. adding a settings cog button)?

> My presumption is the latter, as this would align with the organization of the web interface.

@dcalhoun I would say the latter as well — let's add a settings sheet to the Heading block, which (as you mentioned) will means we'll have to add the settings icon to the inline block controls and a bottomSheet that contains the block settings (a text input cell titled "HTML anchor").

<a href="https://user-images.githubusercontent.com/1200432/103590519-ab00c900-4eb3-11eb-920c-fb6d3458d7bf.png"><img src="https://user-images.githubusercontent.com/1200432/103590519-ab00c900-4eb3-11eb-920c-fb6d3458d7bf.png" width="1129"></a>

> Was the intention that navigating to modify the heading anchor setting would present a bottom sheet with an "Advanced" settings group leveraging the Block Settings grouping implemented within [#1397](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1397)?

I think for now, let's just ignore the grouping and worry about that later if/when we add other settings groups (advanced, color, typography, etc).

> My presumption is that we will use an inline text input for now.

Considering should generally be a pretty short string as a selector id, it should work here. If it becomes an issue, we can apply the nested input model.

**Comment by dcalhoun** [comment]
@iamthomasbishop thanks for the guidance. I'll update the section heading and placeholder value in WordPress/gutenberg#27935, and we should be ready for PR review.

**Comment by dcalhoun** [comment]
@iamthomasbishop after [receiving code review](https://github.com/WordPress/gutenberg/pull/27935#issuecomment-759884719), I have come to realize two things:

1. There is opportunity to share more code with the web (which we likely should attempt to do).
2. The architecture of the HTML anchor feature for web is built so that almost any block can have an anchor set, not just headings.

Is the desire for this issue that we enable the mobile editor to set anchors for _only heading blocks_ or _all eligible blocks_?

My presumption is the latter. If I am correct, then using a "Heading settings" section heading likely doesn't make sense for all other blocks (e.g. Quote, List). Would you prefer to use a section heading of "Advanced" to mimic the web editor or attempt to use "<BLOCK_TITLE> settings"? The former would be very easy. I would need to explore implementing the latter.

<details>
<summary>Quote Block Example</summary>

<img width="495" alt="quote-anchor-example" src="https://user-images.githubusercontent.com/438664/104659870-13596280-568b-11eb-88dc-cfd873d5b61a.png">

</details>

Please let me know how you would like to proceed. Thanks!

**Comment by dcalhoun** [comment]
> Is the desire for this issue that we enable the mobile editor to set anchors for _only heading blocks_ or _all eligible blocks_?

To follow up, after receiving some feedback from Stefanos, I moved forward with enabling setting anchors for _heading blocks only_ to keep momentum for the project. Happy to revisit enabling anchors for all blocks later once we have a decision on what the section heading should be.

**Comment by hypest** [comment]
I updated the ticket description to include the bit about the progress on the heading block but not other blocks yet.

**Comment by iamthomasbishop** [comment]
> Is the desire for this issue that we enable the mobile editor to set anchors for only heading blocks or all eligible blocks?

Agreed w/ y'all, only Heading for now. Afaik this is only supported on Heading blocks on the web, and while I think there's a good case in the future to be made for expanding the scope, but let's just roll w/ that for now.

**Comment by dcalhoun** [comment]
> Afaik this is only supported on Heading blocks on the web

@iamthomasbishop from my research, the web block editor allows setting anchors on 25 block different block types. I have created WordPress/gutenberg#28363 to allow us to continue the conversation of when/how we might add wider support for anchors on mobile.

Any input you (or others) have on the subject is welcome. Thanks! 😄

**Comment by iamthomasbishop** [comment]
> from my research, the web block editor allows setting anchors on 25 block different block types

@dcalhoun Ah, I totally missed that! In any case, agreed that we should set aside broader support for next. And when we do that, we can probably align more closely w/ the web by adding an "Advanced" section, where the anchor cell would live across all of those supported blocks' settings sheets.

**Comment by dcalhoun** [comment]
Closing as this was addressed within WordPress/gutenberg#27935.
