### ISSUE TITLE
Android landscape mode - soft keyboard done/next button adds new line/block

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1829]
## Summary
On Android, pressing "Next" or "Done" soft keyboard button when editing paragraph block in landscape orientation adds a new paragraph block instead of closing the keyboard.

![android_landscape_done_button mp4](https://user-images.githubusercontent.com/4656348/73307530-5efdcc80-41ec-11ea-8185-7d7b7e58a765.gif)

## To Reproduce
1. Create a paragraph block
2. With the phone in landscape mode, place the cursor in the middle of the block's text
3. Tap the soft keyboard's Done/Next button **(I'm seeing the "Next" button on the demo app, but WPAndroid is properly showing "Done")**
4. Observe that only the text after the cursor remains
5. Close the keyboard
6. Observe that a new paragraph block has been added.

## Expected Behavior
I think we want this the done button to dismiss the keyboard without creating a new block, but it would be good to get @iamthomasbishop 's thoughts.

## Smartphone
- 1 
  - Device: Pixel
  - OS: Android 10
   - Version: commit 7963eeed

- 2
   - Device: Pixel 3
   - OS: Android 10
   - Version: alpha-206 (latest from beta channel on Jan. 28, 2020)

**Comment by iamthomasbishop** [comment]
Ahh good catch! I noticed this a long while back and forgot to create an issue for it 😄 I think in general, the way our landscape mode behaves feels weird/unexpected to me (automatically focusing the entire editor into a single style-less view — I expected it to just rotate the view, not go into another one altogether), but that's maybe another issue. 

With that said, I agree w/ you, if the button label is `Done`, I also expect it to simply hide the keyboard, not create a new block. This would be a nice improvement.
