### ISSUE TITLE
React Image.getSize callback firing on unmounted components

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#1831]
**Describe the bug**
`Image.getSize` callbacks fire on unmounted components. The source of this issue is that the `Image.getSize` method makes an asynchronous network request, but does not provide a way to cancel the request. This can result in scenarios where the callback fires after the view that initiated the request (and its parent views) have been unmounted.

**To Reproduce** (must have JS debugging turned on)
* Open a new post and insert an image block
* Tap "Add Image"
* Tap "Choose from device" and select a local image to upload
* Wait for upload to complete
* Immediately tap trash icon to delete image block
* Wait and observer the debug console

**Expected behavior**
No errors logged.

**Actual behavior**
Error logged:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

**Smartphone:**
 - Device: Pixel 3a
 - OS: Android X

**Comment by jhnstn** [comment]
I am unable to reproduce this in trunk (currently at v1.71.1)

- Android 12 /  pixel p
- WPAndroid 19.2 rc-3

**Comment by mkevins** [comment]
I haven't had a chance to retest this, but the underlying code has changed a lot since this was opened. I'll close this, and if it becomes an issue again, it can be reopened if needed (a log noise dev issue).
