### ISSUE TITLE
Image url not Resetting When Settings Cleared

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1843]
### Summary

When you adjust the size of an image (i.e., make it thumbnail) and then "Clear All Settings", the url of the image does not get updated (but the `sizeSlug` does) until you deselect and reselect the image.  As a result, the image visually retains its adjusted size until it is reselected.

### Steps To Reproduce

1. Select image block and add an image
2. Open settings and toggle size to thumbnail
3. Tap "Clear All Settings"
4. Observe that the "Size" field resets, but the image's visual appearance does not update
5. If you check the html at this point, I believe you will find that the `sizeSlug` has updated but the image url has not
6. Select the post's title (you can even close and reload the post)
7. Observe the image's visual size has not changed and the url is still for the adjusted image size
8. Select the image
9. Observe the image's visual size updates and the url has been updated appropriately

### Expected behavior
The image's visual size and url should update appropriately when the "Clear All Settings" button is pressed.

### Smartphone
1. Pixel, Android 10, commit 28f7f7e8
2. iPhone Simulator, 13.3, commit 28f7f7e8

**Comment by hypest** [comment]
The "Clear All Settings" feature [has been removed](https://github.com/WordPress/gutenberg/pull/22267) so, closing this as no longer applying.
