### ISSUE TITLE
Editor screen issue : radiobox point need to be center

### ISSUE THREAD

**Issue by akkspros** [wordpress-mobile/gutenberg-mobile#1845]
Editor screen issue : radiobox point need to be center
![Screenshot_20200131-074220](https://user-images.githubusercontent.com/56331609/73540285-56f29680-4451-11ea-8943-5ee774a5fbc4.png)

**Tested on**

![Screenshot_20200131-074334](https://user-images.githubusercontent.com/56331609/73540330-72f63800-4451-11ea-9f7a-784a46fe3612.png)

**Version:** Android-14.1-rc-1

**Comment by SergioEstevao** [comment]
Hello there, the issue you report applies to the web implementation of Gutenberg you should open the ticket in this repo: https://github.com/WordPress/gutenberg.
