### ISSUE TITLE
Free photo library: Allow uploading multiple images into Gallery

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1863]
Choose from the free photo library
Gallery block should allow uploading images from the free photo library.

Note: ❌ On iOS, I observed that only the first image is added to the gallery block, with the rest appended as image blocks.

Steps:

Add a gallery block and tap "Add Media"
Select "Choose from the free photo library" option
Select multiple images from the device and confirm the selection
Expected behavior:

Gallery should show all images being uploaded as dimmed
Progress bars should be displayed indicating the upload progress
After each image upload has completed:
Image should not be dim
Image url scheme should be https:// (not file:///) in HTML mode

**Root cause analysis** 

Refer [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1610#issuecomment-582838335)

We are actually [passing](https://github.com/wordpress-mobile/WordPress-iOS/blob/b6e843af7d08356299d41a05834a21db7ec3d051/WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergStockPhotos.swift#L14) "multipleSelection" but it is ignored intentionally since the desired behavior is to let user select multiple pics. 

What we need to do differently for Gallery is, using that flag for to decide to go for "insertOnBlock" option:

```
// Append the first item via callback given by Gutenberg.
if let firstItem = assets.first {
    insertOnBlock(with: firstItem)
}
// Append the rest of images via `.appendMedia` event.
// Ideally we would send all picked images via the given callback, but that seems to not be possible yet.
appendOnNewBlocks(assets: assets.dropFirst())

```

**Comment by pinarol** [comment]
We can target [this PR's](https://github.com/wordpress-mobile/WordPress-iOS/pull/13374) branch for this fix

**Comment by chipsnyder** [comment]
This was merged to develop and closed by https://github.com/wordpress-mobile/gutenberg-mobile/pull/1855
