### ISSUE TITLE
Add text-alignment support to Headings

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1880]
We currently only have text-alignment support on the paragraph block. More often than not, left-aligned text works fine, but sometimes you want centered heading text. For example, on a Cover block (which is in progress):

<a href="https://user-images.githubusercontent.com/1200432/74270484-ea895a00-4cd0-11ea-87fd-a443f2ad9d59.jpeg"><img src="https://user-images.githubusercontent.com/1200432/74270484-ea895a00-4cd0-11ea-87fd-a443f2ad9d59.jpeg" width="375"></a>

Another use case: centered section text ([example](https://cloudup.com/ch3jzIS2UYZ))

// cc @mchowning @hypest

**Comment by iamthomasbishop** [comment]
@hypest Is there any chance we can expedite this? We could benefit from having it in a few places, especially on the incoming Starter Page Templates feature. 😄

**Comment by mchowning** [comment]
Reopening because there is still [some more work needed to finish this on Android](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2006).

**Comment by mchowning** [comment]
Added for Android in https://github.com/wordpress-mobile/gutenberg-mobile/pull/2006, so now both platforms have this! 🥇
