### ISSUE TITLE
Copying link from the clipboard doesn't work properly

### ISSUE THREAD

**Issue by lukewalczak** [wordpress-mobile/gutenberg-mobile#1885]
**Describe the bug**

When copying the link from the clipboard into link settings the whole sentence is passed into the `URL` field instead of just link.

For example:

```Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris http://loremipsum.com```

The whole text is pasted in `URL` field.

**To Reproduce**
1. Copy text with link from somewhere, e.g text above
2. Add `Paragraph` or `Button` block
3. Click on link settings button
4. Notice that whole text is pasted

**Expected behavior**

The only link should be pasted.

**Screenshots**
![link_bug](https://user-images.githubusercontent.com/22746080/74335680-00645100-4d9d-11ea-8aac-1fa33a9445ec.gif)

**Smartphone (please complete the following information):**
 - Device: simulator iPhone 11
 - OS: 13.1

**Comment by hypest** [comment]
👋 @SergioEstevao , can you have a look at this one? Seems related to https://github.com/WordPress/gutenberg/pull/18279, though not sure if it's a regression or not.

**Comment by lukewalczak** [comment]
🙈 Actually, I forgot about that issue but looks like it solved via https://github.com/WordPress/gutenberg/pull/20172

**Comment by lukewalczak** [comment]
Tested during work over extending the [Button auto-filling link into settings](https://github.com/WordPress/gutenberg/pull/20462)
