### ISSUE TITLE
[GlobalStep] iOS - Using “Other Apps” when adding an Image causes the “Site Fast Switcher” and the Back button to disappear

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#1887]
### Description
When adding an Image block, selecting the “Other Apps” option and returning to the Post Editor causes the header to be displayed white and the “Site Fast Switcher” along the Back button disappears despite still functioning.

### Reproduction Rate
4/4 100%

### Expected behavior
The Post Editor appearance should remain as it was before using the “Other Apps” option.

### Actual behavior
The Post Editor’s header becomes white and the “Site Fast Switcher” along the Back button disappears.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Open the Post Editor.
4. Add an Image Block.
5. Tap “Add Image”.
6. Select “Other Apps”.
7. Press “Cancel”.
##### Tested on the following
iPhone XR (12.0.1)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/74344720-edee1580-4da4-11ea-911b-b00e58d911d2.jpg" />

### Submitted by:
Luis Pimenta

**Comment by illusaen** [comment]
Closed because could not reproduce on iOS 14, WPiOS 16.8, iPhone 12 Mini.

<details>
  <summary>GIF</summary>

  ![issue](https://user-images.githubusercontent.com/13263478/110385577-b643b280-8024-11eb-81f2-11d0f544e041.gif)
</details>
