### ISSUE TITLE
[GlobalStep] Android – Adding multiple images from ‘Free Photo Library’ only adds the first selected.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#1902]
### Description
With the block editor enabled when the user goes to create a new post, selecting ‘Image’ then ‘Choose from Free Photo Library’ and makes any search, the user is able to select multiple images, however when they add these to the post only the first one is added. On iOS this adds all images as expected.

### Reproduction Rate
4/4 100%

### Expected behaviour
All images are added to the post.

### Actual behaviour
Only the first selected image is added to the post.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Login to an account.
3. Select ‘My site’.
4. Select the add post icon.
5. Blog post.
6. Tap the plus icon and select Image.
7. Add image.
8. Choose from Free Photo Library.
9. Search any generic term.
10. Select multiple images and add them.

##### Tested on the following
Samsung Galaxy S7 (7.0)
Huawei P20 Pro (9.0)

#### Please see the attached video for more information
[multiple_images_android.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4199548/multiple_images_android.zip)

### Submitted by:
Oliver Howe

**Comment by hypest** [comment]
👋 @marecar3 , you worked last on the Pexels integration, please have a look to try to enable this. FWIW, the image block already supports multiple images when selected from the WP Media library so.

**Comment by marecar3** [comment]
> 👋 @marecar3 , you worked last on the Pexels integration, please have a look to try to enable this. FWIW, the image block already supports multiple images when selected from the WP Media library so.

Will do, thanks @hypest !

**Comment by pinarol** [comment]
Related recent PR https://github.com/wordpress-mobile/WordPress-Android/pull/11912

**Comment by marecar3** [comment]
Closing this one as it's fixed with this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/11912

Thanks, @pinarol, and @mkevins!
