### ISSUE TITLE
Bad layout on bottom sheets with big text sizes

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1906]
**Describe the bug**
iOS: Using accessibility text sizes, the inserter looses the column layout.
Android: The Media selector options on Image Blocks gets its layout broken.

![layout](https://user-images.githubusercontent.com/9772967/74524186-d5096f80-4f1e-11ea-882c-67973fd14937.png)

**To Reproduce**
Steps to reproduce the behavior on iOS:
1. Activate one of the big accessibility text sizes on the OS system.
2. Open the block inserter.
3. Check that the layout is not right.

Steps to reproduce the behavior on Android:
1. Activate one of the big text sizes and a **big display size** on the OS system.
2. Add an image block.
3. Open the media selector as shown in the screenshot.
4. Check that the layout is not right.

**Expected behavior**
The layout should be as expected.

Not sure if this PR might be related to these issues: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1837

cc @lukewalczak @pinarol

**Comment by rachelmcr** [comment]
This also seems related to the i18n issue observed in the block picker in https://github.com/wordpress-mobile/gutenberg-mobile/issues/1907.

**Comment by lukewalczak** [comment]
Thanks! Working on that!
