### ISSUE TITLE
[GlobalStep] Videos added via block editor do not show a thumbnail when previewed or published.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#1909]
### Description
If the user goes to make a site or blog post and adds a video using the block editor, when the post is previewed or viewed after being published the video does not show a thumbnail of its contents, on Android a generic play symbol is shown in the background, on iOS there is no thumbnail at all.

### Reproduction Rate
4/4 100%

### Expected behavior
A thumbnail of a frame of the video is displayed.

### Actual behavior
There is no thumbnail of the video displayed.

### Steps to reproduce the behaviour
1.	Install WordPress 14.2
2.	Login.
3.	Select to make a new post.
4.	Tap the icon to add content.
5.	Select video.
6.	Take a video or choose one from gallery.
7.	Allow the video to upload then preview the post.

##### Tested on the following
Samsung Galaxy Tab S2 8.0” (7.0)
LG G3 (5.0)
iPhone 6 (12.4)

#### Please see the attached videos for more information
[Android Video Preview.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4204499/Android.Video.Preview.zip)
[iOS_Video_Preview.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4204500/iOS_Video_Preview.zip)

### Submitted by:
Oliver Howe

**Comment by SiobhyB** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/35637.
