### ISSUE TITLE
Issue with contextual menu and our format bar.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/gutenberg-mobile#193]
Selecting a word in the first line of a block may cause the native iOS contextual menu to cover our format bar, making it impossible to click on the format buttons.

<img width="368" alt="screen shot 2018-10-24 at 2 31 01 pm" src="https://user-images.githubusercontent.com/1836005/47449693-a7347080-d799-11e8-918d-847fb73c3932.png">

Seems to affect iOS only, as in Android I could not get a similar menu to come up.

Options I can think of:

- Remove the native contextual menu, and handle cut, copy & paste in a different way.
- Try to make the contextual menu show elsewhere.  I'm not sure this is possible.
- Move the formatting options elsewhere.

Ping @iamthomasbishop

**Comment by koke** [comment]
It’s been bothering me as well, but the toolbar will be moved soon to the bottom of the screen

**Comment by iamthomasbishop** [comment]
What @koke said. The toolbar will sit above the keyboard or along the bottom edge of the screen when the keyboard is hidden.
