### ISSUE TITLE
Crash on pasting HTML

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1950]
**Describe the bug**

The app crashes when pasting content copied from https://automattic.com/work-with-us/

Tested on iOS device (iPhone XS) running last develop (d514b1d865e2744bf3339c38d4d92ed4745010d7). Copying from Safari 13.05 on MacOS 10.15.3.

**To Reproduce**
1. Go to https://automattic.com/work-with-us/
2. Copy the first part of the page (from `Work With Us` until the end of the `Coming on board` paragraph).
3. Paste on Gutenberg Mobile (on an empty post).
4. See error `Type error: undefined is not an object`.

**Expected behavior**
It should paste the content creating the different blocks as on web (https://mysitefortestingetoledom.wordpress.com/2020/02/24/paste-test-on-web/)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6, Pixel 4]
 - OS: [e.g. iOS 8.1,  Android X]

**Additional context**

**Comment by etoledom** [comment]
It also crashes on current WPiOS Beta (14.2).

**Comment by designsimply** [comment]
Still crashing in WPiOS 14.4.0.0 TestFlight beta on iPhone 11 iOS 13.3.1. ([40s](https://cloudup.com/cXQwJpzDl1o))

@etoledom since #1964 has the 1.24 Milestone, I should be able to see the fix in 14.4 beta correct?

**Comment by etoledom** [comment]
@designsimply - We haven't yet released the version 1.24 of the editor, so this fix should come with the next WP Apps release (14.5)

**Comment by designsimply** [comment]
That explains it! 😆 Thanks!

(I thought the version numbers aligned, i.e. 14.4 and 1.24.)
