### ISSUE TITLE
Buttons blocks added using the block editor on WordPress.com show up as "Unsupported"

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#1956]
Steps to reproduce:

1. On the web, log in to WordPress.com and go to a WordPress.com-hosted site.
1. On the web, create a new post, add a button block, and save the post as a draft.
1. In the app, open the post and try to view the button block in the editor.

**Result:** button blocks added using the block editor on WordPress.com show up as "Unsupported" in the block editor in the iOS app.

**Note:** this problem only happens with button blocks created with Calypso Gutenberg. Buttons added to Jetpack or self-hosted sites using Gutenberg do not have the same problem.

<img src="https://user-images.githubusercontent.com/1119271/75326632-3511e700-5838-11ea-9122-dd0ae5bfbab9.PNG" width="270" alt="IMG_3447">
<sup>Tested with WPiOS 14.3.0.0 TestFlight beta on iPhone 6S iOS 13.3.1.</sup>

**Comment by lukewalczak** [comment]
Hello @designsimply, please notice that Button**s** are not supported not Button. Could you please confirm that on the web you've added Button (it should not be possible since we are not supporting it) instead of Buttons?

**Comment by designsimply** [comment]
I see! On the web I did add the "Buttons" block but didn't realize it would work any differently than the "Button" block. 😁 I also see that work is happening at https://github.com/wordpress-mobile/gutenberg-mobile/issues/1790 to support the Buttons block, which should close this issue when it's completed.

**Comment by lukewalczak** [comment]
> I also see that work is happening at #1790 to support the Buttons block, which should close this issue when it's completed.

Exactly, working on it to ship it asap! :D

**Comment by pinarol** [comment]
Since this is opened due to a misunderstanding do you see value keeping this one open? @designsimply ? This is trackable by https://github.com/wordpress-mobile/gutenberg-mobile/issues/1790

**Comment by designsimply** [comment]
I think it still feels like a bug for the Buttons block (even though it's expected since it's not technically supported yet). I would leave it open and let it be closed by 1790. That way, if others find the same problem they will hopefully search and see that this issue is being worked on already. 

Note: I also updated the title to say "Buttons" block instead of "Button" block.

**Comment by pinarol** [comment]
Closing since Buttons block is merged on mobile a while ago.
