### ISSUE TITLE
Button Block: links copied to clipboard are auto-filled to URL field in the link settings but not in the block settings

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#1957]
Links copied to clipboard were automatically added to the URL field when tapping the link settings (link icon in toolbar) but the same thing does not happen for links copied to the clipboard when tapping the block settings (gear icon on block). This confused me. 

Auto-filling the URL field with the link from the clipboard should work the same way for both the link settings and the block settings.
 
Video: [1m3s](https://cloudup.com/cD1iTISMTRP)
<sup>Tested with WPiOS 14.3.0.0 TestFlight beta on iPhone 6S iOS 13.3.1.</sup>

<img width="270" alt="Screen Shot 2020-02-26 at Feb 26 1 56 35 AM" src="https://user-images.githubusercontent.com/1119271/75328571-75269900-583b-11ea-9176-3237a43a9685.png">

**Comment by pinarol** [comment]
Thanks for the issue @designsimply Just to clarify, the feature wasn't implemented at all for block settings so this will be an improvement rather than a bug fix.
