### ISSUE TITLE
Hide FloatingToolbar for top level blocks that doesn't have nesting capabilities

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1960]
FloatingToolbar behavior was unified among different blocks with [this PR](https://github.com/WordPress/gutenberg/pull/20064). But, we are getting some feedback about how FloatingToolbar can be confusing. Let's consider hiding it for top level blocks that doesn't have nesting capabilities. @iamthomasbishop 

> Hello! Can someone tell me what the point of the ‘paragraph’ pop-up tag that shows up with the arrow in the Android app is? https://share.getcloudapp.com/WnuNNx0Y A user has reported these as ‘useless’ and to be honest I can’t really see what they are for neither other than identifying the block.

**Comment by pinarol** [comment]
@iamthomasbishop we can start this as soon as you give the 👍

**Comment by iamthomasbishop** [comment]
Considering the position we're in (don't have the ["ideal" version](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1414) of the toolbar as soon as we were expecting because of technical challenges), I think this is a good next step to resolve some of the friction until we can close the gap by shipping the ideal version.

I'm not sure if it's noted anywhere, but we also should consider hiding the `⤴️` button on the toolbar for top-level blocks.

**Comment by pinarol** [comment]
@jbinda could you start the work on this? 

>I'm not sure if it's noted anywhere, but we also should consider hiding the ⤴️ button on the toolbar for top-level blocks.

I don't think we have another issue for that. Could you describe the case for hiding that button please? How should we hide the FloatingToolbar if we remove it?

**Comment by iamthomasbishop** [comment]
> Could you describe the case for hiding that button please?

We should hide the ⤴️ button and the separator to the right of it on all top-level blocks, whether using InnerBlocks or not because it is not possible to go "up" an additional level. Does that make sense?

**Comment by pinarol** [comment]
@iamthomasbishop Sorry my question was not clear. The up button also dismisses the FloatingToolbar on top level elements, how do we dismiss the FloatingToolbar if there's no  ⤴️ button? Or we just don't? It'll dismiss itself when user selects another block.

**Comment by jbinda** [comment]
I have open new issue: #1967 to

>consider hiding the ⤴️ button on the toolbar for top-level blocks.

and will post PR to revert FloatingToolbar visibility for root list block soon
