### ISSUE TITLE
Make SPTs(Layouts) public

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1962]
Let's remove the feature flag and open SPTs(Layouts) for public usage.

**Comment by pinarol** [comment]
After the completion of [SPTs metrics](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1883), it seems like we are ready to do this. Let me know if you have any concerns. @koke @iamthomasbishop

**Comment by koke** [comment]
I think it's good to go 😊

**Comment by iamthomasbishop** [comment]
I'm not 100% sure what "make public" means in this case, but assuming it's just removing the DEV flag so we can test internally, I think that's a 👍 from me. To be clear, I need to do a more comprehensive design review now that we are ready to test all of the individual pieces together, but if that's all correct then 👍 from me!

**Comment by pinarol** [comment]
> but assuming it's just removing the DEV flag so we can test internally

Right, we'll remove the DEV flag, thus, you'll be able to test.  Once we merge this change it'll be available in prod so, we'll need your review/approval on the PR. @iamthomasbishop

**Comment by iamthomasbishop** [comment]
Perfect! Let’s do it :shipit:

**Comment by koke** [comment]
I’ll take it. I started this last week so I could get CircleCI to generate an installable build, so most of it is done, it just needs PRs to be created
