### ISSUE TITLE
"Take a Photo" option fails often when adding images to gallery or image blocks

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#1965]
Steps to reproduce:

1. Add a gallery block.
1. Add an image using "Choose from device"
1. Tap the "+" button at the bottom of the gallery block.
1. Add an image using the "Take a Photo" option.
1. You may need to try several times before it fails.
1. Add an image block.
1. Tap "ADD IMAGE".
1. Try adding an image using the "Take a Photo" option.

**Result:** the "Take a Photo" option fails often when trying to add images to the gallery block or the image block—this happens most often after adding an image in another way _first_, such as using the "Choose from device" option.

Video 1: [2m28s](https://cloudup.com/c2S0nAFVtAF)
<sup>Tested with WPiOS 14.3.0.0 TestFlight beta on iPhone 6S iOS 13.3.1.</sup>

* App logs: [text.txt](https://github.com/wordpress-mobile/gutenberg-mobile/files/4264263/text.txt) (tokens redacted)
* WPiOS 14.3.0.0 TestFlight beta
* iPhone 6S (WiFi only)
* iOS 13.3.1.
* Jetpack 8.2.3 site (but it fails for me in any site type)
* WiFi connection speed: 54 Mpbs down, 60 Mbps up (Google Fiber)

Video 2: [1m23s](https://cloudup.com/ceqxkbWHM9q)
<sup>Tested with WPiOS 14.3.0.0 TestFlight beta on iPhone 6S iOS 13.3.1.</sup>

* App logs: [text-2.txt](https://github.com/wordpress-mobile/gutenberg-mobile/files/4264302/text-2.txt) (tokens redacted)
* WPiOS 14.3.0.0 TestFlight beta
* iPhone 6S (WiFi only)
* iOS 13.3.1.
* WordPress.com Premium
* WiFi connection speed: 54 Mpbs down, 60 Mbps up (Google Fiber)

**Comment by mkevins** [comment]
@designsimply :wave: thanks so much for providing such a high level of detail! This will be very helpful in reproducing the issue and finding a solution.

When you mention:

> You may need to try several times before it fails.

Was the "Take a photo" option working for you in some cases, or just the "choose from device" option? If so, once it was in a "broken" state (where "take a photo" was not working), do you remember if every attempt failed after that?
