### ISSUE TITLE
Bolding text using the toolbar causes whitespace to be lost

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#1966]
### Description
When bolding text using the toolbar button on iOS or Android, any whitespace present at the beginning of the line is removed causing the the text to jump to the left and the whitespace to be lost. This affects the pre-formatted block, the verse block, and, to a lesser extent, the paragraph block. **This issue is not present on Gutenberg web.**

On iOS, bolding through the native iOS edit menu (the toolbar menu that displays selection options) is not affected by this bug.

The same bug is present for italics or strikethrough.

### Steps to Reproduce

There are two distinct scenarios where this bug is present.

#### Scenario 1: Styling non-selected text

In a paragraph block, type some spaces, then tap the toolbar bold button and observe that the cursor jumps back to the start of the line. The cursor should stay put when the bold button is tapped.

#### Scenario 2: Styling selected text

1. In a paragraph (or verse or pre-formatted) block, type some spaces and then text, such as:
```
    Hello
```
2. Bold the Hello portion of the line using the toolbar bold **B** button (on iOS, don't use the native iOS edit menu)
3. Observe the text has shifted to the left and the whitespace has disappeared 
4. The same occurs for the toolbar italics and strikethrough options

iOS | Android
-|-
<img width="300" src="https://user-images.githubusercontent.com/1898325/75491168-453ed900-5994-11ea-9a6a-2a242d05691a.gif"> | <img width="300" src="https://user-images.githubusercontent.com/1898325/75548525-3e53ad00-5a0c-11ea-8c7e-e8998a9704dc.gif">

### Expected Behavior
Applying bold/italics/strikethrough to text should not affect leading whitespace or reposition the text in any way.

## Devices
| | iOS | Android
--|--|--
**Device** | iPhone 7 | Google Pixel Emulator
**OS** | iOS | Android 10
**OS Version** | 13.3.1 | API 29 Version Q 

## Additional Context

This bug is present in the Gutenberg editor in the WordPress for iOS app **and** in the Gutenberg example iOS and Android projects in this repo. It is **not** present on the Aztec for iOS example app or the WordPress for iOS Classic editor.

**Comment by guarani** [comment]
I've seen this 💥 while reproducing this bug on Android. It seems to happen when you shift text to the right, bold it, and repeat. On the second iteration I've seen this crash often.

<img width="250" src="https://user-images.githubusercontent.com/1898325/75549516-a1464380-5a0e-11ea-9a07-7f25f5f3c08e.png">

**Comment by hypest** [comment]
> This bug is present in the Gutenberg editor in the WordPress for iOS app and in the Gutenberg example iOS and Android projects in this repo

I see the Android demo app is not mentioned. Does the issue happen there too?

From the looks of this, I'd suspect something on the RN/JS level is trimming the whitespace? Have you investigated there @guarani ? In particular, find out if trimming does happen intentionally or not, under which circumstances or assumptions and whether we can suppress that in this case.

**Comment by guarani** [comment]
> I see the Android demo app is not mentioned. Does the issue happen there too?

Are you referring to the Gutenberg demo/example Android project? Then yes – but let me know if you're referring to something else.

It's been a while since I debugged this so I'll do that and write up a summary here.

**Comment by guarani** [comment]
Where is this bug present?
| Where | Is present? | 
|--|--|
| WordPress for iOS/Android | Yes |
| Gutenberg Mobile Demo App for iOS/Android | Yes |
| Aztec Editor for iOS/Android | No |

This leaves three possibilities for where the bug lies:
1. `react-native-aztec` (the bridge between each React Native rich text component and its corresponding native Aztec view)
2. `react-native-gutenberg-bridge` (the bridge between the native app itself and the React Native Gutenberg editor)
3. The JS code of rich text.

Possibility nº 1 would be straightforward to test if `react-native-aztec` with a standalone React Native project that imports Aztec as a native view. Possibility nº 2 can be tested with the Gutenberg mobile example project for iOS/Android. Possibility n° 3 should be tested by looking at the `preserveWhiteSpace` attribute and `willTrimSpaces` function of the `<RichText>` component.

Will update with results from tests of these three possibilities.

**Comment by guarani** [comment]
Reopening to fix issue where whitespace is deleted on second and subsequent lines within a block. Fix coming here: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1285

**Comment by guarani** [comment]
Fixed by https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1285

**Comment by fylgjur** [comment]
Device: Samsung Galaxy S9+
Version: WordPress Android beta 15.0-rc-1
Theme: P2 (A8c Personal)

Although bolded text with spaces before it doesn't jump to the left in block editor, spaces are removed when viewing in the app or on web, though all is fine again in the P2 front edit:
![jabb1](https://user-images.githubusercontent.com/65490337/83735924-ddf68c00-a648-11ea-9b8d-2e9d84fe5dd3.gif)

It appears correctly in the Reader:
![jabbreader](https://user-images.githubusercontent.com/65490337/83735998-f4044c80-a648-11ea-9dfd-065802f0089c.png)

HTML: 

![Screenshot_20200604-095309_WordPress](https://user-images.githubusercontent.com/65490337/83736305-578e7a00-a649-11ea-93ce-1604b802274c.jpg)

If you need any different info, please say (first post!).

**Comment by guarani** [comment]
@fylgjur thanks a lot for uncovering this – the root cause seems to be an autosave issue, which is now being tracked here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2349
