### ISSUE TITLE
Consider hiding the ⤴️ button on the toolbar for top-level blocks

### ISSUE THREAD

**Issue by jbinda** [wordpress-mobile/gutenberg-mobile#1967]
According to [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1960) and Slack discussion I separate `Consider hiding the ⤴️ button on the toolbar for top-level blocks` to another issue

**Comment by jbinda** [comment]
@iamthomasbishop  @pinarol  

Please take a look on below GIF:

<image src="https://user-images.githubusercontent.com/21242757/75545804-8f24cf00-5a27-11ea-869c-47ed8c9c938d.gif" width="300" />

**Comment by iamthomasbishop** [comment]
Looks right to me 👍
