### ISSUE TITLE
Issues with the Beta Version

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/gutenberg-mobile#1975]
**Describe the bug**
1. The editor won't add new blocks where the user wants. Instead all go to the bottom.
2. The option to move blocks up or down is gone.
3. This item doesn't seem to do anything for the user
![](https://d.pr/i/qXV6BE+)
(Image link: https://d.pr/i/qXV6BE )

**Smartphone (please complete the following information):**

Site : https://mydialectics.wordpress.com
OS Version: Android 8.0.0
Version of WordPress : 14.3-rc-2

#2754154-zen

**Comment by hypest** [comment]
👋 @sarahfg, sorry for the delay getting back to this ticket.

> The editor won't add new blocks where the user wants. Instead all go to the bottom.

Tried some tests myself but seems to work as expected on my side. If nothing is selected (not the title nor any block) then indeed the new block is added at the end of the post. If anything is selected then the new post gets added right below it. Long-tapping on the Inserter button also let's you decide if the block should be added _above_ or below the current block.

Do you perhaps have some steps to reproduce the issue?

> The option to move blocks up or down is gone.

Hmm, not able to reproduce this either, are there any steps to repro? The buttons are there as normal in my testing. Screenshot from my test:

![screenshot-1586168331455](https://user-images.githubusercontent.com/1032913/78548317-4a9c0880-7809-11ea-917c-5c02c71ec048.jpg)

> This item doesn't seem to do anything for the user
>
> (Image link: https://d.pr/i/qXV6BE )

Unfortunately, the image doesn't seem to be available anymore but, checked out the Zendesk ticket and it seems the user is referring to the popup navigation toolbar. That toolbar displays a "breadcrumb" of the block nesting, particularly useful in blocks that have inner blocks. A ticket is also opened (and addressed by the time or writing) [for hiding the "Out" button when at the top level of the post](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1967).

cc @iamthomasbishop , @pinarol to share this ^ feedback.

**Comment by iamthomasbishop** [comment]
> Long-tapping on the Inserter button also let's you decide if the block should be added above or below the current block.

It’s also worth mentioning that long-press while _no blocks_ are selected will give you the option to add at the beginning or end of the post.

> The option to move blocks up or down is gone.

I wonder if this is happening on a certain type of block or certain situation where the movers would be in a  “disabled” state? For example, if you have a single block inside something like a Group block, or a single paragraph inside a Media & Text block, the movers will be disabled because you can’t really move the block anywhere. That’d be my guess but maybe there is a bug here.

> it seems the user is referring to the popup navigation toolbar

That seems right, and there is some work being done to improve how this works and add some clarity. 👍

**Comment by SiobhyB** [comment]
As this issue is labelled `unreproduced` and is nearing four years without similar reports, I'll go ahead to close in the hopes it was either an edge case or has been resolved over the years.
