### ISSUE TITLE
Beta Version user reporting sluggish functionality

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/gutenberg-mobile#1978]
**Describe the bug**

> I Am unable to type fluently, no apps hang and get slowed down and no other apps are Sluggish in functionality, but it's only your app where I'm unable to compose a story, I'm unable to type fluently and it hangs

**Smartphone (please complete the following information):**
 

Android 9
WordPress - 14.3-rc-1 - Version code: 832
Android device name: Vivo 1902
Editor: Gutenberg

#2755182-zen

**Comment by SiobhyB** [comment]
I'm going to close in favour of other open tickets related to poor performance, i.e. https://github.com/wordpress-mobile/gutenberg-mobile/issues/2628 and https://github.com/wordpress-mobile/gutenberg-mobile/issues/1888.
