### ISSUE TITLE
Very slow loading on editor start

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/gutenberg-mobile#1986]
> Using a Moto e5 play with Android 8.1.0, every time I open the block editor it takes ~15 seconds to load. If I exit and re-open the editor more than a couple times in a single session it feels impossibly slow to keep working in the app. - @rachelmcr 

I don't know if there any trick to make this faster. I wonder if there is a way to strip the bundle or do some other optimization. We can also think about pre-loading it after app start or keep it in memory if the loading time was too slow.

First step: gather some data (or track loading times if not tracked yet).

**Comment by rachelmcr** [comment]
Sorry, I should have mentioned there's already an open issue for this at https://github.com/wordpress-mobile/gutenberg-mobile/issues/1888.
