### ISSUE TITLE
Refactor RangeControl to render Stepper or Slider inside

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1992]
We want to keep the components API same with web, so let's Refactor RangeControl to render Stepper or Slider depending on the item count. If it has <=8 items it should render a Stepper, otherwise Slider.

Related discussion: https://github.com/WordPress/gutenberg/pull/20231

**Comment by pinarol** [comment]
Item count is currently not a good factor to distinguish between Stepper & Slider because we decided to allow for unlimited number of columns in Columns block but we are still keeping the Stepper there. We'll need to introduce a different prop to RangeControl to be able to decide what to render inside.

**Comment by chipsnyder** [comment]
Could we add something as basic as always having it default to a stepper control unless a passed a key like `useSlider=true` or vice versa?

**Comment by chipsnyder** [comment]
another option would be to have a key of `type=slider`

**Comment by pinarol** [comment]
‘type=slider’ sounds good to me.
