### ISSUE TITLE
Refine +/- icons used in Stepper control

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1999]
## Problem

I believe we're currently using the [Dashicons](https://developer.wordpress.org/resource/dashicons/) versions of the `+` and `-` icons, which frustratingly have different weights. As a result, the pairing looks unbalanced. Example:

<a href="https://user-images.githubusercontent.com/1200432/76425764-16533a80-6378-11ea-9de0-9e960c3a8789.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76425764-16533a80-6378-11ea-9de0-9e960c3a8789.jpeg" width="375"></a>

## Proposal

We should bring these in line so that they feel balanced.

@etoledom can you advise on what best approach would be here?

* Find an alternative in the existing icons package (not sure if an alternative exists)
* Use an icon from [Gridicons](http://automattic.github.io/gridicons/) or [Material](https://material.io/resources/icons/?style=baseline)
* Make a custom icon

**Comment by SiobhyB** [comment]
I'm no longer seeing the different weights in the latest (`24.3`) version of the app. Going ahead to close this issue.

<img width="399" alt="Screenshot 2024-02-21 at 11 53 24" src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/2998162/f39fdd6b-c02a-4d66-8b4e-83caa4281971">
