### ISSUE TITLE
[Android] Remove `Cancel` button from Gallery settings quick action sheets

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2001]
We are displaying a `cancel` button on the "Link to" and "Image size" quick action sheets, but we aren't on any sheets (on Android). I've only seen these on the Gallery block settings, so let's remove these buttons but also investigate if they are used in other places.

Note: this is Android-only, where we're replicating the iOS-equivalent of ActionSheet (which _does_ generally have a cancel action).

**To Reproduce**
1. Add a Gallery block
2. Tap on the `cog` (settings) icon
3. Tap on `Link to` row
4. See `Cancel` button

**Screenshots**

<a href="https://user-images.githubusercontent.com/1200432/76443370-4e667780-6390-11ea-9557-a4e1fd51c18b.png"><img src="https://user-images.githubusercontent.com/1200432/76443370-4e667780-6390-11ea-9557-a4e1fd51c18b.png" width="990"></a>

cc @mkevins — would you mind taking a look at this? Seems like it should be a quick one.

**Comment by iamthomasbishop** [comment]
Ah shoot, I just realized this was already documented on some [existing Gallery block issues](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1674). @mkevins feel free to close this one if you'd like to address as part of that work!

**Comment by mchowning** [comment]
I'm no longer seeing the cancel button, but there does appear to be some extra padding at the bottom. I assume we want to remove that padding. cc: @iamthomasbishop 

![image](https://user-images.githubusercontent.com/4656348/158869829-13b65355-4c6d-4f85-a131-382bdad51d3f.png)

**Comment by iamthomasbishop** [comment]
@mchowning That'd be great. I believe there should be only 8px spacing below the list there.

**Comment by mchowning** [comment]
With the merge of #40056 addressing the padding issue, I'll close this since I don't see the cancel button anymore on these action sheets on Android.
