### ISSUE TITLE
Tapping on a link in the editor doesn't open the link settings

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2010]
Steps to reproduce:

1. Create a new post.
1. Add a link.
1. Tap elsewhere in the post.
1. Try to edit the link.

**Result:** tapping briefly on a link does not open the link bottom sheet as expected. Previously, lightly tapping the link would pull up the link dialog. Tap and hold does open the bottom sheet, but sometimes a preview opens instead.

iOS Video: [1m6s](https://cloudup.com/cW8r2WhSMYj)
<sup>Tested with WPiOS 14.4.0.0 TestFlight beta on iPhone 11 iOS 13.3.1.</sup>

![cannot-tap-link](https://user-images.githubusercontent.com/1119271/76582543-25cba400-649c-11ea-87db-da5aa4ebed63.gif)
<sup>Tested with WPiOS 14.4.0.0 TestFlight beta on iPhone 11 iOS 13.3.1.</sup>

**Note:** it's working as I would expect in Android, I can tap on a link briefly and it opens the link settings.

Android Video: [33s](https://cloudup.com/ceH7e5Oa2z6)
<sup>Tested with WPAndroid 14.4-rc-1 on Pixel 4 Android 10.</sup>

**Comment by etoledom** [comment]
There's a bug on iOS where the API doesn't behaves as expected when interacting with links. We did some previous workarounds resulting in a bit of instability, and the current workaround have been working pretty much fine.

If we try to fine-tune this workaround we might end up again with instability.

Some more detailed info here:
https://github.com/wordpress-mobile/gutenberg-mobile/pull/1540

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/1540.
