### ISSUE TITLE
Refine border-color/width of inner selection highlights

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2019]
## Border Color

Currently, we're using "old" blues (WordPress.com blue) from [Colors Archive](https://dotcombrand.wordpress.com/colors-archive/) for the inner highlight when certain blocks are selected (and I'm not 100% sure if we're using the same blue across the board or not). 

This border color should be the same color as the block-level selection border (`blue-50` in light mode and `blue-30` from [Color Studio](https://color-studio.blog) in dark mode, IIRC).

This applies to the following blocks (and maybe more that I'm missing):

<details>
  <summary>Image</summary>
 
 <a href="https://user-images.githubusercontent.com/1200432/76652589-e4d39e00-6534-11ea-88b7-da6d9d4123d4.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76652589-e4d39e00-6534-11ea-88b7-da6d9d4123d4.jpeg" width="375"></a>

<a href="https://user-images.githubusercontent.com/1200432/76652618-f87f0480-6534-11ea-8578-f9131638dde7.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76652618-f87f0480-6534-11ea-8578-f9131638dde7.jpeg" width="375"></a>
</details>

<details>
  <summary>Video</summary>

  <a href="https://user-images.githubusercontent.com/1200432/76652677-1482a600-6535-11ea-946a-c8821a3f2a47.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76652677-1482a600-6535-11ea-946a-c8821a3f2a47.jpeg" width="375"></a>

<a href="https://user-images.githubusercontent.com/1200432/76652694-1d737780-6535-11ea-986f-413a63b06752.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76652694-1d737780-6535-11ea-986f-413a63b06752.jpeg" width="375"></a>
</details>

<details>
  <summary>Gallery</summary>
  
<a href="https://user-images.githubusercontent.com/1200432/76653257-59f3a300-6536-11ea-94b0-40044aa1c018.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76653257-59f3a300-6536-11ea-94b0-40044aa1c018.jpeg" width="375"></a>

<a href="https://user-images.githubusercontent.com/1200432/76653285-67109200-6536-11ea-87ca-7aeb0640ab75.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76653285-67109200-6536-11ea-87ca-7aeb0640ab75.jpeg" width="375"></a>

</details>

<details>
  <summary>Spacer</summary>

<a href="https://user-images.githubusercontent.com/1200432/76653309-70016380-6536-11ea-8c76-e70a63c0eef2.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76653309-70016380-6536-11ea-8c76-e70a63c0eef2.jpeg" width="375"></a>

<a href="https://user-images.githubusercontent.com/1200432/76653325-77287180-6536-11ea-9d38-7626c5298869.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76653325-77287180-6536-11ea-9d38-7626c5298869.jpeg" width="375"></a>

</details>

Note:  If we haven't already established this, we might want to create a variable for `$element-highlight` or similar (I'm not able to think of a better name at the moment) that will use the primary color (`blue-50` in light, `blue-30` in dark) and be used for block selection borders, inner selection borders, media upload progress indicators, etc.

## Border Width

I believe in the code we are using a 3px border-width on the element highlights — we can tone that down to 1px. I've been using 1px in our design library for a little while to see how it feels, and it feels more balanced.

Here's a comparison of current (3px) and proposed (1px):

<a href="https://user-images.githubusercontent.com/1200432/76654201-72fd5380-6538-11ea-812e-cb80eda71a5c.png"><img src="https://user-images.githubusercontent.com/1200432/76654201-72fd5380-6538-11ea-812e-cb80eda71a5c.png" width="800"></a>

**Comment by maxme** [comment]
> I believe in the code we are using a 3px border-width on the element highlights — we can tone that down to 1px. I've been using 1px in our design library for a little while to see how it feels, and it feels more balanced.

It was 3px and I think it was recently changed to be 2px (at least on the gallery block): https://github.com/WordPress/gutenberg/commit/0192d0703ff8b586383988da5403c480cf2bd7a0#diff-01fde8c001e37baf7fd56edeea8e912b

**Comment by iamthomasbishop** [comment]
> It was 3px and I think it was recently changed to be 2px (at least on the gallery block):

Ah, okay, that makes sense. 👍

**Comment by geriux** [comment]
Closing since we removed most of the block outlines.
