### ISSUE TITLE
Remove extra padding on Post Title

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#2021]
The post title has an extra left/right padding. It should be aligned with the post content.

<a href="https://user-images.githubusercontent.com/1200432/76649620-177a9800-652f-11ea-8c43-10787c69fce0.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76649620-177a9800-652f-11ea-8c43-10787c69fce0.jpeg" width="375"></a>

- Taken from https://github.com/wordpress-mobile/gutenberg-mobile/issues/992#issuecomment-598859371 (@iamthomasbishop)

**Comment by SergioEstevao** [comment]
This was solved by this PR:https://github.com/WordPress/gutenberg/pull/22331
