### ISSUE TITLE
Blinking Slider after press ( BottomSheet settings cell )

### ISSUE THREAD

**Issue by jbinda** [wordpress-mobile/gutenberg-mobile#2022]
**Describe the bug**
Pressing on Slider row title in block Settings cause the whole row to blink (ripple effect)

**To Reproduce**
1. Add `Spacer` block
2. Open `Spacer` settings
3. Press on Slider row title
4. See the whole row has ripple effect (which I suppose shouldn't happens)

Reproduce the same for `Gallery` and see how Stepper control behaves

**Expected behavior**
I think the Slider should behave in the same way as Stepper (in Stepper pressing on title do not cause whole row to blink)

**Screenshots**
Below GIF shows how `Gallery` Stepper behaves vs how `Spacer` Slider behaves.
<img src="https://user-images.githubusercontent.com/21242757/76750012-cad8cc00-677d-11ea-8f4b-01364198dced.gif" width="300" />

**Comment by jbinda** [comment]
@pinarol @iamthomasbishop I have open a PR for that. Just need to make sure if it's behaviour that we would like to introduce (according to how Stepper work I assume we would like to have Slider works in the same way - which is do not have ripple effect)

**Comment by iamthomasbishop** [comment]
@jbinda @pinarol I'm curious about the rationale for the ripple (and for that matter, the entire cell being a tap area to take the associated control's action). It feels a little odd to me as a primarily-iOS user, but I'm guessing there was a reason that it's included in the library we're using. IIRC there was some discussion of some accessibility benefits we get from the current behavior. // cc @etoledom I think it might have been you that made mention of the accessibility benefits — any thoughts here?

To me, the effect _sort of_ makes sense on a cell that has something like a Toggle control, but I don't feel like it's necessary for others.

**Comment by jbinda** [comment]
From the implementation point of view it looks as follow. 

Whole content of each row cell in BottomSheet settings is wrapped in TouchableOpacity component which is responsible for ripple effect after onPress event. We have option to lock it by passing `disable={true}` to that cell.

You right that on iOS it works differently (only e.g. the Switch is animated not the whole title). However it's hard for me to say something more because that was the state I saw from the beginning of work on this project. Until now I did not noticed this as something unexpected

**Comment by etoledom** [comment]
From the accessibility point of view, it's good to be able to trigger the main cell action (focusing on text field, toggling a switch, etc...) without the need to search for that specific component inside the cell.

I found also good to leave this behaviour to all users, increasing the actionable area, and make it easier for users to focus the text field or toggling the switch. Besides, technically when we have an input control with content, what we show is a label, so we need a trigger to switch it to a text field and focus it.

But of course this doesn't make much sense with settings that has more than one action or use a different gesture (like sliding). Maybe we should disable it by default and activate it in these specific cases where it is helpful.

**Comment by jbinda** [comment]
Is below correct ?
1. We should disable ripple for Slider (it means merge [this](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2023))
2. Consider disable ripple by default for all type of bottom sheet rows

**Comment by iamthomasbishop** [comment]
@etoledom Good points regarding a11y. I don't necessarily think we should remove the ability to tap the whole row, but the ripple animation feels odd (esp on iOS). I also think it might be weird if only certain types of rows perform that feedback animation, so I would either keep on all rows or remove it on all.

For now, let's remove the ripple for Stepper and Slider. Moving forward @jbinda are you able to create a build that removes the ripple effect (but leaves the *ability* to tap the whole row in order to perform the relevant row action)? Once we have a build to test, we can test on both iOS and Android and refine if necessary.

**Comment by jbinda** [comment]
>Moving forward @jbinda are you able to create a build that removes t

Sure I will prepare builds today :)

**Comment by jbinda** [comment]
@iamthomasbishop 

build for iOS with disable ripple effect for each bottom sheet cell is available [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/13691#issuecomment-601725727)

build for Android failed on CI 😢  so I need to check what happens and apply fixes and then share the link

**Comment by iamthomasbishop** [comment]
I think iOS feels natural without the ripple effect, so 👍 there from me. @etoledom what do you think?

I'll hold judgment on Android until I have a build to test.

**Comment by etoledom** [comment]
Looks good to me too. I commented[ on the PR about an issue with VoiceOver](https://github.com/WordPress/gutenberg/pull/20922#pullrequestreview-379262836). Other than that looks great!

**Comment by jbinda** [comment]
@etoledom I saw your comment and will check it :)

@iamthomasbishop below is the link to builds on Android which finally passed the CI and refreshed iOS as well:

iOS:[ IPA 25600 ](https://github.com/wordpress-mobile/WordPress-iOS/pull/13691#issuecomment-601725727)
Andorid: [APK 42228 ](https://github.com/wordpress-mobile/WordPress-Android/pull/11483#issuecomment-603278212)

**Comment by iamthomasbishop** [comment]
@jbinda Ok, had a chance to test on Android quick, and I have a couple of thoughts 😄 

* **For iOS**, I think it's safe to remove the ripple effect altogether.
* **For Android**, removing the effect on `Slider` and `Stepper` makes sense.
* **For Android**, we can keep a ripple effect (_see note below on effect preference_) for other input types, such as: 
  * `text input`
  * `switch`
  * `"cycle" button` (not sure what the proper component name is... it's the one we use on `image size` on image block), sub-sheet (eg. `link to` and `image size` in Gallery), and `button` (eg. `Remove link` button on link settings sheet) 
  * I might be missing some other types but these are the ones off the top of my head.
* Assuming we keep a ripple effect on Android, I think we should instead use the standard Android "full row" ripple effect (if possible).

**Comment by jbinda** [comment]
@iamthomasbishop thanks for feedback

>Assuming we keep a ripple effect on Android, I think we should instead use the standard Android "full row" ripple effect (if possible).

You mean the light-grey effect which spreads from tap point to sides of a row (e.g in Android settings screen ?)

**Comment by iamthomasbishop** [comment]
> You mean the light-grey effect which spreads from tap point to sides of a row (e.g in Android settings screen ?)

@jbinda Exactly 😄

**Comment by jbinda** [comment]
ok I will take a look after I deal with the Column PR.

According to this:

>For Android, removing the effect on Slider and Stepper makes sense.

I assume that after I check the Voice Over a11y I can merge [this one](https://github.com/WordPress/gutenberg/pull/20922) ?
