### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#203]
We want gutenberg-mobile to be localized to the languages we support in the apps. This includes a few challenges that we need to solve:

- Where are the translations coming from? Currently from the Gutenberg plugin, after 5.0 likely from core
- Do we combine strings with the apps or keep the translations separate?
- Do we need any special configuration to have React Native pick up the right language?
- The original/translated strings doesn't seem to be in the repo. What changes to build scripts do we need to test and release localizations?

Master PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/536

**Comment by koke** [comment]
From @hypest:

Assumptions:

- stay close to GB-web
- pick strings from GB
- Minimal bridge interface, if needed at all
- Get device/site language from parent

Subtasks (all include some learning/research):

- script fetching translations from GlotPress (3d)
- Bridge interface to pass the device/site language setting (1d)
- convert .po from GlotPress to GB-usable translation data (2d)
- bootstrap GB (@wordpress/i18n packacge) with translations (5d)
- test out outputing some translating string in the UI (1d)

extra Subtask:

- make sure all current UI strings in GB-mobile pass through the translation function (2d)

Estimation: 14d of effort, closing in to **4 weeks**.

**Comment by koke** [comment]
For this one, once we have more clarity on what we need to make it work, let's do a technical doc before implementing this so we're all clear on where translations come from and how they will be updated and loaded.

**Comment by Tug** [comment]
> convert .po from GlotPress to GB-usable translation data (2d)

We don't need to, we can access JSON versions of the translations at `https://widgets.wp.com/languages/${ project }/${ locale }.json`

The data downloaded is ready to be passed down to `setLocaleData` here: https://github.com/WordPress/gutenberg/blob/master/packages/i18n/src/index.js#L45

So
> bootstrap GB (@wordpress/i18n packacge) with translations (5d)

Shouldn't be as long either

**Comment by koke** [comment]
Also GlotPress allows export to JSON (in a few different flavors), https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/fr/default
