### ISSUE TITLE
Invalid image URL after Close/Re-opening Gallery multiple times during upload of multiple images

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#2041]
**Describe the bug**
Close/Re-opening a gallery block multiple times while images are uploading will result in an invalid URL.

**To Reproduce**

Follow instructions from this test case: - Gallery [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc008)
but keep in mind that you need to close/reopen gallery block multiple times during upload.

More details can be found here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2025#issuecomment-601241846

**Expected behavior**
The image URL should be valid when the upload is finished.

**Comment by pinarol** [comment]
Resolved with associated PRs
