### ISSUE TITLE
Make “images size” label in Image block settings sheet singular

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2043]
The text label on the image size row should be “Image size” (singular), not “Images size” (plural).

Example:

![image](https://user-images.githubusercontent.com/1200432/77232864-82505280-6b71-11ea-8e39-b1d86f5451ae.jpeg)

Cc @mkevins

**Comment by enejb** [comment]
It seems that this is coming from the gutenberg repo. https://github.com/WordPress/gutenberg/blob/f6a401be500bb24c60bb6e5ccd9833fcd9fa2c5c/packages/block-library/src/gallery/edit.js#L408

Is that where the change needs to happen?

**Comment by mkevins** [comment]
Hi @enejb :wave: :smiley: 

> It seems that this is coming from the gutenberg repo. https://github.com/WordPress/gutenberg/blob/f6a401be500bb24c60bb6e5ccd9833fcd9fa2c5c/packages/block-library/src/gallery/edit.js#L408
> 
> Is that where the change needs to happen?

You are correct! In this case (for the Gallery block), the mobile implementation of the block editor is shared with the web via this `edit.js` file, so a change there will also be a change in the web version of the editor.

The `gutenberg-mobile` repository currently has the `gutenberg` repository as a git submodule, so what we typically do when we need changes in the `gutenberg` is open two PRs: one on `gutenberg` with the code changes, and one on `gutenberg-mobile` which updates the submodule reference.
