### ISSUE TITLE
Menu item changes to "Visual Mode" even though the switch to html mode failed

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#2046]
**Describe the bug**
Trying to change to HTML mode while media is uploading is not happening but, the menu item does change and displays "Visual Mode" even though the editor is still in Visual Mode.

**To Reproduce**
1. Start a new Gutenberg post and add an image block
2. Add a photo from the device so the media is uploading
3. While media is uploading, go to the 3-dots menu and hit the "HTML mode" option
4. A toast informs that the switching cannot happen while media is uploading and the editor stays in Visual Mode
5. Go to the 3-dots menu again and notice that the menu item now reads "Visual Mode", as if the current mode is HTML and the item allows you to go to Visual 💥 

**Expected behavior**
The menu item should have stayed to "HTML mode" after the switching was prohibited.

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 10
 - Version WPAndroid 14.4-rc-1, gutenberg-mobile v1.23.0

**Comment by SiobhyB** [comment]
I tested this in the last beta (`24.3`) on Android and confirmed the menu item no longer changes to "Visual Mode" when it fails. 🎉
