### ISSUE TITLE
Image is not dimmed on opening a post with uploading image

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#2049]
**Describe the bug**
Opening a post that has an image still uploading, shows the image as fully ready (undimmed and without a progress bar), only to show the dimming and progress bar a second or so later.

**To Reproduce**
1. Start a Gutenberg post, add an Image block and select an image from the device to upload
2. Go back to the post list by tapping the "Back" button, without publishing the post
3. Quickly enough, tap on the draft to open it again while the image is still uploading
4. Notice that the image appears fully ready for a small amount of time and then is dimmed and adopts a progress bar as the uploading progresses 💥

**Expected behavior**
The image should immediately have the dimming and the progress bar upon opening the post so to be no confusion about its state.

**Screenshots**
See the GIF:

![upload-no-progress-for-split-second](https://user-images.githubusercontent.com/1032913/77329539-c6d11f00-6d26-11ea-9bff-8bfc468a4c94.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 10
 - Version WPAndroid 14.4-rc-1, gutenberg-mobile v1.23.0

**Additional context**

**Comment by SiobhyB** [comment]
Going to close as I'm not able to reproduce as of 24.3. Also related: There are discussions to remove the opacity/process indicator for uploading images as part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/6603.
