### ISSUE TITLE
Can't scroll longer Post after dark mode is implemented

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#2056]
With Dark mode merged I'm seeing an issue where I can't scroll up on a longer post after opening and closing the keyboard of a paragraph block. Hard to see the screen twitch while I try and scroll in my low frame rate GIF, but that's what's happening. I'm testing now to see if this issue is isolated to the Post-Dark mode version of the release.

Steps:

1. on a longer post that allows scrolling, add a paragraph block at the bottom
2.  let the keyboard open for input on a paragraph block at the bottom of a long post
3.  then hit back to close the keyboard
4. try and scroll back up, it sort of jumps and doesn’t let you scroll up until you try multiple times. Worse in landscape mode. 

![cant-scroll](https://user-images.githubusercontent.com/1103838/77197647-cb85a100-6aa2-11ea-8e39-3b05f0e313b7.gif)

**Comment by hypest** [comment]
Fixed via https://github.com/wordpress-mobile/WordPress-Android/pull/11569 (and got merged via https://github.com/wordpress-mobile/WordPress-Android/pull/11580).
