### ISSUE TITLE
Image selection and upload

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#206]
The user should be able insert or edit an image block, and use the media picker to select and upload an image. The image block should show progress while the image is uploading and an error if it fails.

@iamthomasbishop are there existing designs for the image upload progress and error states? I imagine we'd want to keep it close to what Aztec does, but checking just in case.

**Comment by iamthomasbishop** [comment]
> are there existing designs for the image upload progress and error states? I imagine we'd want to keep it close to what Aztec does, but checking just in case.

Yes, and yes :) The picker might end up slightly different, but I think we should utilize the existing progress + error states that we have in Aztec. Here's a recent mockup of the flow – not final, but the general flow is accurate:

<img width="1453" alt="screen shot 2018-10-30 at 12 29 38 pm" src="https://user-images.githubusercontent.com/1200432/47737709-7fcd2000-dc3f-11e8-9608-b193a758935d.png">

**Comment by koke** [comment]
From @etoledom:

> The bridging part should be straightforward, and the native side is already done for Aztec. From previous tests I believe that the difficulty will be on extracting the code that handles the image selection and upload to be shared between Aztec and Gutenberg.
> Estimation: one week time, in case we encounter unexpected problems (that’s highly possible).

**1 week per platform**

**Comment by hypest** [comment]
Subtasks

Android:
- [x] Wireup the "Media library" button to select an image from the already uploaded ones ([PR](https://github.com/wordpress-mobile/WordPress-Android/pull/8553))
- [ ] Wire up the "Upload" button to the image picker
- [ ] Update image upload state in editor's UI

**Comment by marecar3** [comment]
Hey @iamthomasbishop, do you maybe have some idea about cancel media/image upload while it's in the progress?

cc: @SergioEstevao @koke

**Comment by iamthomasbishop** [comment]
We can probably re-use the interaction model from Aztec.

## In-Progress Upload

### On iOS
If you tap on an image while it's uploading, you see an **Action Sheet** with the following: 

* Title: `Media Options`
* Actions: `Stop upload` | `Dismiss`

### On Android
If you tap on an image while it's uploading, you see a **Simple Dialog** with the following:

* Title: `Stop uploading?`
* Actions: `No` | `Yes`

I think in the future we could fine-tune this messaging, but let's leave that for now.

## After Upload

Once an image is added to the canvas, tapping on the image itself should do the following:

### On iOS

Tapping image shows an **Action Sheet** with the following:

* Title: `Media Options`
* Actions: `Remove image` | `Edit` | `Dismiss`

### On Android

Tapping on the image shows individual Media Settings (**Full-Screen Dialog**), where the user can remove the image or edit it manually.

**Comment by marecar3** [comment]
Thanks @iamthomasbishop !

**Comment by marecar3** [comment]
What's missing :

- [ ] [Image upload - failed/retry state](https://github.com/wordpress-mobile/gutenberg-mobile/issues/507)
- [ ] [Image upload - cancel action](https://github.com/wordpress-mobile/gutenberg-mobile/issues/508)

**Comment by marecar3** [comment]
- [x] [Introduce media options sheet](https://github.com/wordpress-mobile/gutenberg-mobile/issues/532)
