### ISSUE TITLE
[GlobalStep] Android - Rotating the device while Previewing a Site Page’s Template causes a crash.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#2064]
### Description
While creating a new Site Page, selecting one of the available templates to enter Preview mode and then rotating the device causes the Block Editor to be displayed again and without any content which consequently causes a crash to occur when the user types anything in the Block Editor.
This issue was only seen to occur on Android.

### Reproduction Rate
4/4 100%

### Expected behavior
The Preview window should remain displayed when the device is rotated.

### Actual behavior
The application crashes.

### Steps to reproduce the behavior
1. Install WordPress 14.5
2. Log in to a valid account.
3. Press the “Add new” button.
4. Press the “Site Page” button.
5. Select any of the 5 available Templates.
6. Rotate the device.
7. Type anything in the default paragraph block.
##### Tested on the following
Samsung Galaxy Tab S2 8.0" (7.0)

#### Please see the attached video and crashlog for more information
[AndroidTemplateCrashes.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4386797/AndroidTemplateCrashes.zip)
[AndroidTemplateCrashLog.txt](https://github.com/wordpress-mobile/gutenberg-mobile/files/4386818/AndroidTemplateCrashLog.txt)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Great find! 

Tested and confirmed that rotating the device while looking at a page template _before_ applying it and then editing or rotating back will cause a crash. ([1m17s](https://cloudup.com/cD3my4GzPZ3))
<sup>Tested with WPAndroid 14.5-rc-2 on Pixel 3 Android 10.</sup>
