### ISSUE TITLE
Quote block

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#207]
Add support for the `quote` block.

What we're *not* implementing in the beta:
- Text alignment
- Inspector settings: text size and color
- Quote styles. Not specific to quotes, we might need block transformations first.

**Comment by koke** [comment]
From @daniloercoli:

> I did some research and guess we can tackle this block in a couple of days, even though it could be necessary to make some changes to AztecWrapper. 1 week from start to end to be on the safe side.

**Comment by SergioEstevao** [comment]
@iamthomasbishop here is a screenshot with the current state of quotes:

![Simulator Screen Shot - iPhone Xʀ - 2019-06-03 at 10 31 42](https://user-images.githubusercontent.com/651601/58791897-fe7da780-85ea-11e9-8a6c-c5a428084b1d.png)

**Comment by iamthomasbishop** [comment]
This is looking really close already, great work @SergioEstevao ! I apologize for not having the specs in the Zeplin project earlier – I 100% thought they were already in there! There are a couple of _tiny_ things that jump out at me:

* There should be a small space between the quote and citation – 16pt

* The citation font-size should be slightly smaller – 14pt

For visual reference: 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/1200432/58835998-1706b580-861d-11e9-99bd-371a9624fd97.png">
