### ISSUE TITLE
[GlobalStep] Android - Softlock when changing to classic editor and attempting to preview without adding more text.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#2072]
### Description
When the user has the 'Use Block Editor' toggled on, adding a new blog post or site page will soft lock the app with a 'Saving...' screen, if the user types everything on either Block Editor or HTML Mode, swaps to classic editor, and attempts to Preview the blog/page.

### Reproduction Rate
4/4 100%

### Expected behaviour
The app should take the user to a preview of the currently edited blog/page.

### Actual behavior
The app stays in an infinite 'Saving...' cycle with no way for the user to exit.

### Steps to reproduce the behavior
1. Install and Launch WordPress 14.5
2. Log in with a valid email address.
3. Tap 'Continue'.
4. Ensure 'Use Block Editor' is toggled on, on Settings.
5. Tap on the pink button to create a new blog/page.
6. Tap on either 'Blog Post' or 'Site Page'.
7. On the edit mode, either create the blog/page on Block Editor or HTML Mode.
8. Tap the meatballs and tap on 'Switch to classic editor'.
9. Tap the meatballs and tap 'Preview'.

##### Tested on the following
Samsung Galaxy S7 (6.0.1)
Huawei P30 Pro (9.0)
Google Pixel C (8.1)

#### Please see the attached video for more information
[Android softlock.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4393604/Android.softlock.zip)

### Submitted by:
Ricardo Silva

**Comment by hypest** [comment]
Just an update, had a look and have detected a possible source of the bug: when switching to the classic editor, the new post erroneously stops being reported as "has changes" and is not saved remotely. Will try to fix this.
