### ISSUE TITLE
[Latest-Posts] Disable Categories on Latest-Posts until Multi-Select Support

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2073]
**Describe the bug**
WordPress 5.4 adds support for Multi-Select on Categories in the Latest-Posts Block. We'd like to wrap this setting behind a development flag until we too can add support for multi-select.

**To Reproduce**
1. Go to a site running WordPress 5.4 or later
2. Navigate to a page with the Latest-Posts Block and categories set
3. Click on the Settings
4. See Categories appear as "NaN"

**Screenshots**
<img width="300" alt="Screen Shot 2020-03-27 at 10 04 44 AM" src="https://user-images.githubusercontent.com/3384451/77764086-71d92580-7012-11ea-9aca-6fe8a9412c14.png">

**Additional context**
Support for Multi-Select is being tracked in https://github.com/wordpress-mobile/gutenberg-mobile/issues/2069

**Comment by SergioEstevao** [comment]
@chipsnyder  I'm moving this to 1.26, feel free to move it back to 1.25 if this is something that can be considered a regression.

**Comment by chipsnyder** [comment]
Thanks for catching this @SergioEstevao The PRs already merged but it looks like the ticket didn’t auto close. I’ll flip it back and close this issue
