### ISSUE TITLE
[GlobalStep] Scrolling in certain Block’s settings screen is inconsistent.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#2075]
### Description
While using the Block Editor, certain Blocks like “Latest Posts” or “Button” feature a settings menu. This menu feature scrolling which only happens when the user holds the finger down on one of the buttons. If the user presses a text area then the window is dragged instead of pagination occurring which leads to difficult scrolling functionality.
This was only seen to occur on phone devices as the whole Settings menu of these blocks is displayed on Tablets.

### Reproduction Rate
4/4 100%

### Expected behaviour
The Menu should always scroll when dragged regardless of where the user taps to hold.

### Actual behaviour
The Window is dragged out of the screen.

### Steps to reproduce the behaviour
1. Install WordPress 14.5
2. Login to a valid account.
3. Create a new Blog Post.
4. Add a new “Latest Posts” block.
5. Tap the block’s Cogwheel button.
6. Scroll to the bottom of the menu.
7. Tap and hold “Sorting and filtering” and swipe down to scroll back up to the top of the menu.
##### Tested on the following
iPhone 5S (12.0)
iPhone SE (13.1.3)
Huawei P30 Pro (9.0)

#### Please see the attached video for more information
[ScrollingBlockSettings.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4394192/ScrollingBlockSettings.zip)

### Submitted by:
Luis Pimenta

**Comment by SiobhyB** [comment]
I haven't been able to reproduce issues scrolling in the block settings, but feel welcome to reopen if I'm missing something here.
