### ISSUE TITLE
Cannot dismiss keyboard while editing in landscape mode on Android

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2089]
**Describe the bug**

Tapping "Done" while editing a paragraph block in landscape mode creates a new paragraph block and immediately opens edit mode again without showing the new content or dismissing the keyboard—if you leave the post and re-open it, the page looks blank even if you had added content previously. ([1m17s](https://cloudup.com/ct5z4hqpLrw))

**To Reproduce**

1. Go to My Sites > Pages > +.
1. Rotate the device to landscape mode.
1. Tap the "Start writing…" prompt (the default first block).
1. Tap the "Done" button.
1. Tap the "Done" button a few more times. 
1. Try adding some text.
1. Tap the "Done" button.
1. Rotate the device back to portrait mode.
1. Tap the back button to leave the page.
1. Notice that the page was saved as a draft.
1. Re-open the post and notice that the content area is blank.
1. Close and re-open the post again and notice that the content area is no longer blank.

**Expected behavior**

I expect to be able to edit page content in landscape mode and tap "Done" to return to the post normally and that re-opening a new page after editing will show the same content that it did previously.

**Screenshots**

<img src="https://user-images.githubusercontent.com/1119271/78086161-53f52300-737a-11ea-8c05-ad0dff8d1373.png" width="540" alt="Screenshot_20200331-180514">
<sup>Tested with WPAndroid 14.5-rc-2 on Pixel 3 Android 10.</sup>

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Version: WPAndroid 14.5-rc-2

**Comment by maxme** [comment]
> I expect to be able to edit page content in landscape mode and tap "Done" to return to the post normally. 

I'm not sure about that, should we only return to "view" mode only when the user hides the keyboard? This fullscreen view is not the best experience IMO, I thought we wanted to change that but I can't find any related ticket. cc @iamthomasbishop 

I wasn't able to reproduce the blank page situation. I wonder if this is an unrelated problem (thi might be a sync issue).

**Comment by maxme** [comment]
>This fullscreen view is not the best experience IMO, I thought we wanted to change that but I can't find any related ticket. 

This was actually implemented:
https://github.com/wordpress-mobile/gutenberg-mobile/pull/1842

and reverted:
https://github.com/wordpress-mobile/gutenberg-mobile/pull/1989

**Comment by designsimply** [comment]
Thanks for having a look! I've now found that the empty page issue is separate and was filed at https://github.com/wordpress-mobile/WordPress-Android/issues/11339 and partially fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11568 (props @jd-alexander 🎉) with one remaining issue being tracked at https://github.com/wordpress-mobile/WordPress-Android/issues/11539. 👍

So the next step for this issue is to get design input/feedback on the fullscreen view.

**Comment by hypest** [comment]
In the meantime while this ticket gets more reviewing, adding it to the `[Flow: Improvements]` project to keep it in the radar.

**Comment by SiobhyB** [comment]
In testing the latest version (24.3 beta), I can confirm that content is no longer lost when following the reproduction steps. As the flows and UI described here have changed a lot since this issue was created, I'll go ahead to close, but feel welcome to reopen if anything remains relevant.
