### ISSUE TITLE
Assess if react-native-gutenberg-bridge Jest mock is still needed

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#210]
We added a Jest mock for react-native-gutenberg-bridge [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/201/commits/6df5e28113cfff00c36cd598c333ad9e7dde1e95#diff-606adbd6a8c97d177b17baee5a69cdd9R1) to make the iOS tests pass for the wpandroid [integration effort](https://github.com/wordpress-mobile/gutenberg-mobile/pull/201/).

This ticket is opened as a reminder to make sure if the mock is still needed after we implement the proper iOS side of `react-native-gutenberg-bridge`.

**Comment by koke** [comment]
Is this needed for the alpha?

**Comment by hypest** [comment]
Yes, apparently testing without the mocks is failing. I think we need the mocks to mock out Native Modules.

I will mark this ticket as wontfix and close it.
