### ISSUE TITLE
[Latest Posts Block] Cannot scroll to see all categories in the latest posts block Category selector

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2100]
**Describe the bug**

Cannot scroll to select categories offscreen in the "Category" selector in the Latest Post block bottom sheet settings. ([1m43s](https://cloudup.com/cazZ9rIqmtx))

**To Reproduce**

1. Go to My Site > Blog Posts > +.
1. Add a title.
1. Go to More > Post Settings > Categories.
1. Use the + button at top right to add enough categories so you have to scroll to see all of them.
1. Go back to the editor.
1. Add a Latest Posts block.
1. Tap the Category selector.
1. Try to select any category initially offscreen in the bottom sheet.

**Note:** on my iPhone 6s I had to add 8+ categories and on my iPhone 11 I had to add 11+ before there were enough categories on the device to need to scroll—so adding 15 or 20 categories for testing would be a good amount.

**Expected behavior**

I expected to be able to select any category from my blog in the Latest Posts block settings.

**Screenshots**

<img src="https://user-images.githubusercontent.com/1119271/78280490-6c7a5000-74d6-11ea-85f5-3771a6de05e2.PNG" width="200" alt="IMG_3705">
<sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 11 iOS 13.4.</sup>

**Smartphone**
 - Device: iPhone 11
 - OS: iOS 13.4
 - Version: WPiOS 14.5.0.1 TestFlight beta

**Comment by chipsnyder** [comment]
Closing this and adding a note to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2069 to handle this case

**Comment by chipsnyder** [comment]
Forgot to mention that the category selector has been disabled so this issue will be hidden from users as we work to readdress it
