### ISSUE TITLE
[Latest Posts Block] Category setting is set back to the default when the post is re-opened in the editor

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2101]
**Describe the bug**

The category setting in the Latest Posts block is reset when you re-open the post for editing. ([1min](https://cloudup.com/cfJpCUm4j5P))

**To Reproduce**

1. Go to My Site > Blog Posts > +.
1. Add a title.
1. Add a Latest Posts block.
1. Tap the Category selector and choose a non-empty category.
1. Save the post as a draft.
1. Close and re-open the post in the block editor.
1. Go back to the Latest Posts block setting and check to see if the Category is still the one that was previously saved in the last session.

**Note:** the problem only seems to happen when any post (published or draft) is re-opened in the block editor—if you create a post with a Latest Posts block and publish it without ever editing it again then the category setting is respected.

**Expected behavior**

I expected that any block settings I change and save in a draft will stay correctly when I re-open the post for editing at a later time.

**Screenshots**

<img src="https://user-images.githubusercontent.com/1119271/78283040-73a35d00-74da-11ea-94de-99c68ebd5b62.PNG" width="200" alt="IMG_3710">
<sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 11 iOS 13.4.</sup>

**Smartphone**
 - Device: iPhone 11
 - OS: iOS 13.4
 - Version: WPiOS 14.5.0.1 TestFlight beta

**Comment by chipsnyder** [comment]
Closing this for now and adding it to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2069 to handle the tracking and retesting of this flow after the re-implementation

**Comment by pinarol** [comment]
Let's also mention, we have hidden this option as of 14.6. We'll reimplement this option in a way that allows multi selection.

**Comment by chipsnyder** [comment]
Thanks @pinarol, I forgot to mention that.
