### ISSUE TITLE
When scrolling a bottomsheet that contains sliders it's very easy to change settings unintentionally

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2102]
**Describe the bug**

Scrolling through settings should not change any settings values. ([1m59s](https://cloudup.com/cdusCWfy-9y))

**To Reproduce**

1. Go to My Site > Blog Posts > +.
1. Add a title.
1. Add a Latest Posts block.
1. Tap the gear icon or "CUSTOMIZE" link.
1. Scroll back and forth through the settings several times and notice how when your finger lands on a slider when trying to scroll that those values get changed inadvertently.

**Expected behavior**

I expected to be able to scroll through any block settings without unintentionally changing any settings values.

**Screenshots**

<img src="https://user-images.githubusercontent.com/1119271/78282019-db58a880-74d8-11ea-8a70-3b5b9508a0e2.PNG" width="200" alt="IMG_3709">
<sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 11 iOS 13.4.</sup>

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.4
 - Version: WPiOS 14.5.0.1 TestFlight beta

**Comment by pinarol** [comment]
Let's check this one again after [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1884) is done. The order of which gesture to handle isn't something we directly control with React Native, but that issue will change the foundations of BottomSheet so it may have a chance to fix this as well.

**Comment by lukewalczak** [comment]
We've already gathered some conclusion why it doesn't work properly, discussed and planned how to fix it. The plan is to:
1. create our custom extended ScrollView component with overwritten value `delaysContentOnTouches=YES`
2. create a PR to rn-slider to disable `[touchToSeekFeature](https://github.com/react-native-community/react-native-slider/pull/117)` for iOS
3. test slider and app parts where ScrollView is used
4. Propose a PR to RN
