### ISSUE TITLE
Cover block background when there's a video is totally black

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#2104]
**Describe the bug**
The background is black on the Cover block when it's waiting for the video to show under Dark Mode, making it look like there's an issue. It should probably be grey, like on Light Mode.

**To Reproduce**
1. Start a Gutenberg post and add a Cover block
2. Add a video to the cover block
3. While waiting for the video to show, notice that the background is totally black

See a gif of the issue:
![cover-video-dark-mode-too-black](https://user-images.githubusercontent.com/1032913/78357976-17fcd080-75bb-11ea-95f8-73d0a0535274.gif)

**Expected behavior**
I'd expect the background to be grey or something to denote the placeholder position.

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 10
 - Version 1.25 + Dark mode support (currently WIP)

**Comment by pinarol** [comment]
Dark mode was considered during implementing Cover. This particular case was either missed or it was caused by the player.
