### ISSUE TITLE
Slider component only allows adjusting in increments of 10 via drag gesture

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2117]
**Describe the bug**
Slider component only allows adjusting in increments of 10 via drag gesture.

**To Reproduce**
1. Add a Spacer block
2. Open block settings by tapping on the cog/gear icon
3. Try dragging to adjust the height of the block
4. Notice that you can only adjust in increments of 10

**Expected behavior**
I expect to adjust by increments of 1.

**Screenshots**
![RPReplay_Final1586206890-min 2020-04-06 16_03_41](https://user-images.githubusercontent.com/1200432/78604932-40393900-7820-11ea-9eb9-9e0444ace083.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.3.1
 - Version: Tested via build 26428 via [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/13690#issuecomment-601687941) (cc @lukewalczak), but I'm also seeing this issue on the latest primary internal beta. **Not seeing this on production, so it must have been a recent change.**

**Comment by pinarol** [comment]
@lukewalczak Could you check what’s going on here? Let’s try to fix this one as soon as possible.

**Comment by lukewalczak** [comment]
It looks like it's the effect/result of [PR](https://github.com/WordPress/gutenberg/pull/20746/files) related to sharing `edit` method with web, where `step` was unified and set to `10` _probably_ to match the web behaviour. 
If there is no reason to keep that I will suggest using `Platform` API and set the correct step value according to platform e.g:

```
import { Platform } from '@wordpress/element';

...
<RangeControl
	...
	step={ Platform.OS === 'web' ? 10 : 1 }
/>
```

**Comment by iamthomasbishop** [comment]
Ah, okay, thanks for investigating @lukewalczak! Maybe I'm missing some rationale that the web folks have for single increments to be 10px vs. 1px, but it feels really odd to me (even on the web, but esp in the context of a slider on mobile). Are we able to override that to apply increments of `1`?

**Comment by lukewalczak** [comment]
I didn't take part in refactoring `Spacer` block, so it looks incorrectly for me as well! 

> Are we able to override that to apply increments of 1?

Sure, my suggestion above is fixing that in this way _(mobile_: step = 1, _web_: step = 10). Let's wait for @pinarol opinion on that ✌️

**Comment by iamthomasbishop** [comment]
> Sure, my suggestion above is fixing that in this way (mobile: step = 1, web: step = 10),however let's wait for @pinarol opinion on that ✌️

Sounds good! To be fair, it is a nice thing to have the _ability_ to set step values (particularly something that has a smaller range but a Stepper isn't desirable — like image sizes or something along those lines), but the default unit, imo, should be 1.

FYI @SergioEstevao (who worked on the Spacer refactoring recently, although I don't think he changed anything w/ this step value 😄)

**Comment by lukewalczak** [comment]
> Sounds good! To be fair, it is a nice thing to have the ability to set step values (particularly something that has a smaller range but a Stepper isn't desirable — like image sizes or something along those lines), but the default unit, imo, should be 1.

Agree on that!

**Comment by pinarol** [comment]
> Sure, my suggestion above is fixing that in this way (mobile: step = 1, web: step = 10),however let's wait for @pinarol opinion on that ✌️

Sounds good to me considering that @iamthomasbishop is giving the 👍

**Comment by SergioEstevao** [comment]
I defer to you @iamthomasbishop but I don't think it makes sense increments of 1, do you think our users will increment/want spacers with  1px difference? 

Can we check with the web folks what is the rationale there? Or you already checked with them?

**Comment by SergioEstevao** [comment]
I talked a bit with @pinarol and @lukewalczak and I changed my mind because of two things:

 - On the web there is the option to directly manipulate the spacer size, 
 - and also write a custom value, so we can have values that are different from multiples of 10
 
So I agree that we should have steps of 1 on mobile.

**Comment by iamthomasbishop** [comment]
> I talked a bit with @pinarol and @lukewalczak and I changed my mind because of two things:

👍 Sounds good. It'd still make sense to touch base w/ the web folks to see what their rationale may have been.
