### ISSUE TITLE
Refine spacing on cells that contain Slider controls

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2126]
Cells that contain the Slider control feel a bit too spacious in most cases — particularly on block settings bottom sheets. For example:

## Current

| iOS  | Android |
| ------------- | ------------- |
| <a href="https://user-images.githubusercontent.com/1200432/78714560-b94c9500-78e1-11ea-9595-1ec4b6746373.png"><img src="https://user-images.githubusercontent.com/1200432/78714560-b94c9500-78e1-11ea-9595-1ec4b6746373.png" width="410"></a> | <a href="https://user-images.githubusercontent.com/1200432/78714600-c9647480-78e1-11ea-9772-37fa4ddfd07f.png"><img src="https://user-images.githubusercontent.com/1200432/78714600-c9647480-78e1-11ea-9772-37fa4ddfd07f.png" width="386"></a> |

Note: Android appears to have even _more_ spacing than iOS (about ~10px more), so we could also tighten that spacing up to the same values as iOS unless we want to provide more spacing on Android. **Edit: I just realized this 10px disparity might be because of the drag handle size difference between platforms.**

## Proposal

While it was designed this way in an effort to align with some of the native patterns, over time it has become clear that spacing feels a bit too much in practice, esp on Android. What I'm proposing is to essentially remove about ~14px of spacing between cell title and slider on iOS and ~24px on Android, like this:

| iOS  | Android |
| ------------- | ------------- |
| <a href="https://user-images.githubusercontent.com/1200432/78714684-e731d980-78e1-11ea-995a-44edb81d2e17.png"><img src="https://user-images.githubusercontent.com/1200432/78714684-e731d980-78e1-11ea-995a-44edb81d2e17.png" width="410"></a>  | <a href="https://user-images.githubusercontent.com/1200432/78714723-f9ac1300-78e1-11ea-99ab-4a6366462e58.png"><img src="https://user-images.githubusercontent.com/1200432/78714723-f9ac1300-78e1-11ea-99ab-4a6366462e58.png" width="386"></a> |

## Before/After

| iOS | Android |
| ------------- | ------------- |
| <a href="https://user-images.githubusercontent.com/1200432/78715212-b0a88e80-78e2-11ea-9557-5d25c0c69abf.png"><img src="https://user-images.githubusercontent.com/1200432/78715212-b0a88e80-78e2-11ea-9557-5d25c0c69abf.png" width="1346"></a> | <a href="https://user-images.githubusercontent.com/1200432/78715294-d3d33e00-78e2-11ea-9d81-0c0935cf496c.png"><img src="https://user-images.githubusercontent.com/1200432/78715294-d3d33e00-78e2-11ea-9d81-0c0935cf496c.png" width="1307"></a> |

cc'ing for feedback: @SylvesterWilmott @mattmiklic  — do you think this feels _too_ condensed? Should we worry about matching the native component _exactly_ or is it okay to refine these based on how they've felt in context?

**Comment by mattmiklic** [comment]
Doesn't feel too condensed to me; I couldn't find any specific guidance in the Material Design spec for spacing around the slider, only the size of the thumb and track. 22pt makes sense on iOS as it's 1/2 the size of the tap target (44pt on iOS) for the thumb. On Android I might increase that to 24dp so it aligns to the 8dp grid and is 1/2 the size of the tap target (48dp on Android) for the thumb.

**Comment by iamthomasbishop** [comment]
> Doesn't feel too condensed to me

Okay cool, glad to hear 😄 

> I couldn't find any specific guidance in the Material Design spec for spacing around the slider

Yea, I think I ended up literally designing over a screenshot for Android for the initial version of the component. The track and thumb should be 1:1 w/ the guidelines.

> 22pt makes sense on iOS as it's 1/2 the size of the tap target (44pt on iOS) for the thumb

To be clear, I'm not 100% sure if these are 100% accurate values, but they are based on screenshots from the app/editor as it exists today. That said, I think most of our row content styling matches sizings between platforms, so in other words, row height is 48 on both platforms.

> On Android I might increase that to 24dp so it aligns to the 8dp grid and is 1/2 the size of the tap target (48dp on Android) for the thumb.

I'm not 100% sure if that would make it align to the grid per se, because I'm not positive of what the height of the slider component's "container" itself is (it _looks like_ 28px which is the height of the iOS slider thumb, but I'm not 100% sure where the paddings/margin lay.

**Comment by SylvesterWilmott** [comment]
Looks good to me too. Personally I would use 24dp on Android both for the reason @mattmiklic said. If you imagine that the slider sits within a 48dp invisible bar then 24dp puts the label just above that bar.

**Comment by SylvesterWilmott** [comment]
Looks good to me too. I would place the slider itself within an invisible 44pt bar on iOS and 48dp bar on Android and align the label to the top of that bar. But doing that gives you close enough values to 22pt/dp on both platforms so it doesn't really matter so much anyway.

**Comment by antonis** [comment]
This is Reopened with https://github.com/WordPress/gutenberg/pull/24109
due to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2501
