### ISSUE TITLE
Breakages, regressions, and new issues in RTL layout

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#2133]
**Describe the bug**
There have been many new issues in RTL layout.
Related old issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1461

## Placeholders are gone

This one might be iOS only.

![placeholders](https://user-images.githubusercontent.com/9772967/78786100-7f929180-79a8-11ea-81fd-0c5b98a9aed7.png)

- All RichText placeholders seem to be missing.

## Toolbar buttons and List Block

![buttons-lists](https://user-images.githubusercontent.com/9772967/78787032-fd0ad180-79a9-11ea-9292-160bc25366ef.png)

- Default text alignment icon is inconsistent with default RTL language alignment
- Undo and Redo should have flipped position.
  - It's still correct to have Undo pointing to the left, and Redo to the right, since it's a representation of time.
- List block has the bullets in the opposite side.
- List block icons need to be flipped (we might need a new ordered list icon if it doesn't exist) cc @iamthomasbishop 
  - Keeping "ident" at the left and "unindent" at the right.

## Galery block and Inner blocks

![gallery-inner](https://user-images.githubusercontent.com/9772967/78788064-9090d200-79ab-11ea-8da2-6fb93031997b.png)

- Gallery: Image mover icons are reversed.
- Inner block floating toolbar: Arrows icons need to be flipped.

**To Reproduce**

- On iOS, the best way is to change the device to a RTL language to have the full experience.
- Alternatively you can set `forceRTL` to true.
  - After doing this, you will need to load Gutenberg two times. (Once to set the setting in native side, other for the changes to take place).
 https://github.com/wordpress-mobile/gutenberg-mobile/blob/3b62fb99a3a5ea063a9ebe687f8e2cd4847c7778/src/index.js#L36 
- One more option in Xcode is to set `Right to left Pseudo-language` in language settings in: Product > Scheme > Edit Scheme > Run > Options > Application Language.

**Comment by iamthomasbishop** [comment]
Thank you for surfacing these issues, @etoledom!

> Placeholders are gone

😱 

> Toolbar buttons and List Block

Agreed w/ all of this.

> List block icons need to be flipped

We'll need a new G2 icon for this, I will ping the designers on web.

> Gallery: Image mover icons are reversed.

@mkevins would you mind taking care of this one?

> Inner block floating toolbar: Arrows icons need to be flipped.

@jbinda would you mind taking a look at this, as you're currently working on the floating toolbar? If you're not able to, maybe @chipsnyder could take a look?

**Comment by jbinda** [comment]
@iamthomasbishop 

No problem I will add RTL support to FloatingToolbar in my PR [here](https://github.com/WordPress/gutenberg/pull/21446)


>**List block icons need to be flipped**
We'll need a new G2 icon for this, I will ping the designers on web.
**Gallery: Image mover icons are reversed.**
@mkevins would you mind taking care of this one?

I have just add a function to ColumnBlock PR which handle rotate the Block movers. I believe that we can also use to flip/switch icons between mentioned buttons in Gallery and List block (undo/redo)

[Here](https://github.com/WordPress/gutenberg/pull/19013#discussion_r405487628) is link to my comment about switch. You can check the whole movers file to get the point in wider scope

**Comment by jbinda** [comment]
I have implement RTL support for FloatingToolbar:

<img width="250" src="https://user-images.githubusercontent.com/21242757/78877062-8ffe4700-7a50-11ea-8583-21e75a58d34f.png"><img width="265" src="https://user-images.githubusercontent.com/21242757/78877053-8d035680-7a50-11ea-90d7-1bad262d5773.png">

The changes will be introduce with [this PR](https://github.com/WordPress/gutenberg/pull/21446).

One note here. Does the `Save` text in right top corned should be reversed in RTL ?

I will also handle rest of breakages in separate PR

**Comment by jbinda** [comment]
I have also add support in Gallery Block and undo/redo button. See below screenshots and [PR here](https://github.com/WordPress/gutenberg/pull/21502)

**LTR vs RTL mode**
<img width="250" src="https://user-images.githubusercontent.com/21242757/78885730-6566bb00-7a5d-11ea-8e4c-8632cd56eb98.png"><img width="250" src="https://user-images.githubusercontent.com/21242757/78885737-6697e800-7a5d-11ea-8054-a9978fa49958.png">

**Comment by iamthomasbishop** [comment]
@jbinda looks solid, thank you for fixing that part of this 😄

**Comment by jbinda** [comment]
@iamthomasbishop 

No problem, there's still some work to do according to my PR TODOs list.

@pinarol 
I think maybe it's worth to add `RTL mode` section to our sanity-testing as well after we fix mentioned issue here ?  wdyt ?

**Comment by pinarol** [comment]
No harm documenting RTL test cases for sure but Sanity testing is done to make sure the basic & most commonly used functionality is not broken. RTL tests would be a bit too much to run bi-weekly imo. @jbinda

**Comment by jbinda** [comment]
I  just thought that having this in sanity-test will also point all other places to check if you doing something with RTL. We can also schedule wider timeframe for RTL in [sanity-testing schedule](https://mobilegutenpagesp2.wordpress.com/sanity-testing-rotations/) (e.g. once per month)

I try to keep sanity-test up to date because it helps me to catch edge case that I might broke in other block during work on some common/shared feature. RTL is one of that kind of feature

Please let me know if something changes.

**Comment by jbinda** [comment]
According to `List` block, shouldn't we also rotate the icon for List block in BottomSheet menu in RTL mode ? See screenshot

<img width="300" src="https://user-images.githubusercontent.com/21242757/79215735-5496ba80-7e4c-11ea-9b25-3c1ae6e6b6ce.png">

**Comment by etoledom** [comment]
> According to `List` block, shouldn't we also rotate the icon for List block in BottomSheet menu in RTL mode ? See screenshot

Good point! I think we should 👍

**Comment by jbinda** [comment]
I think I will also check other blocks because I have found issue also in MediaText align in horizontal layout. Icons should be reversed as well because it has rotated orientation according to what layout you see

<img src="https://user-images.githubusercontent.com/21242757/79224951-418be680-7e5c-11ea-938a-03d2be201b7a.png" width="500">

Anyway I will be update the PR code soon. Stay tuned :)

**Comment by etoledom** [comment]
> Anyway I will be update the PR code soon. Stay tuned :)

Amazing 😁
Good catch!

> I also think that in vertical layout it should be rotate by 90 degrees. 

Rotating vertically will make the horizontal lines vertical too, right? We might need a new icon.
But maybe it's not necessary since the layout on the final website will still be horizontal. The vertical layout on small screen sizes is more like a special case.

**Comment by jbinda** [comment]
>Rotating vertically will make the horizontal lines vertical too, right? We might need a new icon.

I think so

>But maybe it's not necessary since the layout on the final website will still be horizontal. The vertical layout on small screen sizes is more like a special case.

I think it is kind of UX fix just to be consistent (another example might be the block movers in Columns/Buttons)

Can you take a look once again on PR code ? I dropped some comments

**Comment by iamthomasbishop** [comment]
> According to List block, shouldn't we also rotate the icon for List block in BottomSheet menu in RTL mode ? See screenshot

@jbinda I think that would be good.

> I have found issue also in MediaText align in horizontal layout. Icons should be reversed as well because it has rotated orientation according to what layout you see

Good catch. Let's rotate these as well.

> I also think that in vertical layout it should be rotate by 90 degrees

I don't think rotating 90% will be a good solution here, we'll need a new icon. Until then let's just use the same mirrored icons as mentioned above. In the long run, this would probably be good, but for now we can just mirror.
