### ISSUE TITLE
[GlobalStep] Android – The Download button of a Video Block does not function.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#2134]
### Description
When viewing a Post consisting of a Video Block, a Kebab Menu featuring a “Download” button is displayed. This “Download” button does not function.

### Reproduction Rate
4/4 100%

### Expected behaviour
The Download button should function as intended.

### Actual behaviour
The Download button has no functionality.

### Steps to reproduce the behaviour
1. Install WordPress 14.6
2. Login to a valid account.
3. Create a New Post.
4. Add a Video Block.
5. Insert a Video.
6. Publish the Post.
7. View the Post.
8. Click the Kebab menu.
9. Click the Download button.
##### Tested on the following
Samsung Galaxy S8+ (8.0)

#### Please see the attached video for more information
[AndroidVideoDownload.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4450828/AndroidVideoDownload.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Thanks for reporting this!

Moved to https://github.com/wordpress-mobile/WordPress-Android/issues/11627 in WordPress-Android since this is a Webview and not technically part of the editor.
