### ISSUE TITLE
[GlobalStep] Android – The last word on Media Blocks is seen to be missing.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#2136]
### Description
When adding a Media Block, the messages “Add Image”, “Add Video” or “Add Image or Video” can be read. However, it was observed that on certain devices this message was trimmed and missing the last word of the sentence.
This issue was also tested on Samsung Galaxy S8+ (8.0) but not seen to occur.

### Reproduction Rate
4/4 100%

### Expected behaviour
The whole message should be displayed without issues.

### Actual behaviour
The message of Media Blocks was seen constantly missing its last word.

### Steps to reproduce the behaviour
1. Install WordPress 14.6
2. Login to a valid account.
3. Create a new Post.
4. Add any Media Block.
##### Tested on the following
One Plus 6 (9.0)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/78795287-bf5b7800-79ac-11ea-855d-677c6a02ed9e.jpg" />

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Thank you for including a screenshot!

I didn't expect to see the problem but I did a quick check from my Pixel 3 Android 10 device and the media block links such as "Add image or video" and "Add video" looked okay to me ([screenshot](https://user-images.githubusercontent.com/1119271/78867601-95cb3c80-79fe-11ea-9b6a-96b2bcbca5e8.png)). It's worth looking into on some other devices though.

**Comment by hypest** [comment]
Looks like this is a known issue with React Native on OnePlus (and other) devices. See [this ticket](https://github.com/facebook/react-native/issues/15114) and [this one](https://github.com/facebook/react-native/issues/15114). I'm not particular fond of any of the workarounds I saw on those tickets and would prefer if a real fix is left with the framework (React Native) on this one.

@designsimply , I'd suggest we put a lower priority on this one, but in the meantime, I can try to allow more space for the text to render in an attempt to work around the problem in the Image/Media placeholders. Not that won't fix any potential manifestations of the same problem in other blocks or view. Sounds OK?

**Comment by cameronvoell** [comment]
A fix for this was merged to gb-mobile here. https://github.com/wordpress-mobile/gutenberg-mobile/pull/2151

It did not make the editor release window this week, so we'll have to keep an eye on whether this issue persists when gb-mobile editor release v1.29.0 makes it to the WPAndroid / play store. I'll leave this ticket open for now unless we think it's better to close and reopen if we get another report about this about a month from now.
