### ISSUE TITLE
[GlobalStep] iOS - ‘No media matching your search’ message is outside of view by default.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#2143]
### Description
It is possible for a ‘No media matching your search’ message to display when attempting to add media using the block editor such as an image or video to a post. However, by default this message is hidden out of sight, above the search bar, off-screen. To replicate this issue, it may be necessary to have no saved WordPress media tied to the account used, as this appears in place of the message if present.

### Expected behavior
The message is onscreen and visible by default.

### Actual behavior
The message is off-screen and can’t be seen without scrolling.

### Steps to reproduce the behavior
1.	Install WordPress 14.6
2.	Register or login to an account.
3.	Ensure from settings menu there is no media attached to the account.
4.	Select to create a new post.
5.	Select Video.
6.	Select WordPress Media Library.
7.	Type anything into the search bar.
8. 	Delete the searched text.
9. 	Swipe down to reveal the hidden text.

##### Tested on the following:
iPhone X (12.3.1)
iPhone 6S Plus (13.4.1)

#### Please see the attached video for reference.
[nomedia_offscreen_ios.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4455943/nomedia_offscreen_ios.zip)

#### Submitted by:
Oliver Howe

**Comment by hypest** [comment]
This issue might actually not be related to the editor, but rather to the WP Media library picker itself. Does the issue happen if you try searching directly in the "Media" section from the "My Site" top level screen (for that same media-less account) @wptester9845? cc @designsimply .

**Comment by mchowning** [comment]
> Does the issue happen if you try searching directly in the "Media" section from the "My Site" top level screen (for that same media-less account)

I'm only seeing this behavior when selecting media from the library through Gutenberg. Neither opening the media library from "My Site" or from the Aztec Editor show this behavior, so it makes sense to have this issue in the gutenberg-mobile repository.

**Comment by SiobhyB** [comment]
I'm no longer able to reproduce in 24.3. As we haven't had reports in four years, going ahead to assume this was fixed somewhere along the line.
