### ISSUE TITLE
Formating buttons aren’t updated accordingly when text is deleted

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2154]
**To Reproduce**

1. Add a paragraph block
2. Add normal, bold, italic text sequentially
3. Tap backspace button to remove the text

Result:
The active state of format buttons don't change

4. Try adding new text

Result:
The new text added doesn't match the active format Buttons

**Expected behavior**

1. Add a paragraph block
2. Add normal, bold, italic text sequentially
3. Tap backspace button to remove the text

Expected:
The active state of format buttons should change according to the caret position

**Screenshots**
Download to see the screencapture:
[format-buttons.mov.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4474746/format-buttons.mov.zip)

**Smartphone (please complete the following information):**
 - Device: [iPhone XS]
 - OS: [iOS 13.3]
 - Mobile Gutenberg Editor Release 1.26, 1.25, 1.24

**Comment by dcalhoun** [comment]
For additional context, here is a video of what I believe to be the same issue.

https://user-images.githubusercontent.com/438664/108368917-9ad14e80-71c0-11eb-8401-1472e28a1fe4.MP4

**Comment by jostnes** [comment]
Was able to reproduce this during exploratory testing of WordPress iOS v18.0, found that after a typo and backspace to fix typo the formatting is no longer respected:

https://user-images.githubusercontent.com/17252150/129043653-50c249af-4ac7-4b09-b4d2-918862389220.MP4

**Comment by fluiddot** [comment]
Closing this issue as it was already solved in https://github.com/WordPress/gutenberg/pull/37676 and released in version `19.0`.
