### ISSUE TITLE
Bug: Autoscroll on text based block does not work when nested inside InnerBlock (e.g. Group)

### ISSUE THREAD

**Issue by jbinda** [wordpress-mobile/gutenberg-mobile#2157]
**Describe the bug**
Autoscroll does not scroll to current caret position when text based blocks (e.g paragraph, heading) is inside InnerBlock (e.g. Group block) . See below step to reproduce and GIFs for more details.

**Unexpected behaviour:**

Steps to reproduce the behaviour:
1. Add Group block
2. Add Paragraph Block inside Group block
3. Start adding new lines
4. When you reach bottom of the screen noticed that the UI won't scroll to current caret position

<img src="https://user-images.githubusercontent.com/21242757/79349201-445b0a00-7f36-11ea-9461-4cb5e8db250e.gif" width="300"/>

**Expected behaviour:**

For InnerBlock it should work as for RootList level. See by reproduce below steps:

Steps to reproduce the behaviour:
1. Add Paragraph Block at RootList level
2. Start adding new lines
3. When you reach bottom of the screen and put new line noticed that the UI will scroll to current caret position

<img src="https://user-images.githubusercontent.com/21242757/79349925-1e823500-7f37-11ea-88a2-d5fe4818dfee.gif" width="300" />

**Comment by pinarol** [comment]
Worth checking if the `onCaretVerticalPositionChange` event can be propagated into inner blocks.
