### ISSUE TITLE
Bottom sheet won't scroll tapping on PanelBody Title

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#2160]
**Describe the bug**

Starting the scroll interaction tapping on a PanelBody title, the bottom sheet will start the bidding animation instead of scrolling its content. This is particularly easy to reproduce in the `Latests Post` block settings.

![Screenshot 2020-04-16 at 13 46 00](https://user-images.githubusercontent.com/9772967/79452910-2ef2e800-7fe9-11ea-9ca9-9408a1b179b5.png)

**To Reproduce**
1. Insert a Previous Posts block.
2. Open the settings.
3. Tap over a PanelBody title and try to scroll the content.

**Expected behavior**
The settings content should scroll.

**Comment by pinarol** [comment]
Fixed as a part of https://github.com/WordPress/gutenberg/pull/21326
