### ISSUE TITLE
Improve i18n process to support jetpack

### ISSUE THREAD

**Issue by Tug** [wordpress-mobile/gutenberg-mobile#2162]
Currently we import many translations from gutenberg that we don't need.

Moreover, after adding jetpack as a submodule we will need translations for it as well and we should avoid distributing jetpack translations files as they are pretty big (>400KB per locale).

We could be a bit smarter:
1. Download all translation files from gutenberg and jetpack and merge them into `i18n-cache/temp/{locale}.json`
2. Extract all strings from `bundle/{platform}/App.js`
3. For the ones that have a translation entry in `i18n-cache/temp/{locale}.json` -> add them to `i18n-cache/data/{locale}.json`
4. For the others they will be generated as a `gutenberg-mobile.pot` file (we can update our pot generation to take `bundle/{platform}/App.js` as input and substract strings from `gutenberg.pot`)
5. We use the `bin/po2android.js` and `bin/po2swift.js` scripts to convert the gutenberg-mobile.pot file to bundle/android/strings.xml and `bundle/ios/GutenbergNativeTranslations.swift` (same as today)
6. We receive translations for those strings from the main apps at runtime (same as today) (edited)

**Comment by fluiddot** [comment]
Following with the idea of avoiding distributing the entire jetpack translation files, I've benchmarked the size of the JS bundle in relation to the translations, here are the results:

### Only include Gutenberg translations
- Bundle including all translations: 12.8 MB _(current size)_
- Bundle without translations: 5MB
- **Translations are increasing by 7.8 MB the bundle size.**

I was surprised that the translations mean 61% of the bundle size 😨 .

### Include Jetpack and Layout Grid translations

**All translations:**
- Bundle including all translations: 28.3 MB
- Bundle without translations: 5 MB

**Translations are increasing by 23.3 MB the bundle size.**

As you can see, if we don't optimize the translation files, we would almost be doubling the current bundle size and translations would mean 82% of the total size.

**Optimized translations (filtering out unused strings):**
- Bundle including optimized translations: 7MB
- Bundle without translations: 5 MB

**Translations are increasing by 2 MB the bundle size.**

On the other side, by optimizing the translations files we would save more than 89% of the total size that translations introduce to the bundle 🏋️ .

<hr>

With these results looks clear that optimizing the translations is mandatory unless we want to significantly impact the bundle size and therefore the final app size.

**Comment by fluiddot** [comment]
This issue has been addressed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4366.
