### ISSUE TITLE
Update existing templates using the new blocks

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2168]
Let's revisit existing templates and update them using new blocks.

**Comment by iamthomasbishop** [comment]
## New blocks to utilize
Here are the newly available blocks that we'll make use of:

* Columns
* Cover
* Latest Posts
* Buttons (shipping next)

## Layouts to update
With those new blocks in mind, here are the layouts/templates that will be updated to utilize these blocks:

* About
* Blog page
* Services

Here are some quick static mockups (Figma) that show roughly what the layouts will now look like (phone size mockup on left, portrait tablet on right), and some notes that explain what will need to change about for each.

### About layout

<a href="https://user-images.githubusercontent.com/1200432/79807057-76ea7580-832f-11ea-82ff-bcb121194738.png"><img src="https://user-images.githubusercontent.com/1200432/79807057-76ea7580-832f-11ea-82ff-bcb121194738.png" width="850"></a>

* Use the Columns block to place each quote in a separate Column

We might want to consider adding a fourth column here to balance things out a bit on tablet size, but that won't make or break the template.

### Blog page layout

<a href="https://user-images.githubusercontent.com/1200432/79807332-27f11000-8330-11ea-9eca-1e955c7cc8d7.png"><img src="https://user-images.githubusercontent.com/1200432/79807332-27f11000-8330-11ea-9eca-1e955c7cc8d7.png" width="876"></a>

* We can now utilize the Cover block. Or, if it's not quite ready for use we can use a static image (which I believe we're already doing as of the last release)
* We can remove the "Latest Posts" heading block, as it is a bit redundant

### Services layout

<a href="https://user-images.githubusercontent.com/1200432/79807619-19572880-8331-11ea-9631-8d8c056d2ce2.png"><img src="https://user-images.githubusercontent.com/1200432/79807619-19572880-8331-11ea-9631-8d8c056d2ce2.png" width="788"></a>

<a href="https://user-images.githubusercontent.com/1200432/79807671-38ee5100-8331-11ea-88d2-4b4ce0d133ea.png"><img src="https://user-images.githubusercontent.com/1200432/79807671-38ee5100-8331-11ea-88d2-4b4ce0d133ea.png" width="780"></a>

* Now can utilize Columns for the 3 sections of content in the middle part of the page
* We might want to add a fourth section to balance things a bit

## Other notes

* We can swap Button blocks for the new Buttons block, and ensure that they are center-aligned (note: our default button color is gray, so ignore the blue in the mockups)
* I've gone through and refined the copy to use our now-recommended sentence casing
* We might want to add a fourth column in cases of About and Services to balance out the layouts a bit

------------

@pinarol let me know if I missed or need to clarify anything!

**Comment by pinarol** [comment]
Thank you @iamthomasbishop !

> We might want to add a fourth section to balance things a bit

Agreed. I was wondering where all the other images come from? We can search the same source to find a new image for the fourth section.

**Comment by iamthomasbishop** [comment]
> I was wondering where all the other images come from? 

I _think_ we have been using images from Pexels, so we can continue to do the same. I'll add a fourth column and pull from that library.

**Comment by mkevins** [comment]
Thanks for the designs @iamthomasbishop :smiley: :+1: . I've opened some PRs for this :point_up_2: , so please let me know whenever we have the additional content / columns / copy, and I'll add it to the templates.

**Comment by iamthomasbishop** [comment]
@mkevins I've updated the mocks to include a fourth column on the examples that use Columns — the About layout got a fourth quote block and the Services layout got the fourth column with a new picture and heading block. No changes to the Blog layout.

## About layout

<a href="https://user-images.githubusercontent.com/1200432/80324607-3a1ef280-87f7-11ea-9d3c-6e883b17f3fd.png"><img src="https://user-images.githubusercontent.com/1200432/80324607-3a1ef280-87f7-11ea-9d3c-6e883b17f3fd.png" width="1291"></a>

New quote block copy:

* Quote body: "Technology is best when it brings people together."
* Source: Matt Mullenweg

Note: I'll add the `Needs Copy Review` label on this issue to request a copy review from the Editorial team.

## Services layout

<a href="https://user-images.githubusercontent.com/1200432/80324715-ba455800-87f7-11ea-8e56-241df89ff4eb.png"><img src="https://user-images.githubusercontent.com/1200432/80324715-ba455800-87f7-11ea-8e56-241df89ff4eb.png" width="1271"></a>

New content:

* Image: from [Pexels](https://www.pexels.com/photo/photo-of-women-at-the-meeting-3811082/)
* Heading: "Determination"
* Paragraph: "A short description of your company and the services you offer." (same copy as other paragraphs)
