### ISSUE TITLE
Add a Tooltip for template selection buttons

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2169]
We need to add a Tooltip to point to the template selection buttons.

**Comment by iamthomasbishop** [comment]
@geriux Here are some notes on the design component and how it should behave in the context of the editor, as a starting point. Keep in mind that this is a first pass, so we will likely iterate to ensure we're aligning stylistically and behaviorally with tooltips elsewhere.

<a href="https://user-images.githubusercontent.com/1200432/80428126-c2ac9a00-88ae-11ea-8993-648b5fa3bffa.gif"><img src="https://user-images.githubusercontent.com/1200432/80428126-c2ac9a00-88ae-11ea-8993-648b5fa3bffa.gif" width="900"></a>

⬆️ [View the prototype on Figma](https://www.figma.com/proto/2E2IBuDA3eBa0G4dQXkWFg/Starter-Page-Templates-Mobile-MVP?node-id=640%3A30358&viewport=-805%2C269%2C0.8444179892539978&scaling=scale-down)

## Visibility

In the context of SPTs, the tooltip should only be shown once, just as a subtle hint to try out the feature via the layout selection buttons.

The tooltip should appear after a slight delay (details on transitions below), and should be dismissed when the user taps anywhere outside of the tooltip, _with the exception of the inline layout selection buttons_ — the tooltip should stay visible as the user scrolls this portion of the UI. Tapping on the canvas above, to its side, or on the keyboard should dismiss the tooltip.

## Style

You can find detailed style, measurements, etc. on the [design documentation](https://zeroheight.com/226850145/p/19a850-tooltip). Note: we might end up tweaking the background color and shadow styling during implementation, so the documentation and our implementation might not be final.

## Transitions

### Entry

Tooltip fades in and slides up ~4px.

* **Delay**: Tooltip starts entering `~500ms` after the editor initially loads
* **Opacity**: When it starts appearing, it enters from `0%` opacity to `100%`
* **Y-translation**: It starts `-4px` down on the Y axis, relative to its end position (There is `~8px` spacing between tooltip pointer and inline layout selection buttons — [example](https://cloudup.com/cDFc7Siu6yn))
* **Duration**: `~300ms`
* **Easing**: `easeOut`

### Exit

Tooltip fades out quickly in-place.

* **Delay**: No delay
* **Opacity**: `100%` opacity to `0%`
* **Y-translation**: none — the tooltip fades out in-place
* **Duration**: `~150ms` (half the duration of the entry transition)
* **Easing**: `easeOut`
