### ISSUE TITLE
JitPack build fails with "Git clone took longer than 180 s"

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#2182]
It has been reported (in Slack) a few times already that the JitPack build randomly fails with the following error message (in JitPack's log):

```
Git error. Retrying.
Git error. Git clone took longer than 180 s
```

**To Reproduce**
No steps to reproduce, but it looks like it is too frequent at this point. An example is [this WPAndroid PR](https://github.com/wordpress-mobile/WordPress-Android/pull/11594) on which we've failed to make the JitPack build dependency succeed.

**Comment by hypest** [comment]
Looks like the issue is still happening, this time on 30d5f0a, part of the 1.27.0 release cut.

**Comment by mchowning** [comment]
Closing this since we no longer rely on Jitpack to build the entire gutenberg-mobile library. We do still use it to build some of our React Native dependencies, but those are substantially smaller and have not encountered this "Git clone took longer than 180 s" error.
