### ISSUE TITLE
Apply background/foreground colors to blocks

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2195]
We are almost finished with the [first step of Global Styles support](https://github.com/WordPress/gutenberg/pull/21637). That means we can now inherit color settings from container blocks. But, we aren't yet applying them to the UI.

We need some design point of view to apply background colors. On web, an extra padding is applied when a block gets background color. Should we do a similar thing? @iamthomasbishop If yes, how much padding would you recommend? Also any other thoughts about how it should look on mobile?

<img width="994" alt="Screen Shot 2020-04-27 at 19 36 24" src="https://user-images.githubusercontent.com/5032900/80516431-1e008a00-898c-11ea-8329-3f9d7f59b43b.png">

**Comment by iamthomasbishop** [comment]
@pinarol I think we could approach the padding slightly differently, because of the way our block UI/structure works. For example, our block borders are optically "inset" to about 3-4px on each side, so the block background could extend to that outer border, thus giving the block some optical padding without the need to re-structure or add additional padding. That would look like this — no additional padding on left, and example of with additional padding on right:

<a href="https://user-images.githubusercontent.com/1200432/80620228-54c9b500-8a0b-11ea-8c1c-e7cf96708ba4.png"><img src="https://user-images.githubusercontent.com/1200432/80620228-54c9b500-8a0b-11ea-8c1c-e7cf96708ba4.png" width="1802"></a>

In my opinion, the additional padding doesn't necessarily look _bad_ per se, and it is more consistent with what is rendered on the front-end. But in practice, I think utilizing the existing structure and just making the background extend to the optical boundary (blue border) makes more sense. 

If we were to add additional padding, it would give us a little less room when we get into nesting and groups. We do handle the margins/spacing quite well by forcing blocks to be full-width in most cases, but adding additional padding here would likely challenge that a bit.

So my vote would be to use the left approach as a starting point and test for stress cases.

**Comment by iamthomasbishop** [comment]
One thing I hadn't thought about is how this applies to other blocks — for example, the Cover block. The first approach I mentioned might not actually work very well if we extend the background color outside the inner container. If we can choose when to "contain" the background to a certain container then it should in theory work.

For example, if you apply a color overlay to the Cover block, we want it to extend to the edges of the image that it's overlaying, not beyond that to the selection borders, if that makes sense. Curious to hear what you think of this dilemma @pinarol .

**Comment by pinarol** [comment]
@iamthomasbishop Not all the blocks have background color support, Cover is one of them. I think we should only apply colors inside block content not inside the borders(similar to the right side screenshot👆 ), because our borders have some distance from the real block content. It won't match the preview if we apply the color inside borders, especially when some blocks can't have background colors. 

I think the real challenge starts when we start to think about nesting. Curious how you'd imagine it'd look in mobile in such a hierarchy? 👇

- Group. (blue)
    - Paragraph 1 (none) -> Inherits blue
    - Paragraph 2 (pink)
    - Group (green)
          - Paragraph 1 (none) -> Inherits green
          - Paragraph 2 (yellow)
    - Paragraph 3 (none) -> Inherits blue

Basically what web is doing is just applying paddings to those blocks that have background color, it seems the same for all the blocks. I think we can have a similar approach but maybe with less padding amount since we don't have enough space. 

<img width="1023" alt="Screen Shot 2020-04-29 at 19 40 51" src="https://user-images.githubusercontent.com/5032900/80622381-63d35600-8a51-11ea-8393-583675459463.png">

The code:

```

<!-- wp:group {"customBackgroundColor":"#369bc6"} -->
<div class="wp-block-group has-background" style="background-color:#369bc6"><div class="wp-block-group__inner-container"><!-- wp:paragraph -->
<p>Paragraph 1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"customBackgroundColor":"#d481cd"} -->
<p style="background-color:#d481cd" class="has-background">Paragraph 2</p>
<!-- /wp:paragraph -->

<!-- wp:group {"customBackgroundColor":"#30a300"} -->
<div class="wp-block-group has-background" style="background-color:#30a300"><div class="wp-block-group__inner-container"><!-- wp:paragraph -->
<p>Paragraph 1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"customBackgroundColor":"#dccf42"} -->
<p style="background-color:#dccf42" class="has-background">Paragraph 2</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p>Paragraph 3</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->
```

**Comment by iamthomasbishop** [comment]
> Curious how you'd imagine it'd look in mobile in such a hierarchy?

I think with the way we structured nested blocks, all blocks are 100% width and we are not adding any visual padding — so this may complicate that logic a bit. I imagine it'll look cleanest if we do add a small bit of padding to `.hasBackground`.

I played around with the spacing/sizing a little bit today in Figma, and found that if we add ~6px of padding to anything that has a background fill, and refine our spacing on nested block outlines (dashed borders), we can pretty gracefully scale this in a way that should work for anything less than ~4 or so levels deep.

This is what it could look like (note: I used a very narrow viewport to make sure we can scale easily upwards from there). This is an example using a parent Group block, which has the same nesting structure as your example above.

<a href="https://user-images.githubusercontent.com/1200432/80847658-159b8f80-8bd6-11ea-9467-788faca92820.png"><img src="https://user-images.githubusercontent.com/1200432/80847658-159b8f80-8bd6-11ea-9467-788faca92820.png" width="685"></a>

I think this is about as good as we're going to get, and as far as I can tell, it should be as simple as adding a 6px padding to anything that has `.hasBackground`.

**Comment by pinarol** [comment]
I'll try to list some items that may effect our UX decisions on color support.

1. Colors can be defined on block level as well as on theme level. Themes currently use css&php to inject styles. However, there's an ongoing global styles work and when done, theme authors will be able to define style specs in [theme-json](https://developer.wordpress.org/block-editor/developers/themes/theme-json/). And we'll hopefully be able to fetch that json via an endpoint and render styles on mobile. But that work will not be completed very soon.

2. If we set a color from the custom color picker it won't get effected by theme change.

3. If we set a color from the color palette it will get effected from theme change. But the computed color value depends on the new theme and it is not predictable.

4. Some themes on .com has a mechanism that [changes the text colors depending on the background](https://github.com/WordPress/gutenberg/issues/24166).
      * This behavior will eventually be absorbed by [theme-json](https://developer.wordpress.org/block-editor/developers/themes/theme-json/)/Global Styles. 
      * Not every theme has the same mechanism. 
      * When this happens the the text color changes on frontend as well.
      * This mechanism is present only for palette colors not for the custom colors that are picked from the color picker.
      * Cover block has a similar mechanism, text color changes according to the Cover image. But luckily this is a Core feature so we don't need to worry about the possible inconsistencies between the editor and the frontend.

5. .com Starter Page Layouts usually have background colors defined in the block level but text colors are usually left undefined, thus, they just fallback to theme default. This way when the user changes the theme the text colors adjust automatically. This is also valid for button background colors. Since this is the desired behavior, editing the existing .com layouts to define text colors is not an option.

**Comment by pinarol** [comment]
Here's my thoughts about what we can do on mobile to help layouts and the whole page editing experience work well. 

I think we should try not to put the user in a position that they'll need to set the text colors just to be able to see the text in the editor. Because in that case the text colors can loose the ability to adjust well to theme changes. As far as I see from the existing .com layouts they intentionally avoid defining foreground colors(like button, text colors) in the block settings for this reason. So let's say the user changes the background color to a very light/dark color, I think we can imitate [this behavior](https://github.com/WordPress/gutenberg/issues/24166) and adjust the text colors accordingly. To be more clear, the block's html would remain colorless but the editor will show a different text color depending on the background color. 

Currently we don't know which color from the theme palette is light/dark foreground colors, so we'll need to use default fallback colors like white/black. And once [this issue](https://github.com/WordPress/gutenberg/issues/24166) is resolved and the GSS is available for us via an endpoint we can fetch this info and improve what we have.

There are trade offs about this behavior as well. Not every theme might have dynamic text colors depending on the background, so there may be a miss-match between the real preview and the editor. But it looks less of a problem to me currently.

@iamthomasbishop Any thoughts?

**Comment by pinarol** [comment]
This is a tricky effort to split, here's my first approach:

1. Introduce background/text color settings to text based blocks: Paragraph, Header, Quote, PullQuote etc.
    * Add necessary paddings when background color is applied
    * Adapt bordering logic if needed

2. If any needed, introduce color settings to other leaf blocks that don't have inner blocks

Start with container blocks:

3. Group block: Introduce background color settings
    * Add necessary paddings when background color is applied
    * Adapt bordering logic if needed

4. Dynamic text colors depending on the background (This is for edge cases where the overlay is too dark or too light making the text hard to read) 
    * Cover block has this functionality on Core as well, but other blocks have it depending on the theme.[More context](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2195#issuecomment-665615350)

5. Other container blocks:
- Columns, Media & Text etc.

**Comment by iamthomasbishop** [comment]
@pinarol I still need to catch up on the previous discussion, but this sounds pretty reasonable to me. One suggestion: perhaps we can prioritize the dynamic color mechanism sooner rather than later because in addition to having it for the other items listed here, it's seems rather certain that we'll use it in a variety of places. For example, I can see a case for using this mechanism for block UI like bordering, icons, etc.

**Comment by pinarol** [comment]
> One suggestion: perhaps we can prioritize the dynamic color mechanism sooner rather than later because in addition to having it for the other items listed here, it's seems rather certain that we'll use it in a variety of place.

👍  I moved that upwards in the order of things. We can start tackling it with the first container block(Group) we'll introduce colors to.
