### ISSUE TITLE
Have to "undo" two times to restore after trashing post's only block

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#2201]
**Describe the bug**
When a block has only a single block and you trash it, you have to press the undo button twice to bring the trashed block back. If the post has more than one block, however, a single undo tap restores the trashed block (as you would expect).

**To Reproduce**
1. Open a new post
2. Add a single block to the post and type some text
3. Tap the trash icon to delete the block you just added the text to
4. Tap the undo button
5. Observe that the trashed block is not restored. If the keyboard was open, I see the keyboard is closed. If the keyboard is not open, I don't see any change.
6. Tap the undo button a second time
7. Observe that the trashed block is restored.

**Expected behavior**
After trashing a block, pressing the undo button a single time should restore the trashed block.

**Screenshots**

![undo_trashed_block mp4](https://user-images.githubusercontent.com/4656348/80638870-1fcf5980-8a2f-11ea-981a-b6ad5ddeffde.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone Xr, Pixel
 - OS: iOS 13.3.1, Android 10

**Additional context**
Reported by @akirk
p1588187516110100-slack-mobile-gutenberg

**Comment by SiobhyB** [comment]
In the latest version of the app (`24.3`), the undo button now appears to be working as expected in this scenario. It only took one tap for the trashed post to be restored on both Android and iOS.
