### ISSUE TITLE
Kotlin-fy the Android code for the bridge

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#2203]
Currently, the RN bridge and glue code on Android is written in Java. Nothing's wrong with that but it would be better to migrate to Kotlin for smoother navigation between the WPAndroid and gutenberg-mobile codebases.

**Comment by maxme** [comment]
Fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/2211
