### ISSUE TITLE
Done button in paragraph block (landscape mode text editing) leads to loop

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#2210]
**Describe the bug**
When in landscape mode in Android, the edit text enters a landscape mode, which takes up the top half of the screen, with the keyboard occupying the bottom half. After tapping "done", the editor jumps into a new paragraph block, which reopens the keyboard without allowing the user to "escape".

**To Reproduce**
1. Start a new post
2. Rotate the device to landscape orientation
3. Add a paragraph (observe landscape mode editing, with "done" button)
4. Type some text and press "done"

**Expected behavior**
The previously entered text should be visible in the paragraph block without re-entering the landscape editing mode for the next block, which obscures the view of the text just added.

**Screenshots**
<details>
<summary>Edit loop</summary>

![paragraph-landscape-done-loop](https://user-images.githubusercontent.com/8507675/80564405-147d2d80-8a31-11ea-96af-7f8775bc94c1.gif)
</details>

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android X

**Additional context**
The user can "exit the loop" by pressing the back button. However, it seems that "done" should allow a user to see what they just finished typing, so IMO this _feels_ like a bug, even if it is a limitation of the current UX.

**Comment by SiobhyB** [comment]
I'm no longer able to reproduce this issue in 24.3, using a Pixel 6.
