### ISSUE TITLE
Implement opt-in mechanism for the alpha

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#222]
Even if the alpha is only available for internal testers in the apps, we still need to decide how will users select which editor they want to use:

- We have an API to sync opt-in settings for web and mobile that's per site/user.
- Where will the toggle exist? Site settings?
- Do we always open Gutenberg for posts with Gutenberg content?
- Will we offer a way to open a specific post with the non-default editor without having to switch the setting for the site?

We might want to simplify a bit for the alpha, but we still have to implement some of it, since we can't just default to Gutenberg for everything at that stage, even for internal testing.

**Comment by hypest** [comment]
A simplified proposal for the Alpha since the timings are tight:

1. Open all non-Gutenberg posts in Aztec. No prompts to switch to Gutenberg yet. We don't have a good migration path yet to prompt about.
2. Default opening all Gutenberg posts directly in gutenberg-mobile. Offer a button to escape to Aztec. We can track that button press to monitor the rate at which users escape.
3. For Gutenberg posts escaped to Aztec, offer a similar button to return to gutenberg-mobile
4. No persistent setting anywhere

**Comment by koke** [comment]
That's a good start, I think. One of the [goals](https://github.com/wordpress-mobile/gutenberg-mobile/milestone/4) and the main reason we're doing the integration is to allow for easy user testing. So while I'm not sure this is a blocker for release, allowing testers to create a new post in gutenberg-mobile should be a priority.

**Comment by hypest** [comment]
> allowing testers to create a new post in gutenberg-mobile should be a priority

Oh, makes sense. Updated the proposal above to include item 5.

**Comment by koke** [comment]
I might anticipate some testers wanting to opt-out of that, but it doesn't seem like a blocker for the alpha, so we can deal with that later.

@iamthomasbishop what do you think?

**Comment by iamthomasbishop** [comment]
I think that's about what I was expecting, and seems to align with most of what we've talked about previously. @mzorz can you confirm this is in line with our discussions? I want to clarify one point, though:

> Default opening all Gutenberg posts directly in gutenberg-mobile. Offer a button to escape to Aztec. We can track that button press to monitor the rate at which users escape.

Are you imagining this would be an alert of sorts, similar to the compatibility alert (but more of an opt-in, less of an alarm bell)? Or just a trigger/toggle somewhere in the UI to allow switching to Aztec?

**Comment by mzorz** [comment]
I agree with the outline made by @hypest in https://github.com/wordpress-mobile/gutenberg-mobile/issues/222#issuecomment-436541154

> Are you imagining this would be an alert of sorts, similar to the compatibility alert (but more of an opt-in, less of an alarm bell)? Or just a trigger/toggle somewhere in the UI to allow switching to Aztec?

Also good question @iamthomasbishop  - I think probably we can add a button on the toolbar that allows to switch to Aztec just for the alpha? wdyt?

**Comment by koke** [comment]
If we put it in the toolbar then we have to modify aztec’s toolbar as well so you can go back. I was thinking something similar to the switch to html mode, but I’m worried it’s not discoverable enough

**Comment by mzorz** [comment]
> but I’m worried it’s not discoverable enough
I think, for the alpha, anything even rudimentary that we can give instructions about in release notes would do

**Comment by iamthomasbishop** [comment]
> I was thinking something similar to the switch to html mode, but I’m worried it’s not discoverable enough

I don't think the toggle itself needs to be a top-level navigation item (nor do I think there's really much space to put it in the navbar/app bar), so I'd put it in the ellipsis menu for now. If we feel we need to call it out, we can do so in release notes and if necessary, could trigger an alert or announcement of sorts.

**Comment by koke** [comment]
With the integration ready on iOS and expected to land this week on Android, we want to make it possible to access Gutenberg on internal builds. This doesn't replace the existing proposal, but it is a temporary measure until the decide opt-in flow is ready.

We'll have a simple switch on Me > Settings that replaces what the `-gutenberg` command line argument does now.  This setting (and Gutenberg) should only be visible on debug and internal builds. Below, it should have some explanation that this is an experimental feature.

**Comment by mzorz** [comment]
> We'll have a simple switch on Me > Settings that replaces what the -gutenberg command line argument does now. This setting (and Gutenberg) should only be visible on debug and internal builds. Below, it should have some explanation that this is an experimental feature.

As discussed elsewhere, I understand this manual switch is a need for showcasing the feature and giving the user full control (at their own risk)  just for internal testing (alpha).

Created new issue in the respective repos here:
- Android https://github.com/wordpress-mobile/WordPress-Android/issues/8684
- iOS https://github.com/wordpress-mobile/WordPress-iOS/issues/10554
