### ISSUE TITLE
[GlobalStep] [Android] At Create blog post, after adding two buttons "+"/appender symbol gets non-functional.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2227]
**Environment:**
 Samsung Galaxy s9(v10)

**Reproduction Rate:** 
4/4 100%
 
**Steps To Reproduce:**
 1. Install and open the application.
 2. log in with valid credentials.
 3. Tap on "My site"
 4. Tap on "+" symbol to add new blog post.
 5. Tap on Blog Post.
 6. From footer tap on "+" symbol to add buttons.
 7. Notice a button is added to the blog.
 8. Tap on "+" symbol to add 1 more buttons.
 9. Again tap on "+"symbol to add another button.
 10. Now tap on "+" symbol on the same inline appender.
 11. Observe that upon adding two buttons in the same inline appender, "+" symbol gets non-functional

**Actual Result:**
At Create blog post, after adding two buttons "+"/appender symbol gets non-functional. 
 
**Expected Result:**
"+"/appeneder should be functional even after adding more than 2 buttons.

[#2227.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4588160/2227.zip)

**Comment by designsimply** [comment]
I tested with 14.8-rc-3 and was unable to see the inline button appender get stuck after adding several buttons. ([48s](https://cloudup.com/czfhKWcx5bR))

<p style="clear:both;"><sup>Tested with WPAndroid 14.8-rc-3 on Pixel 3 Android 10 (shown in video) and on a Samsung Galaxy Tab4 (SM-T330NU), Android 5.1.1.</sup></p>

@lukewalczak could you help double check that multiple buttons can be added in a row when you test with 14.8-rc-3 (available in the Google Play Store if you join the https://play.google.com/apps/testing/org.wordpress.android) or from `develop` if that's easier?

**Comment by lukewalczak** [comment]
Hi @designsimply, I'm able to reproduce it on beta version. Will investigate it.

Testing on:
Samsung S8, Android version 9

**Comment by lukewalczak** [comment]
Created a PR which is fixing that.
