### ISSUE TITLE
Unexpected behavior with <mark> tag

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#2232]
### Describe the bug
When a paragraph block has a mark tag (1) tapping enter adds a new line to the paragraph block instead of creating a new block and (2) it is not possible to merge another block back into the block with the paragraph block

### To Reproduce

Use HTML like this in the following tests:

```
<!-- wp:paragraph -->
<p><mark>abc</mark>d</p>
<!-- /wp:paragraph -->
```

#### Enter creates newline instead of new block
1. Create a paragraph block with the ^above^ html
2. With cursor after the visible `d` character, tap Enter
3. Observe that a newline is added in the paragraph block

#### Cannot merge into block
1. Create a paragraph block with the ^above^ html
2. Create a second paragraph block _after_ the first one with some text
3. Put your cursor at the beginning of the second block and tap backspace
4. Observe that nothing happens (the blocks are not merged)

### Expected behavior
- Tapping Enter within a paragraph block should create a new paragraph block
- Tabbing backspace at the beginning of a paragraph block that is after another paragraph block should merge the two blcoks

![mark_handling_ios mov](https://user-images.githubusercontent.com/4656348/81213182-06388f80-8fa4-11ea-9ee0-a4a820678504.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS 13
 - Version: 827a098b9b

### Additional context
Ran across this while investigating problems Android was having with these tags: https://github.com/wordpress-mobile/WordPress-Android/issues/9832

**Comment by geriux** [comment]
This is no longer reproducible after we implemented the `mark` tag functionality in bot platforms.
