### ISSUE TITLE
Remove border-bottom from border-radius cell on Button block settings sheet

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2233]
The cell containing the border-radius setting on the Button block settings sheet shouldn't have a border-bottom (per the guideline that the last cell in a table section shouldn't have a border).

**To Reproduce**
1. Add a Buttons block, then select an individual Button
2. Access block settings by tapping on the settings icon (⚙️)
3. Note that the border-radius cell has a border-bottom

**Expected behavior**
The last cell in a table section/group shouldn't have a border.

**Screenshots**
![image](https://user-images.githubusercontent.com/1200432/81251210-59343600-8fe8-11ea-97f7-e3b34c97b71b.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 10
 - Version: WPAndroid 14.8 int beta

**Comment by SergioEstevao** [comment]
This is fixed on release 1.28 of GB-mobile trough this PR: https://github.com/WordPress/gutenberg/pull/21365
