### ISSUE TITLE
[Globalstep]"Oops! That Page can't be found" error is shown upon tapping any linked image.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2239]
"Environment:
iOS: iPad Air 2(v13.3.1),  iPad (6th Gen) - v12.4

Steps To Reproduce:
 
 1. Install and launch the application.
 2. Tap on ""Log In"".
 3. Log in to the app using valid credentials.
 4. Open Site Pages go to Drafts section
 5. Tap on "+" icon and create a page.
 6. Add an Image with a URL link.eg.www.google.com
 7. Publish your page.
 8. Observe that when user taps on linkable image it prompts an error message stating
    "Oops! That Page can't be found"

Actual Result:
"Oops! That Page can't be found" error is shown upon tapping any linked image.

Expected Result:
Image link should redirect to specific page when user taps on an linkable image.

[#2239.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4594805/2239.zip)

**Comment by SergioEstevao** [comment]
Hello there, I was able to reproduce this issue, the problem here is we are expecting a full url like: 
`https:\\www.google.com` in order to link to the exterior site.

If you just insert `www.google.com` the link will be translated to `yoursite.com/www.google.com` and then you get the 404 error.

**Comment by hypest** [comment]
This is the same behavior as Gutenberg-web. But, the classic editor on the web is automatically inserting the `http://` in front of the URL if it's missing so, let's close this ticket as non mobile specific and @SergioEstevao , can you open a relevant ticket on Gutenberg-web if not there already? Thanks!
