### ISSUE TITLE
Buttons Block: "Problem displaying block" error for button blocks with custom colors or gradient backgrounds

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2260]
Steps to reproduce:

1. On the web, create a new post and add a buttons block.
1. Add a button and select the outline style in block settings.
1. Add a button and select a theme background and text color in the block settings.
1. Add a button and select a custom background and text color in the block settings.
1. Add a button and select a linear gradient background color in the block settings.
1. Add a button and select a radial gradient background color in the block settings.
1. Publish the post.
1. In the app, open the post in the editor and check to see if the button colors are rendered.

**Result:** button blocks with custom colors or gradient backgrounds are not rendered in the block editor in the app and instead show a "Problem displaying block" error.

WP.com block editor|WP.com block settings|WPAndroid block editor
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/81889732-8beaab00-9561-11ea-9656-5842820286f5.png" width="200" alt="Screenshot_20200513-172749">|<img src="https://user-images.githubusercontent.com/1119271/81889739-91e08c00-9561-11ea-8f48-aa50bda7b3b3.png" width="200" alt="Screenshot_20200513-172942">|<img src="https://user-images.githubusercontent.com/1119271/81889744-960ca980-9561-11ea-8fa9-82ca81bcae82.png" width="200" alt="Screenshot_20200513-143215">

<p style="clear:both;"><sup>Tested with WPAndroid 14.8-rc-3 on Pixel 3 Android 10 (seen in screenshots above) and with WPiOS 14.8.0.2 TestFlight beta on iPhone 11 iOS 13.4.1, both apps were tested using a WordPress.com Free site.</sup></p>

**Note:** see test cases [TC016](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc016), [TC017](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc017), [TC018](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc018), [TC019](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc019) at [Buttons Block - Test Cases](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#buttons-block---test-cases).

**Comment by designsimply** [comment]
Here is a copy of the buttons block HTML from the post affected for reference:

```
<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link">Outline</a></div>
<!-- /wp:button -->

<!-- wp:button {"backgroundColor":"primary","textColor":"subtle-background"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-subtle-background-color has-primary-background-color has-text-color has-background">theme dark bg light text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"text":"#ffffff","background":"#090909"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="background-color:#090909;color:#ffffff">custom black bg white text color</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"gradient":"radial-gradient(rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%)","text":"#eae120"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="background:radial-gradient(rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);color:#eae120">radial gradient</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"gradient":"linear-gradient(232deg,rgb(238,238,238) 0%,rgb(0,0,0) 100%)"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-background" style="background:linear-gradient(232deg,rgb(238,238,238) 0%,rgb(0,0,0) 100%)">Linear gradient black to gray angle 232</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```

**Comment by pinarol** [comment]
hey @designsimply 👋 I don't expect that invalid block error happening on custom colors, it should work according to the documented test cases. But sometimes those kinds of things can happen due to difference of gutenberg editor versions between web and mobile since the generated HTML differs(especially when the button was created with a newer version of the editor in one platform and then opened with an older version in the other platform, in this case the new markups can't get recognized by the older editor. I raised this problem to web folks internally but unfortunately there's no fix for this currently. The problem also exists when you install the latest version of the gutenberg plugin and then remove it on web). 

We already repeated these tests on the upcoming editor release which will be included in 14.9 and couldn't detect such errors. Can you check again with the apk here: https://github.com/wordpress-mobile/WordPress-Android/pull/11894#issuecomment-627564375 ?

**Comment by designsimply** [comment]
Tested and confirmed I can no longer see an error for button blocks with colors added via WordPress.com on 2020-05-11 in the block editor on WPAndroid using the .apk file from https://github.com/wordpress-mobile/WordPress-Android/pull/11894#issuecomment-627564375. 🎉

<img src="https://user-images.githubusercontent.com/1119271/81968250-60a3a280-95d9-11ea-8e91-585333edea5c.png" width="200" alt="Screenshot_20200514-074554"> <img src="https://user-images.githubusercontent.com/1119271/81968246-5f727580-95d9-11ea-97ab-f7bb7aefb6fd.png" width="200" alt="Screenshot_20200514-074730">

<p style="clear:both;"><sup>Tested with WordPress-pr-11894-build-50728.apk on Pixel 3 Android 10 on a [post](https://made4testing0318.blog/2020/05/11/more-buttons-with-colors/) created with Calypso Gutenberg at WordPress.com on 2020-05-11 via Firefox 75.0 on macOS 10.14.6.</sup></p>

**Comment by designsimply** [comment]
Closing as fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11894. Props @mchowning. 🎉
