### ISSUE TITLE
Merge text strings

### ISSUE THREAD

**Issue by knutsp** [wordpress-mobile/gutenberg-mobile#2267]
"Get in Touch!"
"Get in touch!"
"Get in Touch"

Please!

Regards,
The translator

**Comment by designsimply** [comment]
It looks like [these strings](https://github.com/wordpress-mobile/gutenberg-mobile/blob/a549fa3fd66b553a8d6fb535e91fbc8acdefe799/bundle/ios/GutenbergNativeTranslations.swift#L64-L66) were added as part of Page Templates in 14.5 (see https://github.com/wordpress-mobile/gutenberg-mobile/pull/1987). We should be able to consolidate them! Thank you for the suggestion.

**Comment by mkevins** [comment]
Resolved in https://github.com/WordPress/gutenberg/pull/22620 :tada:
