### ISSUE TITLE
Try to have a change-detection solution that doesn't depend on computing hashes

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#227]
#225 adds an md5-based content change detection mechanism to inform the parent app of whether the content is modified or not. We'd like to avoid computing hashes for this and perhaps rely on solution similar to Gutenberg-web's. Opening this ticket to keep this in our radar.

Some context: https://github.com/wordpress-mobile/gutenberg-mobile/pull/225#issuecomment-436638366

**Comment by koke** [comment]
Closing in favor of #266 which is similar
