### ISSUE TITLE
[iOS] Underline on some links within List block extend beyond text label

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2274]
**Describe the bug**
When writing a List block on iOS, some link underlines extend to the right edge of the block, beyond the list item's text contents. More specifically:

* This happens when the link spans to the last character in a list item _and_ additional characters
* It does _not_ happen when the link doesn't contain the last character
* It does _not_ happen on the _last item_ of a list

Note: I've seen this a few times and thought it had been fixed, but flagging again to be sure we can prioritize it. I haven't tried to replicate on Android but we might want to double-check. // cc @maxme @hypest @SergioEstevao 

**To Reproduce**
1. Add a List block (use any list-type)
2. Add a few list-items
3. Apply a link that contains at least the last character to a list-item
4. Apply a link that does not cover the last character of a list-item
5. Apply a link on the last list-item that spans the whole item
6. Observe something like the following:

<a href="https://user-images.githubusercontent.com/1200432/82380317-e070a900-99ed-11ea-96f1-83a4baf0f598.jpeg"><img src="https://user-images.githubusercontent.com/1200432/82380317-e070a900-99ed-11ea-96f1-83a4baf0f598.jpeg" width="600"></a>

**Expected behavior**
Underlines should not extend beyond the text label of each list-item.

**Smartphone (please complete the following information):**
 - Device: iPad Pro, iPhone 11 Pro, iPhone XS Max
 - OS: iOS 13.x
 - Version: WPiOS 14.9b

**Comment by SergioEstevao** [comment]
Good catch @iamthomasbishop ! We did fix this in the past, but before it was associated with the use of `nbsp` entities, and this one looks a new instance of the problem.

I will check on Aztec to see if I can find what is going on.

**Comment by SergioEstevao** [comment]
Fixed in release 1.49 of WP-iOS.

**Comment by iamthomasbishop** [comment]
Awesome, thank you @SergioEstevao!!
