### ISSUE TITLE
Cover: Allow creating the block with only color/gradient backgrounds (without an image)

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2275]
There's no way to create a color/gradient background for Cover blocks on mobile. We can render this if it is set on web but there's no way to create one. On web, this can be created with the options on the Placeholder:

<img width="801" alt="Screen Shot 2020-05-20 at 12 47 36" src="https://user-images.githubusercontent.com/5032900/82432325-91338280-9a98-11ea-9169-f889139f3a4f.png">

There's also no way to remove the image once you set it, same on web. 

How do you think we should do this on mobile? @iamthomasbishop

**Comment by iamthomasbishop** [comment]
@pinarol I would suggest we do something similar, at least for a v1. We now have color picker components that we can utilize, which is really exciting 😄 Here's what I think the flow could look like, hoping we can use existing components:

* The placeholder would be very similar to what exists now, but like the web would show some shortcut swatches. I suggest we show black and white first, then 2-3 solid defaults if we are able to display a couple of theme defaults (if not, we'd skip these 2-3), then the custom color picker indicator (the rainbow swatch).
* If you tap a swatch in this list that isn't the custom color, that color will be applied straight away, and — a notable change to the current flow — the parent (cover) stays selected. In the top corner, a little "image" icon shows to hint that you can also add an image background.
* If you tap the custom color swatch, the custom color picker UI shows. You can tap "Cancel" to go back, or tap "Apply" to proceed. That color is then set as the background of the block.

<a href="https://user-images.githubusercontent.com/1200432/83098993-a187c680-a071-11ea-83d4-4ae56f6c5850.png"><img src="https://user-images.githubusercontent.com/1200432/83098993-a187c680-a071-11ea-83d4-4ae56f6c5850.png" width="902"></a>

> There's also no way to remove the image once you set it, same on web.

A couple of things here:

* We currently allow a long-press on the image to show a menu of image sources to choose from (essentially the "replace image" task). I think this would be one place for a "Clear media" menu button.
* The other place we might want to consider showing this option is in the block settings sheet. We obviously don't have any media-related settings in the sheet yet, but I think there was some discussion about adding focal point and other items soon, so I would put this "clear media" button nearby those items (similar to web).

------------

Does all of this make sense? Let me know if you have any questions about the flow or design.

**Comment by antonis** [comment]
This issue is broken down in the following subtasks
- [] Clear Media (issue: https://github.com/WordPress/gutenberg/issues/23789, PR: TBD)
- [] Add Media when only background colour is set (issue: TBD, PR: TBD)
- [] Apply default colour (issue: TBD, PR: TBD)
- [] Select and apply custom colour (issue: TBD, PR: TBD)

As part of the GB-Mobile Monorepo migration the new issues are opened in the [Gutenberg project](https://github.com/WordPress/gutenberg)

**Comment by antonis** [comment]
Hello @iamthomasbishop,
I was also thinking of adding a 'clear color' button like the web. It seems like a quick win on the code side.
![Screenshot 2020-07-10 at 4 08 25 PM](https://user-images.githubusercontent.com/304044/87157924-a02ff780-c2c7-11ea-9379-4a20f1bca144.png)
Wdyt?

**Comment by antonis** [comment]
Closed with https://github.com/WordPress/gutenberg/issues/23789, https://github.com/WordPress/gutenberg/issues/23831, https://github.com/WordPress/gutenberg/issues/23868 and https://github.com/WordPress/gutenberg/issues/23877
