### ISSUE TITLE
[GlobalStep] [Android] "Get in Touch" button is misaligned as well as "Exclamation point symbol" is missing from "Let's build something together" text in default page templates for "About" and "Services" .

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2287]
**Environment:**
Android: Samsung Galaxy s9 (v10), Samsung Galaxy S7 (v8), Samsung Galaxy Tab A (v9).
Build WPAndroid [version]: v14.9

**Steps To Reproduce:**
 1. Install and launch the application on both the platforms.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Tap on Site Pages option.
 5. Tap on Add page "+" icon.
 6. Select About/Services page template and tap on apply button.
 7. Tap on Publish button.
 8. Pop-up appears tap on "Publish now".
 9. Now tap on three dots symbol and tap on view option.
 10. Observe that "Get in Touch" button is not centrally aligned and" Exclamation point symbol" also missing with this "Let's build something together "text.
 
 Note: Compared the template with this link.
 Link: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2168#issuecomment-616857093

**Actual Result:**
 "Get in Touch" button is misaligned as well as "Exclamation point symbol" is missing from "Let's build something together" text in default page templates for "About" and "Services" .

 **Expected Result:**
 Application should display "Get in Touch" button centrally aligned as well as "Exclamation point symbol" should be present for "Let's build something together" text.

**Attachment:**
[#2287.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4662985/2287.zip)

**Comment by designsimply** [comment]
Screenshots from the attachment:

Template Preview|Webview
---|---
![#2287_Service](https://user-images.githubusercontent.com/1119271/82692870-b69dc900-9c1d-11ea-826a-630d9e0892bc.jpg)|![#2287_About](https://user-images.githubusercontent.com/1119271/82692733-78080e80-9c1d-11ea-85d9-bbae7d0646c8.jpg)

**Comment by mkevins** [comment]
Resolved in https://github.com/WordPress/gutenberg/pull/22620 :tada:
