### ISSUE TITLE
[GlobalStep] [Android] Unable to operate or handle all tags in HTML mode.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2292]
**Environment:**
Android: Samsung Galaxy s9 (v10), Samsung Galaxy S7 (v8), Samsung Galaxy Tab A (v9).
Build WPAndroid [version]: v14.9

**Steps To Reproduce:**
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Tap on "Create a new Post" symbol.
 5. Enter any text at title.
 6. Tap on (More)three dots symbol at top right side.
 7. Now tap on Switch to HTML mode.
 8. Enter any tag except paragraph.
 9. Observe that user is not able to add all other tags apart from Paragraph.

Note: Paragraph tag <p> gets automatically added when we enter text in HTML view.

**Actual Result:**
Unable to operate or handle all tags in HTML mode.

**Expected Result:**
User should be able to operate smoothly in HTML mode.

**Attachment:**
[#2292.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663095/2292.zip)

**Comment by designsimply** [comment]
Screenshots from the video attachment:

<img width="200" alt="Screen Shot 2020-05-22 at May 22 1 23 55 PM" src="https://user-images.githubusercontent.com/1119271/82702621-8fe88e00-9c2f-11ea-9e81-f7e3cf3703d6.png"> <img width="200" alt="Screen Shot 2020-05-22 at May 22 1 24 03 PM" src="https://user-images.githubusercontent.com/1119271/82702616-8e1eca80-9c2f-11ea-8337-796783c9ecc6.png">
