### ISSUE TITLE
[GlobalStep] [iOS] Application fails to display Buttons and Cover Blocks upon switching from Block editor to Classic editor and in vice-versa it displays "Problem displaying block".

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2293]
**Environment:**
iOS- iPhone 8 (v13.4.1), iPhone 11 pro (v13.2.2), iPhone XS (v13.2.2).
Build[version]: v14.9

**Steps To Reproduce:**
  1. Install and launch the application.
  2. Tap on "Log In".
  3. Log in to the app using valid credentials.
  4. Go to My site and tap on "Pages" icon.
  5. Go to Drafts and tap on "CREATE A PAGE" button.
  6.  Enter any text at title.
  7. Now from footer tap on "+" symbol to add Buttons and Cover.
  8. Tap on (More)three dots buttons.
  9. Tap on Switch to Classic editor.
 10. Note that it fails to display Buttons and Cover blocks instead displays a line under the button's text.
 11. Again Tap on (More)three dots buttons.
 12. Tap on Switch to Block editor. 
 13. Observe that now it displays "Problem displaying block".

**Actual Result:**
Application fails to display Buttons and Cover Blocks upon switching from Block editor to Classic editor and in vice-versa it displays "Problem displaying block".

**Expected Result:** 
 Application should support buttons and Cover block irrespective of the editor it's viewed in. 

**Attachment:**
[#2293.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663118/2293.zip)

**Comment by designsimply** [comment]
Screenshots from the attached videos:

<img width="200" alt="Screen Shot 2020-05-22 at May 22 2 19 31 PM" src="https://user-images.githubusercontent.com/1119271/82706636-5287fe80-9c37-11ea-8f98-09b18ab59e09.png"> <img width="200" alt="Screen Shot 2020-05-22 at May 22 2 19 41 PM" src="https://user-images.githubusercontent.com/1119271/82706633-4ef47780-9c37-11ea-951c-e079c9891097.png">

**Comment by designsimply** [comment]
This issue is very similar to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2282 so let's close this one in favor of consolidating this problem to one issue.
