### ISSUE TITLE
[GlobalStep] [iOS] Application malfunctions after editing/renaming buttons upon adding an image in cover block while creating a blog.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2294]
**Environment:**

iOS: iPhone 8 (v13.4.1), iPhone 11 pro(v13.2.2).
Build[version]: v14.9

**Steps To Reproduce:**
  1. Install and launch the application.
  2. Tap on "Log In".
  3. Log in to the app using valid credentials.
  4. Tap on MySite .
  5. Now Tap on "+" to create a blog post.
  6. Enter any text at title.
  7. From footer tap on "+" symbol to add Add Cover without adding any image.
  8. Add two buttons & rename it.
  9. Now add image from free photo library(Eg. Sunrise).
 10. Observe that application malfunctions/haywires when user uploads an image in cover block. 

**Actual Result:**
Application malfunctions after editing/renaming buttons upon adding an image in cover block while creating a blog.

**Expected Result:** 
Application should smoothly display cover block and buttons. 

**Attachment:**
[#2294.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663139/2294.zip)

**Comment by designsimply** [comment]
Short gif pulled from the attached video:

![2294](https://user-images.githubusercontent.com/1119271/82707195-cecf1180-9c38-11ea-9b8e-4df61b840a13.gif)

**Comment by designsimply** [comment]
Closing in favor of consolidating to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1696. Great to have additional examples of this and steps to reproduce!
