### ISSUE TITLE
[GlobalStep] [iOS] "Get in Touch" button is misaligned as well as "Exclamation point symbol" is missing from "Let's build something together" text in default page templates for "About" and "Services" .

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2295]
**Environment:**
iOS: iPhone 8 (v13.4.1), iPhone 11 pro(v13.2.2), iPhone XS (v13.2.2).
Build WPiOS [version]: v14.9

**Steps To Reproduce:**
1. Tap on Site Pages option.
1. Tap on Add page "+" icon.
1. Select About/Services page template and tap on apply button.
1. Tap on Publish button.
1. Note that confirmation Pop-up appears tap on "Publish".
1. Now tap on three dots symbol and tap on view option.
1. Observe that "Get in Touch" button is not centrally aligned and" Exclamation point symbol" also missing with this "Let's build something together "text.
 
 Note: Compared the template with this link.
 Link: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2168#issuecomment-616857093

**Actual Result:**
Default page templates for "About" and "Services", "Get in Touch" button is not displayed centrally aligned as well as "Exclamation point symbol" is missing from "Let's build something together" text.

 **Expected Result:**
Default page templates for "About" and "Services", "Get in Touch" button should be centrally aligned and "Exclamation point symbol" should be present with "Let's build something together" text on respective page.

**Attachment:**
<img src="https://user-images.githubusercontent.com/41110392/82573007-d6dc7200-9ba2-11ea-9267-e0da7be3045e.jpg" width="200" alt="#2295">

**Comment by mkevins** [comment]
Resolved in https://github.com/WordPress/gutenberg/pull/22620 :tada:
