### ISSUE TITLE
Button: Toolbar goes up and down for a split second when dismissing settings

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2301]
**To Reproduce**
1. Add a Button
2. Click on Button block settings
3. Focus on URL field
4. Close the Bottom sheet by tapping outside of it

Result: Toolbar goes up and down detaching from the keyboard for a split second

**Expected behavior**
Toolbar stays on the keyboard

**Screenshots**

![May-22-2020 12-48-08](https://user-images.githubusercontent.com/5032900/82655223-86a8f280-9c2a-11ea-8336-eec4fd6caece.gif)

**Smartphone (please complete the following information):**
 - Device: iPhoneXS
 - OS: iOS 13
 - Version WordPress iOS 14.8

**Comment by chipsnyder** [comment]
Discovered an error as part of the original fix for this. Reverted the original change here (https://github.com/WordPress/gutenberg/pull/24388) and reopening to re investigate.
