### ISSUE TITLE
Posts loading very slowly for a Google phone with Japanese input

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2320]
> I used Google Japanese input and Pixel 3a, but this application was useless. When I try to edit a post, it takes a long time to load it after tapping it, which is frustrating. I can't understand why it is so highly evaluated. Sakura? ? ?

* 1-star app review May 22, 2020 at 11:11 PM
* Device: Pixel 3a (sargo)
* OS: Android 10
* WPAndroid: 14.8

Needs further investigation followed by a reply to the app review.

**Comment by hypest** [comment]
There's already a ticket tracking the slow loading performance issue (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1888). The report here doesn't seem to add more context than already known so, may I suggest closing the ticket and adding the report as a comment in the older ticket?

**Comment by designsimply** [comment]
That makes sense to me. Closing as a duplicate in favor of https://github.com/wordpress-mobile/gutenberg-mobile/issues/1888.
