### ISSUE TITLE
A more reliable communication mechanism between the main apps and the RN app

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2325]
Let's investigate if we can make a more reliable communication mechanism between the main apps and the RN editor.

Currently we know that some events can fall through cracks if they are fired during the time editor is bootstrapping. This is causing such bugs:

https://github.com/wordpress-mobile/gutenberg-mobile/issues/2041

https://github.com/wordpress-mobile/gutenberg-mobile/issues/1928

**Comment by chipsnyder** [comment]
Just as an FYI here is an interesting find from React-Core 

https://github.com/facebook/react-native/blob/1fa3a8e4752fb7b34aaa8b464d7a678427f65ed4/React/Modules/RCTEventEmitter.m#L67

There is then this logic at the bridge that attempts to send the events after the bridge has loaded https://github.com/facebook/react-native/blob/master/React/CxxBridge/RCTCxxBridge.mm#L1236-L1273

This is just the iOS side so far but I'm exploring working around these areas to see if there is something we can tweak here.

**Comment by mkevins** [comment]
Hi @chipsnyder :wave: :smile: 

> There is then this logic at the bridge that attempts to send the events after the bridge has loaded wich seems like if allowed to run would solve some of our issues (probably not all though)

Is this `_loading` state referring to the JS runtime initialization state? I guess we will need to wait until after all the components with listeners have mounted, so even with eventEmitter calls queued / batched over the bridge during editor startup, we'll need to make sure all the blocks have mounted first (so sometime after the initial content is parsed and blocks various components are instantiated).

**Comment by pinarol** [comment]
I see that all the PRs are merged, I think we can close this issue. Let me know if something is pending.
