### ISSUE TITLE
Insert block button adds duplicate blocks once switch to html view and back

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#233]
- Tap "View html output" switch twice on the demo app
- Insert a new block
- Notice that same block is added twice

![insert_block_duplicate](https://user-images.githubusercontent.com/5032900/48413733-addf5380-e759-11e8-9cfd-8ea34005e668.gif)

**Comment by etoledom** [comment]
This issue was fixed with the change to Gutenberg Store.
via https://github.com/wordpress-mobile/gutenberg-mobile/pull/226
