### ISSUE TITLE
Show "Add to beginning" and "Add to end" option for all blocks when long-pressing the inserter button

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2344]
We've heard from users that adding a block to the end of a very long post or page is a challenge. We already have the option to add a block to the beginning or end of a post/page via a long-press on the inserter button while the post/page title is selected, but we should consider adding it to all blocks regardless of which block is selected.

Here is an example — title selected on the left, and a block in the post/page body selected on the right, with some arrows proposing where we'd place the new buttons:

<a href="https://user-images.githubusercontent.com/1200432/83578709-1426f500-a4fd-11ea-8d7b-b16602a53180.png"><img src="https://user-images.githubusercontent.com/1200432/83578709-1426f500-a4fd-11ea-8d7b-b16602a53180.png" width="1357"></a>

cc @hypest @ceyhun

**Comment by guarani** [comment]
> We already have the option to add a block to the beginning or end of a post/page via a long-press on the inserter button while the post/page title is selected, but we should consider adding it to all blocks regardless of which block is selected.

@iamthomasbishop just to clarify, since we also have the beginning/end options available when _no_ block is selected, will we now be showing these options in all circumstances when the user long-presses the inserter button? (That is to say, if any of the following are true: the post title is selected, no block is selected, any block selected.)

**Comment by iamthomasbishop** [comment]
> will we now be showing these options in all circumstances when the user long-presses the inserter button?

That's correct 😄

**Comment by AmandaRiu** [comment]
Hey @iamthomasbishop 👋 I'm working on this task item and have found that the current version of the app now includes icons for these options and both the "Add to [beginning|end]" and "Add block [before|after]" options share the same icons:

Beginning / End | Before / After
-- | --
![Screenshot_1611692523](https://user-images.githubusercontent.com/5810477/105913441-d5e5c500-5ffa-11eb-92f9-a5309192986f.png)|![Screenshot_1611692472](https://user-images.githubusercontent.com/5810477/105913445-d716f200-5ffa-11eb-80d1-f486bade27c8.png)

Do you want me to use different icons to differentiate between the options when all of them are displayed at the same time?

**Comment by iamthomasbishop** [comment]
@AmandaRiu For now, let's use those existing icons (with the lines on top/bottom) for the beginning/end and use the the (+) icon (aka `plusCircle` for both above and below. Example:

![image](https://user-images.githubusercontent.com/1200432/106181962-da79bd00-6163-11eb-80bf-d17871e92a91.jpeg)

As for the long-term, we might want to add custom icons for above/below — something like this, for example:

![image](https://user-images.githubusercontent.com/1200432/106182867-12353480-6165-11eb-90e2-69e10f5301ea.jpeg)
