### ISSUE TITLE
Issues with translated words of the templates in Portuguese-Brazil.

### ISSUE THREAD

**Issue by gpxlqa** [wordpress-mobile/gutenberg-mobile#2351]
**Describe the bug**
When I use the app in Portuguese-Brazil some words of the templates of pages are translated in Portuguese-Brazil and others words are in English.

**To Reproduce**

**Pre-conditions**
1. The language of the application must be in Portuguese-Brazil.

**Steps to reproduce**
1. Click on Pages;
2. Click on button to create a new Page;
3. Some words of the template selection buttons are in english and others words are in Portuguese-Brazil. 

**Expected behavior**
All words must be in Portuguese-Brazil.

**Screenshots**
![Screenshot_20200604-153348](https://user-images.githubusercontent.com/6579591/83797669-642ac680-a679-11ea-89dd-35ea7b4f3574.png)

**Smartphone (please complete the following information):**
 - Device: Samsung A5 2016
 - OS: Android 7.0

**Comment by maxme** [comment]
Hi @gpxlqa thanks for you contributions. The apps and the block editors are open source projects. The translations for the block editor are managed by the community on a GlotPress website.

You can help translate the project by doing suggestions on the [missing strings for Portuguese Brazil here](https://translate.wordpress.org/projects/wp-plugins/gutenberg/stable/pt-br/default/?filters%5Bterm%5D=&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)

**Comment by maxme** [comment]
Re-opening this one, after investigation, it seems that some gutenberg mobile strings are excluded from the app translations if they are also present in the web version.

This is likely to be an issue with [` --subtract=./gutenberg.pot` here](https://github.com/wordpress-mobile/gutenberg-mobile/blob/ec775dd39491cfc72b593788bf3226358aabb4f8/package.json#L84-L85). If we exclude all the strings from Gutenberg Web but some are duplicates in the native.js files, we would not get them in the apps.

**Comment by antonis** [comment]
Closing this issue since the templates inside the editor have been deprecated
