### ISSUE TITLE
Editor crashes on media upload for some page layouts

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2367]
**To Reproduce**

Create a Page
Apply "Services" starter page layout
Add gallery block
Select 3 images from the device library and let it upload
Notice the gutenberg crashes 

**Screenshots**

<img src="https://user-images.githubusercontent.com/2261188/84259362-a7bd7e80-ab18-11ea-9600-93c407610610.png" width="200px" />

**Smartphone (please complete the following information):**
Reproducible on both Platforms 
 - Device: Huawei p20 lite, iPhone XS
 - OS: Android 9, iOS 13.5
-  [1.30.0 release candidate](https://github.com/wordpress-mobile/WordPress-Android/pull/12141 ) 

Not reproducible in the previous gutenberg-mobile versions.

**Additional context**
It happens on Image block as well, so it looks related with uploading. 
Does not happen on every starter page layout, but I was able to see this on About, Portfolio, Services, Team

**Comment by SergioEstevao** [comment]
Solved on release 1.30.0
