### ISSUE TITLE
Cannot split block after prepending to word

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#2372]
### Describe the bug

On Android only, adding a character in front of a word in a paragraph block and then pressing enter results in a new line instead of splitting the block.

![paragraph_split_newline mp4](https://user-images.githubusercontent.com/4656348/84394558-1a873200-abcb-11ea-9565-028f200fe116.gif)

### To Reproduce

1. Add multiple words to a paragraph block
2. Place the cursor directly in front of one of the words and type one or more characters
3. Press Enter (your cursor should be in the middle of a "single" word composing the word that you placed the cursor in front of and the word you just typed)
4. Observe that the paragraph block was not split and instead a new line was entered

## Expected behavior

Pressing Enter within a paragraph block should always split the block.

## Smartphone
 - Device: Pixel 1
 - OS: Android X
 - Version: 1.30 release testing (c2a85e0)

**Comment by guarani** [comment]
Can reproduce on WPAndroid 15.2.1 using the Gboard keyboard. The bug isn't present when using the Samsung keyboard.

**Comment by AmandaRiu** [comment]
This appears to be fixed as of `1.57.0`. Tested on a physical Pixel 4 running android 11 with Gboard:


https://user-images.githubusercontent.com/5810477/125340557-97ca2c80-e320-11eb-8bd7-a93af1790112.mp4

closing 👍
