### ISSUE TITLE
Pasting external content

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#238]
Let's make sure we test pasting contents from another app and evaluate what we need to fix for the beta.

> Customer research has reveled that most people at least start their draft elsewhere

So far, pasting multiple paragraphs of text on iOS works visually, but:
- [x] they're not split into separate paragraphs
- [x] the block doesn't resize to fit the content until you type #438
- [ ] since I was pasting from a website, it inherited the custom font size. Should "Paste and match style" be the default for Gutenberg?

**Comment by koke** [comment]
@daniloercoli @diegoreymendez as you work on split/merge, try to do some tests pasting content and log the issues here

**Comment by hypest** [comment]
I think this ticket involves work on multiple levels so, allow me to split it up in smaller targets that might help us tackle it in steps:

# Target 1:
Be able to paste multi-paragraph *simple text* and having it split into multiple blocks. Think: copy multiple paragraphs of text that doesn't include rich text whatsoever (like bold/italics/headings/etc). Will need effort on Aztec (native) and RN the least.

# Target 2:
Be able to paste multi-paragraph *rich-text*. Think: paragraphs, headings, bold, italics. Blocks should pick up the styling from each of the copied sections. Will need effort on Aztec (native) and RN the least.

# Target 3:
Be able to paste rich-text along with images and more. Think: Targets 1, 2 plus images, unsupported blocks. Will involve effort on all layers (Aztec, RN, WP apps). Images pasted will need to get uploaded on the spot.

**Comment by diegoreymendez** [comment]
Closing.  Let's open issues for any pending work.
