### ISSUE TITLE
Media-Text: Remove the block type limitation when adding blocks

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2386]
Currently the block types that can be added inside Media-Text is quite limited. It was limited because the inner blocks UI was not mature enough by the time. But I expect that the current state of InnerBlock component is able to handle this.

So let's enable all the blocks to get added into Media-Text and see how it is playing with different type of blocks: especially Group, Columns, Buttons, Cover etc.

**Comment by antonis** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/23456
