### ISSUE TITLE
Expose focus() and blur() API in order to get working keyboard dismiss functionality

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#240]
Currently, we can't use RN `Keyboard.dismiss()` API as we are missing `focus()` and `blur()` API on the Aztec level.

**Comment by koke** [comment]
Added this to the alpha milestone, but not a blocker. If it doesn't make it in time, we'll disable the button to hide the keyboard until this is ready

**Comment by koke** [comment]
This one seemed to be working fine, should we close it?
