### ISSUE TITLE
Crash when removing an inner block from a specific content

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2409]
**To Reproduce**
1. Create a new post with [this html](https://cloudup.com/c0XSbi5S7Yj) << Can't repro with another content so there must be something in that html triggering this.
2. Select the image inside the Columns block
3. Remove the image
4. See crash

**Expected behavior**
No crash

**Screenshots**
See [screen recording](https://drive.google.com/file/d/1P4fqen3eAQ2TT9iKiQOYBMCAwI7pvk2e/view?usp=sharing)

**Smartphone (please complete the following information):**
 - Device: iPhoneXS
 - OS: iOS 13.5
 - WPiOS 15.1

**Comment by iamthomasbishop** [comment]
@pinarol Thanks for adding this ticket! I was testing this again and realized that I am able to reproduce when I create a new page using the "Services" layout — _which the page HTML above is based on_ — so maybe this stems from something in that layout's HTML specifically.

**Comment by pinarol** [comment]
Solved with https://github.com/WordPress/gutenberg/pull/23352
