### ISSUE TITLE
Preview seems to be hanging while previewing a draft

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2411]
**Describe the bug**
While testing Buttons block - The newly created Buttons has set background color to the theme-default color in preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc021) I ran into an issue where the preview is hanging for one of my test sites (verified that this is working on a 15.1 test build)

**To Reproduce**
1. Open a draft
2. Open Preview for a post

**Screenshots**
<table><tr><td><img width=300 src="https://user-images.githubusercontent.com/3384451/85166313-18f5e380-b235-11ea-847f-fe8849bc2125.png"/></td></tr></table>

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.5

**Additional context**
This might be related to https://github.com/wordpress-mobile/WordPress-iOS/issues/14220 however for this same site and post I was able to load the preview in WPiOS 15.1 beta. 

- This is also working on Android

**Comment by hypest** [comment]
👋 @chipsnyder , what's the WPiOS version/hash you notice the issue on?

**Comment by chipsnyder** [comment]
Hey @hypest I tested this against `develop` => `053837669740bc7015587fe2d3bebf6547d5ef53` 
but I originally discovered this while testing `try/after-monorepo` => `b359cee7aab4635774ec10c4871c571cf1a34aba`

**Comment by hypest** [comment]
@etoledom is working on a User-Agent fix that we think will fix this issue too.

**Comment by etoledom** [comment]
This seems closely related to the issue fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/14360
We can close this one and re-open if it happens again.

Since it was a hotfix, the code still hasn't landed to `develop` but it should soon.

**Comment by chipsnyder** [comment]
Closing this based on @etoledom comment [above](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2411#issuecomment-648281441)
