### ISSUE TITLE
Add API Endpoint containing the current with starter page layouts

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/gutenberg-mobile#2413]
Currently we ship Gutenberg Mobile with a set of Starter Page Layouts. 

Found in https://github.com/WordPress/gutenberg/tree/8fc02a040d4f453e5a57d1e359cf84d1c319bfa6/packages/block-editor/src/components/page-template-picker/templates

We want to introduce many more layouts and want the that list to grow. 

Lets create a new api endpoint that contains the current layouts that we have. 

The layouts that we should offer are
About, Contact, Portfolio, Service, Team

**Comment by pinarol** [comment]
@enejb Can you clarify below items to finalize the 'definition of done' for this task:

- Are we copying [all the existing mobile layouts](https://github.com/WordPress/gutenberg/tree/8fc02a040d4f453e5a57d1e359cf84d1c319bfa6/packages/block-editor/src/components/page-template-picker/templates) to backend in this task? 
- What's the process of copying? Manual or automated? 
- What should the backend copy look like?
- What's the plan for translating the strings for this particular task?

Thanks!

**Comment by pinarol** [comment]
Another thing we should make sure is using the most up to date versions of the templates, currently they are in the repo: https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/page-template-picker/templates

**Comment by enejb** [comment]
Done when

1. All existing layouts are copied to back-end. 
2. Translation of layouts
3. Partial translations (part by part) (every sentence will be translated se). 
4. Request/Response model will be approved by chip. 
5. Thumbnails should be in the correct size according to the device's scale.  
6. In production.

**Comment by enejb** [comment]
I am marking this as done. 

Since I deployed D45124-code

The request/response model was approved by @chipsnyder. 
We will make any changes as required in future PRs. 

And the endpoint is now available in production. 
See:
<img width="1702" alt="Screen Shot 2020-06-24 at 4 42 42 PM" src="https://user-images.githubusercontent.com/115071/85578030-0b2bce00-b63a-11ea-81d6-a6dc2557cc2b.png">

**Comment by GhBsx-png** [comment]
Is this ok now? Thank you for your help!
