### ISSUE TITLE
Gallery Settings: You should show the currently selected option and settings label before you change.

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/gutenberg-mobile#2428]
**Describe the bug**
Currently when you are editing the gallery options such as Link to or Image Size. 

There is no indication what is selected or what option you are editing. 

See:
<img width="651" alt="Screen Shot 2020-06-25 at 10 28 54 AM" src="https://user-images.githubusercontent.com/115071/85685062-fc432b00-b6ce-11ea-8cb9-4ed9ea7781b6.png">

Is that intended? 

My proposal would be to provide a title and display the setting. In order to make it more clear what the setting is that we are changing. 
As well as a checkmark next to the currently selected value so that we know what he current value of the setting is. 

**To Reproduce**
1. Add a gallery block. 
2. Choose the gear icon to get to the gallery settings. 
3. Click on "Link to"

**Expected behavior**
An indication that that you are editing the "Link to" setting as well as the current selection. 

**Screenshots**
<img width="651" alt="Screen Shot 2020-06-25 at 10 28 54 AM" src="https://user-images.githubusercontent.com/115071/85685062-fc432b00-b6ce-11ea-8cb9-4ed9ea7781b6.png">

**Comment by pinarol** [comment]
It should be possible to put a title to the action sheet but it will take some extra space and I am not sure if it is worth it. And plus, Android doesn't have it so it'll require a different development. TBH, I think we don't need to worry about this much, the action sheet component is integrated in the editor almost from the beginning and it is displayed in multiple places. We haven't heard any complaints about what is being edited is not clear. Not sure what @iamthomasbishop thinks about it though.

**Comment by iamthomasbishop** [comment]
I think adding a descriptive header to the top of the actionSheet would be worthy usage of the space, so I'd be fine with adding one. However, I think there is some on-going work on the link settings (by @mkevins) so it might not make sense to implement something here that'll be overridden with any of that work. If we _do_ decide to add a header to the sheet here, we should add it as a small section title on the Android bottom sheet.

**Comment by antonis** [comment]
Closing this issue as the selection is more clear with the new Gallery block implementation with nested images. Please reopen if that is not the case.
