### ISSUE TITLE
Media Text: Failed to insert media overlay has icon that is different colour from text

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/gutenberg-mobile#2429]
**Describe the bug**
The current icon in the Failed to insert media overlay is light blue. Is that intended. 

See:
<img width="655" alt="Screen Shot 2020-06-25 at 10 36 25 AM" src="https://user-images.githubusercontent.com/115071/85686041-e97d2600-b6cf-11ea-8274-06c2e689e1ca.png">

**To Reproduce**
1. Insert media text block. 
2. Upload an image. 
3. Disconnect the phone from the internet. (Flight mode)

**Expected behavior**
I am expecting the icon to be the same colour as the text. (White) 

**Screenshots**
<img width="655" alt="Screen Shot 2020-06-25 at 10 36 25 AM" src="https://user-images.githubusercontent.com/115071/85686041-e97d2600-b6cf-11ea-8274-06c2e689e1ca.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13
 - Version 1.31

**Comment by antonis** [comment]
Hello @iamthomasbishop 👋 
Should I leave the icon in the Failed to insert media overlay light blue or change it to the same colour as the text?

**Comment by antonis** [comment]
This is already handled by https://github.com/WordPress/gutenberg/pull/22788

**Comment by iamthomasbishop** [comment]
> Should I leave the icon in the Failed to insert media overlay light blue or change it to the same colour as the text?

@antonis I believe it can be changed to the same color as the text label.
