### ISSUE TITLE
[Modal Layout Picker] Enable the new Layout Picker for release

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2447]
### Is your feature request related to a problem? Please describe.
This task is part of the effort to rework the Starter Page Template Picker for new pages. This should be the last issue of this [project](https://github.com/wordpress-mobile/gutenberg-mobile/issues?q=is%3Aissue+is%3Aopen+%5BModal+Layout+Picker%5D). Once we've completed enough of the tasks and have successfuly are ready to release the new Layout Picker to production, we should revist the feature flags added as part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2419 and set those to be enabled for release (or consider removing the flag completely). 

### Goals
+ The work done as part of the [Modal Layout Picker project](https://github.com/wordpress-mobile/gutenberg-mobile/issues?q=is%3Aissue+is%3Aopen+%5BModal+Layout+Picker%5D) should be enabled for release. 
+ Feature Flags should be cleaned up from the code. 

### Additional context

<details>
<summary>Blueprint Flow - iOS</summary>
<img src="https://user-images.githubusercontent.com/3384451/85329020-bce2c780-b49f-11ea-88f3-5db30c13af03.jpg" />
</details>

<details>
<summary>Blueprint Flow - Android</summary>
<img src="https://user-images.githubusercontent.com/3384451/85889853-40f7c080-b7ba-11ea-819b-21f075afc772.jpg" />
</details>

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/13190 and https://github.com/wordpress-mobile/WordPress-iOS/pull/15138
