### ISSUE TITLE
[Modal Layout Picker] Add analytics metrics for the layout picker

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2454]
### Is your feature request related to a problem? Please describe.
This task is part of the effort to rework the Starter Page Template Picker for new pages. This part of the initiative will focus on adding analytics metrics to the layout picker's actions. We'll want to be able to track when a template is previewed and as well as when it is applied.

### Goals
+ Editor analytics session should include `template` if a layout is applied
+ `(wpios_wpandroid)_editor_session_template_apply` should fire with the property `template` filled out with the template `slug` when a page is created from a given template.
    + This should fire when a page is created without previewing as well after a template is previewed and then created.
+ `(wpios_wpandroid)_editor_session_template_preview` should fire with the property `template` filled out with the template `slug` when a page is previewed for a given template.

### Additional context

<details>
<summary>Blueprint Flow - iOS</summary>
<img src="https://user-images.githubusercontent.com/3384451/85329020-bce2c780-b49f-11ea-88f3-5db30c13af03.jpg" />
</details>

<details>
<summary>Blueprint Flow - Android</summary>
<img src="https://user-images.githubusercontent.com/3384451/85889853-40f7c080-b7ba-11ea-819b-21f075afc772.jpg" />
</details>

**Comment by chipsnyder** [comment]
When getting ready to work on this I noticed a couple of things and I wanted to capture the conversation I had with myself 😄so others could comment on the answers to the self questions I posed. 

Today we [track](https://github.com/wordpress-mobile/WordPress-iOS/blob/2a189fe4035dd1f1ee873652775e70b59857314e/WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift#L750-L755) start time to get information on the editor loading. This is part of a [single editor session ](https://github.com/wordpress-mobile/WordPress-iOS/blob/2a189fe4035dd1f1ee873652775e70b59857314e/WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift#L307). 

### Question 1: Would we want the analytics events above to be tracked as part of that same session?

I would think the answer to this would be yes so we can get a better understanding of the user's flow through the page creation flow. However, I'm not sure if this is necessary.

### Question 2: If we say yes to Q1, what happens if a user cancels out of the page creation flow?

I think we would want to call [`end`](https://github.com/wordpress-mobile/WordPress-iOS/blob/2a189fe4035dd1f1ee873652775e70b59857314e/WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift#L72) with an outcome of `cancel`. 

### Question 3: If we're tracking that we canceled the editor session, do we then also want an event along the lines of _editor_session_template_prompt?

I don't think we'd want to use the start event because that is used to track startup times. But we might be interested to know when users cancel out of the flow. 

### Complication a post hasn't been created yet for these flows.

One complication is the editor uses a Post to set up the editor session and at the point where MLP is on the screen, the post hasn't been created yet. So the path of least resistance would be to not use the same session but we could still work around this problem.

---- 
@pinarol If you have time I was wondering if you had time to give your thoughts to see if you agree with what I have or have other ideas. 

@koke I'm not sure if you're still working on the editor dashboards at all but maybe you have thoughts on this one as well?  

FYI @antonis

**Comment by koke** [comment]
I think your approach sounds fine. Editor sessions were meant to capture the flow from when the editor opens until its closed, so it makes sense to add templates there. The only comment is that `_editor_session_template_prompt` might not be strictly necessary if this is used for all new pages, since you could infer that the template picker was shown in all `post_type=page`/`content_type=new` session starts. Although a dedicated event might make creating funnels a bit easier.

**Comment by pinarol** [comment]
> Would we want the analytics events above to be tracked as part of that same session?

Sorry not sure I understood the question right. Does that mean firing editor_session_start before the editor opens, let's say when the layout selector is displayed? If so, it doesn't sound right to me. Same way, I think we shouldn't fire editor_session_end when user dismisses the layout selector. According to the new flow the editor isn't open yet.

But we should pass the selected layout id to the editor session somehow, if this 'session' serves this purpose and we don't need to change places of editor_session_start/end, then it sounds fine to me to use the same session.

**Comment by chipsnyder** [comment]
> Does that mean firing editor_session_start before the editor opens, let's say when the layout selector is displayed? 

My initial thought was to have the `editor_session_start` event fire once the editor actually started to load so you would get events like: 

`_editor_session_template_preview` then `_editor_session_template_apply` then `editor_session_start`


> Same way, I think we shouldn't fire editor_session_end when user dismisses the layout selector. According to the new flow the editor isn't open yet.

This sounds good to me.

> But we should pass the selected layout id to the editor session somehow, if this 'session' serves this purpose and we don't need to change places of editor_session_start/end, then it sounds fine to me to use the same session.

Based on this and chatting with @koke a bit more it sounds like not associating these events to the editor session would be the way to go. But we do want to make sure the `template` is still passed along to the session.

Thank you both for your help!
