### ISSUE TITLE
Unsupported Block Editor not working on Atomic sites

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#2470]
**Describe the bug**
The Unsupported Block Editor does not work on Atomic sites.

**To Reproduce**
1. On a post that contains a block not supported by Gutenberg Mobile
2. Tap the `(?)` and a bottom sheet is shown
3. Notice there is no option on the bottom sheet for editing the block

**Expected behavior**
The Unsupported Block Editor should work on Atomic sites.

**Screenshots**

**Smartphone (please complete the following information):**
- Android or iOS, any versions

**Comment by mchowning** [comment]
Looks like we forgot to update this PR's milestone. I'll update it to 1.34, which is the next release.

**Comment by guarani** [comment]
Whoops, I actually shouldn't have added a milestone to this because it's an issue, not a PR. So removing it now. Sorry for the confusion.

**Comment by marecar3** [comment]
Hey @guarani should we close this one? Thanks.

**Comment by guarani** [comment]
> Hey @guarani should we close this one? Thanks.

Yes, it's working on Atomic sites as of the current 15.9 release.
