### ISSUE TITLE
Unsupported Block Editor not working on sites where Jetpack is connected to WordPress.com

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#2471]
Related: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2358

**Describe the bug**
The Unsupported Block Editor does not work on self-hosted sites which have Jetpack installed **and** connected to WordPress.com

**To Reproduce**
1. Create a self-hosted site, install the Jetpack plugin and connect it to a WordPress.com account (easily done using https://jurassic.ninja/)
2. Log into the WordPress iOS or Android app and choose the self-hosted site
3. Add a block to a post that is not yet supported on mobile (can be done via web or by adding it as HTML)
4. With the post open in the editor (in Visual Mode), tap the `(?)` button on the unsupported block placeholder
5. When the bottom sheet appears, notice the lack of an option to edit the unsupported block

**Expected behavior**
The Unsupported Block Editor should be available on self-hosted sites, regardless of whether Jetpack is connected or not.
Note: The bug is only present if Jetpack is connected, it's not present if the Jetpack plugin is installed but not connected.

**Screenshots**
<kbd>
<img width="500" alt="Screen Shot 2020-07-08 at 22 02 24" src="https://user-images.githubusercontent.com/1898325/86988693-da35b800-c166-11ea-8771-1ea66d4bf278.png">
</kbd>

**Smartphone (please complete the following information):**
 - Android or iOS

**Comment by hypest** [comment]
For context, it was decided to disable the feature on Jetpack connected sites until we fix the issue of using the wrong cookie to access the site.

**Comment by guarani** [comment]
Once the cookie issue is resolved, it might only be possible to enable the Unsupported Block Editor on sites where Gutenberg (not Classic) is the default editor.

On iOS, the API request that may provide indication of which editor is set as the default is:
https://github.com/wordpress-mobile/WordPressKit-iOS/blob/a06182b86d3c8542c16ce38c765769e1d50b0d5f/WordPressKit/EditorServiceRemote.swift#L5-L19

**Comment by guarani** [comment]
@etoledom @marecar3 I've just been testing [the Android implementation of this](https://github.com/WordPress/gutenberg/pull/24476) and wanted to ask a few questions (asking here instead of on the Gutenberg repo since it's Jetpack/Atomic related and applies to both Android and iOS).

Regarding the self-hosted/Jetpack experience:

1. These PRs allow users to use the unsupported block editor by turning on SSO. Should the app include a message explaining this? Not sure if this was discussed already.
2. Once the user turns on SSO and opens the unsupported block editor, they're presented with a screen to tap to log in:
    
    <details>
    <summary>Screenshot</summary>
    <img alt="Screenshot showing tap to login screen" width="350" src="https://user-images.githubusercontent.com/1898325/91233991-66dd0b00-e700-11ea-9e54-88d320d9cc22.png">
    </details>
    
    Will users understand this screen? I wonder if there's any way to help the user by performing the "log in" action on their behalf, is this possible? 
3. Again regarding the above screen, the "Log in with WordPress.com" button text and icon isn't vertically aligned. Is it worth pinging the Jetpack team to get this centered?
4. On subsequent uses of the unsupported block editor, I noticed the loading screen is now blue and there's some visual glitches (the top nav bar flashes briefly). 

    <details>
    <summary>Screen recording</summary>
    <img width="350"  alt="Screen recording showing visual glitches while unsupported block editor loads" src="https://user-images.githubusercontent.com/1898325/91234565-7d379680-e701-11ea-8003-9ea9d855a41b.gif">
    </details>

Regarding the Atomic experience:
1. I don't see the visual glitches when the unsupported block editor loads (like I did with self-hosted sites), but the loading screen is blue — is that the expected color for the loading screen? AFAIK it used to be white.
2. After turning off SSO on an Atomic site, I could still use the unsupported block editor (not sure how 🤷‍♂️).

Overall, I think this is very close to working, but I'd appreciate your thoughts on the above questions.

**Comment by marecar3** [comment]
> @etoledom @marecar3 I've just been testing [the Android implementation of this](https://github.com/WordPress/gutenberg/pull/24476) and wanted to ask a few questions (asking here instead of on the Gutenberg repo since it's Jetpack/Atomic related and applies to both Android and iOS).
> 
> Regarding the self-hosted/Jetpack experience:
> 
> 1. These PRs allow users to use the unsupported block editor by turning on SSO. Should the app include a message explaining this? Not sure if this was discussed already.
> 2. Once the user turns on SSO and opens the unsupported block editor, they're presented with a screen to tap to log in:
>     
>     Screenshot
>     <img alt="Screenshot showing tap to login screen" width="350" src="https://user-images.githubusercontent.com/1898325/91233991-66dd0b00-e700-11ea-9e54-88d320d9cc22.png">
>     
>    Will users understand this screen? I wonder if there's any way to help the user by performing the "log in" action on their behalf, is this possible?
> 3. Again regarding the above screen, the "Log in with WordPress.com" button text and icon isn't vertically aligned. Is it worth pinging the Jetpack team to get this centered?
> 4. On subsequent uses of the unsupported block editor, I noticed the loading screen is now blue and there's some visual glitches (the top nav bar flashes briefly).
>     
>     Screen recording
>     <img alt="Screen recording showing visual glitches while unsupported block editor loads" width="350" src="https://user-images.githubusercontent.com/1898325/91234565-7d379680-e701-11ea-8003-9ea9d855a41b.gif">
> 
> Regarding the Atomic experience:
> 
> 1. I don't see the visual glitches when the unsupported block editor loads (like I did with self-hosted sites), but the loading screen is blue — is that the expected color for the loading screen? AFAIK it used to be white.
> 2. After turning off SSO on an Atomic site, I could still use the unsupported block editor (not sure how 🤷‍♂️).
> 
> Overall, I think this is very close to working, but I'd appreciate your thoughts on the above questions.

Hey @guarani thanks for testing this one!

Regarding 4. I have changed the color to white and also I have increased a delay in presenting a foreground view so maybe you won't see glitches anymore.

> After turning off SSO on an Atomic site, I could still use the unsupported block editor (not sure how 🤷‍♂️).
Not sure if we are talking about Atomic sites which are wordpress.com or Atomic sites which are self-hosted but connected through Jetpack on wordpress.com, but what would be the difference then comparing to self-hosted sited with jetpack?

I was sure that it's clear to me what is the meaning of the atomic site, but it seems that it isn't 👎 

cc @mchowning and @etoledom.

**Comment by etoledom** [comment]
Thanks @Guarani for the review!

> After turning off SSO on an Atomic site, I could still use the unsupported block editor (not sure how 🤷‍♂️).

This happens because after you successfully load the Gutenberg on the Web View, you already have the necessary auth cookies locally, so Gutenberg will load successfully again. What should happen is that the should be no option to open the Unsupported Block Editor. 

@marecar3 - maybe we haven't modify the capabilities for the Atomic case? Is UBE always enabled on Atomic? It should be exactly the same as Jetpack sites.

https://github.com/wordpress-mobile/WordPress-iOS/blob/cc0eaf2b78ba0edd1dd09668484bbea269598f49/WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift#L916-L919

(On a second thought, we could also check for auth cookies to decide enabling UBE, but I'd leave this for a future enhancement).

**Comment by guarani** [comment]
Thanks for the replies!

> I have changed the color to white and also I have increased a delay in presenting a foreground view so maybe you won't see glitches anymore.

Ok, thanks.

> Not sure if we are talking about Atomic sites which are wordpress.com or Atomic sites which are self-hosted but connected through Jetpack on wordpress.com, but what would be the difference then comparing to self-hosted sited with jetpack?
> I was sure that it's clear to me what is the meaning of the atomic site, but it seems that it isn't 👎

I think one difference between Atomic sites and "self-hosted but connected to WordPress.com via Jetpack" sites is that Atomic sites have SSO enabled by default while "self-hosted but connected to WordPress.com via Jetpack" sites have SSO _disabled_ by default. 

> This happens because after you successfully load the Gutenberg on the Web View, you already have the necessary auth cookies locally, so Gutenberg will load successfully again. What should happen is that the should be no option to open the Unsupported Block Editor.

Thanks for the explanation @etoledom.

**Comment by etoledom** [comment]
Closed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/2542 and https://github.com/wordpress-mobile/gutenberg-mobile/pull/2610
