### ISSUE TITLE
Additional starter page layouts for mobile

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2502]
Let's add some more layouts for mobile users. By doing this:

- We'll have a safe set of mobile layouts which we have full control on.
- .org users will be able to use them as well and their layout picker won't look that empty after all. :)
- There's always a possibility .com layouts change in a way that doesn't look well on mobile, we may need to hide some .com layouts in the future because of this. In such a case we won't need to worry much if we have our own set.
- We can compare their usage with .com ones and see our users' preference on mobile.

**What should we add?**

I am highly open to suggestions on this. My initial idea is:

- Add +1 layouts to each of the existing categories
- Add a new Homepage category and +2 layouts in it
- Make the new layouts more lightweight compared to .com ones. Shorter content, less places to edit, maybe less nesting levels etc. 

cc @iamthomasbishop @SylvesterWilmott

**Comment by antonis** [comment]
Closing this as more mobile page layouts have been added.
