### ISSUE TITLE
Feature Request: change block type such as paragraph to heading or quote

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2525]
The following feedback was sent in an app review:

> It's still lacking the option to change block type perhaps from paragraph text to heading or quote etc.
> 
> <sup>1-star app review by Oscar Obians Jul 23, 2020 at 4:32 AM - WPAndroid 15.3-rc-2 OnePlus3 Android 10</sup>

<sup>(internal reference: play-store-feedbackid=gp:AOqpTOEW6IqilTJihC7rxUrHs1k4Xa6nHWjwgwyIkqY7IHaplvhf3jD9nW5rOnBmAnQj-DIxIQh5Qrpq9tmDmxvE)</sup>

@SergioEstevao @mchowning do you think we should break this request out per-block so they are easier to work with from a developer perspective?

**Comment by SergioEstevao** [comment]
No need to split it out for each block, the transform feature when implemented will be across all blocks.

**Comment by mchowning** [comment]
We're currently planning to start work on this at the end of August! 😁

**Comment by guarani** [comment]
This came up in an App Store review (emphasis mine):

> Please bring ALL of the functionality for the block editor to the iPad app or restore the classic editor. **It is not possible to take a paragraph (text) and convert it to a header.** However, you can do that in Safari. Also, where is the block type “classic”? Answer: it is missing from the app. Fixing the app or restoring the classic will result in 5 stars. Thanks!

**Comment by mchowning** [comment]
I believe this work is complete. Can you confirm (and close this issue if it is) @illusaen ?

**Comment by guarani** [comment]
Thanks for the reply @mchowning! I was still on 17.1 so I hadn't noticed it, I upgraded to 17.2 and can now see it! 😎 

@illusaen, it looks like this feature didn't make it into 17.2 release notes. I can see release notes were part of https://github.com/wordpress-mobile/gutenberg-mobile/pull/3321, but that seems to have been closed without merging.

**Comment by illusaen** [comment]
Yep it is in. Unfortunately the release notes were merged early so removed and never got readded back in :( 

Closing since functionality should be there now at least!

**Comment by guarani** [comment]
The most important thing is that we now have block transforms! :yay:

**Comment by mchowning** [comment]
> Yep it is in. Unfortunately the release notes were merged early so removed and never got readded back in :(

What would you think about opening a PR to add this release note back in @illusaen ? I realize it won't be included in the release, but at least we'll have it available in the repo in case someone ever wants to look back and see when this feature went out.

**Comment by illusaen** [comment]
> What would you think about opening a PR to add this release note back in @illusaen ?

@mchowning  Sure! Should I add it to both iOS and Android in the native repos or in gb-mobile?

**Comment by mchowning** [comment]
My inclination would be to update the release notes in all 3 repos.
