### ISSUE TITLE
Increase tap-target of primary action on unsupported blocks

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2567]
## Problem

As we've been rolling out the UBE (unsupported block editing) mechanism, we have received feedback that it's not immediately obvious that you can edit _any_ unsupported block using the UBE mechanism.

To be clear, _some level of friction is intentional_ -- we definitely don't want to aggressively encourage users to do this unless they very much need to, because this is our first experiment at an unsupported block-editing flow, so until we are certain that this is the path worth continuing on, we have kept with a conservative approach with regards to how this feature is surfaced and promoted in the editor UI. With that said, I think there is some room to make the entry point a bit more clear without drawing _too much_ attention.

## Current

Currently, an unsupported block is displayed as a placeholder on the canvas. It contains a text label of "Unsupported" and a (?) icon-button (44px tap-target) intended to direct people to more information. When they tap this (?) icon, we display a bottom sheet with informational text and a button to edit the block in the in-app web browser. When they tap to edit, we launch the in-app browser with that specific block loaded in the web editor. Here are some screenshots of the current flow:

| **Selected** | **Informational Sheet** | **In-app editor** |
| --------------- | --------------- | --------------- |
| <a href="https://user-images.githubusercontent.com/1200432/90937048-2877e100-e3cc-11ea-8619-a4a8a3d22b31.jpeg"><img src="https://user-images.githubusercontent.com/1200432/90937048-2877e100-e3cc-11ea-8619-a4a8a3d22b31.jpeg" width="375"></a> | <a href="https://user-images.githubusercontent.com/1200432/90937019-1bf38880-e3cc-11ea-9744-5e8c918f90e9.jpeg"><img src="https://user-images.githubusercontent.com/1200432/90937019-1bf38880-e3cc-11ea-9744-5e8c918f90e9.jpeg" width="375"></a> | <a href="https://user-images.githubusercontent.com/1200432/90936991-0e3e0300-e3cc-11ea-9869-d4091d3a64a8.jpeg"><img src="https://user-images.githubusercontent.com/1200432/90936991-0e3e0300-e3cc-11ea-9869-d4091d3a64a8.jpeg" width="375"></a> |

## Proposal

<a href="https://user-images.githubusercontent.com/1200432/90937823-4560e400-e3cd-11ea-8f7e-0344b00e2305.png"><img src="https://user-images.githubusercontent.com/1200432/90937823-4560e400-e3cd-11ea-8f7e-0344b00e2305.png" width="800"></a>

Rather than add any new UI like a button or strong text label, let's first try increasing the tap target that launches the informational bottom sheet to cover the entire block.

With this change, I think we will want to change the logic so that you first have to select the block before the tap target becomes "active", which follows some other similar blocks like the Latest Posts block, and most importantly, the select-first interaction gives the user the other block controls such as movers and the overflow (•••) menu.

cc @maxme @hypest @etoledom @marecar3 -- if possible, can we get this one slotted into the next couple of sprints? Happy to answer questions and/or discuss other options as well!

**Comment by maxme** [comment]
> Rather than add any new UI like a button or strong text label, let's first try increasing the tap target that launches the informational bottom sheet to cover the entire block.

I agree, this is tricky. I think that's a good first step and we can see if it has any impact on analytics.

**Comment by guarani** [comment]
Is this ready to move to the backlog @maxme? It looks like @etoledom has already linked to this on the UBE project issue.

**Comment by maxme** [comment]
> Is this ready to move to the backlog @maxme? 

I moved it to "Scheduled".

**Comment by iamthomasbishop** [comment]
Thanks, y'all! ❤️
