### ISSUE TITLE
Can we have a separate initial-html.js for non-core blocks?

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2586]
**Is your feature request related to a problem? Please describe.**

Currently we have only 1 demo content in [initial-html.js](https://github.com/WordPress/gutenberg/blob/master/packages/react-native-editor/src/initial-html.js) and it lives in the gutenberg repo. The downside is, it contains `jetpack/contact-info`, which is a .com block so actually it should be removed from that file. We'll be adding `jetpack/layout-grid` soon and there are more .com blocks along the way so we need to be able to add them in the demo content.

**Describe the solution you'd like**

- [x] Remove `jetpack/contact-info` from [initial-html.js](https://github.com/WordPress/gutenberg/blob/master/packages/react-native-editor/src/initial-html.js)
- [x] Create a separate initial content in the gutenberg-mobile repo for non-core blocks

**Comment by hypest** [comment]
👋 @cameronvoell , please have a quick look at this ticket to see if we can easily add a separate example content file or override the one from Gutenberg. Let me know if this looks too complex after the first look. Thanks!

**Comment by cameronvoell** [comment]
@hypest Yep, will take a look and will let you know if there's any reason it can't be quickly completed. 👍

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/2690
