### ISSUE TITLE
Toolbar "jumps" away from keyboard when hitting enter on Paragraph Block

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#2592]
**Describe the bug**
See video: With the cursor in an empty block, tap the return key: notice that the toolbar "jumps" up and then animates down again, while I would expect it to stay put.

First found here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2588#issuecomment-685085231

**To Reproduce**
Hit Enter in paragraph block many times, when the screen fills up and block is at the bottom of the screen you will see the gap between keyboard and toolbar.

**Expected behavior**
Toolbar should not have a gap between it and keyboard, should look the same as when you hit enter in an article with a single or few paragraph blocks, and not look different when paragraph blocks reach the bottom of the screen. 
**Screenshots**
![jumping-toolbar](https://user-images.githubusercontent.com/1103838/92067965-7b518100-ed5a-11ea-9c1b-bb8a58b87dcd.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone XR, Samsung S10

**Comment by cameronvoell** [comment]
Issue first discovered in GB-Mobile 1.36.0 Release process, however I verified you can recreate the issue in at least one previous version of the editor (1.35.0 in the WP 15.6 Apps on Android and iOS)

**Comment by marecar3** [comment]
This is still reproducible on: 
WP Internal: 15.7
iOS 14
iPhone: 10 XS

**Comment by lukewalczak** [comment]
Hello @marecar3, could you please test if the issue is reproducible on the [upcoming release version](https://github.com/wordpress-mobile/WordPress-iOS/pull/14894)?

**Comment by marecar3** [comment]
Hey @lukewalczak,

I have checked on the latest version and I can't reproduce the issue anymore.

iOS 14
iPhone: 10 XS
