### ISSUE TITLE
Heading Block split and merge adds bold words

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#2593]
**Describe the bug**

Following [TC005 steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md) - Merge multiple blocks: In the test here that involves the Header block, I see some words (randomly) become bold after splitting a Header block.

**To Reproduce**

1. Write (or paste) a Heading with a few lines
2. Set the caret by the half of the heading
3. Press enter two times to create an empty block in between
4. Press back two times to merge everything again.
5. Notice words sometimes become bold

**Expected behavior**
Words should not randomly become bold. 

**Screenshots**
    <img width="300" alt="WordPress for iOS screen recording showing header content become bolded after splitting header block" src="https://user-images.githubusercontent.com/1898325/91902812-4406a580-ec70-11ea-964e-40aa33e8be21.gif">

**Smartphone (please complete the following information):**
-Reproduced on  iPhone SE 2020 with iOS 14 beta 6

**Comment by cameronvoell** [comment]
I was not able to reproduce this on the iPhone 11 emulator running iOS 13.7 or my physical iPhone XR running 13.4 The attached video shows it not working in the example app, but I could not reproduce the issue in the WP App either while testing the 1.36.0 release build. 

![heading-split-ios](https://user-images.githubusercontent.com/1103838/92159928-0bd3a400-ede3-11ea-9b29-8cb58a653236.gif)

**Comment by SiobhyB** [comment]
Verifying that this issue has been fixed since this report, going ahead to close.
