### ISSUE TITLE
Implement x-posting using + trigger character

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#2602]
**Is your feature request related to a problem? Please describe.**

Implement x-posting in WordPress mobile app for sites that have the O2 plugin installed. The `+` character should trigger a dropdown allowing selection of a site from the list of available sites. This doesn't include the UI to add a x-post via the toolbar menu (which is covered by https://github.com/wordpress-mobile/gutenberg-mobile/issues/2612).

**Describe the solution you'd like**

Gutenberg on Calypso uses the https://example.com?get-xpost-data endpoint, which is provided by the O2 plugin.

**Describe alternatives you've considered**

The [/me/sites endpoint on the WordPress.com API](https://developer.wordpress.com/docs/api/1.1/get/me/sites/) returns the user's sites, and is already implemented by the WordPress mobile apps. The downside is that it doesn't perform the additional filtering that the O2 plugin does, so if we were to implement it, we'd have to duplicate logic, e.g.:
- Filter out the current site
- Filter out sites that have incompatible privacy settings
- Any other logic

Leveraging the `?get-xpost-data` allows us to avoid duplicating any of this logic.

**Comment by mchowning** [comment]
> This doesn't include the UI to add a x-post via the toolbar menu.

Do you think we should add a separate issue for adding an x-post via the toolbar menu @guarani (or maybe it's already in an issue and I just missed it)?

**Comment by guarani** [comment]
> Do you think we should add a separate issue for adding an x-post via the toolbar menu @guarani (or maybe it's already in an issue and I just missed it)?

That's a good idea, I created one here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2612

**Comment by guarani** [comment]
Because the `?get-xpost-data` endpoint uses cookie-based authentication which is not widely used by the WordPress mobile apps, we ultimately decided to add a new endpoint which is bearer token based:

```
curl -H 'authorization: Bearer TOKEN_HERE' 'https://public-api.wordpress.com/wpcom/v2/sites/examplesite.wordpress.com/xposts'
```

This endpoint returns an object with of the following format:

```
[
  {
    "blog_id": 123456789,
    "title": "Example Site",
    "siteurl": "https://examplesite.wordpress.com",
    "subdomain": "examplesite",
    "blavatar": "https://examplesite.files.wordpress.com/2020/109/logo.png?w=32"
  },
  ...
]
```

The apps will use this endpoint to fetch x-post suggestions.

**Comment by guarani** [comment]
Closed by https://github.com/wordpress-mobile/WordPress-iOS/pull/15139 (iOS) and https://github.com/wordpress-mobile/WordPress-Android/pull/13184 (Android).
