### ISSUE TITLE
ATM

### ISSUE THREAD

**Issue by Ibrar555** [wordpress-mobile/gutenberg-mobile#2603]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6, Pixel 4]
 - OS: [e.g. iOS 8.1,  Android X]

**Additional context**

**Comment by mchowning** [comment]
👋 @Ibrar555 ! Just checking to see if this issue was opened by accident or if you were planning on filling it out?

**Comment by hypest** [comment]
👋 Thanks for checking with the author @mchowning !

Since in its current state the ticket can be considered as "draft" at best, I will close it as not having enough info/context for now but, @Ibrar555 please feel free to reopen after you add the info required to make the ticket actionable. Thanks!
