### ISSUE TITLE
Mentions UI does not detect lack of internet connection and displays "Loading..." forever

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#2609]
**Describe the bug**
On iOS ~~and Android~~, adding a mention from within Gutenberg when both (a) the list of possible mentions has not been previously downloaded and (b) there is no internet connection, results in a perpetual "Loading..." message.

**To Reproduce**
1. Select a site where mentions have not been downloaded (i.e. a fresh install of the app guarantees this)
2. Disconnect the device from the network
3. Attempt to add a mention from within the gutenberg editor
4. Observe that it displays "Loading..." forever

**Expected behavior**
When mentions are not available and there is no internet connection, we should provide a message that indicates mentions are unavailable instead of "Loading...".

**Screenshots**
![loading_forever mp4](https://user-images.githubusercontent.com/4656348/92745140-198fa900-f350-11ea-9560-e71c7141e70e.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel 1
 - OS: Android X
 - Version: 15.6

**Comment by mchowning** [comment]
Reopening because this has been addressed on Android, but I believe it is still an issue on iOS.

**Comment by guarani** [comment]
I tested the latest version of WPiOS, 16.3, and this issue is no longer present so closing this issue. 
We can track the need to improve the messaging around the suggestions UI on WPiOS app in https://github.com/wordpress-mobile/WordPress-iOS/issues/15148.
