### ISSUE TITLE
Strings from Jetpack are not included in the bundle

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#2615]
**Describe the bug**
When we run our bundle script we are not including strings from jetpack in the resulting bundle.

**To Reproduce**
1. `npm run genstrings`
2. Observe that the strings files (i.e., `bundle/android/strings.xml`) do not contain relevant strings from the jetpack repo: for example, ["Link address to Google Maps"](https://github.com/Automattic/jetpack/blob/f6f313d268c336491c8bca1afcf3e5d3663597ce/extensions/blocks/contact-info/address/edit.native.js#L42)). 

**Expected behavior**
Relevant strings from the jetpack repos should be included in our bundles for translation.

**Comment by mchowning** [comment]
This may actually be a duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2162.

**Comment by fluiddot** [comment]
> 2\. Observe that the strings files (i.e., `bundle/android/strings.xml`) do not contain relevant strings from the jetpack repo: for example, ["Link address to Google Maps"](https://github.com/Automattic/jetpack/blob/f6f313d268c336491c8bca1afcf3e5d3663597ce/extensions/blocks/contact-info/address/edit.native.js#L42)).

The string `Link address to Google Maps` is included in the Jetpack's GlotPress project ([reference](https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/en-gb/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7273954&filters%5Btranslation_id%5D=63471351)), so it's not expected that this string will be part of the localization strings files (i.e. `bundle/android/strings.xml`), as these files only contain the strings that are exclusively referenced in JS native files (i.e. `*.native.js`).

As an alternative example, the string `Address Settings` ([code reference](https://github.com/Automattic/jetpack/blob/f5482ec74bf6bef4d81fe6718efb0dc3e07e9035/projects/plugins/jetpack/extensions/blocks/contact-info/address/edit.native.js#L91)) is one that is only referenced in a JS native file, and besides is already included in the localization strings files ([reference](https://github.com/wordpress-mobile/gutenberg-mobile/blob/74362154680f75935cee557b9d7e1f11ba00df32/bundle/android/strings.xml#L34)).
