### ISSUE TITLE
Request to add the option to type a forward slash `/` to call up a list of blocks and insert one

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2620]
On the web, if you type a forward slash into an empty block it will call up a list of blocks and you can insert a block by typing out it's name or selecting one. Would it be possible to add that option to Gutenberg Mobile?

Chrome on Android|WPAndroid 15.7 beta
---|---
<img src="https://user-images.githubusercontent.com/1119271/93308119-187ed180-f7bf-11ea-8404-3b82197903f4.png" width="270" alt="Screenshot_20200916-014920">|<img src="https://user-images.githubusercontent.com/1119271/93308122-1a489500-f7bf-11ea-8be1-3caf57ed79d4.png" width="270" alt="Screenshot_20200916-014550">

<p style="clear:both;"><sup>Tested with WPAndroid 15.7-rc-3 on Pixel 3 Android 11.</sup></p>

<sup>(Originally reported in beta testing, internal reference: p5T066-1vr-p2#comment-5840)</sup>

**Comment by chipsnyder** [comment]
We ended up taking this on as a HackWeek project and will be wrapping it up as we have time between projects. The current status is being tracked in this PR https://github.com/WordPress/gutenberg/pull/29772
