### ISSUE TITLE
Activate the link button at the end of a string

### ISSUE THREAD

**Issue by kyleaparker** [wordpress-mobile/gutenberg-mobile#2631]
**Describe the bug**
When part of a sentence is a link, it can be difficult to select and change the link. Right now you have to select the text and then you can edit the link. If all the text is a link it's much easier as it only takes one click. I would expect the link button to highlight even if the cursor is at the end of the string. 

**To Reproduce**
1. Write a sentence and add a link to one word in the sentence 
2. Try to change the link by clicking the word
3. The cursor should be at the end of the word but the link button is not active

**Screenshots**
<img width="999" alt="Screen Shot 2020-09-17 at 1 41 00 PM" src="https://user-images.githubusercontent.com/712873/93409648-714b8880-f8eb-11ea-9b31-20d3a3b11f3a.png">

**Expected behavior**
Ideally the link button can be highlighted if the cursor is at the end of the string (no space after it)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.7

cc @iamthomasbishop

**Comment by hypest** [comment]
> I would expect the link button to highlight even if the cursor is at the end of the string.

It's not always clear what the user would prefer to do while the caret is at the end of the styled text. Same holds for any styling actually (bold/italic) where preferences can bounce between expecting the end to belong to the previous style or not. On the web, the editor is solving this problem by introducing a "mode" where the caret can be either in or out of the style without changing position.

I think it could make sense to try to follow that behavior. Just a note here that we'll need to make some non-trivial changes to Aztec (the rich-text component powering all RichText blocks in gutenberg-mobile) to support such behavior.

**Comment by kyleaparker** [comment]
Just noticed we already had an issue for this: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2054. I'll close this one in favour of the existing issue.
