### ISSUE TITLE
Pluralize "Choose Image" heading on Gallery Block 

### ISSUE THREAD

**Issue by kyleaparker** [wordpress-mobile/gutenberg-mobile#2632]
**Describe the bug**
When selecting images for the Gallery Block, the heading on the popup should say "Choose Images" rather than "Choose Image" 
 
**To Reproduce**
1. Add the Gallery Block 
2. Click on 'Add Media'
3. Notice the heading on the popup menu

**Screenshots**
![IMG_D41AB521A108-1](https://user-images.githubusercontent.com/712873/93409929-17978e00-f8ec-11ea-96ac-667b2b11d3d4.jpeg)

@jd-alexander @iamthomasbishop

**Comment by jd-alexander** [comment]
Hi everyone, I plan to work on this ticket next week. I'll keep you updated on the progress when I begin.
