### ISSUE TITLE
[Android] Align slider with the content on the left

### ISSUE THREAD

**Issue by kyleaparker** [wordpress-mobile/gutenberg-mobile#2667]
Sliders on Android aren't aligned with the content on the left. Ideally we can line the slider up with the left of the text:

<img width="453" alt="Screenshot_20200914-232738 png+%2810802160%29+2020-09-23+15-40-21" src="https://user-images.githubusercontent.com/712873/94215861-f2c99900-ff31-11ea-80d1-5b2ac5be3d82.png">

**Comment by guarani** [comment]
Approved via https://github.com/WordPress/gutenberg/pull/25660#pullrequestreview-501459256.
