### ISSUE TITLE
Use a consistent size image selector on image and gallery blocks

### ISSUE THREAD

**Issue by kyleaparker** [wordpress-mobile/gutenberg-mobile#2668]
**Is your feature request related to a problem? Please describe.**
There are two blocks in the editor where you can change the image size, the image block and the gallery block. We are using a different design pattern on each of these blocks when changing the image size. 

1. On the image block you tap through the sizes until you find the one you want

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/712873/94217209-8e103d80-ff35-11ea-89b8-f590dd35b731.gif)

2. On the gallery block we launch a list of options using the bottomSheet

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/712873/94217004-09252400-ff35-11ea-9463-47179db6ac4d.gif)

**Describe the solution you'd like**
We should use the same pattern for both blocks. The bottomSheet selector on the gallery block is more user friendly as you can easily see the full range of image sizes available. 

cc @iamthomasbishop

**Comment by iamthomasbishop** [comment]
@kyleaparker thanks for raising this! We should probably use the Sheet here (which uses native ActionSheet on iOS, RN-based BottomSheet on Android).

I think the Cycle control is also being used in an additional place or two — probably on some block settings sheets, but I can't think of where off the top of my head 🤔

**Comment by SiobhyB** [comment]
This has been resolved now that the Gallery block uses Images blocks, meaning that the same settings UI is accessible for both.
