### ISSUE TITLE
Localization of "color" in the color settings

### ISSUE THREAD

**Issue by kyleaparker** [wordpress-mobile/gutenberg-mobile#2669]
**Describe the bug**
I'm seeing different spellings of the word "Color" depending on my language settings:

<img width="931" alt="Untitled 2020-09-25 14-16-45" src="https://user-images.githubusercontent.com/712873/94219037-f19c6a00-ff39-11ea-81bd-9a5e07f66515.png">

**Expected behavior**
Australia, UK, and Canada English should all use "Colour" 

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro and Pixel 3
 - OS: iOS 14, Android 10

**Comment by SiobhyB** [comment]
I haven't been able to reproduce this in recent testing. The word "colour" was correctly localised when reviewing a few different places it appears within the editor.

<img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/2998162/5f04204f-7d17-47c8-beb8-8af2a781e5a4" width="50%" />

I'm going to go ahead to close this issue as I believe it was fixed as part of unrelated updates. Feel free to re-open if you can still reproduce, though!
