### ISSUE TITLE
Unsupported Block Editor: cannot view or interact with the classic block on Jetpack sites

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2695]
Steps to reproduce:

1. On the web, create a post with a classic block on a Jetpack site (note: I used Jetpack 9.0.1 WordPress 5.5.1 in this test).
1. Save or publish the post.
1. In the app, open the post from the previous step in the block editor.
1. Tap on the classic block.
1. Tap on the classic block again.
1. Select the option to "Edit using the web editor."
1. Observe whether or not you are able to load or interact with the classic block.

**Result:** "This block has encountered an error and cannot be previewed." is displayed for all classic blocks I've tried using a Jetpack 9.0.1 WordPress 5.5.1 site—other types of sites work normally, including WordPress.com Business with plugins, and other types of blocks also seem fine. ([2m27s](https://cloudup.com/cFmYO_gExqY))

<img src="https://user-images.githubusercontent.com/1119271/95390028-f6eea280-08b1-11eb-835a-aed67dfa6c00.png" width="270" alt="Screenshot_20201007-152858"> <img src="https://user-images.githubusercontent.com/1119271/95390037-fa822980-08b1-11eb-9352-308c2cdef2e5.png" width="270" alt="Screenshot_20201007-131715">

<sup>Tested with WPAndroid 15.9-rc-1 on Pixel 3 Android 11.</sup>

**Comment by designsimply** [comment]
@marecar3 as requested via Slack, I've sent you the patient-dwarf.jurassic.ninja and testuser0313 WP.com account login credentials for testing purposes. 👍

**Comment by marecar3** [comment]
Hey 👋 @designsimply 

Here is the potential fix for this issue: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2709
