### ISSUE TITLE
In DEV mode the initial_html content overwrites post content

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2702]
## Describe the bug
When running Gutenberg-Mobile with the metro server the `initial_html` content overwrites the data from the app. 

### Existing Content
1. Start a metro server using the command `npm start`
1. In WPiOS or WPAndroid open the app 
1. Open an existing Page/Post
**Notice** the `initial_html` content has replaced the body of the page/post
**Expected behavior** the content should match what the page/post originally had

### New Content
1. Start a metro server using the command `npm start`
1. In WPiOS or WPAndroid open the app 
1. Create a new Page/Post
**Notice** the `initial_html` content has populated the body of the page/post
**Expected behavior** the body should be empty

## For Sanity
1. Start a metro server using the command `npm run core start`
1. In WPiOS or WPAndroid open the app 
1. Perform either of the previous tests
1. The app will perform as expected 

## Smartphone (please complete the following information):
 - Device: iPhone 11 simulator
 - OS: iOS 
 - Version 13.5

**Comment by mchowning** [comment]
I wonder if this might be related to https://github.com/wordpress-mobile/gutenberg-mobile/pull/2690. cc: @guarani

**Comment by chipsnyder** [comment]
Yeah, I think that's the root cause. I just need to build the demo app to make sure that works as expected still but the fix I have in place is

```
		if ( initialData === undefined ) {
			initialData = initialHtml + initialHtmlGutenberg;
		}
```

**Comment by mzorz** [comment]
closing via #2705
