### ISSUE TITLE
Make createBlockAction create a block instead of carrying a model

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#271]
Originally in #58, moved here as this is a nice to have:

- [ ] make `createBlockAction` actually create a block instead of carry a block model and insert it in the list (https://github.com/wordpress-mobile/gutenberg-mobile/pull/88#discussion_r209299767)
- [ ] after this one above (`createBlockAction` change), enhance the `CREATE_BLOCK` action tests to run through all registered blocks and create each one, verifying the expected block type has been created

Estimated 1 week

**Comment by koke** [comment]
I don't fully understand this one, is this still necessary after the store changes?

**Comment by mzorz** [comment]
Probably not, closing this
