### ISSUE TITLE
[Home Page Picker] Connect Preview Button

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2720]
## Description
Building off of the work done in https://github.com/wordpress-mobile/gutenberg-mobile/issues/2719, this step will handle connecting the Preview button in the footer. After selecting a Home Page Layout, and selecting Preview the user should be taken to a preview screen that shows a sample preview of the site (ex https://public-api.wordpress.com/rest/v1/template/demo/alves/overton/?site_title=&font_headings=Cabin&font_base=Raleway&use_patterns=false )

📓 The API will provide a URL that can be passed to the existing preview screens to present a preview in a webview.

## Goals
- Taping Preview on the Layout Picker should take the user to the Preview Screen
- The Preview Screen should load the preview URL similar to the one in the description.
- Show footer with the choose button
- Selecting back or close should navigate back.

## Screenshots

<img width=300 src="https://user-images.githubusercontent.com/3384451/95904475-92c25780-0d65-11eb-9028-9d95b59487a2.png" />

## Additional context

<details>
<summary>Design i1</summary>
<img src="https://user-images.githubusercontent.com/3384451/95901257-0e6dd580-0d61-11eb-8775-9a15bbfd33b9.png"/>
</details>

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/15293 and https://github.com/wordpress-mobile/WordPress-Android/pull/13399
