### ISSUE TITLE
[Home Page Picker] Connect Choose to the flow of existing UI's

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2721]
## Description
Building off of the work done in https://github.com/wordpress-mobile/gutenberg-mobile/issues/2720, this step will handle connecting the Choose buttons in the footers. After selecting a Home Page Layout, and selecting Choose from either the Layout Page and Preview page then the user should be taken to the existing “Choose a Domain” flow. This should also update the site creation API (rest/v1.1/sites/new) with the needed parameters to pass along the chosen options. 

📓 The “choose a domain” screen and the final confirmation page are both existing screens. The goal here is to plug into the existing UI’s to make sure you can successfully navigate through the “choose a domain” flow to create your site. Choose a Domain will have some UI updates in https://github.com/wordpress-mobile/gutenberg-mobile/issues/2721 

## Goals
- Update relevant APIs with the needed parameters to create the site with the selected home page layout. 
    - This will be a modification of `rest/v1.1/sites/new` This issue will be updated later when that API is available.
- Selecting Choose from the Layout Picker should take you to the “choose a domain” page which should then let you create a site with the selected layout.
- Selecting Choose from the Preview should take you to the “choose a domain” page which should then let you create a site with the selected layout.
     - 📓 Preview has been moved to Round 2 so this requirement is now not required until that view is implemented
- Selecting "Skip" from the Layout Picker should take you to the “choose a domain” page which should then let you create a site with the "blank" option.

## Additional context

📓Updated designs will come later than what is currently linked here.
<details>
<summary>Design i1</summary>
<img src="https://user-images.githubusercontent.com/3384451/95901257-0e6dd580-0d61-11eb-8775-9a15bbfd33b9.png"/>
</details>

**Comment by chipsnyder** [comment]
@Tug I was working on this today and came across an interesting use case that I wanted to get your thoughts on. On the domain suggestion screen, it uses the selected segment (`Blog`, `Business`, `Professional`, or `Blank Canvas`) to help filter the results. If you select `Blog` the backend will include `.blog` domains in addition to the dotCom options. 

What are your thoughts here? Should we include the `.blog` domains? (The amount of work is trivial so that's not a problem.)

**Comment by Tug** [comment]
I'm not sure to understand, how are they excluded from the response currently? I do think we should display whatever the backend is returning in terms of recommendation.

**Comment by chipsnyder** [comment]
> I do think we should display whatever the backend is returning in terms of recommendation.

Closing the loop on this. After a side discussion, we're going to modify the site-design endpoint to provide a segment_id to be used for the domain suggestions
