### ISSUE TITLE
[Home Page Picker] Update the design of the “Choose a Domain” screen

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2722]
## Description
As part of the project for adding a Home Page Picker to the site creation flow, we'd like to tweak the design of the existing "Choose a Domain" screen to match the feel of the other screens. 

📓These design changes do not need to be behind the feature flag for the project.

## Goals
- Design elements should be updated to match the new UI this should include
    - Adding the Help Button
    - Changing the title text to “Choose a domain” and updating the font
    - Updating the background.
- Update the header design and navigation bar design.

## Screenshots
<img width=300 src="https://user-images.githubusercontent.com/3384451/95905966-80e1b400-0d67-11eb-8c06-f8f544af52eb.png" />

## Additional context

📓Updated designs will come later than what is currently linked here.
<details>
<summary>Design i1</summary>
<img src="https://user-images.githubusercontent.com/3384451/95901257-0e6dd580-0d61-11eb-8775-9a15bbfd33b9.png"/>
</details>

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/15324 and https://github.com/wordpress-mobile/WordPress-Android/pull/13424
