### ISSUE TITLE
Link picker search does not work on WordPress.com Business or Jetpack sites

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2724]
**Describe the bug**

Link picker search does not work on WordPress.com Business or Jetpack sites. ([1m43s](https://cloudup.com/cHF9CfrqQjG), [2m18s](https://cloudup.com/cSr-GRr8BxK))

**To Reproduce**

1. Open a WordPress.com or Jetpack site using WPAndroid 15.9-rc-1 or later.
1. Create a new post using the block editor.
1. Add some text and highlight one of the words.
1. Tap the link icon in the editor toolbar.
1. Search for a post or page on the site that you know exists.

Result: no results are shown for searches for existing content done via the link picker search if you are using a WordPress.com Business or Jetpack site. Tested with WordPress.com Business on 2020-10-07 and 2020-10-13 and also with Jetpack 9.0.1 WordPress 5.5.1.

**Expected behavior**

I expect searching for an existing post or page from within the link picker will produce results.

**Screenshots**

“Search or type URL” for the link field|No results for "test" in link picker search|Results for "test" in Posts List search
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/95907336-9ac7ca80-0d58-11eb-921f-8e70a5b3974b.png" width="270" alt="Screenshot_20201007-120612">|<img src="https://user-images.githubusercontent.com/1119271/95907340-9d2a2480-0d58-11eb-95eb-fea927c8bec6.png" width="270" alt="Screenshot_20201007-120733">|<img src="https://user-images.githubusercontent.com/1119271/95907352-9f8c7e80-0d58-11eb-962e-9415c77ad21d.png" width="270" alt="Screenshot_20201007-120821">

<sup>Tested with WPAndroid 15.9-rc-1 on Pixel 3 Android 11 on artindesignco.blog (WordPress.com Business) while logged in as testuser0313.</sup>

**Smartphone**
 - Device: Pixel 3 
 - OS: Android 11
 - Version 15.9-rc-1 and 15.9-rc-2

**Comment by designsimply** [comment]
Because this is a new feature in 15.9 and this issue was found during 15.9 beta testing, @dratwas do you think you could have a look at this one? cc @Tug

**Comment by mkevins** [comment]
:wave: :smile: @dratwas , I've been looking into this a bit already, so I've assigned myself on this one.

**Comment by mkevins** [comment]
This was due to a missing API mapping for Jetpack sites, and is now resolved. :tada:  Thanks again for testing and reporting Sheri! :smiley:
