### ISSUE TITLE
[Home Page Picker] Enable the feature and remove the old flow

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2727]
## Description
Once all other tasks have been completed as part of the [Home Page Picker project](https://github.com/wordpress-mobile/gutenberg-mobile/issues?q=is%3Aissue+label%3A%22Project%3A+Home+Page+Picker%22+), and we’ve hit a comfortable level of testing. We should enable the feature, remove the feature flag, and clean up the code for the now unused step of “choosing a segment”

## Goals
- Enable the Home Page Picker for production
- Remove the unused code related to "choose a segment."

## Additional context

📓Updated designs will come later than what is currently linked here.
<details>
<summary>Design i1</summary>
<img src="https://user-images.githubusercontent.com/3384451/95901257-0e6dd580-0d61-11eb-8775-9a15bbfd33b9.png"/>
</details>

**Comment by antonis** [comment]
Features is now enabled on both platforms. Additional cleanup on Android was performed with https://github.com/wordpress-mobile/WordPress-Android/pull/14269
