### ISSUE TITLE
Gallery block is not removed when undo is pressed

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/gutenberg-mobile#2735]
**Describe the bug**
When you add a Gallery Block to the Block List and you press the undo button the Gallery Block is not removed. This issue was first discovered on the `master` branch of gutenberg.

This issue was observed was also observed on WPiOS 15.9.0.1.

**To Reproduce**
1. Create a new post. 
2. Add a Gallery Block. 
3. Press the undo button. 
4. Observe that the Gallery Block is not removed no matter how many times you press the undo button. 

**Expected behavior**
It's expected that all blocks including the Gallery block will be removed when the undo is done, i.e once it doesn't contain any content as that would cause the content's removal from the Gallery Block to supersede it's removal. 

**Screenshots**
<kbd><img src="https://user-images.githubusercontent.com/1509205/96303517-22fbd900-0fc0-11eb-83b7-0b4f1bcdb827.gif" width="320"></kbd>

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - OS: Android 11
 - Version : 15.9

**Comment by jd-alexander** [comment]
This is being resolved by https://github.com/WordPress/gutenberg/pull/26377

**Comment by chipsnyder** [comment]
Tested in WP 16.7 this seems to be resolved now
