### ISSUE TITLE
[Modal Layout Picker] Retry view

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#2740]
**Is your feature request related to a problem? Please describe.**
When the loading of layouts fails and there are no cached data an empty screen appears. This is not consistent with other screens where an error screen with a retry option is presented.

**Describe the solution you'd like**
Add a retry view to handle the case where the loading of layouts fails and there are no cached data

<img width="360" src="https://user-images.githubusercontent.com/304044/96276559-d9b98280-0fdb-11eb-8fb3-6786bc347513.png"/>

**Comment by cameronvoell** [comment]
Hi @antonis, we'll be cutting the 1.40 release branch at the beginning of this week. Please try to get this merged Monday or bump the milestone. Thanks much 🙇

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/13159
