### ISSUE TITLE
Consider allowing users to change font size the same way they can on the web

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2757]
We received a request in an App Review asking to be able to change font size.

> Why don't you have the font size and other formats in the application menu, unlike the web version, please make it equal so that blogging activities are more enjoyable using WordPress. such as adjusting paragraph spacing in the application there is also no font.

<sup>1-star review - Oct 26, 2020 at 3:40 AM - realme 6, WPAndroid 15.6, Android 10</sup>

* Device: Realme realme 6
* Device language: Indonesian
* App version code: 915
* App version name: 15.6
* Android version (SDK): Android 10 (SDK 29)

<sup>play-store-reviewid=gp:AOqpTOGeNw4SkhE95DCWrVWd1Y3xxNaUaB-aHPfRwoyVXucunfERtFhV5_ruBFEFMEXqwjs5DlM6P3q487TkoQ</sup>

![Screen Shot 2020-10-26 at Oct 26 12 23 31 PM](https://user-images.githubusercontent.com/1119271/97212595-3fe59880-1786-11eb-8fb8-3ed4fe6e08fb.png)
<sup>Tested on Calypso Gutenberg on a WordPress.com Premium site using Firefox 81.0.1 on macOS 10.15.6.</sup>

![Screen Shot 2020-10-26 at Oct 26 12 27 19 PM](https://user-images.githubusercontent.com/1119271/97213073-cf8b4700-1786-11eb-8085-020e531aa28c.png)
<sup>Tested on Calypso Gutenberg on a WordPress 5.5.1 (self-hosted) site using Firefox 81.0.1 on macOS 10.15.6.</sup>

**Comment by designsimply** [comment]
Translated from Portuguese using Google Translate:

> […] a moment, out of nowhere, change fonts and you can't use the same fonts on two blogs and, our very little synergistic, the app I couldn't adapt, I'm migrating to another platform

<sup>2-star review - Oct 27, 2020, 23:18 - Asus ZenFone Max Shot, WPAndroid 15.9.1, Android 9</sup>

* Device: Asus ZenFone Max Shot (ZB634KL)
* Device language: Portuguese
* App version code: 938
* App version name: 15.9.1
* Android version (SDK): Android 9 (SDK 28)

<sup>play-store-reviewId=gp%3AAOqpTOH3DSKQ8dSz3i86Hn37Sn9_6Ly72BB8SCB-wpMrOpnjPC571yZAvEDuX2gmPK_NcUDVbSFqyVIH1av2NA</sup>

Note: this is about fonts and not specifically font size. Do you think I should create a separate issue for this?

**Comment by reginabally** [comment]
Another request in 4091121-zd-woothemes

**Comment by erricgunawan** [comment]
Another request from 4673440-zen

**Comment by antonis** [comment]
Allowing users to change font size is behind a development flag and will be released soon.

**Comment by geriux** [comment]
Closing since this feature shipped in https://github.com/WordPress/gutenberg/pull/38205
