### ISSUE TITLE
Spacer fails to render when height is set > 500px

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#2761]
**Describe the bug**
Spacer fails to render when height is set > 500px

**To Reproduce**
Follow the steps in [test-case TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#settings-height-range-extends-if-spacer-comes-from-the-web-is-higher-than-500px)

**Expected behavior**

**Screenshots**

<img width="360" src="https://user-images.githubusercontent.com/304044/97298466-19922c80-185c-11eb-90da-a72a8c572b11.jpeg"/>

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: iOS 14.2

**Additional context**
The issue was reported [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2758#issuecomment-717178163).

**Comment by chipsnyder** [comment]
Tested this on WP 16.7 the editor will restrict the input to be 500 px. If you change it in the code editor it will still display but will reset to 500 if you try to edit it visually again.
