### ISSUE TITLE
[Home Page Picker] Add Skip option to “Choose a Domain” screen

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2828]
## Description
As part of the project for adding a Home Page Picker to the site creation flow, we'd like to tweak the design of the existing "Choose a Domain" to add a Skip option to this screen as mentioned in https://github.com/wordpress-mobile/WordPress-iOS/pull/15231#issuecomment-724965218

## Goals
- Add a Skip option to the Choose a Domain screen

## Additional context

<details>
<summary>Design i1</summary>
<img src="https://user-images.githubusercontent.com/3384451/95901257-0e6dd580-0d61-11eb-8775-9a15bbfd33b9.png"/>
</details>

**Comment by chipsnyder** [comment]
From the linked [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/15231#issuecomment-724965218) in the description:
>It looks like this is an option if you create a site on web. When I created a site we ended up with a site that was my username + random number. So this might be an option but I would like to do some more exploration before adding it to this iteration. Maybe we can add it as an iteration 2 item.

I had done an initial research that this seems feasible at least from the web side. I took a brief look into from the mobile side and currently have to following questions:
- I see [evidence](https://github.com/wordpress-mobile/WordPress-iOS/blob/2f53a276895c669e9028e27c7d864ffafb5896c8/WordPress/Classes/ViewRelated/Site%20Creation/WebAddress/WebAddressWizardContent.swift#L28-L29) on the iOS side that we used to have a skip button. 
- I would like to investigate why the skip button was removed. This also needs some investigation on if there are any API changes that need to happen to support this. 


cc @kyleaparker

**Comment by antonis** [comment]
I did a preliminary research on Android but I couldn't find an evidence of a skip button on the domain screen.
There seems to be a [removed Skip button](https://github.com/wordpress-mobile/WordPress-Android/pull/11460/commits/8dbbe483f163ebcd7525bfe9b17420dc669249d8) in the parent `Activity` but the `siteName` parameter in the api call [was `@NonNull` since it was introduced](https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/4ecbe11a5a975e2eb57c8490f9222f6bf6b485c0#diff-89759506e2b36176a7461b36f478e8437f4f305be3b84114b820d6d50b86f33fR104).

**Comment by chipsnyder** [comment]
@kyleaparker I did some more investigation on this and added in a skip button. When we make the API request without selecting a domain I get the error:

```
{
    "error": "blog_name_required",
    "message": "Please enter a site name."
}
```

So we might need to do some investigation on the backend. @enejb I would be interested in learning more about how we would go about adding support for this if you find time to investigate.

**Comment by enejb** [comment]
I am not 100% sure but I think there is a `find_available_url` url parameter that if set to true would help with creating a finding an avaialve url and using it so that you wouldn't have to pass one in. See https://github.com/Automattic/wp-calypso/blob/05c40beca783ea09b73ac269b048f847086a9600/packages/data-stores/src/site/actions.ts#L43 

Would that help? I haven't tried it yet but I think it would help avoid the error that you are seeing.

**Comment by chipsnyder** [comment]
Thanks for finding this @enejb 
Just including that didn't help but I may have made some progress. Your link led me to https://github.com/Automattic/wp-calypso/blob/e1372f44049ce54068b16380ca7ef16503dfdb13/client/lib/signup/step-actions/index.js#L209-L215 

It looks like we're supplying the username as the tool to create the site. That doesn't yet close the gap though because I already have a site with `myusername.wordpress.com` But going through calypso I and skipping I'll get a site that's username + (seemingly) random number. I'm not sure how that number is being added so I'll keep digging.

**Comment by antonis** [comment]
Hello @kyleaparker @iamthomasbishop 👋 
We have started checking the implementation details of this.Regarding the design and UX should we just add a **skip** button at the top right of the screen similar to the *Choose design* screen? Note that after this step the site creation is triggered.

**Comment by kyleaparker** [comment]
>We have started checking the implementation details of this.Regarding the design and UX should we just add a skip button at the top right of the screen similar to the Choose design screen? Note that after this step the site creation is triggered.

Yes the Skip button would be in the same place as the Choose design screen :)

**Comment by chipsnyder** [comment]
@enejb and I did some more investigation on this and had success with using the following parameters:

```
{
	"public": 1,
	"options": {
		"template": "default",
		"site_information": {
			"site_tagline": ""
		}
	},
	"validate": false,
	"blog_name": "{{username}}",
	"client_id": "11",
	"lang_id": "1",
	"client_secret": "{{client_secret}}",
	"blog_title": "Site Title",
        "find_available_url": true
}
```

The key piece here was no *.wordpress.com in the `blog_name` when formulating the request.

**Comment by chipsnyder** [comment]
Closing this issue out after our discussions to not move forward with it as part of site creation as it stands today. We can reopen this later or clone it with details that would relate to any updates to the Choose a domain flow.
