### ISSUE TITLE
Heading Block: cannot highlight and replace content or highlight and press backspace to add new text to a heading when it is inside a cover block

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2863]
**Describe the bug**
When I try to replace text in a heading, the heading is unexpectedly removed instead of allowing me to either delete and add new text or highlight and replace text.

**To Reproduce**
1. Create a new post and add a cover block with a heading and a paragraph inside it and add text to each.
1. Save the post as a draft.
1. Exit the editor.
1. Re-open the draft.
1. Highlight the content in the heading and press backspace.
1. Observe that the entire block disappears when only the text should disappear. ([2m55s](https://cloudup.com/cpjLn2bMfvt))

Note: this only seems to happen to me after a post has been saved and re-opened (it took me a while to figure that part out 😂) and it also happens with the starter mobile content from the homepage picker or page templates.

**Expected behavior**
I expect to be able to highlight text in any block and if I press backspace I expect that I can continue typing without the block suddenly being removed.

**Screenshots**

<img src="https://user-images.githubusercontent.com/1119271/101097043-b5126d80-357d-11eb-8de0-fbd97c1a77aa.png" width="270" alt="Screenshot_20201203-153714">
<sup>Tested with WPAndroid 16.3-rc-2 on Pixel 3 Android 11.</sup>

**Smartphone** 
 - Device: Pixel 3
 - OS: Android 11
 - Version WPAndroid 16.3-rc-2

**Additional context**
I think this is possibly edge case for others but it also catches me out almost every time! It's also possible more users will run into this since a heading inside a cover block is a common design piece used in mobile starter page or page template content.

**Comment by chipsnyder** [comment]
@geriux and I had a side conversation on this so sharing the results of that here:

@geriux pointed out that this may be related to https://github.com/wordpress-mobile/AztecEditor-Android/pull/928 which was a fix for wordpress-mobile/gutenberg-mobile#1663 and wordpress-mobile/gutenberg-mobile#1524. The underlying issue there was that there is a zero space white-space character that is added to the Heading Block when it's created. It seems like the goal of that character is to prevent this scenario (ie keep the block around if it has no text but does have valuable formating). 

From those steps, it seems like the Save As Draft is the important piece. However, it looks like when creating the block from a save that the Zero space character mentioned isn't being added back to the block. I'll help dive to confirm if that's actually the case.

**Comment by chipsnyder** [comment]
This went as part of GB-mobile 1.43.0
