### ISSUE TITLE
Button Link Settings: Toggling off the new tab toggle removes any custom text in rel link field

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/gutenberg-mobile#2879]
**Describe the bug**
Toggling off the new tab toggle ("Open in new tab") removes any custom text in the rel link field. 

**To Reproduce**
1. Add a new button. 
2. Go to settings. 
3. Toggle the new tab toggle. Notice that the rel text field gets populated. 
4. Change the rel link field. 
5. Toggle off the new tab toggle.
6. Notice that the rel link text filed is now empty.

**Expected behavior**
I expected the filed to stay the same. 

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro, Samsung A8
 - OS: iOS 8.1,  Android

**Comment by hypest** [comment]
Which app version is that on Enej? I don't see the "rel link" field on WPAndroid v16.3-rc-1 (gb-mobile v1.42).

**Comment by enejb** [comment]
Do you see in on the button component?

**Comment by hypest** [comment]
Ah, replicated now 👍, I was only looking in the normal links, not buttons 🤦 . Can we rename the ticket title to include "Button"?

**Comment by enejb** [comment]
Done update to say Button Link Settings :)
