### ISSUE TITLE
Crash when deleting block from page template

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/gutenberg-mobile#2886]
**Describe the bug**
When I create a page using a template and then delete a block, the app crashes - and not very gracefully. 

**To Reproduce**
1. In the app, create a new page using a template for a site with Jetpack installed. - I can only repro this on JP sites so far 
2. In the editor, delete a pre-set block
Crash
https://cloudup.com/ctvbVn5iqHn

**Expected behavior**
Block deletes with no crash

**Screenshots**
https://cloudup.com/cN4cvHBFV0e

**Smartphone (please complete the following information):**
iPhone 12 Pro, iOS 14.2.1, WP 16.3 beta

**Additional context**

**Comment by guarani** [comment]
> I can only repro this on JP sites so far

Just noting that I could reproduce this on a Simple WP.com site too
