### ISSUE TITLE
Swap instances of Button block on Starter Page Templates/Layouts to use Buttons block instead

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2905]
When we introduced Starter Page Templates (aka Layouts), we had not yet introduced the Buttons block. As a result, all of these templates use the individual Button block. 

Now that the Button block has been replaced by Buttons, let's swap out all instances of the Button block for Buttons on our starter page templates.

**Instances**

Note: Please add to the list if any are missing.

- [ ] About 1
- [ ] About 2
- [ ] Homepage 1
- [ ] Homepage 2
- [ ] Homepage 3
- [ ] Homepage 4
- [ ] Homepage 5
- [ ] Homepage 6
- [ ] Homepage 7
- [ ] Homepage 10
- [ ] Services
- [ ] Team

**Screenshots**

![image](https://user-images.githubusercontent.com/1200432/102296444-fa865180-3f12-11eb-8d86-8d9346267f0e.jpeg)

cc @Tug — is there any way we can update these on our end ASAP? Apologies, as I should've realized this sooner. 

cc @chipsnyder @enejb and FYI @kyleaparker

**Comment by chipsnyder** [comment]
I reviewed all of the layouts that were tagged `is_mobile` and the change to buttons on each one. Although the list that needed updating didn't really align with the list in their post. @iamthomasbishop When you get some time and confirm if I hit your goal or not.

## Updated:
✅ `hever`
✅ `morden`
✅ `shawburn`
✅ `about-6`
✅ `alves-2`
✅ `leven-2`
✅ `twenty-twenty`


cc @enejb

**Comment by chipsnyder** [comment]
Closing this out as I don't see any remaining instances and nothing came up in the site audit
