### ISSUE TITLE
api-fetch query parameters are dropped

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#2922]
**Describe the bug**
Because `URL` is only partially implemented on mobile, in certain cases, query parameters are dropped prior to invocation of api-fetch. This results in incorrect behavior, since the API request is missing parameters. In link picker, it manifests as omitting the `search` parameter, which results in the same results (a "blank" search) being returned in all cases.

**To Reproduce**
1. Create a new post or page (on a site with some published posts and pages)
2. Add a button block
3. Edit the link in the button block
4. Tap "Search or type URL" to open link picker
5. Begin typing a few characters and wait for the results
6. Erase the search a type a few different characters

**Expected behavior**
The results should be different for searches which have differerent queries. The search results should reflect the query being searched for.

**Comment by guarani** [comment]
Hi @mkevins 👋 It looks like you've done some work on this. Do you know which project board this issue should be added to?

**Comment by hypest** [comment]
Added it to the Gutenpages project board since most of the people working on this are in Manakin anyway.
