### ISSUE TITLE
[Layout Switching] Tweaks to pages list

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#2937]
## Description
The pages list is enhanced to:
* List the Homepage first
* Show icons for homepage and posts page

![Pages - Option 1](https://user-images.githubusercontent.com/304044/103219080-6b6f3580-4925-11eb-8f7c-54bb2064acd9.png)

## Goals
* The list of pages always starts with the Home page whenever the site has a homepage and the homepage is part of that list.
* When no homepage is selected (Your latest posts) then the most recently updated page is shown first (as usual)
* An icon is shown next to the  homepage and posts page as depicted in the design

## Additional context
This issue is part of the [Layout Switching project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Layout%20Switching)

<details>
<summary>Design i3</summary>

![Screenshot 2020-12-28 at 4 10 50 PM](https://user-images.githubusercontent.com/304044/103219759-467bc200-4927-11eb-88d8-cecaeb74635a.png)
</details>

**Comment by antonis** [comment]
Hello @kyleaparker, @iamthomasbishop 👋 
while implementing the page sorting on [iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/15575) I realised that I [missed](https://github.com/wordpress-mobile/WordPress-Android/pull/13691) the case where the the **homepage is not at top level**.
<image width="360" src="https://user-images.githubusercontent.com/304044/103751934-b0742580-5011-11eb-983e-b5a075583d37.png"/>
Some possible solutions I could think are the following:
- Move the whole branch that contains the homepage in the first position and order the homepage first among the pages of the same level. This is more complex to implement but seems more correct to me.
- Always display the homepage first and at the top level (probably add some indication that this is actually nested, e.g. parent name/hierarchy in parenthesis)
- Drop the ordering requirement

Wdyt?
cc @chipsnyder

**Comment by chipsnyder** [comment]
That seems really weird that we allow Homepages to be nested but that's probably out of our control to change 😄 

> Move the whole branch that contains the homepage in the first position and order the homepage first among the pages of the same level. This is more complex to implement but seems more correct to me.

I think I would want to avoid this option because I could see the rules becoming confusing depending on where the page is. I just imagine a user setting this up with it being three levels deep with multiple pages at each level. How would we sort it then and would that be clear?

My preference would be to display the homepage first if it's a top-level page and preserve the order if not this way it more accurately reflect their site's hierarchy.

**Comment by antonis** [comment]
> My preference would be to display the homepage first if it's a top-level page and preserve the order if not this way it more accurately reflect their site's hierarchy.

I agree Chip. This should be more clear for the user and simpler to implement.
I proceeded with this approach since the [already merged Android PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13691) introduced a [bug](https://github.com/wordpress-mobile/WordPress-Android/pull/13720).
If needed I can tweak this further in the next iteration.

**Comment by kyleaparker** [comment]
>My preference would be to display the homepage first if it's a top-level page and preserve the order if not this way it more accurately reflect their site's hierarchy.

Agreed with this approach 👍

**Comment by antonis** [comment]
Fixed with:
* Android: https://github.com/wordpress-mobile/WordPress-Android/pull/13691 and https://github.com/wordpress-mobile/WordPress-Android/pull/13720
* iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15575
