### ISSUE TITLE
[RNmobile] Multiline Pullquote using break instead of p tag

### ISSUE THREAD

**Issue by jhnstn** [wordpress-mobile/gutenberg-mobile#2967]
**Describe the bug**
On Android only, new lines with out trailing whitespace on Pullquotes use `<br>` to separate the lines when it should use a `<p>` tag

**To Reproduce**
1. Add a new Pullquote block
2. Start typing and make sure there are no trailing whitespace characters 
3. Press enter to create a new line
4. Add a second line of text
5. Switch to HTML view and note that the lines are split by a `<br>` tag 
6. Add a new Pullquite block
7. Start typing and add trailing whitespace
8. Press enter to create a new line
9. Add a second line of text
10. Switch to HTML view and note that the lines are split with `<p>` tags

**Expected behavior**
Multiple lines in a Pullquote without trailing whitespace should be split by `<p>` tags

**Screenshots**
![2021-01-06 07 11 51](https://user-images.githubusercontent.com/744755/103802437-faeea580-5003-11eb-9f99-2595f882f761.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 11
 - Version 16.4-rc-3

**Comment by guarani** [comment]
Thanks for filing this @jhnstn. Could this be moved to the Gutenberg repo itself?
The general guideline I'm aware of is to reserve this repo for Jetpack/WP.com specific issues and PRs, and file all other issues in Gutenberg. The "Mobile App Android/iOS" label is used in the Gutenberg repo on both issues and PRs to identify them as related to the React Native project.

**Comment by jhnstn** [comment]
> Could this be moved to the Gutenberg repo itself?

Absolutely @guarani , I'll move it over there now. Thanks!
