### ISSUE TITLE
[Layout Switching] Add Tablet and Desktop mode in HPP Preview

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#2977]
## Description
A desktop icon (the same used in site/page preview) will be added on the top bar (right on Android and left on iOS in order not to affect the rest of the design). This should present a small popup with “Desktop”, “Tablet”, “Phone” options and act the same way with the site/page preview screens.
The preview screen should preserve the setting that's currently set on the [HPP design](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2978) selection screen and vice-versa.

<image width="360" src="https://user-images.githubusercontent.com/304044/103025312-385e2800-455a-11eb-8f44-a42e05d0e0d4.png"/>

## Goals
* The HPP preview screen displays a desktop preview icon.
* When the icon is pressed a popup appears with “Default” and “Desktop” “Desktop”, “Tablet”, “Phone” options.
* The “Default” “Phone” option shows the mobile preview.
* The “Tablet option shows a tablet preview.
* The “Desktop” option switches to a desktop preview with a small indication in the bottom/right corner.

## Additional context
This issue is part of the [Layout Switching project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Layout%20Switching)

**Comment by chipsnyder** [comment]
Just an idea I had when looking at other pages. This would be awesome if we could preserve the setting that's currently set on the HPP screen and vice-versa.

**Comment by antonis** [comment]
> Just an idea I had when looking at other pages. This would be awesome if we could preserve the setting that's currently set on the HPP screen and vice-versa.

That's a good idea Chip 👍 
I'm adding it to the issue description.

**Comment by mkevins** [comment]
Closing as resolved, since both Android and iOS implementations are merged.
