### ISSUE TITLE
[Layout Switching] Add mobile/tablet/desktop thumbnails in HPP design selection screen

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#2978]
## Description
The HPP design selection screen should be enhanced by adding the ability to select between mobile(default) and desktop thumbnails.
The HPP API call should be enhanced to provide the mobile and tablet thumbnail urls.

<image width="360" src="https://user-images.githubusercontent.com/304044/103789359-96096e80-5048-11eb-84aa-4450a608ed15.png"/>

## Goals
* The HPP design selection screen displays a thumbnail mode icon.
* When the icon is pressed a popup appears with “Desktop”, “Tablet”, “Phone”options.
* The “Default” “Phone” option shows the mobile thumbnails and loads on first launch.
* The “Tablet” option switches to a tablet thumbnail mode.
* The “Desktop” option switches to a desktop thumbnail mode.

## Additional context
This issue is part of the [Layout Switching project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Layout%20Switching)

**Comment by mkevins** [comment]
Closing as resolved, since both Android and iOS implementations are merged.
