### ISSUE TITLE
Convert Starter Page previews to use the web view implementations from Home Page Picker

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2980]
**Is your feature request related to a problem? Please describe.**
When implementing the new [Starter Page Picker](https://github.com/wordpress-mobile/gutenberg-mobile/issues?q=is%3Aissue+is%3Aclosed+%5BModal+Layout+Picker%5D) we decided to replicate the preview functionality that was currently in place in the Gutenberg Editor (ie a read-only view of the editor). During that project, we updated the previews to provide a web view that loads an autosave of the page. 

**Describe the solution you'd like**
Update starter page picker's preview screen to provide:
- WebView that loads a URL representing the chosen page
    - Similar to the Editor's Preview and Site Creation
- A toggle to support Mobile vs Desktop
    - Default to mobile (or to the setting on the [previous screen](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2979) if available)
- **Bonus** if the preview applied the current theme.

Current | Site-Creation comparison | Editor Comparison
--- | --- | ---
<kbd><a href="https://user-images.githubusercontent.com/3384451/103943417-0f17cd00-5100-11eb-8791-081199ec450e.PNG"><img width="300" src="https://user-images.githubusercontent.com/3384451/103943417-0f17cd00-5100-11eb-8791-081199ec450e.PNG"/></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/103943520-3b334e00-5100-11eb-8d6a-bc1e043a6195.PNG"><img width="300" src="https://user-images.githubusercontent.com/3384451/103943520-3b334e00-5100-11eb-8d6a-bc1e043a6195.PNG"/></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/103943561-4be3c400-5100-11eb-979e-1a479dfb2c84.PNG"><img width="300" src="https://user-images.githubusercontent.com/3384451/103943561-4be3c400-5100-11eb-979e-1a479dfb2c84.PNG"/></a></kbd>

**Additional context**
- This will need some API changes in addition to app changes and likely some exploration into the bonus goals of applying the site's theme. 

cc @iamthomasbishop @kyleaparker

**Comment by chipsnyder** [comment]
cc @enejb Would you be able to take a look at the backend components of this? (I think you've done research into this already)

**Comment by enejb** [comment]
@chipsnyder sorry I missed this.

Yes, I did some research here. It is kind of summarized in pb3aDo-sq-p2. 

The main take away is that we can make it work so that it displays nicely for a set of themes but to make it look great for any site is a much harder problem that requires significantly more time to do right. It would mean that we we would be creating previews of content that doesn't exist on the site yet.

**Comment by antonis** [comment]
The `editor_session_template_preview` event (as introduced [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2454)) has been replaced with the following new events that match the Home Page Picker implementation: `layout_picker_preview_mode_changed`, `layout_picker_thumbnail_mode_button_tapped`, `layout_picker_preview_mode_button_tapped`, `layout_picker_preview_loading`, `layout_picker_preview_loaded`, `layout_picker_preview_viewed`, `layout_picker_error_shown`

The new events should be registered as part of this issue.

**Comment by antonis** [comment]
Pending iOS and registering new tracks events.
