### ISSUE TITLE
[Layout Switching] Display “Try another layout” banner

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#2984]
## Description
A new banner component should appear at the top of the editor screen with the “Try another layout” action. The banner will appear only when the user has not changed the content of the homepage. When you click into a block to edit, the banner will slide up and out of view to indicate that the layout can’t be changed after this point.

When the user clicks on the banner a new layout selection screen appears (this implementation is not part of this issue).

Notes:
* All the implementation can be done on the client.
* The banner can be implemented either on the native (iOS and Android) side or in the gutenberg editor (similar to the “Page Created” banner in MLP). It might be simpler to keep this on the native side only to reduce complexity but further evaluation of this is needed prior to the implementation.

## Goals
* When a users opens a page for editing and the content of the original layout has not changed a new banner component appears at the top of the editor screen with the “Try another layout” action.
* When a users opens a page for editing and the content of the layout has been edited no banner appears.
* When the banner is shown an analytics event should be emitted

## Screenshots
![2  Edit homepage](https://user-images.githubusercontent.com/304044/104018001-ccb6c480-51c1-11eb-95f2-adff7963d2ce.png)

## Additional context
This issue is part of the [Layout Switching project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Layout%20Switching)

<details>
<summary>Design i3</summary>

![Group 44](https://user-images.githubusercontent.com/304044/104017738-54e89a00-51c1-11eb-958c-3a0702a71049.png)
</details>

**Comment by chipsnyder** [comment]
Closing this issue as we decided to explore a different approach
