### ISSUE TITLE
[Layout Switching] Display “Change layout” screen

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#2985]
## Description
When the user presses the “Try another layout” action the change layout screen should appear. The design of this screen is the same with the HPP screen and may reuse or customize the same implementation.

Initially the active layout is selected. The active layout is also highlighted with a bottom ribbon as depicted in the screenshots. In that state the (only) bottom action button is “Keep Existing Layout”. When pressed the screen dismisses without any change (the same as pressing the close/back button).

When the user selects another layout the bottom action button changes to “Change Layout”.

The “Change Layout” action will be implemented in a separate issue.

Notes:
* An api call returning the designs or enhancement of the HPP api call to include currentLayout.
* Android & iOS client side implementation.

## Goals
* When the user presses the “Try another layout” action the change layout screen appears.
* The active layout is highlighted with a bottom ribbon.
* The current user selection is highlighted with a purple border.
* Initially the active layout is selected.
* When the active layout is selected the (only) bottom action button is “Keep Existing Layout”.
* When the user selects another layout the bottom action button changes to “Change Layout”.
* When the “Keep Existing Layout” is pressed the screen dismisses without any change. The same happens when the user presses the close/back button.
* When the user presses the “Try another layout” action an analytics event should be emitted

## Screenshots

|Other layout selected|Current layout selected|
|---|---|
|![4  Change layout](https://user-images.githubusercontent.com/304044/104018388-58c8ec00-51c2-11eb-9ca8-98ef2d64a082.png)|![3  Change layout](https://user-images.githubusercontent.com/304044/104018391-5a92af80-51c2-11eb-9507-816c7c4179c5.png)|

## Additional context
This issue is part of the [Layout Switching project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Layout%20Switching)

<details>
<summary>Design i3</summary>

![Group 44](https://user-images.githubusercontent.com/304044/104017738-54e89a00-51c1-11eb-958c-3a0702a71049.png)
</details>

**Comment by chipsnyder** [comment]
Closing this issue as we decided to explore a different approach
