### ISSUE TITLE
[Layout Switching] “Change Layout” action implementation

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#2986]
## Description
When the user presses the “Change Layout” action the layout change is triggered and the editor opens with the new layout. A bottom notification appears informing the user that the “Homepage layout changed” with an “Undo” action. The undo action should trigger a fallback to the previous layout.

Since no user editing has occurred the “Try another layout” banner is available and will disappear when the user edits the page.

Notes:
* An api call to change the layout.
* An api call to undo design selection.
* Android & iOS client side implementation.

## Goals
* When the user presses the “Change Layout” action the layout change is enforced and the editor opens with the new layout.
* A bottom notification appears informing the user that the “Homepage layout changed” with an “Undo” action.
* When the user presses the undo action the previous layout is restored.
* The “Try another layout” banner appears and disappears when the user edits the page.
* When the user presses the “Change Layout” and "Undo" buttons analytics events are emmited

## Screenshots

![5  New layout](https://user-images.githubusercontent.com/304044/104018670-df7dc900-51c2-11eb-8c09-73430483d815.png)

## Additional context
This issue is part of the [Layout Switching project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Layout%20Switching)

<details>
<summary>Design i3</summary>

![Group 44](https://user-images.githubusercontent.com/304044/104017738-54e89a00-51c1-11eb-958c-3a0702a71049.png)
</details>

**Comment by chipsnyder** [comment]
Closing this issue as we decided to explore a different approach
