### ISSUE TITLE
Updating a Published Page/Post notifies "Page Published" instead of updated

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#3018]
**Describe the bug**
Updating a Published Page/Post notifies "Page Published" instead of "Page Updated."

**To Reproduce**
1. Go to a published Page / Post
2. Make a change
3. Save the change
4. The toast says, “Page Published”; however, “Page Updated” is more accurate to the action taken.

**Expected behavior**
Update the toast to say, “Page Updated.” 

**Screenshots**
<kbd><a href="https://user-images.githubusercontent.com/3384451/104965324-81b06480-59ac-11eb-92e2-aeafd4b11445.gif"><img width="300" src="https://user-images.githubusercontent.com/3384451/104965324-81b06480-59ac-11eb-92e2-aeafd4b11445.gif"/></a></kbd>

**Additional context**
This was called out in one of our recent Empathy Challenge.

**Comment by antonis** [comment]
iOS PR is still open https://github.com/wordpress-mobile/WordPress-iOS/pull/15759
