### ISSUE TITLE
Focus Loop when deleting content and blocks 

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#302]
I can reproduce both on emulators and real devices a focus loop that makes the editor (and the app) unusable, since you cannot do much to recover from it, except looking at the screen and see the logic giving and moving the focus between blocks in the editor.

Made a video of the problem https://cloudup.com/chW89JFycRS

Steps to reproduce the issue:
- Start the demo app
- Tap into the first Para block (`Hello World!`)
- Tap Enter and add a new empty block after
- Write something in the block
- Repeat the step above by adding more blocks quickly

Sometime the issue start here, otherwise:
- on the last added block, press delete and keep it pressing for remove the content and the block.

I was also able to reproduce the issue by just adding one block and deleting it.

**Comment by daniloercoli** [comment]
cc @mzorz

**Comment by mzorz** [comment]
> I can reproduce both on emulators and real devices a focus loop

Interesting! Can you add steps to reproduce here please? thanks

**Comment by daniloercoli** [comment]
Added testing steps in the description.
