### ISSUE TITLE
[iOS] Heading Block: When the alignment actionsheet appears the block scrolls down outside the screen

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#3024]
**Describe the bug**
When the alignment actionsheet appears on a heading block the block is scrolled outside the screen 

**To Reproduce**
1. Open a post/page for editing
2. Focus on a heading block that is near the bottom of the screen
3. Notice that the heading block scrolls up to become visible above the keyboard
4. Press the alignement button
5. Notice that the heading block scrolls back behind the alignment actionsheet

**Expected behavior**
The heading block should stay visible above the alignment actionsheet

**Screenshots**

https://user-images.githubusercontent.com/304044/105019367-af4dea00-5a4e-11eb-9625-ec2c6c50fda9.mov

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: iOS 14.2
 - Version 16.5 (replicated at least since 16.3)

**Comment by lukewalczak** [comment]
Should be fixed via: https://github.com/WordPress/gutenberg/pull/28352
