### ISSUE TITLE
Add analytics to track the thumbnail/preview mode (mobile, tablet, desktop) selection

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#3025]
## Description
Track the[ thumbnails mode](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2978) and the [preview mode](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2977) in the home page design picker

|Thumbnails mode|Preview mode|
|---|---|
|![mobile](https://user-images.githubusercontent.com/304044/104484591-1e03f100-55d2-11eb-9ea2-582a0b2d3cf0.png)|![tablet](https://user-images.githubusercontent.com/304044/104584480-586d9c80-566b-11eb-8075-bd82e9dd95ba.png)|

## Goals
* Track the user tap on the mode button for the design and preview screens
* Track the mode change for the design and preview screens
* Track the default mode used in the user session

## Additional context
This issue is part of the [Layout Switching project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Layout%20Switching)

**Comment by mkevins** [comment]
We should probably also register the new tracks events, and update the ones where additional properties have been added. I can wrangle that after these new events have propagated from our testing.

**Comment by chipsnyder** [comment]
@antonis @mkevins Can this issue be safely closed now?

**Comment by antonis** [comment]
Yes. It is now closed by:
- https://github.com/wordpress-mobile/WordPress-Android/pull/13831
- https://github.com/wordpress-mobile/WordPress-iOS/pull/15808
and the registration of the tracks events.
