### ISSUE TITLE
Remove the switch to Classic editor from within the Block editor

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#3048]
https://github.com/wordpress-mobile/gutenberg-mobile/issues/3092 tracks the need to remove the "Use block editor" switch from site settings. This issue addresses the need to remove the "Switch to classic editor" option from the block editor itself as well, for all site types.

**Describe the solution you'd like**

The screenshot below shows the setting which we're considering removing.

<img src="https://user-images.githubusercontent.com/1898325/105758722-5985b000-5f2e-11eb-92d4-18560c66ae35.jpeg" alt="" width="350">

Despite similarities, the web and mobile differ with regard to how this option is implemented. In WP Admin, the setting that determines whether or not users can switch to the classic editor while using the Block editor is called "Allow users to switch editors" and is found under Setting → Writing for sites that have the Classic plugin activated. It is not available in Calypso, AFAIK. When this is ON, the editor toggle setting can be found in the editor's ellipsis menu, under Plugins, and is called "Switch to classic editor".
On mobile however, the "Switch to classic editor" option is shown unconditionally at the moment (i.e. its visibility is not controlled by a backend setting).

**Describe alternatives you've considered**

We could delay removing this setting and wait for more Core blocks to be supported – however, the block editor supports the most commonly used blocks and is more feature-packed than the classic editor, so it feels like now is the right time to make this change.

**Comment by guarani** [comment]
I've made this issue Simple site specific and created a separate issue for Atomic sites since they'll be shipped separately. I also removed the Needs Discussion label since this is now decided.

**Comment by guarani** [comment]
After offline discussion with @kyleaparker, we determine that its best to remove the "Switch to classic editor" from within the block editor now, on all types of sites. Once a user is using the block editor, switching back to classic need not be a prominent option.

Also, given that [the notice we're now displaying in the classic editor](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3209) doesn't make sense in the context of users switching from the block editor to the classic editor, making this change will help remove confusion around this notice.

**Comment by mchowning** [comment]
> Once a user is using the block editor, switching back to classic need not be a prominent option.

Once we removed the "Switch to classic editor" button would it be possible to switch back to classic? I thought the answer would be no, but wanted to see if I might be missing something in light of the word "prominent". Not second guessing, just checking my understanding.

**Comment by jd-alexander** [comment]
> > Once a user is using the block editor, switching back to classic need not be a prominent option.
> 
> Once we removed the "Switch to classic editor" button would it be possible to switch back to classic? I thought the answer would be no, but wanted to see if I might be missing something in light of the word "prominent". Not second guessing, just checking my understanding.

This is a good question. I am also interested in this answer as I wanted to work on adding [the block editor tests](https://github.com/wordpress-mobile/WordPress-Android/issues/14228) to Android this groundskeeping. Currently the test enables the block editor within Site Settings and then it opens the block editor and switches to the classic editor.  Is it that the logic to toggle the classic editor should remain in the test and then that logic would be removed when the classic editor is officially removed? Or should I just focus the test on the Block Editor itself?

**Comment by guarani** [comment]
> > Once a user is using the block editor, switching back to classic need not be a prominent option.
> 
> Once we removed the "Switch to classic editor" button would it be possible to switch back to classic? I thought the answer would be no, but wanted to see if I might be missing something in light of the word "prominent". Not second guessing, just checking my understanding.

On Simple sites the answer would be no, it's not going to be possible to switch back to classic. On other site types though (i.e. Atomic, Jetpack, self-hosted) it will still be possible to switch to classic by changing the site's default editor (but only admins can do that). Of course this also will stop being an option once we remove the mobile editor preference for these other site types. 

> This is a good question. I am also interested in this answer as I wanted to work on adding the block editor tests to Android this groundskeeping. Currently the test enables the block editor within Site Settings and then it opens the block editor and switches to the classic editor. Is it that the logic to toggle the classic editor should remain in the test and then that logic would be removed when the classic editor is officially removed? Or should I just focus the test on the Block Editor itself?

Regarding editor tests, on WPiOS, while the current UI test suite makes use of the mobile editor preference switch in Site Settings, I don't think they make use of the "Switch to classic editor" option in the block editor. (I'm double checking this by running the UI tests on my [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/16131) to resolve this issue on iOS., but I'm pretty sure of this.)

@jd-alexander when you say you're adding block editor tests to Android, which tests would that be?

Just want to note that @cameronvoell would have a better Android perspective here.

**Comment by fluiddot** [comment]
@guarani Looks like the PR https://github.com/wordpress-mobile/WordPress-Android/pull/14334 already addressed the issue, as I no longer see the "Switch to Classic editor" option in the block editor, so we can close this issue.

Android|iOS
--|--
![Screenshot_20211125-180012_WordPress](https://user-images.githubusercontent.com/14905380/143480131-7e48682b-0462-4770-b9a7-aaeaabae0430.jpg)|![IMG_B45A1D583C69-1](https://user-images.githubusercontent.com/14905380/143480134-2ec3b43e-6dbc-4b54-909f-9243223996b7.jpeg)

**Comment by guarani** [comment]
Thanks for catching this issue @fluiddot, I agree it should be closed. 

FWIW I think this was a case of one WPAndroid PR and one WPiOS PR both addressing this issue (using the "addresses" keyword in their PR descriptions, as neither wanted to close this issue before the other 😅), so when both PRs were merged, we forgot to go back and close this issue.

**Comment by fluiddot** [comment]
> Thanks for catching this issue @fluiddot, I agree it should be closed.
> 
> FWIW I think this was a case of one WPAndroid PR and one WPiOS PR both addressing this issue (using the "addresses" keyword in their PR descriptions, as neither wanted to close this issue before the other 😅), so when both PRs were merged, we forgot to go back and close this issue.

Awesome, thanks for checking and closing it 🙇 .

NOTE: I've just seen the related [WordPress-iOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/16131) 😅 .

**Comment by guarani** [comment]
> NOTE: I've just seen the related [WordPress-iOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/16131) 😅 .

Ah yes, that's the WPiOS PR I was referring to 👍
