### ISSUE TITLE
Align "Your site has been created!" between Android and iOS

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#3053]
## Description
The final site creation screen differ between iOS and Android in the following:
* iOS has no subtitle
* The button text is different (`OK` vs `Done`)
* The header font is different

## Screenshot

![Screenshot 2021-01-26 at 4 48 56 PM](https://user-images.githubusercontent.com/304044/105866366-94eeb000-5ffc-11eb-80ae-6c782b5c9157.png)

**Comment by antonis** [comment]
Hello @kyleaparker, @iamthomasbishop 👋
we noticed the above minor differences between the two platforms and thought would be good to align them.
Those are legacy differences since we haven't tweaked this part in the HPP project.
Do you think we should align and if yes which is the right approach?
cc @chipsnyder

**Comment by iamthomasbishop** [comment]
Good call, @antonis. My first thought was that a descriptive subtitle (like on Android) is fine, but that specific copy doesn't make as much sense to me now that we have a more visual theme/layout driven process prior to that point. If we can come up something a bit more contextually relevant there — such as a message of encouragement or congrats — I'd apply it across both platforms.

Regarding the `OK`/`Done` buttons, agreed that we should align the platforms but I'm not bullish on what we use as long as it's consistent with other similar cases.

**Comment by kyleaparker** [comment]
We are working on adding a browser frame in the empty state of the [choose a domain screen](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3019#issuecomment-768472634). It would be nice if the frame was the same on both of these screens, and we could also update the header to match the other screens during site creation. Here are a couple of examples: 

Flat 
![Flat](https://user-images.githubusercontent.com/712873/106045477-f96a4780-60ae-11eb-912a-163046dd5474.png)

Raised
![Raised](https://user-images.githubusercontent.com/712873/106045494-fe2efb80-60ae-11eb-946c-b791999f1ede.png)

I've left the "Done" copy in here for now, but we could also change it to something more actionable such as "Start editing". WDYT?

**Comment by antonis** [comment]
Hey @kyleaparker 👋 
I like your proposals. I will start working on this along the choose domain screen.

> I've left the "Done" copy in here for now, but we could also change it to something more actionable such as "Start editing". WDYT?

Ok. I'll try the `Start editing` and review this in the PR for possible changes.

**Comment by antonis** [comment]
As reported in https://github.com/wordpress-mobile/WordPress-Android/issues/13925 we can also enhance this screen to keep the selected preview mode
Internal ref `p5T066-1K5#comment-6952`

**Comment by chipsnyder** [comment]
We are currently scoping out a project (ref `pb3aDo-NT#comment-1454`) that might end up replacing this screen. So putting this on hold for now.

**Comment by antonis** [comment]
Closing this issue as deprecated
