### ISSUE TITLE
Adding a link to text is inconsistent with where the cursor moves to at the end.

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#3057]
**Describe the bug**
Depending on how you dismiss the link settings box: you could run into a situation where either the selected text will remain selected, or the cursor will move to the end of the text, which causes a confusing user experience.

**To Reproduce**
1. Create a new post
2. Add some text to the paragraph block.
3. Go add a URL to your clipboard (if it's not already there)
4. Highlight some text including a trailing whitespace
    - This was difficult to reproduce consistently so take a look at the linked video
5. Open the link settings
6. Notice the URL is auto-populated
7. Dismiss the settings box by swiping
8. Notice the entire text is highlighted

Alternate flow
1. Double-tap on a word to select it
2. Open the link settings
3. Notice the URL is auto-populated
4. Dismiss the settings box by swiping
5. Notice the cursor is at the end of the word

**Expected behavior**
After applying a link we should have a consistent experience ideally the cursor will move to the end of the previously selected text so that we can continue typing our posts.

**Screenshots**
<kbd><a href="https://user-images.githubusercontent.com/3384451/105914007-b733fe00-5ffb-11eb-999c-206ee2c0a596.gif"><img width="300" src="https://user-images.githubusercontent.com/3384451/105914007-b733fe00-5ffb-11eb-999c-206ee2c0a596.gif"/></a></kbd>

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.5.1
 - Tested in WP iOS 16.5

**Additional context**
On Android, no text is selected and the block loses focus. It would be nice if the cursor remained selected.

**Comment by fluiddot** [comment]
👋 @chipsnyder I see this issue is assigned to `1.46` milestone, since we're cutting the release I'll bump this to `1.47`. Please let me know if you think it needs to be included in this release, thanks!.

**Comment by geriux** [comment]
For the android behavior, I created a [new issue](https://github.com/WordPress/gutenberg/issues/28748) since its not related to the link selection.
