### ISSUE TITLE
Documentation: Note for Android Studio/Xcode Configurations

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#3062]
Android Studio is listed as a prerequisite in the README.md but there isn't any note about the fact some changes are needed to the default set up in order to get the demo app working correctly with it. I ended up falling down a bit of a rabbit hole with this as I had Android Studio already and had been successfully using it for app development, but couldn't figure out why I couldn't get the demo app working.

The specific configurations I needed to make are listed in React Native's documentation here: https://reactnative.dev/docs/environment-setup

I think it'd be useful to add a quick note about this in our README.md, it'd have saved me a bit of time.

**Comment by designsimply** [comment]
omg thank you!
