### ISSUE TITLE
Contact Info Block is Missing Inner Blocks

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#3064]
**Describe the bug**
When inserting a contact info block, inner blocks (address, email, phone, etc) that normally come with it are gone.

**To Reproduce**
1. Go to post, open block inserter.
2. Click on 'Contact Info'
3. See blank block inserted instead of block with address/email/phone inner blocks.

**Expected behavior**
Contact info blocks should come with inner blocks.

**Screenshots**
### Issue
![contactinfo](https://user-images.githubusercontent.com/13263478/106071809-9daeb700-60cc-11eb-8ced-095f2d0a2d29.gif)
<img width="394" alt="Screen Shot 2021-01-27 at 20 12 25" src="https://user-images.githubusercontent.com/13263478/106071813-9edfe400-60cc-11eb-9101-0f0e61504b59.png">

### Expected
<img width="394" alt="Screen Shot 2021-01-27 at 19 59 42" src="https://user-images.githubusercontent.com/13263478/106071843-a901e280-60cc-11eb-99d2-618910807a81.png">

**Additional context**
Dev note: Issue started since `gutenberg-mobile` commit [73ec0c7f7](https://github.com/wordpress-mobile/gutenberg-mobile/commit/73ec0c7f7cec9c50b070dd8cc3731feb358c9d49). Might be caused by changes on `gutenberg/master` between `e4eb4b` and `ce37b6`, which was the [reference update in the latest gutenberg-mobile commit](https://github.com/wordpress-mobile/gutenberg-mobile/commit/c7ef7ff27620314a814b4b7626a3b04d9e6f178a).

**Comment by hypest** [comment]
👋 @illusaen , looks like you have a PR on going to fix this, thanks!

Judging from you fix PR, is it fair to say that https://github.com/WordPress/gutenberg/pull/28489 is the change that broke the Contact Info block?

I wonder, can we add a simple test (UI/snapshot or other) to capture the basic rendering of the Contact Info block to avoid this type of basic breakage?

**Comment by mzorz** [comment]
> Judging from you fix PR, is it fair to say that WordPress/gutenberg#28489 is the change that broke the Contact Info block?

👋 Just chiming in to say I can confirm setting the gutenberg hash to https://github.com/WordPress/gutenberg/commit/a596309b088b0de2b36507fc04488b02ca99e698 which is the commit just previous to https://github.com/WordPress/gutenberg/commit/ce37b6bff504198dc263eed7058318e0fb9d6cdb (the merge commit for WordPress/gutenberg#28489), shows the Contact Info block rendering correctly so yes, the changes in WordPress/gutenberg#28489 introduced the problem for the Contact Info block.

**Comment by illusaen** [comment]
@hypest It was actually [commit 1e90244](https://github.com/WordPress/gutenberg/commit/1e90244af08459a56c84c8d083ba159f52ce9039) that broke the inner blocks for Contact Info. Hrmm, I think a UI test would work best as the inner blocks are technically still there; they're just not rendered so I'm not sure a snapshot would capture the issue.

**Comment by mzorz** [comment]
>  It was actually commit 1e90244 that broke the inner blocks for Contact Info. 

Oh wow that commit belongs to a previous PR - I wonder why my tests narrowed it down to https://github.com/WordPress/gutenberg/pull/28489 (in my checks, the commit right before the merge of this later PR shows the Contact Info block rendering correctly).

Nevermind, glad you were able to pinpoint that one and have a fix for it @illusaen ! 😄

**Comment by illusaen** [comment]
@mzorz Huh, that is interesting, hehe. I'm not sure; I can see how that would also cause the issue (adding `isRootList` to the if statement) would cause the `blockWidth` to not get set to `layoutWidth`. I wonder if it broke, got fixed, broke again, and now got fixed again haha.

**Comment by hypest** [comment]
> Hrmm, I think a UI test would work best as the inner blocks are technically still there; they're just not rendered so I'm not sure a snapshot would capture the issue.

Fine by me 👍, whichever test type can guard the super basic functionality of rendering the block fully and correctly. Go ahead with either opening a follow up ticket to include such a test, or add a checklist item in this ticket, which ever works better for you. Either way, I feel it makes sense for us to work on it right after the fix PR.

**Comment by illusaen** [comment]
@hypest Makes sense haha. Adding UI test to the gutenberg-mobile PR connected to this one.
