### ISSUE TITLE
Undo/redo: Undoing a "enter for new block" action seems to add several actions to the Undo history

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#307]
Undoing a "enter for new block" action seems to add several actions to the Undo history:
1. launch the app
2. tap in the middle of "Wel|come" in the "Welcome to Gutenberg" title
3. tap enter key
4. observe a new block is created
5.a tap `undo`, observe first tap does nothing
5.b tap `undo` again, observe new block is deleted, and "Welcom|" gets formed in the original block
5.c tap `undo` again, observe the original block now really gets the original content "Welco|me to Gutenberg", and see the cursor is after the "o" in "Welcome".

Expected behavior:
- After step 4, tapping `undo` should bring state to step 1.

**Comment by mzorz** [comment]
This issue is mirrored on GB side in https://github.com/WordPress/gutenberg/issues/8882 and this PR https://github.com/WordPress/gutenberg/pull/11005 addresses it. 

Leaving this one open till then.

**Comment by mchowning** [comment]
Just wanted to leave a note that in testing on Android I cannot recreate the issue in the "Welcome to Gutenberg" title, but I can recreate the issue (or rather very similar issues) in other blocks. 

## Heading
1. launch app
2. tap in the middle of "What is Gute|nberg?" heading
3. tap `enter` key
4. observe a new heading block is created, so heading block 1 contains "What is Gute", and heading block 2 contains "nberg?"
5. tap `undo`, observe heading block 1 is restored to "What is Gutenberg?", but heading block 2 still contains the cursor and "nberg?"
5. tap `undo` a 2nd time, heading block 2 is removed, heading block 1 still contains "What is Gutenberg?"

![output_heading](https://user-images.githubusercontent.com/4656348/56073418-9391bc00-5d71-11e9-887c-f7dae55f58ee.gif)

## Paragraph

Same behavior as headings.

## List
1. launch the app
2. Scroll to the list block containing 5 list items at the bottom of the screen
3. Tap at the end of the second list item
4. tap `enter` key, observe that a new empty list item is created in the third position on the list
5. tap `enter` key again, observe that two new list blocks are created, so we now have 
   - The original list block containing the first 2 of the 5 items in the original list; 
   - An empty paragraph block containing the cursor, but no text; and 
   - A new list block containing the last 3 items from the original list.
6. tap `undo`, observe the first tap does nothing
7. tap `undo` a 2nd time, observe that the empty paragraph block and the second list item block are removed. The original list item block remains, but it only contains the first two items from the list. _The 3rd, 4th, and 5th list items have disappeared._
8. tap `undo` a 3rd time, observe that the list block has been restored to its original state with 5 list items.

![output_list](https://user-images.githubusercontent.com/4656348/56073443-eff4db80-5d71-11e9-9829-30c7e394d019.gif)

**Comment by SergioEstevao** [comment]
I've retested this on the last version and all the issues above look they are fixed.
So blocks are restored the correct status after undo, the only issues I see is the positioning of the cursor after the undo.
But that is mentioned on this ticket here #303
