### ISSUE TITLE
Add support for Search Block

### ISSUE THREAD

**Issue by AmandaRiu** [wordpress-mobile/gutenberg-mobile#3073]
## Description
Add support for the search block to the mobile platform. The **Search block** returns results from the titles and the bodies of posts and pages, and from media titles, alt text, file names, and single image captions. It will not return results from widgets, comments, categories, gallery captions or other text, or tags.

Also, note that the search results will display posts with the matching term in the post title in reverse-chronological order. Then, it will display posts with the matching term in the post body in reverse-chronological order. So for example, if you have just published a post about Michigan titled “This Weekend,” and you also have an older post titled “Michigan,” searching for ‘Michigan’ will display that older post, with Michigan in the title, at the top of the list.

![Screen Shot 2021-01-29 at 5 40 23 PM](https://user-images.githubusercontent.com/5810477/106334681-2d816c00-6259-11eb-8ac4-e7c8821d74b3.png)

Block configuration options:
- Change the text of the placeholder
- Change the button text
- Use an icon instead of button text
- Toggle search label
- Configure search button position
- Change the width of the block (custom | 25% | 50% | 75% | 100%)

## Tasks

TBD

**Comment by AmandaRiu** [comment]
@iamthomasbishop @kyleaparker  - Any design considerations for this project?

**Comment by iamthomasbishop** [comment]
@AmandaRiu We haven't done any design work on the Search block quite yet. It's in our next set of projects, so realistically it'll probably be 2-3 weeks until we can focus any meaningful amount of time on it. However, if it's ready to be worked on on your side, in the meantime we (@kyleaparker or I) can probably do a quick pass at discovery in order to analyze the web flow and make note of any potential snags and/or differences vs our approach on web. Would that help?

**Comment by AmandaRiu** [comment]
> @AmandaRiu We haven't done any design work on the Search block quite yet. It's in our next set of projects, so realistically it'll probably be 2-3 weeks until we can focus any meaningful amount of time on it. However, if it's ready to be worked on on your side, in the meantime we (@kyleaparker or I) can probably do a quick pass at discovery in order to analyze the web flow and make note of any potential snags and/or differences vs our approach on web. Would that help?

@iamthomasbishop I have started the project so if you or @kyleaparker can do a quick pass that would be great. It's still an onboarding project for me so it's likely to be a while till I need actual designs so don't rush, but it'd be good to have something before I get too deep into the project. Thanks!

**Comment by AmandaRiu** [comment]
Search block was implemented [in this final PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3210). Closing.
