### ISSUE TITLE
Undo/redo: cursor positioning when undoing action that happened on another block

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#309]
This happens when try undoing changes that were done on different blocks

#### Steps to reproduce:

1. tap on a block and type a letter.
2. tap on another block
3. type something else there
4. now tap undo, observe the last change is undone.
5. tap undo again, you'll notice the changes in the previous block get undone, but the focus and caret remain on the block tapped on step 2.

#### Expected:
It should bring the focus to the block where the undo is working on, along with the block being selected, and if needed, the screen should scroll to show it and make it visible.

Note: I tested the same on Gutenberg web (same steps as above on a post with several blocks), and they don't show a caret nor scroll to the position where the change is happening, but I think in mobile it's even  more apparent that it's something we need to show. I'm lost as to not having any kind of feedback of what is being "undone".

**Comment by koke** [comment]
> they don't show a caret nor scroll to the position where the change is happening

I think we should move this to an issue in the Gutenberg repo and continue the conversation there. This sounds like something worth fixing on the web as well. @mzorz can you take care of that?

**Comment by SergioEstevao** [comment]
I've tested this again and it now it's working correctly: when undoing the focus moves to the block where the undo is happening.
