### ISSUE TITLE
Characters are misplaced when pressing enter within Pullquote or Quote block text

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#3105]
**Describe the bug**

When you create a Pullquote or Quote and you press enter multiple times in the middle of the block's content it starts moving the cursor a character forward and then it puts that character on a new line.

First reported by @jd-alexander [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2874#issuecomment-742236687).

**To Reproduce**
1. Add a Quote block to the editor
2. Add a couple of lines of text
3. Place the cursor somewhere in the middle of that text
4. Press enter repeatedly and notice that as new lines are created, characters are unexpectedly shifted down on to these new lines

**Expected behavior**
Pressing enter should create blank new lines

**Screenshots**

| Pullquote block | Quote block |
| - | - |
| <img src="https://user-images.githubusercontent.com/1509205/101722952-42bbf480-3a79-11eb-9cb5-1181b35a0295.gif" width="320"> | <img src="https://user-images.githubusercontent.com/1509205/101722959-48b1d580-3a79-11eb-889b-ee9acce6c0e5.gif" width="320"> |

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 10
 - Version: WordPress for Android 16.6-rc-2

**Comment by fluiddot** [comment]
👋 I think this issue might be duplicated because I was checking the [Multiline components - Test Cases](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/multiline-components.md#multiline-components---test-cases) and I spotted that @jd-alexander already created an [issue](https://github.com/WordPress/gutenberg/issues/27690) for this.

**Comment by fluiddot** [comment]
I'm not sure if it's related to the device but I can't manage to reproduce it on my device, here is a video capture:

https://user-images.githubusercontent.com/14905380/106909551-b2103680-6700-11eb-9008-d17e36df4d69.mp4

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S20 FE 5G
- OS: Android 10
- Version: WordPress for Android - Pre alpha - Build 94309

**Comment by guarani** [comment]
> 👋 I think this issue might be duplicated because I was checking the [Multiline components - Test Cases](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/multiline-components.md#multiline-components---test-cases) and I spotted that @jd-alexander already created an [issue](https://github.com/WordPress/gutenberg/issues/27690) for this.

Silly me, I'd only checked the Gutenberg Mobile repo and not the Gutenberg repo. Thanks for flagging this as a dupe, closing.

**Comment by guarani** [comment]
> I'm not sure if it's related to the device but I can't manage to reproduce it on my device, here is a video capture:
> quote-block-multiline.mp4
> 
> **Smartphone (please complete the following information):**
> 
>     * Device: Samsung Galaxy S20 FE 5G
> 
>     * OS: Android 10
> 
>     * Version: WordPress for Android - Pre alpha - Build 94309

I could reproduce this today on 16.6-rc-2, but maybe you could add that comment to the other issue for better visibility.
