### ISSUE TITLE
Add Analytics event to capture when a category filter is selected

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#3130]
## Description
When selecting a category in the Starter Page Picker, or the Home Page Picker (after https://github.com/wordpress-mobile/gutenberg-mobile/issues/3125) we'd like to fire an analytics event to track the engagement.

## Details

~- Event Name`filter_changed`~
~- Properties~
    ~- `location` = `site_creation` or `page_picker`~
    ~- `filter` = the selected filter(s) comma seperated~ 
    
Update to the requirements after testing this out some

- Event Name`category_filter_selected`
- Properties 
    - `location` = `site_creation` or `page_picker`
    - `filter` = the selected filter
    - `selected_filters` = the selected filter(s) comma separated 
    
- Event Name`category_filter_deselected`
- Properties 
    - `location` = `site_creation` or `page_picker`
    - `filter` = the deselected filter
    - `selected_filters` = the selected filter(s) comma seperated or empty string
    
So when I tap `blog` I should see:
`Tracked: category_filter_selected, Properties: {"location":"page_picker", "filter":"blog", "selected_filters":"blog" }`

Then tapping `splash` will give
`Tracked: category_filter_selected, Properties: {"location":"page_picker", "filter":"splash", "selected_filters":"blog,splash" }`

Then deselecting `splash` will be
`Tracked: category_filter_deselected, Properties: {"location":"page_picker", "filter":"splash", "selected_filters":"blog" }`

and deselecting `blog`
`Tracked: category_filter_deselected, Properties: {"location":"page_picker", "filter":"blog", "selected_filters":"" }`

**Comment by antonis** [comment]
The new `filter_changed` event should be registered in tracks as part of this issue.

**Comment by antonis** [comment]
Pending iOS and registering tracks events

**Comment by chipsnyder** [comment]
Still pending: registering tracks events

**Comment by antonis** [comment]
Track events merged:
* https://github.com/Automattic/tracks-events-registration/pull/463
* https://github.com/Automattic/tracks-events-registration/pull/464
* https://github.com/Automattic/tracks-events-registration/pull/465
* https://github.com/Automattic/tracks-events-registration/pull/466
