### ISSUE TITLE
Test plan for 16.7 Beta version of WordPress Android app

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#3133]
Due to the recent issue regarding the merged [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13699) into `WordPress-Android` repository, we have to execute a specific test plan to ensure that it didn't break anything.

**This plan will be executed only on Android.**

- [x] [Writing flow tests](https://github.com/wordpress-mobile/test-cases/tree/trunk/test-cases/gutenberg/writing-flow) - @fluiddot 
- [x] Random tests from the [sanity check test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-tests.md) (preferably one test from each section to cover a wide range) @ceyhun 
- [x] Smoke test the editor flow in general by doing: @fluiddot 
  - Entering exiting the editor
  - Rotate the device in various cases
  - Open and dismiss the bottom sheet
  - Background the app and foreground it again

**Comment by ceyhun** [comment]
### Android Sanity Tests 🟡

WPAndroid 16.7-rc1, Huawei P20 Lite, Android 10

Gallery-1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)

MediaText-1

- [x] Media Text block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)

MultipleUpload-1

- [x] Simultaneous uploads - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)

DarkMode-1

- [x] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)

Shortcode-1

- [x] Shortcode block - Add a youtube link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/shortcode.md#tc001)

Spacer-1

- [x] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)

Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)

Group-1

- [x] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)

Cover-1

- [x] Cover - Add image background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)

Columns - 1

- [x] Columns - Columns percentage mechanism - column's preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc019)

Editor Theme - 1
- [x] Default Colors - Check that default colors still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001)

Color Settings - 1 
- [x] Colors Segmented Controls - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001)

Social Icons - 1
- [x] The newly created Social Icons block is added with 4 icons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc001)

Story block - 1
- [x] Story block - Verify is available in Block Picker - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc001)
- [x] Story block - Verify is not available in Block Picker- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc002)
- [x] Story block - Add media to empty Story block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc003) 🟡
  - While uploading multiple images, the progress bar at the top keeps disappearing and re-appearing for me. Same issue exists on version 16.6. (internal reference: pbD5rk-mE-p2#comment-452)
- [x] Story block - Add media to non-empty Story block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc004)
- [x] Story block - Close/Re-open post with an ongoing Story upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc005)

**Comment by fluiddot** [comment]
### Android: Writing Flow checklist 🟡

**Tested on Samsung Galaxy S20 FE 5G, Android 10 - Version 16.7-rc-1**

#### General
- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components 🟡  
    - **Text flickering when removing a line on some multiline blocks** - #3096
    - **Pullquote Block - Wrong cursor position when merging back** - #308
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
      - **Link button - Remove link when the word is selected doesn't remove it** - #3134
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection 🟡
    - **Heading block stops being rendered as a header when deleting the first word** - https://github.com/wordpress-mobile/gutenberg-mobile/issues/3106
    - **Splitting paragraph block - Deleting the first word after selecting it requires tapping backspace two times** - #3135 
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format 🟡
    - **Undo/redo - Apply text format to a link breaks the undo functionality** - #3136

### Result

I've spotted three new issues I missed when testing the editor release but none of them are new regression issues, I tested on the latest released version `16.6` and they are also reproducible there.

#### Issues spotted on editor release `1.46.0` (not new)
- Text flickering when removing a line on some multiline blocks - #3096
- Pullquote Block - Wrong cursor position when merging back - #308
- Heading block stops being rendered as a header when deleting the first word - https://github.com/wordpress-mobile/gutenberg-mobile/issues/3106

#### Issues spotted on this run (new but not regression)
- Link button - Remove link when the word is selected doesn't remove it - #3134
- Splitting paragraph block - Deleting the first word after selecting it requires tapping backspace two times - #3135  
- Undo/redo - Apply text format to a link breaks the undo functionality - #3136

**Comment by fluiddot** [comment]
### Android: Smoke test checklist 🟡

**Tested on Samsung Galaxy S20 FE 5G, Android 10 - Version 16.7-rc-1**

- [x] Entering exiting the editor
- [x] Rotate the device in various cases
    - [x] Rotate with no block selected
    - [x] Rotate with a block selected
    - [x] Rotate with the keyboard opened 🟡
      - **Keyboard window is dismissed on second rotation** - #3137
    - [x] Rotate with the bottom sheet opened
- [x] Open and dismiss the bottom sheet
    - [x] Open the bottom sheet
    - [x] Dismiss it by tapping outside
    - [x] Dismiss it by dragging it to the bottom
- [x] Background the app and foreground it again
    - [x] Go to opened apps and back to the app
    - [x] Go to home screen and back to the app
    - [x] Close the app and open it again
- [x] Make some changes in a post, close the app, open it again and verify that the changes are saved

### Result

Only one issue has been spotted and it's not new, I tested on the latest released version `16.6` and it's also reproducible there.
