### ISSUE TITLE
Test plan for Beta fix 1.46.1 (iOS only)

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#3148]
This plan describes the steps to be executed to ensure that the beta fix `1.46.1` is safe to be released in WordPress version `16.7`.

**This plan will be executed only on iOS because Android was already tested in a beta version that included the same changes, the results can be checked in the [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3133).**

- [x] [Writing flow tests](https://github.com/wordpress-mobile/test-cases/tree/trunk/test-cases/gutenberg/writing-flow) - @ceyhun 
- [x] Random tests from the [sanity check test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-tests.md) (preferably one test from each section to cover a wide range) - @fluiddot 
- [x] Smoke test the editor flow in general by doing: @fluiddot 
  - Entering exiting the editor
  - Rotate the device in various cases
  - Open and dismiss the bottom sheet
  - Background the app and foreground it again

**Comment by ceyhun** [comment]
### Writing Flow checklist 🟢 

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

<p style="clear:both;"><sup>Tested with iPhone 11 Pro, iOS 14.3, WPiOS 42199</sup></p>

**Comment by fluiddot** [comment]
### Sanity Tests 🟡 

WPiOS 16.7 - build 42258, iPhone 11 - iOS 14.2

Gallery-1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)

MediaText-1

- [x] Media Text block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)

MultipleUpload-1

- [x] Simultaneous uploads - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)

DarkMode-1

- [x] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)

Shortcode-1

- [x] Shortcode block - Add a youtube link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/shortcode.md#tc001)

Spacer-1

- [x] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)

Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)

Group-1

- [x] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)

Cover-1

- [x] Cover - Add image background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Image focal point is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)

Columns - 1 🟡 
- [x] Columns - Columns percentage mechanism - column's preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc019)
- [x] Columns - Columns percentage mechanism - column's slider input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc020)
    - **`NaN` value when using `,` char, this depends on the device's region but on mine (Spain) the only option in the keyboard is that one**.
- [x] Columns - Columns percentage mechanism - predefined percentage values are rendered correctly on frontend- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc021)
    - **When picking `30/70` or `70/30` layouts, the width values are `33.3%` and `66.6%` instead of the ones picked.**
- [x] Columns percentage mechanism - custom percentage values are rendered correctly on frontend- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc022)
- [x] Columns - Multiple slider in columns parent - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc023)
- [x] Columns - Columns block is added with default number of Column - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc001)
- [x] Columns - Adding Column with AppenderButton - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc003)
- [x] Columns - Adding and removing Column with BottomSheet Stepper control - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc004)

Editor Theme - 1
- [x] Default Colors - Check that default colors still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001)

Color Settings - 1 
- [x] Colors Segmented Controls - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001)

Social Icons - 1
- [x] The newly created Social Icons block is added with 4 icons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc001)

**Comment by fluiddot** [comment]
### iOS: Smoke test checklist 🟡

**WPiOS 16.7 - build 42258, iPhone 11 - iOS 14.2**

- [x] Entering exiting the editor
- [x] Rotate the device in various cases
    - [x] Rotate with no block selected
    - [x] Rotate with a block selected
    - [x] Rotate with the keyboard opened 🟡
      - **On landscape, tapping on a paragraph with text doesn't position the view properly**
    - [x] Rotate with the bottom sheet opened
- [x] Open and dismiss the bottom sheet
    - [x] Open the bottom sheet
    - [x] Dismiss it by tapping outside
    - [x] Dismiss it by dragging it to the bottom
- [x] Background the app and foreground it again
    - [x] Go to opened apps and back to the app
    - [x] Go to home screen and back to the app
    - [x] Close the app and open it again
- [x] Make some changes in a post, close the app, open it again and verify that the changes are saved

**Comment by fluiddot** [comment]
I've tried to reproduce the spotted issues so far on the current version of the AppStore (version `16.6.1`) and I managed to reproduce all of them so they're not new regressions.
