### ISSUE TITLE
Add support for sticky posts

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/gutenberg-mobile#3158]
Add support for setting a post as sticky.

Here's a design proposal:

![mark_as_sticky_on_app_i1](https://user-images.githubusercontent.com/36741426/43086208-1d3b38cc-8e9d-11e8-9275-be43490b741e.jpg)

(Migrated from wordpress-mobile/WordPress-Editor-Android#88)

**Comment by rezzap** [comment]
From a 4 star app review:

> Wish it allowed me some functions as with the site's app, like 'stick post to top of blog.' 
> 
> <sup>Feb 12, 2021, 03:26, Device: Huawei HUAWEI Y7 Pro 2019</sup>

**Comment by eduardozulian** [comment]
Also in 3813375-zen

**Comment by guarani** [comment]
Added a Android label to make it clear that making posts Sticky is already supported on WPiOS, but is missing from WPAndroid.

<img src="https://user-images.githubusercontent.com/1898325/112330519-dfa44580-8c96-11eb-8eeb-2cee5e04941b.jpg" alt="" width="250">

**Comment by jhnstn** [comment]
Also in 3961356-zen

**Comment by jd-alexander** [comment]
I am closing this issue as the addition of this option is in relation to changes of the Post Settings screen within the Android app. If necessary, it can be reopened at a further time. The work to include this option will be tracked on this issue https://github.com/wordpress-mobile/WordPress-Android/issues/7953
