### ISSUE TITLE
Add help behavior to the SwitchCell component

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/gutenberg-mobile#3169]
## Description

The `help` behavior should be added to the `SwitchCell` component. The use case for this at the moment is with the Video & Audio Block that requires the user to be informed about the usability implications that will be experienced by users if the `autoplay` attribute is enabled on the block in question. 

### Web
<img width="289" alt="autoplay" src="https://user-images.githubusercontent.com/1509205/108244409-301b0700-711d-11eb-8cd8-976262668a22.png">

### Mobile
![Image from iOS](https://user-images.githubusercontent.com/1509205/108244440-3b6e3280-711d-11eb-9a0e-482f33e9d040.jpg)

The proposed option is # 1  based on design specs below by @iamthomasbishop 

- In-cell subtitles are meant for short labels. 
- Footnotes can get quite long as well, so it's best to utilize them without a divider.

**Comment by mchowning** [comment]
:wave: @jd-alexander ! I think you're more familiar with this feature request than I am. Would you mind selecting a priority label that you think is appropriate for this?

**Comment by jd-alexander** [comment]
> :wave: @jd-alexander ! I think you're more familiar with this feature request than I am. Would you mind selecting a priority label that you think is appropriate for this? 

Sure @mchowning I will do that. Should I put a priority label on all issues I create?

**Comment by mchowning** [comment]
Thanks @jd-alexander ! 🙇 

> Should I put a priority label on all issues I create?

If you have a sense for what the priority should be, that would definitely be helpful since you'll probably have the most context around the issue. If you don't add a priority, then whoever triages new issues will assign a priority.

**Comment by jd-alexander** [comment]
> Thanks @jd-alexander ! 🙇 
> 
> 
> 
> > Should I put a priority label on all issues I create?
> 
> 
> 
> If you have a sense for what the priority should be, that would definitely be helpful since you'll probably have the most context around the issue. If you don't add a priority, then whoever does triages new issues will assign a priority.

Understood. Thanks for clearing that up 🙏🏾
