### ISSUE TITLE
Some toolbar buttons are hidden when in a heading block

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#317]
When a heading block is focused, the Toolbar gets populated with enough buttons to cause an "overflow" and some buttons are pushed outside the view. The toolbar is not scrollable so, those overflown buttons are not reachable.

![screenshot-1543937884364](https://user-images.githubusercontent.com/1032913/49453454-d48a2a80-f7eb-11e8-8a4b-e7c094873f59.jpg)

**Comment by marecar3** [comment]
Hey @hypest ,
Should I solve this one with as high priority task?

Maybe adding horizontal scroll view would be a good and quick solution for the alpha release? @koke @hypest @iamthomasbishop 

Thanks.

**Comment by hypest** [comment]
A horizontal scroll could be a stop gap solution for the Alpha but I'll let @iamthomasbishop chime in as well.

**Comment by iamthomasbishop** [comment]
Absolutely, the user should be able to scroll the toolbar horizontally.
