### ISSUE TITLE
Switching sites within block editor on iOS does not update Audio block availability

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/gutenberg-mobile#3171]
**Describe the bug**
When switching sites using the in-editor select menu for iOS, the Audio block availability is not updated.

**To Reproduce**
1. Launch iOS app.
2. Create a new post in a paid/self-hosted site.
3. Verify Audio block is available.
4. Switch to a free site _from within the block editor_ by tapping the site title atop the editor.

**Expected behavior**
The Audio block should not be available.

**Screenshots**

https://user-images.githubusercontent.com/438664/108281553-90be3a00-7145-11eb-93ac-f83d5a2c46ee.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 14.4
 - Version: `1.47.0` release build ([link](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3155#issuecomment-780896585))

**Additional context**
This is related to #3129.

**Comment by hypest** [comment]
Closing as non applying anymore since the site switcher [has been removed from inside the editor](https://github.com/wordpress-mobile/WordPress-iOS/pull/16158).
