### ISSUE TITLE
Update styling of the "more" block

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#318]
The `more` block currently has some `<!-- -->` around it to emulate the original/html representation of the "more" link. We have better alternatives now (check out the styled "Page break" block) so it's type to update the styling of the `more` block too.

![screenshot-1543939041348](https://user-images.githubusercontent.com/1032913/49454760-832f6a80-f7ee-11e8-9ab8-bc3a97c3a714.jpg)

**Comment by pinarol** [comment]
This is resolved in alpha.

**Comment by pinarol** [comment]
Sorry I might have confused with the next page block :)
