### ISSUE TITLE
App Review Feature Request: Add image through URL

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#3190]
> Can I add photos via URL using the app? Haven't found a way so far.

App review date: Feb 23, 2021, 12:00
Device: Device: Google Pixel 4
Android version (SDK): Android 11 (SDK 30)
App version name: 14.6.1
App Review ID on Google Play Store: play-store-previewId=gp%3AAOqpTOEsio6S6I-0X99uo2eI8cDMGsRwGhrMh9w_l7uA1ZMPeZwSzM6NcZmlQ5QBFSYOd9RciXn_9caJOvwHKQ

Calypso and the Image block supports adding an image through the URL but it's not supported in the app yet.

**Comment by hypest** [comment]
Changed the title to replace the "Upload" word with "Add" since the feature will not actually be **uploading** any media to the site or media Library.
