### ISSUE TITLE
Classname to style conversion isn't working

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#320]
It seems that after [this PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/310/files)  classname to style conversion isn't working anymore. 

Side effects can be seen on Format Toolbar, where all buttons have black color in both active and inactive state.

**Comment by Tug** [comment]
Investigating.
I  bet we can find other ways to have those styles back in our UI, the `classname-to-style` transform applies also to the `save()` method which creates invalid html when serialization occurs.
