### ISSUE TITLE
[Android] Remove Cancel button in bottom sheets

### ISSUE THREAD

**Issue by kyleaparker** [wordpress-mobile/gutenberg-mobile#3222]
I came across several places where we're showing a "Cancel" button in popups from the bottom sheet on Android. @iamthomasbishop had mentioned that this shouldn't be the case.

The blocks include (from left to right): Video, Gallery, Latest Posts, and File 
<img width="1063" alt="Screen Shot 2021-03-05 at 10 12 27 AM" src="https://user-images.githubusercontent.com/712873/110134389-55557980-7d9b-11eb-9242-9af1f5de114a.png">

**Comment by AmandaRiu** [comment]
I'll take this one. Need something small to give my brain a little break from troubleshooting more complex code.
