### ISSUE TITLE
Discuss: Have a styling solution that is close to gutenberg web's

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#323]
With some [recent changes](#310), the React Native app can't use the `className` property from Gutenberg-web anymore. Instead, it relies on the `style` property which is native to RN.

It would be good if we could put a solution in place that is as close as possible to Gutenberg web's so the RN app reuses any logic about styling that the web project has.

Let's discuss.

**Comment by SergioEstevao** [comment]
I think the [implementation of global styles](https://github.com/WordPress/gutenberg/pull/21637#event-3255155543) is the solution for this issues.
