### ISSUE TITLE
Translations broken in the block picker

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#3269]
**Describe the bug**

**This is a bug affecting the current 1.48.1 release (WPiOS 16.9), not 1.47.x (WPiOS 16.8).**

The block inserter isn't displaying block names in the device language (e.g. German).

**To Reproduce**
1. Download the 16.9 beta from TestFlight
2. Switch your device over to German (or any other supported non-English language)
3. Open the block editor
4. Open the block inserter and notice that block names appear in English instead of German
5. Other parts of the editor may also have missing translations

**Expected behavior**
On a device with a language set to German, block names should appear in German, as they did in 16.8.

**Screenshots**
<img src="https://user-images.githubusercontent.com/1898325/111379307-bcb7d700-8681-11eb-92eb-4e3c3f9e4cb9.jpg" alt="German translation not showing up" width="350"> 

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.4
 - Version 16.9 beta

**Additional context**
This does **not** affect Android, I tested WPAndroid 16.9 beta and the translations look fine there.

**Comment by hypest** [comment]
Added the "Pri High" label as this is about a core feature: i18n.

**Comment by mchowning** [comment]
Related issue: [Strings from Jetpack are not included in the bundle](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2615)

**Comment by mchowning** [comment]
Do you think we can close this issue @fluiddot ?

**Comment by fluiddot** [comment]
> Do you think we can close this issue @fluiddot ?

Yeah, this issue has been fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/3423.
