### ISSUE TITLE
[Embed block] Add the top 5 specific embed blocks to the Block inserter list

### ISSUE THREAD

**Issue by ceyhun** [wordpress-mobile/gutenberg-mobile#3278]
### Description
- Add the top 5 specific embed blocks to the Block inserter list:
    - YouTube
    - Twitter
    - WordPress
    - Instagram
    - Vimeo

- ~~Will use colored versions of icons~~ We finally decided to not use the colored versions of the icons ([internal reference](p1632907802004300-slack-C01MTUVN9T3)).

- ~~**Needs research**: These are not necessarily the ones in the screenshot, should look into data to find out the top 8 most-used ones.~~ The list of most-used providers was defined in https://github.com/wordpress-mobile/gutenberg-mobile/issues/3816#issuecomment-907250152.

### Screenshot
<img width="300" src="https://user-images.githubusercontent.com/1845482/115038124-83b49180-9ecf-11eb-849b-f96933c8aba7.jpg">

**Comment by fluiddot** [comment]
I updated the title and description of this issue to match the list of most-used providers that was defined [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3816#issuecomment-907250152).

The list is composed of the following five providers:
- YouTube
- Twitter
- WordPress
- Instagram
- Vimeo
