### ISSUE TITLE
Columns Block: 'number of columns' won't focus using TalkBack

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#3357]
**Describe the bug**
Using TalkBack in the Columns Block settings, when tapping “number of columns”, the cell does not retain focus when interacting. 
This makes it difficult to adjust the number of columns using Android's TalkBack screenreader.

**To Reproduce**
While using TalkBack on Android:
1. Create a Columns Block.
2. Double-tap the 'settings' gear icon to open it.
3. Touch "Number of Columns".
4. Note that "Number of Columns" is selected only momentarily.

It is possible to select "Number of Columns" by long-pressing, however it's very tricky to get right. I could select "Number of Columns" only 1 in 10 tries with this approach.
Note: When I was able to select "Number of Columns", it claimed this was a slider.

**Expected behavior**
Expected "Number of Columns" to be selected, and instructions for adjusting to be read.

**Video including TalkBack speech:**
https://user-images.githubusercontent.com/15107387/114167898-36b54600-9938-11eb-96fb-ce1049f7b054.mp4

**Smartphone:**
Tested on Samsung Galaxy S21, Android 11, WPAndroid 17.1-rc-1

**Additional context**
Initially reported by @bjtitus in p5T066-28a-p2

**Comment by mchowning** [comment]
Probably related to https://github.com/WordPress/gutenberg/pull/29741.

**Comment by guarani** [comment]
I have the same difficulty tapping on column sections e.g. `Column 1` if their unit is changed from Percentage to a different unit that doesn't use a slider (e.g. Pixels). Here's a video:

https://user-images.githubusercontent.com/1898325/114193864-eda3c880-991c-11eb-9119-3f4712e0d23b.mp4

**Comment by AmandaRiu** [comment]
> Probably related to [WordPress/gutenberg#29741](https://github.com/WordPress/gutenberg/pull/29741).

I verified this issue predates the changes in that PR 👍
