### ISSUE TITLE
Columns Block: extra values spoken by screenreader

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#3358]
**Describe the bug**
Using TalkBack or VoiceOver in the Columns Block settings, when tapping a particular column, extra digits are read out loud, though they are not shown in print.

**To Reproduce**
While using TalkBack on Android or VoiceOver on iOS (easier if you turn it on after setting the number of columns to 3):

1. Create a Columns Block, choose the 50|50 format.
2. Double-tap the 'settings' gear icon to open it.
3. Select "Number of Columns" and adjust to 3 columns.
4. Tap Column 1 (33.3%)
5. Note the voice reads "Width is 33.333333333333336 percent"

**Expected behavior**
I expected the value shown to be read as is.

**Videos including screenreader speech:**
These are both recorded with TalkBack on Android, but the same behavior exists in iOS.
32.67% read instead of 32.6%:
https://user-images.githubusercontent.com/15107387/114174264-0d4ce800-9941-11eb-9c3a-019f9377f755.mp4
33.333...36% read instead of 33.3%:
https://user-images.githubusercontent.com/15107387/114174322-20f84e80-9941-11eb-88ab-fc705988c7df.mp4

**Smartphone:**
Tested on Samsung Galaxy S21, Android 11, WPAndroid 17.1-rc-1
And iPhone SE, iOS14.4.2, iOS 17.1 Internal

**Additional context**
Initially reported by @bjtitus in p5T066-28a-p2

**Comment by mchowning** [comment]
Probably related to WordPress/gutenberg#29741.
