### ISSUE TITLE
Contact Info Block: Not shown in "add block" bottom sheet

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#3395]
**Describe the bug**
While I can view and edit a Contact Info Block added from the web, it's not possible to add one from the WP app (either iOS or Android) because the Contact Info Block doesn't appear in the block list when I tap the "+" icon.

**To Reproduce**
1. On a WordPress.com site or a self-hosted site with Jetpack version > 8.5, open a post or page.
2. Tap the "+" icon to add a new block.
3. Scroll down the list to find the "Contact Info" block.
4. Note that it is not listed.

**Expected behavior**
I expected the Contact Info Block to appear in this list, probably next to the recently added Story block.

**Screenshots**

iOS:
![IMG_593602F8270D-1](https://user-images.githubusercontent.com/15107387/115397501-d43d2f00-a1ee-11eb-8e36-33a1eb05421b.jpeg)

Android:
![Screenshot_20210420-152853_WordPress](https://user-images.githubusercontent.com/15107387/115398743-23379400-a1f0-11eb-8541-06351c65241e.jpg)
![Screenshot_20210420-152805_WordPress](https://user-images.githubusercontent.com/15107387/115398730-20d53a00-a1f0-11eb-996b-64f3475afa0e.jpg)

**Smartphone**
Samsung Galaxy S21, Android 11, WPAndroid 17.2-rc-1
iPhone SE, iOS 14.4.2, WPiOS 17.2

cc: @illusaen looks like you've worked on this feature recently in https://github.com/wordpress-mobile/gutenberg-mobile/pull/3340

**Comment by zwarm** [comment]
@FYI: Looks like feature flag is off for Android production builds: 
`buildConfigField "boolean", "CONTACT_INFO_BLOCK_AVAILABLE", "false"`

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/14499 and https://github.com/wordpress-mobile/WordPress-iOS/pull/16347.
