### ISSUE TITLE
Contact Info Block: Optional Sub Headings

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/gutenberg-mobile#3435]
- A contact info block allows me to show my address, phone number, email
- when I publish it, these appear as one block on the front end of the site
- I'd like an option to add subheadings, so that the site visitor can see the titles 'Email', 'Phone', 'Address' and not have them run together.

**Comment by mchowning** [comment]
Any thoughts here @illusaen or @iamthomasbishop ?

**Comment by hypest** [comment]
Cool feature request, but looks like it's not mobile specific per se and a better place to triage it would be the Jetpack repo at https://github.com/Automattic/jetpack. @osullivanchris, what do you think about migrating the ticket there? I'll close the ticket here but, happy to reopen if this is indeed mobile specifc, no prob. Thanks!

**Comment by osullivanchris** [comment]
Thanks for the tip @hypest . I logged it over here https://github.com/Automattic/jetpack/issues/19877
