### ISSUE TITLE
Can't access Unsupported Block Editor (UBE) from Atomic site on iOS

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#3461]
### **Describe the bug**
I have the same test atomic site opened up on WordPress-iOS and WordPress-Android with a post that contains unsupported blocks. 

The UBE opens up for unsupported blocks for the atomic site in WPAndroid, but it does not open on WordPress-iOS. Instead, I see a Bottomsheet that prompts me to open Jetpack security settings. Tapping this option closes the bottom sheet and nothing happens.

#### Pre-requisite:
1. We need a dotcom account with at least one atomic (business) site
2. Create a post for that atomic site from Gutenberg Web that has at least one block not supported on mobile (classic / markdown/ etc.)

#### Steps to reproduce the behavior:
1. Login to the dotcom account on WordPress-iOS that has the atomic site with the post with unsupported block from web
2. Open up the post with the unsupported block
3. Click on the unsupported block and note the bottomsheet that prompts to update settings
4. Note that clicking the bottomsheet does nothing
5. Also note that navigating to jetpack settings and enabling wordpress.com login also does not affect our abilty to edit the unsupported block

### **Expected behavior**
We should be able to edit unsupported blocks on atomic sites from WordPress-iOS, not screen shot below comparing WordPress-Android to WordPress-iOS

### **Screenshots**
| WPAndroid Atomic | WPiOS Atomic |
| -------- | -------- |
| ![Screenshot_20210505-183332_WordPress](https://user-images.githubusercontent.com/1103838/117230649-65f19280-add2-11eb-8b1b-ab8618013658.jpg) |  ![IMG-1592](https://user-images.githubusercontent.com/1103838/117230704-7c97e980-add2-11eb-9d1c-98dca7b2b6cb.PNG) |
| ![Screenshot_20210505-183445_WordPress](https://user-images.githubusercontent.com/1103838/117230802-afda7880-add2-11eb-878f-fdf369ef7672.jpg) |  ![IMG-1593](https://user-images.githubusercontent.com/1103838/117230838-c8e32980-add2-11eb-8474-e38b0e61767c.PNG) |
| ![Screenshot_20210505-183459_WordPress](https://user-images.githubusercontent.com/1103838/117230878-e0baad80-add2-11eb-85f7-7d1a1508d540.jpg) |   ![IMG-1594](https://user-images.githubusercontent.com/1103838/117230902-ed3f0600-add2-11eb-9dd9-ee083e848545.PNG) |

### **To be clear, no matter what I set for Jetpack settings on WPiOS, I cannot seem to get access the UBE for the atomic site**

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.4.2
 - Version WPiOS 17.3 Beta

**Additional context**
Similar issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425

**Comment by guarani** [comment]
After a bit of debugging, what I found was that the app was not fetching Gutenberg settings (`/sites/1234567/gutenberg`) when the user switched sites. 

Explanation: In my tests, this bug would "resolve itself" after I went back to the My Sites screen. It's on that screen in `viewDidLoad` that the app fetches blog/site metadata which includes its Gutenberg settings (i.e the value of the site's `editor_web`, which can be `classic` or `gutenberg`). What I saw is that when the user first logs in, although this data is fetched for the default site, it's not updated when the user changes site in the site picker (e.g. switches to an Atomic site).
This is likely a bug introduced when the site picker was made a modal in https://github.com/wordpress-mobile/WordPress-iOS/pull/16137.

I've made a PR to fix this here, https://github.com/wordpress-mobile/WordPress-iOS/pull/16468, but have run into an error with the UBE web view where it appears that the cookie, `wordpress_logged_in`, is not returned by the server. I'm still looking into this issue.
