### ISSUE TITLE
Inserter UI

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#349]
A continuation of #58, the inserter works, but we still need it to match the designs.

![image](https://user-images.githubusercontent.com/6597771/43523855-14593f5a-9574-11e8-8269-f93e0a7a1caa.png)

It was originally estimated as 1 week of effort

**Comment by koke** [comment]
As reported by @rachelmcr, when we're replacing an existing empty block, the inserter placeholder is still visible saying "Add block here", when it shouldn't.

![photo-12-12-2018-16-30-201](https://user-images.githubusercontent.com/8739/49923547-2437b880-feb4-11e8-9a18-76d92df15062.png)

**Comment by koke** [comment]
Design update from @iamthomasbishop:

<img width="1046" alt="screen shot 2018-12-11 at 3 56 49 pm" src="https://user-images.githubusercontent.com/8739/49936914-76d59c80-fed5-11e8-800c-187012c05161.png">

- Block items need to be styled to match designs
- Let’s remove the sheet header to simplify the design for the alpha and beta, then gauge whether it’s a usability concern via feedback. This essentially makes iOS and Android almost entirely aligned, primary difference is iOS uses SF Pro and Android uses Roboto for labels
- Items should be aligned to the grid (see Zeplin for example), 16pt sheet margins left/right, 16pt left/right between items, 12pt bottom margin on each. iOS is a little tricky bc screen widths are odd numbers

**Comment by iamthomasbishop** [comment]
A note: @etoledom is in the process of implementing RN bottom sheets, so hopefully this can utilize some of that progress: https://github.com/wordpress-mobile/gutenberg-mobile/issues/535
