### ISSUE TITLE
Pullquote block: Odd delete behavior on Android

### ISSUE THREAD

**Issue by AmandaRiu** [wordpress-mobile/gutenberg-mobile#3495]
**Describe the bug**
Hitting enter twice will delete one line which is already reported [in this ticket](https://github.com/WordPress/gutenberg/issues/29861), but if you hit backspace to return to the previous line, letters start getting added to the beginning of words as you hit backspace to delete characters. This only happens _after_ the bug that deletes an extra line happens.

**To Reproduce**
1. Add a Pullquote block to a post. 
2. Type in some text in the quote part of the block and then hit enter twice. Notice how the second line is deleted. 
3. Hit backspace to move back up to the first line and delete the last character of that line. Notice how an additional letter is added to the beginning of that word. 

**Expected behavior**
Hitting backspace to delete a character doesn't add an additional letter to the word.

**Screenshots**

https://user-images.githubusercontent.com/5810477/118063712-9d7ab480-b367-11eb-96fa-28a56e7a1774.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 11

**Additional context**

**Comment by mchowning** [comment]
I don't feel super-strongly, but because this issue is altering the text in unexpected and possibly non-obvious ways, this feels more like a high-priority issue. I'll go ahead and make that change to the label, but feel free to change back if you disagree.

**Comment by AmandaRiu** [comment]
Tested on a physical Pixel 4 running Android 11 and Gboard. Issue appears [to have been fixed when this issue was fixed.](https://github.com/WordPress/gutenberg/issues/27690). Closing. 


https://user-images.githubusercontent.com/5810477/125338646-7700d780-e31e-11eb-81ed-cd587e8dc832.mp4
