### ISSUE TITLE
Improve hide keyboard button

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#350]
As part of #55, we have a functional button to hide the keyboard, but it doesn't match the designs:

<img width="885" alt="screen shot 2018-10-17 at 3 55 14 pm" src="https://user-images.githubusercontent.com/1200432/47115757-2ae3df80-d225-11e8-9e35-a0ba4d4f9c72.png">

We need to make sure it has the right icon and that it stays on the right side of the toolbar

**Comment by koke** [comment]
Moving this to the alpha since the current icon is quite confusing. Only the icon is important for the alpha, the rest is _nice to have_

**Comment by marecar3** [comment]
Hey @iamthomasbishop, please can you share with us some thoughts about what kind of dash icon we can use here? thanks!

**Comment by iamthomasbishop** [comment]
I think the easiest _path_ here would be to use Material's icon. However, my preferred solution would be to use the standard [Material icon](https://material.io/tools/icons/?search=keyboard&icon=keyboard_hide&style=baseline) on Android and for iOS use [this icon](https://cloudup.com/cBCjSiCyibE).

Here they are side-by-side (Android left, iOS right):

<img width="847" alt="screen shot 2018-12-18 at 11 18 49 am" src="https://user-images.githubusercontent.com/1200432/50170973-baa21a80-02b6-11e9-9f4c-58f5cdec2558.png">

**Comment by marecar3** [comment]
Hey @iamthomasbishop , we can't use material icon as it has 24x24 dimension and our view box is 20x20 (which we can't change at this moment)

![screen shot 2018-12-18 at 16 06 58](https://user-images.githubusercontent.com/28219092/50171182-0aea9e00-02f2-11e9-9506-e41a717b44cf.png)

**Comment by iamthomasbishop** [comment]
Ah that's right, I had forgotten those are on a 20pt grid. I'm not familiar with the technical considerations for the view box size, but I think we should switch to use a 24pt icon structure asap, considering Gridicons, Material, and probably all other icons used in this context (and across the apps) are set on a 24pt/dp grid. For the time being, I can create a custom 20pt icon to use here, but we should consider moving to 24 sooner than later, even if that means deciding on a new replacement icon for each toolbar item.

**Comment by marecar3** [comment]
> I can create a custom 20pt icon to use here
This would be perfect for the alpha. @iamthomasbishop can you share it with me when are have it? Tnx.

@koke is switching to 24x24 Material icons realistic for beta? Tnx.

**Comment by koke** [comment]
I don’t imagine any major technical challenges for that on the beta, so it sounds good. I’m not sure I have a good understanding of all the details involved though

**Comment by marecar3** [comment]
@iamthomasbishop @koke I have opened the issue for beta : https://github.com/wordpress-mobile/gutenberg-mobile/issues/403

**Comment by iamthomasbishop** [comment]
Looping back to this, from looking at the latest alpha, it looks like the toolbar is mostly done, but I'd still like to make sure the keyboard toggle is docked to the right side of the screen – or at very least, appended to the end of the tool list.
