### ISSUE TITLE
The editor Crashes when adding a Caption to a Gallery block

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#3510]
**Describe the bug**
The editor Crashes when adding a Caption to a Gallery block

**To Reproduce**
Follow the steps on [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc003) or:
1. Add a Gallery block
2. Add some images from the device or media library
3. Tap on the gallery caption
4. **Notice** the the editor crashes

The **Crash** occurs both on **Android and iOS**

**Expected behavior**
The user is able to add a gallery caption.

**Screenshots**

https://user-images.githubusercontent.com/304044/118486426-463b6200-b722-11eb-9ae9-7b613ea62e17.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL, iPhone SE
 - OS: Android 11.0, iOS 14.4
 - Version Gutenberg Mobile [1.53.0](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3506)

**Comment by mkevins** [comment]
I have reproduced this issue, and debugging it points to the removal of the `onFocusGalleryCaption` in this commit: https://github.com/WordPress/gutenberg/commit/9a6e3fcbc927791d7fb70f35ba88da1ef2d83acb, in this PR: https://github.com/WordPress/gutenberg/pull/31796. I have confirmed that after reverting those changes, I can no longer reproduce the crash.

**Comment by fluiddot** [comment]
This issue can be also reproduced in version `17.3.2`.

**Sentry issue ID:** 1509710590

**Comment by AmandaRiu** [comment]
NOTE: This crash was fixed in [this PR](https://github.com/WordPress/gutenberg/pull/31938) and included in the gutenberg-mobile `1.53.1` release which is bundled in the `17.4` release of the WordPress apps.
