### ISSUE TITLE
The Gallery Image Caption text formatting options disappear

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#3511]
**Describe the bug**
The image gallery caption formatting toolbar disappears when moving focus between image captions

**To Reproduce**
1. Add a Gallery block
2. Add some images to your gallery
3. Set some captions to the images
4. Move the focus between image gallery captions
5. **Notice** that the formatting toolbar disappears 
6. Add a paragraph block
7. Move the focus between image gallery captions
8. Move the focus to the paragraph
9. **Notice** that the formatting toolbar is still missing 

**Expected behavior**
The user is able to format captions on image galleries

**Screenshots**

|Expected (Android)|Actual is missing text formatting toolbar (Android)|Recording(iOS)|
|---|---|---|
|<image width="300" src="https://user-images.githubusercontent.com/304044/118489889-04141f80-b726-11eb-9286-af87c4f9ccc6.png"/>|<image width="300" src="https://user-images.githubusercontent.com/304044/118489908-08d8d380-b726-11eb-8030-12eb57a72cfa.png"/>|<image width="300" src="https://user-images.githubusercontent.com/304044/118802574-f1772300-b8aa-11eb-8f19-b64759180c7d.gif"/>|

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL, iPhone SE
 - OS: Android 11.0, iOS 14.4
 - Version Gutenberg Mobile [1.53.0](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3506)

**Comment by mkevins** [comment]
I have confirmed this as well, and noted also that after applying a revert described here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/3510#issuecomment-842805942 that the same issue occurs on the gallery caption, when focus is changed.

**Comment by antonis** [comment]
As pointed out by @mkevins after the issue is triggered with the gallery block image captions it persists on other rich text blocks (e.g. paragraph block or quote block).
If I create a new paragraph block at this point or focus on the title the toolbar is back.

|Paragraph Block|Quote block|
|---|---|
|![device-2021-05-18-123958](https://user-images.githubusercontent.com/304044/118629365-2f564780-b7d6-11eb-873c-f13f2d374a05.png)|![device-2021-05-18-124143](https://user-images.githubusercontent.com/304044/118629688-82c89580-b7d6-11eb-8a53-5153fe31650a.png)|

**Comment by AmandaRiu** [comment]
> As pointed out by @mkevins after the issue is triggered with the gallery block image captions it persists on other rich text blocks (e.g. paragraph block or quote block).
> If I create a new paragraph block at this point the toolbar is back.

While [testing this PR that reverts the commit mentioned](https://github.com/WordPress/gutenberg/pull/31938) I can confirm the issues in this ticket still persist.
