### ISSUE TITLE
Default to displaying Favicon.ico if No Site Icon is Present

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/gutenberg-mobile#3520]
**Is your feature request related to a problem? Please describe.**
Some site owners upload their site's icon as a favicon.ico file in the root of the site instead of uploading it through the Customizer.

**Describe the solution you'd like**
If no Site Icon is found, display favicon.ico instead.

**Additional context**
 #3999833-zen

**Comment by hypest** [comment]
Thanks for the ticket @mdrockwell ! I wonder though, is this indeed related to something in the block editor or some app screen before it? Let's move the ticket to https://github.com/wordpress-mobile/WordPress-iOS/ if not related to the editor, thanks!

**Comment by mdrockwell** [comment]
@hypest, I guess I may have misunderstood the repo — I assumed it was for issues related to apps on both platforms. I can certainly add this to the app-specific repos if you'd like!

**Comment by hypest** [comment]
> @hypest, I guess I may have misunderstood the repo — I assumed it was for issues related to apps on both platforms.

Ah, I see. Yeah, this repo focuses on the block editor inside the apps. Sometimes we also keep a ticket here when it's still close to the editing experience and happens on both mobile platforms.

> I can certainly add this to the app-specific repos if you'd like!

Yes, please. That will help bring the issues to the appropriate queues, thanks!

I will close this ticket at this point.
