### ISSUE TITLE
Add Syntax Highlighting in Block Editor's HTML Mode

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/gutenberg-mobile#3521]
When editing in the HTML mode, it would be nice to have syntax highlighting similar to what is available within the Classic Editor's HTML view.

In the classic Editor:
![IMG_0999](https://user-images.githubusercontent.com/42454301/118715516-b1079e80-b7f1-11eb-9960-8dbbb25f6b96.PNG)

No syntax highlighting in block editor:
![IMG_0998](https://user-images.githubusercontent.com/42454301/118715545-bf55ba80-b7f1-11eb-84de-172df0de855e.PNG)

**Additional context**

#3999833-zen

**Comment by hypest** [comment]
👋 @mdrockwell , I've [added the report to a ticket already opened](https://github.com/wordpress-mobile/gutenberg-mobile/issues/708#issuecomment-843841746) that includes the syntax highlighting feature request. I will close this new ticket now but please, let me know if there's more context that makes sense to keep this ticket open instead and we can reopen, thanks!
