### ISSUE TITLE
Deleting text on the more block resets it to the default text

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#359]
When you edit the text in the `more` block, the moment you delete it all, it resets to the default "Read more" text

https://cloudup.com/c783LjuGw_Z

**Comment by iamthomasbishop** [comment]
Perhaps we could provide placeholder text (dimmed text, same style as our other placeholder labels) of `Read More` in the case where the label is empty. It would allow the user to delete all of the text, but would indicate what the default would be.

**Comment by koke** [comment]
The web version seems to be using text instead of a placeholder, so I'd rather follow that (or propose the change for the web as well), although I liked the idea :)
