### ISSUE TITLE
[iOS] Preview seems to not show images on some cases

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#362]
It was reported that when previewing a post with an image, the preview won't show the image until it's published. I've confirmed this on iOS (last internal beta) with a WordPress.com blog:

1. Create a new post, add a title
2. Insert an image from the media library
3. Save as draft
4. Preview post, the post is there but the image is not visible

If you open the preview in any other browser it will show fine, so this might be some quirk of the web view

**Comment by etoledom** [comment]
I was able to reproduce the same also in Aztec. It seems to be a `PostPreviewViewController` issue, not directly related to Gutenberg implementation.
I'll upload a video soon.

**Comment by etoledom** [comment]
Preview on Gutenberg then in Aztec. Private site.

![preview](https://user-images.githubusercontent.com/9772967/50076846-7138c900-01eb-11e9-9f48-d33573636c49.gif)

**Comment by hypest** [comment]
FWIW, tried again on wpandroid with a private site and previewing the draft shows the media library image OK.

**Comment by koke** [comment]
@etoledom I understand correctly that this is not related to Gutenberg and also happening on the existing production app? If that's the case, can you close this one and create an issue on the WordPress-iOS repo? It might be a good groundskeeping candidate

**Comment by etoledom** [comment]
That's right.
I could reproduce it on the production app, made a gif and sent a ticket to the WPiOS repo. ✅
https://github.com/wordpress-mobile/WordPress-iOS/issues/10677
