### ISSUE TITLE
New-block indicator and newly added block is in the wrong position after selecting the Title

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#3636]
After selecting the Title and then some other block, and then try to add a new block from the block picker, the blue line/indicator is at the wrong place.

**To Reproduce**
1. In the demo app
2. Tap on the Title
3. Then tap on a block a couple of blocks away
4. Then tap on the "+" toolbar button to add a new block from the picker
5. 💥 Notice that the new-block indicator is right below the title instead of being below the currently selected block. See video below too.
6. Select a new block from the picker and notice that it's added at the wrong place

https://user-images.githubusercontent.com/1032913/122574498-611e3080-d058-11eb-8d59-cc94500cd88e.mp4

**Expected behavior**
The new-block indicator should be below the selected block, not the Title.

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11
 - Version on `develop` hash 11c7f704
 - Verified happening on WPAndroid 17.5 (production at the time of writing)

**Comment by hypest** [comment]
From my debugging so far, looks like the the [editor settings memo](https://github.com/WordPress/gutenberg/blob/4edc47f5187e7f58dc1a9618ba8d732b5d072c00/packages/editor/src/components/provider/use-block-editor-settings.native.js#L35-L42) doesn't get triggered when the Title get unselected.

**Comment by fluiddot** [comment]
Looks like we have the same issue opened in Gutenberg:
https://github.com/WordPress/gutenberg/issues/32154
