### ISSUE TITLE
[iOS] Dictation doesn’t adjust the height of RichText

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#365]
To reproduce:

1. Create a paragraph
2. Dictate some text long enough that it goes over the first line
3. Notice there’s no second line visible
4. End dictation and type anything, the block then adjusts its height properly

Tested on WP Internal 11.4.0.20181210 on iPhone XS Max 12.1

**Comment by etoledom** [comment]
Tested again after the recent changes and it seems to be solved.
