### ISSUE TITLE
Improve HTML editor

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#366]
Compared to Aztec, the HTML editor looks much worse. The grey background is unexpected, and we should leverage the syntax highlighting in the Aztec HTML mode.

**Comment by pinarol** [comment]
Some issues about the HTML editor:
[]Keyboard can not be closed
[]Scrolling area doesn't adjust itself when keyboard opens so there is always some text hidden under the keyboard.

**Comment by koke** [comment]
At the very least let's switch to a white background for the beta. We can revisit the rest after.
