### ISSUE TITLE
Improve style of code block

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#368]
There's not a lot of difference with the paragraph block, except for the monospace font, and some wrong margins:

![img_419a975c4e0c-1](https://user-images.githubusercontent.com/8739/49923898-1f273900-feb5-11e8-9cdc-057cd5b76215.jpeg)

The web version for comparison:

![img_36271d76b0eb-1](https://user-images.githubusercontent.com/8739/49923881-16366780-feb5-11e8-88f8-40dc611aa553.jpeg)

**Comment by iamthomasbishop** [comment]
The simplest fix is probably to just apply a different font-family to the code text – although depending on which font we use, we might have to adjust the font-size as well. 

If we use Menlo, which IIRC is what we're using on Aztec, it'd look like this at 14pt, same 24pt line-height:

Focused
<img width="600" alt="image" src="https://user-images.githubusercontent.com/1200432/50663262-a9236880-0f6e-11e9-9b76-1394e893d394.png">

Static
<img width="598" alt="image" src="https://user-images.githubusercontent.com/1200432/50663378-133c0d80-0f6f-11e9-891d-2a6e49b98ac9.png">

The margins should be taken care of by some clean-up of the global styling/margins of the blocks (which I believe @mzorz is working on separately).

**Comment by iamthomasbishop** [comment]
I'm coming back to this, and wondering if we should make the styling of the code block (and inline code) more distinct. Something like this:

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/1200432/57950205-3a570400-78ac-11e9-89a4-46ae657c8fbf.png">

Thoughts, @koke ?

**Comment by koke** [comment]
It is definitely clearer that it is code than the previous version 😁
I don’t want to take much time with this one, since it’s low priority, but one thing that looks odd to me is the lack of padding inside the background.

**Comment by iamthomasbishop** [comment]
Good catch. The `inline code` basically matches Core's padding (2px around), but the main Code block should have more padding. I need to update the Sketch library to have 2 variations :)

**Comment by iamthomasbishop** [comment]
Here are some updated examples, based on the applied paddings (which are the same as the outer block (12 left/right, 16 top/bottom): 

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/1200432/58357130-4ceab380-7e3f-11e9-8e58-0d76a8712594.png">

<img width="380" alt="image" src="https://user-images.githubusercontent.com/1200432/58357203-86bbba00-7e3f-11e9-8dd4-73d50e4b5d25.png">

The inline code variation has 2 padding left/right.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1200432/58357253-afdc4a80-7e3f-11e9-88e6-42fbec5700ae.png">
