### ISSUE TITLE
Bug: We should only make xposts endpoint request for .com sites on iOS

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/gutenberg-mobile#3683]
**Describe the bug**
Currently, we make an xpost request to the public-api endpoint for all sites. 
This should only happen for .com sites since these sites are the ones that have that feature available.

**To Reproduce**
1. Look at requests that are being made from a device. I used Charles proxy for this. 
2. Notice that a .org site was making the requests to the `public-api.wordpress.com/wpcom/v2/sites/example.com/xposts?locale=en&decode_html=1`

**Expected behavior**
The request shouldn't happen.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Simulator
 - OS: iOS 14
 - Version 17.7

**Comment by guarani** [comment]
I added the iOS label since the title mentions iOS only and I think this is iOS-specific.
