### ISSUE TITLE
Post title writing flow

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#372]
As part of #182, we added the post title in the apps themselves, which has lead to some issues. For the beta, we'd want:

- [x] Title should have no border
- [x] Title shouldn’t be fixed (it should scroll with the content)
- [x] Title and content should be aware of each other in terms of focus. When the title is selected, the toolbar should only contain global tools (Inserter, Undo/Redo, Hide Keyboard)
- [x] The "hide keyboard" button should work on the title as well
- [x] Pressing enter on the title should move to the next block or split a new one if necessary [https://github.com/wordpress-mobile/gutenberg-mobile/issues/502]
- [x] Integrate the Noto font and use it on blocks
- [x] Make sure undo / redo works.
- [x] The title should be [saved in the global store](
https://github.com/wordpress-mobile/gutenberg-mobile/pull/450#discussion_r248672329) instead of part of `AppContainer.js`'s state.
- [x] The title placeholder should read "Add a Title". ([ref](
https://github.com/wordpress-mobile/WordPress-iOS/pull/10794#issuecomment-455329479))

**Comment by hypest** [comment]
Allow me to add that it would be nice if we could timebox (the least) an experiment around this: render the title inside the RN side, effectively introducing the first mobile non-content block.

**Comment by diegoreymendez** [comment]
All tasks are completed... this issue will be closed once all PRs are merged.
