### ISSUE TITLE
Bottom Sheet bounces a bit when going from a caption to adding a block

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#3721]
**Describe the bug**
While editing a caption in the Gallery, if you go from an open keyboard to add a new image the bottom sheet bounces up beyond its bounds then settles in place. 

**To Reproduce**
1. Add a Media block or two 
2. Add some images but leave at least one in a state where you can directly access the Choose media sheet. 
    - For example you can add a gallery or two image blocks leaving one empty
3. Add a caption
4. With the caption still focused Select to add media to the placeholder block from before 
5. Notice the bounce on the bottom sheet as the keyboard hides. 

**Expected behavior**
The bottom sheet will remain fixed at the bottom.

**Screenshots**
I was able to get it every time while not running a screen recording and 30% of the time while recording.

https://user-images.githubusercontent.com/3384451/125510774-28cba86d-3789-449e-a3c1-cfb188567c2c.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Tested in WP Android 17.8-rc-1

**Comment by thehenrybyrd** [comment]
I was able to reproduce on **Samsung Galaxy S21, Android 11, WPAndroid 17.8-rc-1**.
I was able to get it 100% of the time when editing the caption of the top-right gallery item, but less consistently with the other gallery items.

**Comment by mchowning** [comment]
Might this be related to any of the work you were doing @fluiddot ?

**Comment by dcalhoun** [comment]
For additional context, this may relate to/duplicate https://github.com/WordPress/gutenberg/issues/32012.

**Comment by fluiddot** [comment]
> Might this be related to any of the work you were doing @fluiddot ?

Yeah, probably it's related to the recent changes I did for adding the reusable bocks tab in the bottom sheet, as @dcalhoun pointed out, we already have [an open issue related to this](https://github.com/WordPress/gutenberg/issues/32012).

**Comment by hypest** [comment]
Thank you all for elaborating and triaging. Let's close this in favor of the one on Gutenberg as the context is already captured there, including videos and all.
