### ISSUE TITLE
Improve footer copy on color picker BottomSheet

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#3766]
**Describe the bug**

We've heard that some users assume that the "Select a color" label is an action button. I believe we should phrase this slightly more clearly and potentially change what is displayed depending on whether or not the user has a color selected. 

**To Reproduce**

1. Add any block that supports colors (paragraph, button, group, etc)
2. Open the block's settings by tapping on the settings/cog icon near the block's content
3. Tap on one of the color setting cells (i.e. text color or background color)
4. Notice that the footer of the BottomSheet has a text label that says "Select a color" (this is where the confusion arises)

<a href="https://user-images.githubusercontent.com/1200432/127396928-3e42d9fa-5d81-4a56-a494-aff8b1405595.jpeg"><img src="https://user-images.githubusercontent.com/1200432/127396928-3e42d9fa-5d81-4a56-a494-aff8b1405595.jpeg" width="390"></a>

**Proposed solution(s)**

I propose that we change the label to “Select a color above” (other options considered were "Select color above", "No color selected"). This should be a bit clearer, as it directs users to the color-selection control.

We're also not displaying the selected color's hex value (like we are on the "custom color" picker — in monospace font and the ability to long-press to copy the associated hex value) when the user has a color selected, but it would be good to do so; both for consistency and visibility.

Here's an overview of the interaction:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/1200432/127399081-5a3f63b1-b11f-4b22-af07-c6aeadd83407.png">

**Comment by enejb** [comment]
Great work! I think this makes things cleared. 

I wonder if we should display the value next to the colour and if the user clicks on it we can copy it to the clip board. With a little copied tooltip.

And if a user has a colour in the clipboard we could make the copied colour as of the colour that is available to be selected. (maybe even the first one) 

I think that would help address some of the issues faced in https://github.com/wordpress-mobile/gutenberg-mobile/issues/3775 issue.
