### ISSUE TITLE
[Android] Undo/redo history is lost on rotate

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#377]
Rotating the device while having some content changed seems to lose the undo/redo history.

Steps to reproduce:
1. Use wpandroid
2. Open a in gutenberg-mobile and do some minor changes to the content. Verify that undo/redo are working fine.
3. Rotate the device. Notice that the undo/redo buttons are disabled

**Comment by koke** [comment]
Related to https://github.com/wordpress-mobile/WordPress-Android/issues/8739#issuecomment-446882973 ?

**Comment by hypest** [comment]
> Related to wordpress-mobile/WordPress-Android#8739 (comment) ?

Not really but related to rotation in general.

In this case, because we don't actually keep (all of) the RN app's state, undo/redo is just lost on rotation even if we do reinstate the content.

**Comment by mzorz** [comment]
Closed in #9030
