### ISSUE TITLE
Add tests to cover the alignment functionality 

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/gutenberg-mobile#3792]
**Is your feature request related to a problem? Please describe.**
The mobile editor alignment functionality does not have automated testing in place

**Describe the solution you'd like**
Add integration and/or UI tests

**Additional context**
This issue was created after an [incoming breakage ](https://github.com/WordPress/gutenberg/pull/33847)that may have been prevented if tests were in place

**Comment by geriux** [comment]
This will be handled in https://github.com/WordPress/gutenberg/pull/46831
