### ISSUE TITLE
[Embed block] Enable inline preview only for the top 5 most-used providers

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#3816]
Related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/3278.

### Description
- **Needs research:** Determine by looking into data the top 8 most-used ones.
- Add a static list of providers including the top 8 most-used and enable the inline preview for them. The rest of the providers will display the "preview coming soon" message.

**Most-used providers (list based on https://github.com/wordpress-mobile/gutenberg-mobile/issues/3816#issuecomment-907250152):**
1. YouTube ✅ (enabled in https://github.com/wordpress-mobile/gutenberg-mobile/pull/3900)
2. Twitter ✅ (enabled in https://github.com/wordpress-mobile/gutenberg-mobile/pull/3900)
3. WordPress ✅ (enabled in https://github.com/wordpress-mobile/gutenberg-mobile/pull/3853)
4. Instagram ✅ (enabled in https://github.com/wordpress-mobile/gutenberg-mobile/pull/3918)
5. Vimeo ✅ (enabled in https://github.com/wordpress-mobile/gutenberg-mobile/pull/3918)

**Comment by hypest** [comment]
> Needs research: Determine by looking into data the top 8 most-used ones.

Based on data from WPCOM usage, here's the top ones, in order of popularity, we shall look into enabling inline preview for: YouTube, Twitter, WordPress, Instagram, Vimeo.

And just to add more nuance, let's make sure we're able to individually enable inline preview for any of those, as soon as we're happy with each one's preview.

**Comment by fluiddot** [comment]
> > Needs research: Determine by looking into data the top 8 most-used ones.
> 
> Based on data from WPCOM usage, here's the top ones, in order of popularity, we shall look into enabling inline preview for: YouTube, Twitter, WordPress, Instagram, Vimeo.
> 
> And just to add more nuance, let's make sure we're able to individually enable inline preview for any of those, as soon as we're happy with each one's preview.

Thanks @hypest for the usage insights ❤️ !

I'll open a PR to enable the inline preview by providers, this way we could focus on addressing potential issues for each provider and enable them one by one, once we're confident they're ready for usage.

**Comment by fluiddot** [comment]
> I'll open a PR to enable the inline preview by providers, this way we could focus on addressing potential issues for each provider and enable them one by one, once we're confident they're ready for usage.

Here is the [PR](https://github.com/WordPress/gutenberg/pull/34446) that enables the inline previews by providers, for now, I only included YouTube and Twitter.

**Comment by fluiddot** [comment]
Heads up that the previews for WordPress embeds are now available ([related PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3853)) 🎊 .

**Comment by jd-alexander** [comment]
I created a PR that enables Instagram and Vimeo providers https://github.com/wordpress-mobile/gutenberg-mobile/pull/3918 I didn't notice any issues with the rendering of the embed preview.

**Comment by fluiddot** [comment]
Previews for all top 5 most-used providers have been enabled 🎊 .
