### ISSUE TITLE
Embed Block - Enhancement: include Link in Block Settings

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#3887]
After creating an Embed, I may what to double-check what link I entered, or want to edit the link. I find myself frustrated when the link doesn't appear in the Block Settings. 
To edit the link, I need to remember and tap the "edit" button - which I usually forget about despite testing the block editor frequently.

This is also the case for the Audio block if you embed via URL. However, for other blocks that have links, such as the Image block, the link appears in the Block Settings.

**Desired solution:**
It would be great to have the link appear in Block Settings, for consistency with other blocks that include links.
The "Edit" or "Replace" buttons do work, but they could just as well be part of settings.

**Embed Block Settings and Image Block Settings for comparison:**
<img src="https://user-images.githubusercontent.com/15107387/131307758-34a511a8-c90f-49d9-9f61-398cef0126e4.png" width="70%">

**Comment by hypest** [comment]
@kyleaparker , what do you think?

**Comment by kyleaparker** [comment]
@hypest sounds good to me, makes sense that we should add them the link to the block settings if this is the first place people go to look for it

**Comment by fluiddot** [comment]
If we add the URL edit to the block settings, perhaps we should also remove the Edit button from the toolbar (pencil icon) as it could be confusing, wdyt?

**Comment by hypest** [comment]
I think I vaguely remember @iamthomasbishop mentioning once (perhaps in private chat) that having both options in place is not a bad idea (both the toolbar pencil and the entry in the block settings). Thomas, do you recall?

I'd say, it'd be interesting if the pencil actually triggers the block settings and automatically focuses the link input, but I wouldn't consider the auto-focus a hard requirement.

**Comment by kyleaparker** [comment]
I think we could lose the pencil icon, there is currently only one other setting under the Settings menu and I think reducing the number of icons makes things clearer.
