### ISSUE TITLE
RTL: "+" icon not in view when paragraph block is focused

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#3889]
**Describe the bug**
When I have tapped into a paragraph block, I expect to see the "+" icon, visible in order to add a new block. Instead, the "+" icon is scrolled off to the right so I cannot see it.
This happens when using the app in an RTL language, on Android only.

**To Reproduce**
1. Go to Me > App Settings > Interface Language and choose an RTL language such as Arabic or Hebrew.
2. Navigate back to Posts and open a post that has some blocks in it.
3. Note that the "+" icon appears at the bottom-right when you have selected an image block, embed block, or other block with few items in the edit bar (where undo/redo and other items appear).
3. Add an empty paragraph or other text-based block, and tap into it.
4. Note that the "+" icon is not visible on the edit bar. In order to find it, scroll over to the right past the Bold, Indent, and Undo/Redo options.

**Expected behavior**
I expected the "+" icon to appear, with other options scrolled out of visibility. This is the case with LTR languages and for RTL languages on iOS.

**Screenshots**
Compare iOS (left) to Android (right):
![IMG_FCB7B6C64137-1](https://user-images.githubusercontent.com/15107387/131313403-bc9e55e4-eace-45f1-9d42-c91ca652304b.png)

**Smartphone:**
Samsung Galaxy S21, Android 11, WPAndroid 18.1-rc-1

**Additional context**
Discovered while beta-testing WP Android 18.1

**Comment by hypest** [comment]
Added the "High" priority label as this is breaking a very fundamental flow, how to add a block to the content.
