### ISSUE TITLE
Toolbar doesn't animate correctly on rotation

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#389]
Instead of animating alongside the keyboard, the toolbar stays in place during the rotation animation, then it suddenly moves to its final place:

![gb-rotation-toolbar](https://user-images.githubusercontent.com/8739/50096469-18cbf080-0218-11e9-8889-0148d8284a33.gif)

**Comment by SergioEstevao** [comment]
We probably need to check this class on RN-iOS:  https://facebook.github.io/react-native/docs/inputaccessoryview

**Comment by SiobhyB** [comment]
I can't reproduce this behaviour in the latest version (24.0) on iOS. I tested on an iPhone XR and confirmed that the toolbar now appears to smoothly disappear/appear with the rotation, with it never appearing out-of-place in the way that it does in this issue's recording. I'll therefore go ahead to close this issue.
