### ISSUE TITLE
Embed Block - Instagram variant doesn't show block settings

### ISSUE THREAD

**Issue by ceyhun** [wordpress-mobile/gutenberg-mobile#3893]
**Describe the bug**

For Instagram embed block on wpcom web editor we can open the settings and toggle the `Resize for smaller devices` but on mobile editor the settings icon is not shown in the block and this setting cannot be modified.

**To Reproduce**
1. Add an Embed block
2. Paste an Instagram link in the bottom sheet (e.g. `https://www.instagram.com/p/Bl6LgZgFDOm`)
3. Close the bottom sheet and wait for the block to load
4. The Instagram Embed Block doesn't have the settings icon 

**Expected behavior**
Instagram Embed Block should have the settings icon and the ability to toggle the `Resize for smaller devices` option as it does in the web editor.

**Screenshots**
<img width="300" src="https://user-images.githubusercontent.com/1845482/131548732-f6a01a41-60ee-45d6-92f0-7758c70d4bf9.png">

**Smartphone (please complete the following information):**
 - Reproducible on both WPAndroid and WPiOS 18.1 releases

**Additional context**
Instagram embed variation is disabled on .org which might be related:
https://github.com/WordPress/gutenberg/blob/35e16bbad16afb7209fb0e19b87d3a6f4108dd22/packages/block-library/src/embed/variations.js#L82

<p style="clear:both;"><sup>Internal reference p5T066-2Bv-p2#comment-9733</sup></p>

**Comment by fluiddot** [comment]
I noticed that on WPCom sites when using an Instagram URL, the embed is not using the Instagram variation but the generic one. Maybe this is related to why we have this mismatch between the web and native versions.

<img width="1008" alt="Screenshot 2021-09-02 at 12 45 47" src="https://user-images.githubusercontent.com/14905380/131830677-0dbc329f-3780-4e9e-8697-ad8949cd9571.png">

**Comment by fluiddot** [comment]
Closing this issue as it has been addressed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4008.
