### ISSUE TITLE
Opening the demo content on mobile Gutenberg shows an empty post

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#390]
### Expected behavior
Opening the demo content on the integrated WPAndroid - mobile Gutenberg editor should open normally and certainly not make the app crash / restart.

### Actual behavior
The app ~crashes / restarts itself when opening the demo content, and/or~ just doesn't load the content (sits there showing an empty body)

### Steps to reproduce the behavior
1. copy the demo content in https://github.com/wordpress-mobile/gutenberg-mobile/blob/master/src/app/initial-html.js into a new Gutenberg post in a self-hosted WordPress site using Gutenberg. 
2. verify your app has Gutenberg enabled (go to Me->App settings -> scroll down and enable Gutenberg).
3. refresh your posts list 
4. Then, trying to open the post from the Posts list
5. observe ~the app being restarted / or~ content not loaded.

**Comment by koke** [comment]
Are you sure it's android specific, or is it only tested on Android so far? It's not clear from the description and labels

**Comment by mzorz** [comment]
> Are you sure it's android specific, or is it only tested on Android so far?

Good question @koke, I have only tested on Android so far, but the kind of crash info I'm getting suggest it's Android internals going south. Will update when able to pinpoint / repro more consistently.

**Comment by koke** [comment]
I tried this on the latest internal for both iOS and Android and didn't get any crash. Can you verify if it's fixed?

**Comment by mzorz** [comment]
Doesn't seem to happen anymore. Will continue testing more later but we can close it for now

**Comment by mzorz** [comment]
Reopening this one, and editing the title / description to describe current situation
