### ISSUE TITLE
Jetpack Tiled Gallery: Square layout in-editor preview

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#3907]
Implement the square layout of the Jetpack Tiled Gallery. 

Related:
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/3874

**Comment by mchowning** [comment]
I went ahead and marked this as in-progress and assigned you @guarani , but feel free to adjust that if something else makes sense.

**Comment by SiobhyB** [comment]
Closing, as per the conversation at https://github.com/wordpress-mobile/gutenberg-mobile/issues/4190#issuecomment-961897741. We recently shipped the square layout's aspect ratio, as part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/4010. The remaining "piece" left to the square layout's in-editor preview is to remove settings/caption options, and that is being tracked in that separate issue.
