### ISSUE TITLE
Android: new line added to previous block when second block added on <Enter>

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#392]
When typing on a paragraph or Title block and tapping `Enter` to create a new block, everything seems to be alright, but as soon as you enter something else on the second block and tap `<Enter>`, the _previous block_ (first one) seems to get appended an extra newline

![jumpiness](https://user-images.githubusercontent.com/6597771/50013608-63dbce80-ffa0-11e8-99f6-e8a92b83f241.gif)

To test:
1. insert a new paragraph block and type something.
2. Tap `enter`
3. observe a new block is inserted below
4. now, enter some text
5. press `<enter>`
6. observe the block is unselected and the block previously created on step 2 has now a new empty line below the entered text.

**Comment by mzorz** [comment]
Needs prioritization (a.k.a. alpha or beta?) cc @koke

**Comment by koke** [comment]
I'd say we give it a try for the alpha, it seems pretty annoying and jarring
