### ISSUE TITLE
Paragraph  / Heading blocks have extra bottom margin above block controls

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#393]
First reported by @iamthomasbishop - there's an extra space in between the end of the content area for Paragraph and Heading blocks, and their corresponding container (with the up/down arrows and trash controls)

iOS:

![image from ios 12](https://user-images.githubusercontent.com/6597771/50122235-4aee4a00-023a-11e9-9a48-387be001ac08.jpg)

Android:
![screenshot_20181217-202721](https://user-images.githubusercontent.com/6597771/50122283-74a77100-023a-11e9-9d52-51ea9ded9ed6.png)

**Comment by koke** [comment]
I was looking at it yesterday on the RN inspector, and it seems the padding is coming from the native Aztec view, at least on iOS
