### ISSUE TITLE
[Embed block] Include Jetpack embed variants 

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/gutenberg-mobile#3951]
## Description

Jetpack has embed variants for some of the providers we support such as Facebook. The embed block should support all embed variants in Gutenberg and Jetpack. 

- [Embed variants index](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/extended-blocks/core-embed/index.js)
- [Facebook variant](https://github.com/Automattic/jetpack/blob/edbb7f3197ff9f284e7ba5e622dab15b879be07b/projects/plugins/jetpack/extensions/extended-blocks/core-embed/facebook.js)

We would have to refactor how we integrate blocks from Jetpack because these variations overwrite the core ones ([reference](https://github.com/Automattic/jetpack/blob/edbb7f3197ff9f284e7ba5e622dab15b879be07b/projects/plugins/jetpack/extensions/extended-blocks/core-embed/facebook.js#L29-L67)). This means that we would need to import the Jetpack's embed variations before registering the core blocks for this purpose.

-------
Issue inspired by the discussion on this PR https://github.com/WordPress/gutenberg/pull/34626

**Comment by fluiddot** [comment]
Heads up that there's a new variant being implemented in Jetpack to support Getty Images provider (more info in [this PR](https://github.com/Automattic/jetpack/pull/21101)), so it would be great to include it too.
