### ISSUE TITLE
Disable code and more blocks for the alpha

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#398]
Since we've had some issues with `PlainText`, we'll disable the `code` and `more` blocks for a bit, until we can polish some of the issues to avoid extra feedback about those.

After the alpha, we'll want to evaluate if it makes more sense to have an Aztec-powered PlainText instead of using TextInput

**Comment by pinarol** [comment]
Is this for the problems we have while focusing/scrolling to code/more blocks? if so, they are fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/387 on iOS side. And Android doesn't seem to have problem on focusing to code/more blocks.

**Comment by koke** [comment]
Fixed in #406
