### ISSUE TITLE
iOS - iPhone X Landscape/iPad devices - Missing borders on the left/right side of the editor

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#402]
Right now left/right border’s don’t exist so the block doesn’t feel “contained”. Those should be added as below:

<img width="1234" alt="screen shot 2018-12-19 at 8 41 51 am" src="https://user-images.githubusercontent.com/5032900/50227616-2ff51480-03b7-11e9-90f0-c789cbf410e8.png">

cc @iamthomasbishop

**Comment by koke** [comment]
I think this is by design #386, although the title should respect the safe area as well

**Comment by pinarol** [comment]
we are fixing the title with https://github.com/wordpress-mobile/WordPress-iOS/pull/10692
