### ISSUE TITLE
Feature Request: Add support to featured image settings to the Latest Posts block

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#4034]
**Is your feature request related to a problem? Please describe.**
It was requested in 4326230-zd-woothemes to add support to featured image settings for the Latest Posts block.

**Describe the solution you'd like**
Add the support of "Featured image settings" to the Latest Posts block settings in the app according to Calypso's options: https://wordpress.com/support/wordpress-editor/blocks/latest-posts-block/#featured-image-settings

**Comment by erricgunawan** [comment]
From 4736185-zen:

> May I request for additional feature for this "latest post" block? The option to show the thumbnail of the post😊. Thanks

**Comment by SiobhyB** [comment]
x-referencing a larger issue outlining all the missing settings between web vs. mobile with the Latest Posts block: https://github.com/WordPress/gutenberg/issues/29815
