### ISSUE TITLE
Sharing text from other apps results in infinite loading

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/gutenberg-mobile#4040]
**Describe the bug**
When I share any text (even short) from other apps to the WordPress for Android, gutenberg editor never finishes loading (I waited for about a minute and I was able to reproduce the issue) - when I try to leave the editor using the back button a saving dialog is shown and it doesn't get dismissed.

**To Reproduce**
1. Open other app
2. Write some text, eg "111", select it and share it
3. Select WordPress from the list of apps to share to
4. Select a site
5. Notice gutenberg loading starts but never finishes (issue 1)
6. When you verify the loading doesn't finish, tap on back
7. Notice "Saving" dialog is shown and it doesn't get dismissed (might get dismissed after 1+ minute)

**Expected behavior**
When I share any text from other apps to WordPress for Android, I expect the gutenberg editor to load in a reasonable time and contain the text I shared with the app.

**Screenshots**
https://cloudup.com/cMTVZ62PzZ3

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6, Pixel 4] Emulator
 - OS: [e.g. iOS 8.1,  Android X] Android
 - Version [e.g. 22] 30

**Comment by dcalhoun** [comment]
This may be related to https://github.com/wordpress-mobile/WordPress-Android/issues/15025 and https://github.com/wordpress-mobile/WordPress-Android/issues/14972. My impression was that we addressed the former in https://github.com/wordpress-mobile/WordPress-Android/pull/15027. I suppose we have not completely addressed it or it was reintroduced. 

cc/ @antonis

**Comment by antonis** [comment]
> I suppose we have not completely addressed it or it was reintroduced.

Thank you for the ping @dcalhoun. The applied [fix](https://github.com/wordpress-mobile/WordPress-Android/pull/15027) only covered the create page with template workflow. I added this to the backlog to be investigated further ASAP.

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/15697
