### ISSUE TITLE
Bottom sheet animation is sometimes jumpy on WPAndroid

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4080]
**Describe the bug**

When using the editor in the WPAndroid app, I see the bottom sheet (that's shown for things like block settings), animate up too far sometimes, revealing a gap under the sheet which looks odd

**To Reproduce**

I don't have solid steps to reproduce, most of the time the bottom sheet animation looks normal, but sometimes it appears to jump up too far.

**Expected behavior**
The animation should be smooth and not leave a gap under the sheet.

**Screenshots**

I captured the issue in this screen-recording but couldn't reproduce it consistently.

<img src="https://user-images.githubusercontent.com/1898325/136221950-90093baf-9620-4759-b642-1a8fe4de8cb6.gif" alt="Screenrecording showing jumpy bottom sheet animation" width="350"> 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 10
 - OS: Android 11
 - WPAndroid 18.4 (I don't see this issue when running the Gutenberg demo app)

**Additional context**

**Comment by dcalhoun** [comment]
This may be related to https://github.com/WordPress/gutenberg/issues/32012.

**Comment by guarani** [comment]
> This may be related to [WordPress/gutenberg#32012](https://github.com/WordPress/gutenberg/issues/32012).

Thanks! I forgot to check Gutenberg for issues. I couldn't reproduce in the Gutenberg demo app, only in the main apps, but the issue is hard to reproduce. 

I confident it's the exact same issue, so I'm going to close this issue so we can focus on the single issue.
