### ISSUE TITLE
[Embed block] Add integration tests

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4086]
### Description

The integration tests should cover all the user flows implemented for the block:

- [x] Add Generic Embed from block inserter @fluiddot 
    - [x] Set URL upon block insertion
    - [x] Set URL by tapping on the block
- [x] Add the top 5 specific Embed from block inserter ([reference](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3278)) @fluiddot 
- [x] Paste URL to create Embed block @fluiddot 
- [x] Paste URL to create link @fluiddot 
- [x] Adding a caption @jd-alexander 
- [x] Block settings @jd-alexander 
- [x] Change alignment @fluiddot 
- [x] Replace/Edit URL ([reference](https://github.com/WordPress/gutenberg/pull/33253)) @fluiddot 
    - [x] Invalid URL 
    - [x] Upgrading a block (change the URL to a different provider)
    - [x] Auto-paste URL from clipboard
- [x] Retry @fluiddot 
- [x] Cannot embed @jd-alexander 
- [x] Insert embeds from slash inserter
- [x] Other flows
    - [x] Inline preview coming soon + preview post @fluiddot

**Comment by fluiddot** [comment]
@jd-alexander heads up that I appended more cases that we initially didn't cover.

**Comment by jd-alexander** [comment]
> @jd-alexander heads up that I appended more cases that we initially didn't cover.

Thanks for doing that! 🙇🏾

**Comment by hypest** [comment]
👋 all, I notice that the subcases listed in the description are all marked as "checked" at this point. Does this mean we can close this ticket as "done"? WDYT @fluiddot ?

**Comment by fluiddot** [comment]
> 👋 all, I notice that the subcases listed in the description are all marked as "checked" at this point. Does this mean we can close this ticket as "done"? WDYT @fluiddot ?

I was thinking to close it automatically when the PR that introduces the integration tests is merged.
