### ISSUE TITLE
[Embed block] Add remaining tests to the manual test suites

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4088]
### Description

The remaining tests that can't be automated after adding the [integration](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4086) and [E2E](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4087) tests will require to be introduced into the [manual test suites](https://github.com/wordpress-mobile/test-cases/tree/trunk/test-suites/gutenberg).

#### Test cases
- Verify that inline previews are rendered properly for the top 5 most-used providers (YouTube, Twitter, Instagram, WordPress and Vimeo).
- Verify that inline previews are rendered accordingly for each alignment option.

**Comment by fluiddot** [comment]
I'm thinking to include a manual test for verifying that the inline previews of all providers don't produce style issues, as this verification is visual.

**Comment by fluiddot** [comment]
Another potential manual test case is verifying that the alignment options are properly aligning the inline preview.

**Comment by hypest** [comment]
> of all providers

Just to be sure, are you referring to the "Top 5" perhaps? If yes, better to refer as such in the manual test for clarity.

**Comment by fluiddot** [comment]
> > of all providers
> 
> Just to be sure, are you referring to the "Top 5" perhaps? If yes, better to refer as such in the manual test for clarity.

Right, it should be the top 5 most-used indeed, I'll add this item to the issue's description for clarity.

**Comment by fluiddot** [comment]
This task will be addressed when merging https://github.com/wordpress-mobile/test-cases/pull/93.
