### ISSUE TITLE
Run our full automation test suite on all new changes to the develop branch

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4101]
**Is your feature request related to a problem? Please describe.**

We found in the 1.63.0 release that Dependabot caught an incoming Gutenberg breakage after the fact (i.e. after a previous PR had update the Gutenberg submodule ref). Dependabot was able to catch the breakage while the previous PR did not, because Dependabot [runs optional tests by default](https://github.com/wordpress-mobile/gutenberg-mobile/blob/7909858ebef88b1581c8c19afaa848c87843f919/.circleci/config.yml#L359-L365), but regular PRs do not (they are optional tests that must be manually triggered).

**Describe the solution you'd like**

Dependabot [runs daily](https://github.com/wordpress-mobile/gutenberg-mobile/blob/91cd7cbc143c664b3d7f4b3a730ae3b6d017ac8a/.github/dependabot.yml#L11), so to reduce the amount of time between a breakage being introduced and it potentially being caught by Dependabot, this issue proposes to have all updates to the Gutenberg Mobile `develop` branch trigger the full suite of tests. I think this is similar to the main apps which run optional tests after PRs have merged to `develop` (e.g. [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/34378daba930fba6d431b654161ae19758854c4f/.circleci/config.yml#L314) for WPiOS, and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/4ad8ab604d44eb14a2571355098199de63f3ea34/.circleci/config.yml#L361) for WPAndroid).

**Describe alternatives you've considered**

Alternatives include:
- making Gutenberg Mobile optional tests not optional anymore (would slow down our workflow for all developers)
- leaving things as-is since this proposal only shortens the time between an incoming Gutenberg breakage being introduced and it being detected, it doesn't avoid detection happening after the fact
- Moving optional tests to the Gutenberg repo and possibly running them there on all updates to `trunk` (would slow down the workflow for all mobile/web developers)

**Comment by guarani** [comment]
Dependabot might not be the right tool to achieve the goal of running optional tests on every update to `develop`, since this task won't involve updating dependencies.

**Comment by mchowning** [comment]
👍 I like this idea!

**Comment by guarani** [comment]
👋 Hey @mchowning, I've updated the issue now that I think a solution to this involves CircleCI, not Dependabot. I've also added you as a reviewer here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4114
We could definitely discuss this as a team before moving ahead with it (since it's a change that affects our shared workflow), but I'm keen to hear what you think at this early stage.
