### ISSUE TITLE
Quote block still exists after deleting from post via backspacing

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#4120]
**Describe the bug**
After deleting a quote block and exiting the editor (or switching to HTML view) the quote block seems to still be there when opening the post again.

I've verified it both on WPAndroid, WPiOS, as well as the demo app.

**To Reproduce**
1. Go to the demo app or WPAndroid (tested on v18.4-rc-3)
2. Insert a new Quote block
3. Focus the Quote block and delete it by backspacing. Notice the block being removed.
4. Exit the editor (save the draft if asked) or switch to HTML View
5. Re-enter the editor and notice the quote block still being there, or notice the `blockquote` markup if you switched to HTML view 💥

**Expected behavior**
The quote block should not have appeared after re-opening the post, nor be there in HTML view after been backspaced.

**Screenshots**

https://user-images.githubusercontent.com/1032913/137279062-2e25a49e-8958-4328-8428-4729848b5447.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11
 - Version WPAndroid v18.4-rc-3, gutenberg-mobile `develop` 3f190752

**Additional context**

**Comment by hypest** [comment]
Marking this as `[Pri] High` as it involves a content fault.

**Comment by fluiddot** [comment]
I noticed that this can be reproduced with any block if it's added as the first item of the block list. After checking older versions, I confirm this began to happen in version `1.61.0 (18.2)`.

**Comment by fluiddot** [comment]
As mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/35624#issuecomment-943202860), this looks like a breakage from a change in Gutenberg.

**Comment by hypest** [comment]
I'll go ahead and close this ticket for now and we can reopen if for any reason it turns out to only happen on native mobile.
