### ISSUE TITLE
Jetpack Tiled Gallery: Workaround used for `save` functionality

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#4137]
We're currently using a workaround to get `save` functionality and loading from that serialized HTML working correctly. Using this workaround allows us to be unblocked and work on other parts; however, we should revisit this at some point.

Note: test if core blocks also display a different path when the `save` function is called from `getSaveContent` vs the serialization code.  See [this Google doc](https://docs.google.com/document/d/1U7yyBgE6yfedydI7ZFFSrtcg8mUGfOirYFiYX_7zLIk/edit) for details.

See [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4142) for exact web/mobile differences.

Related:
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/4075

**Comment by guarani** [comment]
Resolved by https://github.com/Automattic/jetpack/pull/21643.
