### ISSUE TITLE
Jetpack Tiled Gallery: Max Columns

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#4138]
Do we want to set the maximum columns in the settings to the static number (which we have 8 atm to match with gallery block) or do we want to set it to the number of images?

We can see both ways:
* If we set it to the static number:
    * Less presses for the user if they can set it to 8 even if they only have 2 images right now; when adding more they don't have to keep changing the maximum.
    * Less confusion (the maximum number doesn't keep changing)
    * More confusion as to why they set the number of columns to 8 and it's only showing as 2 columns in the editor when they have 2 images.
 * If we set it to the maximum number of images:
    * Less confusion as to why the setting isn't matching up with what they're seeing
    * More touches in order to set the maximum
    * Gallery block does it this way, as does the web implementation.
 
CC: @iamthomasbishop @mchowning @guarani @SiobhyB 

Related:
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/3947

**Comment by guarani** [comment]
@illusaen, I'd go with the second option above. I think it makes sense to default to the web's Tiled Gallery implementation here to give a consistent user experience across web and mobile. Regarding the Square Layout, here's what I think we should implement based on the web's behavior:

#### The columns setting's upper limit is equal to the number of images

In my testing, unlike the core Gallery block, the Tiled Gallery block does not limit columns to eight. It's instead limited to the number of images in the Tiled Gallery.

#### The columns setting's default value is dynamic

- For three or less images, the column setting is automatically updated to match the number of images in the Tiled Gallery, unless the user has modified the setting to anything other than the default.
- For four or more images, the column setting stays at the default of **three** (or the value the user manually set it to)

#### The columns settings is only shown when there are multiple images

If the user only adds a single image, the column setting is not shown in the block's settings.

--- 

If we decide on this, I think we could close this issue and create a new one to capture the exact requirements we want. Ideally, we can hook into the web's implementation here.

**Comment by illusaen** [comment]
@guarani I think matching functionalities makes sense; however, this does then bring up the question of how we want to handle the editor's preview. If, for example, the user has 8 columns set, do we want to then show 8 columns on the mobile screen? Or do we want to decouple columns _settings_ from columns previewed?

**Comment by guarani** [comment]
I'm just responding here based on what we discussed offline yesterday.

> this does then bring up the question of how we want to handle the editor's preview.

I think this issue covers the actual columns setting's limits (e.g. min and max value) and the question of how many columns will be rendered in the in-editor preview is tracked separately in https://github.com/wordpress-mobile/gutenberg-mobile/issues/4147.
