### ISSUE TITLE
Jetpack Tiled Gallery's Link To implementation

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4156]
In https://github.com/wordpress-mobile/gutenberg-mobile/issues/4136#issuecomment-952021071, it was concluded that the Jetpack Tiled Gallery's "Link To" functionality (found in its settings bottom sheet) should be implemented to match the web's link to options ("Media File" and "Attachment Page"). These options apply at a gallery-level (i.e. link to functionality won't be found in individual blocks, but instead at the parent block level).

At time of writing, the UI of these options is being developed for other blocks (see https://github.com/WordPress/gutenberg/pull/34846). Given this, we also decided that the Tiled Gallery can be shipped without the "Link To" functionality and this can be added later (hence this issue stands to capture that requirement).

For reference, this is what the options should do:
- Media File: This makes the gallery's images clickable. Clicking the images opens a direct link to the image's underlying media file.
- Attachment Page: This also makes the gallery's images clickable, but instead clicking results in a carousel (or other theme-specific) attachment page to be shown.

For reference, the Image block's settings are implemented [here](https://github.com/WordPress/gutenberg/blob/cec3b9baf99e7fe1671bc9673b065154b0f672b0/packages/block-library/src/image/edit.native.js#L586-L588).

**Comment by mchowning** [comment]
I'm not really sure whether the Enhancement label makes sense here. Feel free to remove/replace it.

**Comment by guarani** [comment]
> I'm not really sure whether the Enhancement label makes sense here. Feel free to remove/replace it.

I like this idea because easily filtering a project's issues vs bugs seems useful.
