### ISSUE TITLE
Tiled Gallery `save` workaround: Unit test seeing infinite recursion when rendering the block

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#4168]
See details in the [gbm PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4143). Note: remove the added `.skip` for the unit test when fixed!

**Comment by guarani** [comment]
👋 @SiobhyB just a heads-up, I moved this from "In Progress" to "Todo" on our project board, so feel free to un-assign yourself from this issue.

**Comment by SiobhyB** [comment]
Perfect, thank you @guarani!
