### ISSUE TITLE
Highlighted text shows HTML in block editor on WordPress App

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/gutenberg-mobile#4185]
**Describe the bug**
If you create a post from the WordPress editor which uses the 'highlight' inline text formatting option, when opened in the WordPress app editor this text displays as `[MARK]`. If the app is set to Chinese, it displays with a Question Mark (?) making it confusing for the user to understand how to edit this text.

**To Reproduce**
1. Create a new post from a WordPress site and use the option to highlight text in a paragraph block. 
2. Publish the post or save as draft.
3. Open the same site and post in the WordPress app and confirm instead of showing the text it will display `[MARK]` if your app is set to English. 
4. If you preview the post, the text will display correctly. This only happens in the editor.

**Expected behavior**
I'd expect the text to display even if the formatting option to highlight is not supported in the app. 

**Screenshots**
![Image 2021-10-30 at 2 40 20 pm](https://user-images.githubusercontent.com/10325627/139535514-81b8dac5-3758-4a69-8992-d4f329c0da69.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14.8
 - Version: WP iOS 18.1.0.0 (not sure how to check the Gutenberg version, but it's a WP.com Premium plan site I tested on)

**Additional context**
User reported in 4378760-zen

**Comment by antonis** [comment]
Thank you for reporting @rezzap 🙇 
This is already fixed in the upcoming `18.6` release with https://github.com/WordPress/gutenberg/pull/35956
