### ISSUE TITLE
[WPAndroid] fonts are not the same as in iOS

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#419]
First reported by @pinarol 

GB on Android is not loading Noto Serif apparently

<img width="677" alt="screen shot 2018-12-20 at 17 07 19" src="https://user-images.githubusercontent.com/6597771/50290138-86ab2e80-0449-11e9-82df-a88dec5b8304.png">

**Comment by hypest** [comment]
This ticket was actually worked on in #530 so, moving this to in-progress.

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/513
