### ISSUE TITLE
Check Photonizer's URL that we've currently added a Platform check to in the main app; especially regarding resizes

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#4206]
Double check that the main apps have the resize attribute on the urls when inserting real pictures as opposed to the URLs we get in the demo app.

See [#21643](https://github.com/Automattic/jetpack/pull/21643)

**Comment by guarani** [comment]
@SiobhyB checked and confirmed that the resize attribute is present on the Square layout's HTML.
