### ISSUE TITLE
Add Square layout test for deserializing block from HTML

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4208]
As a follow-up to the Tiled Gallery test added in https://github.com/wordpress-mobile/gutenberg-mobile/pull/3903, a test should be added that loads the Tiled Gallery from its HTML representation. It could be implemented as a group of tests that cover the Square layout in various distinct configurations. For example:
- Load HTML of single row Tiled Gallery into the editor and verify it loads correctly
- Load HTML of multiple row Tiled Gallery into the editor and verify it loads correctly

**Comment by illusaen** [comment]
Moved integration tests to phase 2 due to new issues.
