### ISSUE TITLE
Verify Tiled Gallery's media selection UX

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4212]
**Is your feature request related to a problem? Please describe.**

The Tiled Gallery block's media selection UX should be similar to that of the core Gallery block.

**Describe the solution you'd like**

- Verify that adding more images works as expected (e.g. after some images have been added, the user should be able to add additional images without having to select all images again) and check other common user flows. 
- Verify that editing image selection works as expected (i.e. user adds four images and then decides to remove two).
- Verify that media selection is disallowed for users that don't have the right role (should work similar to other blocks).

If everything works well, this issue can be closed.

**Additional context**

The issue involves first identifying any shortcomings in the Tiled Gallery's current media selection UX and making edits to this issue to ensure they are addressed.

**Comment by illusaen** [comment]
Note: Use the tiled gallery block in the main app like a user to make sure that the initial UX doesn't break and works as a general building block to be polished in Phase 2.

**Comment by SiobhyB** [comment]
I tested the block and confirmed the following:

* It's possible to select multiple images when adding to the gallery, even if some images have already been added.
* Editing an image selection works the same way as it does on the web (i.e. after adding four images, you can still remove any of those individually.). It's also possible to change the position of images within the gallery via the image block's arrow controls.

The above was tested using the default admin user role. I then went on to test as a contributor and found it's possible to upload images to the block, even though it shouldn't be under that role. This bug can also be found in the gallery block, which I've reported at https://github.com/wordpress-mobile/gutenberg-mobile/issues/4293.

@guarani, @illusaen, what do you think about closing this issue in favour of the newly created one?

**Comment by guarani** [comment]
Thank you for verifying the Tiled Gallery's behavior here, @SiobhyB!

> what do you think about closing this issue in favour of the newly created one?

It sounds like apart from the media upload bug, no other issues were uncovered. I'd agree then that this issue can be closed since our media selection UX appears to be in good shape.

**Comment by SiobhyB** [comment]
Perfect, thank you!
