### ISSUE TITLE
Jetpack Tiled Gallery: Add Alignment Options

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#4245]
The alignment options for the Tiled Gallery block on native should match what we see on the web.

As you can see from the following video of the web's functionality, it's possible to access the block's alignment options by either selecting the block as a whole or by selecting an individual image:

https://user-images.githubusercontent.com/2998162/141979219-0ce24f4d-0ac5-413f-936a-d3d7f6512f09.mov

A few additional points to note:

* The _none_, _wide_, _full_, and _center_ alignment options are available, but _wide_ and _full_ will only appear if they're explicitly supported by the active theme.
* It's possible to change the alignment by either selecting the block as a whole or by selecting an individual image i.e. changing an individual image's alignment will impact the _whole_ block, not just that image.

**Comment by SiobhyB** [comment]
The alignment options for the block as a whole appear to work out of the box for me. As the video shows, I'm able to set the _none_, _wide_, _full_, and _center_ alignment options. I confirmed the HTML updates in the same way as I see it update on the web, also: 

https://user-images.githubusercontent.com/2998162/142047256-a10cb0ac-6228-4123-88dc-f8270c75892a.mov

I'll address the alignment options for individual images in a separate comment.

**Comment by SiobhyB** [comment]
The alignment options were hidden from individual images in https://github.com/Automattic/jetpack/pull/21694, as part of the efforts to hide the image block's settings.

Prior to that change, all of the image block's alignment options were available i.e. _none_, _wide_, _full_, _center_, _left_, and _right_. If we decide to bring the options back to individual images, we'd need to figure out the following:

* The code we've introduced to hide the settings would need to be tweaked so that it doesn't hide the image block's alignment options. I think this would be the easier of the two challenges we'd need to figure out.
* As the _left_ and _right_ alignment options aren't supported by the Tiled Gallery block, we'd need to hide them from the inner image blocks. To do that, we'd need to figure out a way to pass the `controls={ [ 'center', 'wide', 'full' ] }` prop to the image block's `BlockAlignmentToolbar` component [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/image/edit.native.js#L610). I'm not sure if there is any straightforward to achieve this and suspect we'd find it hard to get the needed hacks approved on the web-side.

@guarani, @illusaen, what are your thoughts around next steps here? I think there are two options:

1. Stick with only having the alignment options available from the Tiled Gallery block's settings, but not from the inner image blocks. 
2. Work to also make the alignment options available from the individual inner image blocks. 

The second option won't actually add any new functionality, as the alignment will change the whole block, which is possible to do directly from the main block's settings. It also involves further challenges with editing inner blocks, with uncertainty around what the limitations are. However, it will enable us to match with the web's behaviour.  

I'm personally leaning towards the first option, as I feel it includes all the alignment functionality users may need. I'm uncertain whether the work involved with also adding these options to the inner blocks is worthwhile, especially as the block may be refactored in the future.

Interested to hear your thoughts too, and whether I'm missing anything here. Thanks!

**Comment by guarani** [comment]
Thanks for summarizing the options here, @SiobhyB!

I vote for the first option, too. It's my understanding that alignment options on the web appear when you select images because there is nothing else to select but the block itself. Clicking an image effectively selects the whole Tiled Gallery block, thus showing the block's settings sidebar.

It sounds like no PRs will be needed on this issue and will be able to be closed as resolved.

**Comment by SiobhyB** [comment]
Perfect, thanks for confirming Paul! I'll go ahead to close this 🥳
