### ISSUE TITLE
Jetpack Tiled Gallery: Block's initial HTML should match the web

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#4262]
**Describe the bug**

The initial HTML that's loaded when adding the Tiled Gallery block is currently different to the across native and web.

When added via the web, the HTML is as follows: `<!-- wp:jetpack/tiled-gallery /-->`

While on native, the HTML currently includes `columns` and `ids` attributes: `<!-- wp:jetpack/tiled-gallery {\"columns\":2,\"ids\":[]} /-->`

This needs to be updated on native to match the web.

**To Reproduce**

1. With the Tiled Gallery feature branch checked out, open the demo app and add the Tiled Gallery block.
2. Switch the editor to HTML mode to view the block's HTML.
3. See that the block's HTML is as follows: `<!-- wp:jetpack/tiled-gallery {\"columns\":2,\"ids\":[]} /-->`

**Expected behavior**

The HTML should match up with the web: `<!-- wp:jetpack/tiled-gallery /-->`

**Smartphone (please complete the following information):**
 - Device: iPhone 12 simulator
 - OS: iOS 14.5

**Comment by guarani** [comment]
We don't think this affects user-related functionality in any way.

**Comment by guarani** [comment]
👋 @SiobhyB, do you recall if this issue was a contributing factor in the decision to disable https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/jetpack/test/tiled-gallery.js? If I recall correctly, it was this issue as well as https://github.com/wordpress-mobile/gutenberg-mobile/issues/4168.

**Comment by SiobhyB** [comment]
@guarani, you're right that it was https://github.com/wordpress-mobile/gutenberg-mobile/issues/4168 that originally led to the decision to disable those tests, and this issue was discovered after that. Both would need to be fixed before enabling the tests again.
