### ISSUE TITLE
Verify that Tiled Column layout works

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#4267]
Verify that Tiled Column layout correctly sets the HTML so that it can be seen in Preview Post.

Note: Do after Mosaic layout is done as we surmise that most of the work for this is shared with Mosaic layout.

**Comment by guarani** [comment]
Good news is that after the Mosaic layout was implemented in https://github.com/Automattic/jetpack/pull/21767, the Tiled Columns layout's basic functionality appears to be working. The following video shows a preview of a post containing a Tiled Columns block created in the mobile editor.

https://user-images.githubusercontent.com/1898325/143494373-6ec58392-55c2-4c68-b43d-1d9a7f5a3522.mov

**Comment by guarani** [comment]
I'm closing this issue since the above comment confirmed that the Tiled Columns layout works at some level.
I've created the following issue to address an aspect-ratio related bug with this layout:
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/4305
