### ISSUE TITLE
Gallery block: Media selection bottom sheet automatically opens on self-hosted but not Simple sites

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#4269]
**Describe the bug**
Upon adding a Gallery block from the Inserter, the media selection bottom sheet ("Choose from device", "Take a photo", etc..) opens automatically when on a self-hosted site, but doesn't seem to open on WPCOM Simple sites.

**To Reproduce**
1. On a self-hosted site, via WPAndroid or WPiOS,
2. Add a Gallery block to an empty post
3. Notice that media selection bottom sheet pops up automatically
4. ....
1. On a WPCOM Simple site, via WPAndroid or WPiOS,
2. Add a Gallery block from the block Inserter
3. Notice that media selection bottom sheet **doesn't** pop up automatically

**Expected behavior**
The bottom sheet should have the same behavior on Simple and self-hosted sites (either automatically open or not)

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL, iPhone 6s
 - OS: Android 11, iOS 15.1
 - Version WPAndroid v18.7-rc-2, WPiOS v18.7

**Comment by hypest** [comment]
👋 @jd-alexander , I think you worked in the past on automatically opening the media selection bottom sheet, can you take a look on this one? It's a weird misalignment between the site types. Thanks!

**Comment by jd-alexander** [comment]
> 👋 @jd-alexander , I think you worked in the past on automatically opening the media selection bottom sheet, can you take a look on this one? It's a weird misalignment between the site types. Thanks!

I will take a look. 🙇🏾
