### ISSUE TITLE
Make a media processor for the Tiled Gallery block

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4270]
Media processors are used to make sure media uploads work after the user exits the editor.

**Comment by SiobhyB** [comment]
Removing my assignment as I'm not actively working on this. I did some initial work on the Android-side in the following (now closed) PR that may be helpful as a reference for others who may take this over in the future: https://github.com/wordpress-mobile/WordPress-Android/pull/15633
