### ISSUE TITLE
Tiled Gallery layout selection UI should show layout previews

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4274]
**Describe the bug**

When the user chooses a layout in the Tiled Gallery's settings, the app should display an image preview of the layout but currently just shows the layout's name.

| Expected | Actual |
| - | - |
| <img width="200" alt="Screen Shot 2021-11-22 at 18 21 35" src="https://user-images.githubusercontent.com/1898325/142937167-810985c3-b672-48cd-b6d2-2cc95a3aa159.png"> | <img width="300" alt="Screen Shot 2021-11-22 at 18 20 06" src="https://user-images.githubusercontent.com/1898325/142937184-2b8c110d-726f-442e-bbfa-f17dbe15f969.png"> |

_Note: Other UI fixes, such as using a multi-row grid for previews, will be addressed in other issues._

**To Reproduce**

The app must be ran from the Gutenberg Mobile feature branch, `add/tiled-gallery-block`:

1. Add the Tiled Gallery block
2. Tap the settings button
3. Tap the "Gallery style" row
4. Notice the layouts that are shown are missing images

**Expected behavior**
Layouts should show images so users know what they look like.

**Comment by guarani** [comment]
👋 @kyleaparker, for the Tiled Gallery's layout picker, would it make sense to use static images for each layout's preview? While the web dynamically creates each layout's preview using six sample images bundled with the block, that approach would be difficult to pull of on mobile. Do you think we could use the below sample images to compose each layout's preview into a single static preview image? If so, I'd appreciate if you could please help make each layout preview image which we could then include in the apps.

The six sample images can be found here (these are the ones the web uses, and I assume we want to use the same on mobile):
- https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-1.jpg
- https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-2.jpg
- https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-3.jpg
- https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-4.jpg
- https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-5.jpg
- https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-6.jpg

**Comment by kyleaparker** [comment]
> 👋 @kyleaparker, for the Tiled Gallery's layout picker, would it make sense to use static images for each layout's preview?

Yes I think that's OK and the images proposed look good 👍

**Comment by guarani** [comment]
@kyleaparker, sounds good! 👍 

Could you provide us with the final four images (one for each layout) when you get a chance please?

**Comment by kyleaparker** [comment]
Let's try these 4:

https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-2.jpg

https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-4.jpg

https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-5.jpg

https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/tiled-gallery/tiled-gallery_example-6.jpg

**Comment by guarani** [comment]
@kyleaparker sorry, I meant to ask for four images that look something like these:

| Tiled mosaic | Circles | Square tiles | Tiled columns |
| - | - | - | - |
| <img width="135" alt="Screen Shot 2021-11-26 at 09 57 40" src="https://user-images.githubusercontent.com/1898325/143584762-6317011c-6b09-4103-a540-b42329d1111a.png"> | <img width="147" alt="Screen Shot 2021-11-26 at 09 57 50" src="https://user-images.githubusercontent.com/1898325/143584758-9a55c6ba-b9fa-4900-81d1-0b5c54c7a0b6.png"> | <img width="141" alt="Screen Shot 2021-11-26 at 09 57 59" src="https://user-images.githubusercontent.com/1898325/143584749-1f072f4f-7bb1-4f47-8b90-8d0b35d4be6b.png"> | <img width="135" alt="Screen Shot 2021-11-26 at 09 58 05" src="https://user-images.githubusercontent.com/1898325/143584741-b42bbeb3-2132-4856-a8a8-caaa5e4be899.png"> |

If possible, could I ask for:
- The images to be high res
- The images to have transparent backgrounds (e.g. to leave space in-between circles in the Circle layout), if you agree this is a good idea

🙇

**Comment by kyleaparker** [comment]
@guarani ahh sorry, I'll prepare something today!

**Comment by guarani** [comment]
Thanks @kyleaparker!

**Comment by kyleaparker** [comment]
Here are the 4 examples: 
![squares-example](https://user-images.githubusercontent.com/712873/144121322-7b1341c8-bc0a-4311-860f-b36a2415b0c7.png)
![columns-example](https://user-images.githubusercontent.com/712873/144121325-bc53794a-9a46-4367-bb09-2dffc734327f.png)
![circles-example](https://user-images.githubusercontent.com/712873/144121326-b8bdc7e2-2328-4af3-900a-66a3967f7fee.png)
![mosaic-example](https://user-images.githubusercontent.com/712873/144121328-c7df668f-269a-49c3-a5a9-1fc2589e7ecb.png)

Let me know if that works!

**Comment by guarani** [comment]
I'm unassigning myself from this issue while our focus moves to the Square layout (which means this issue, layout selection, won't be needed for now).
