### ISSUE TITLE
Tiled Gallery layout selection UI does not render on multiple rows

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4275]
**Describe the bug**

When the user chooses a layout in the Tiled Gallery's settings, the app should display the layout previews in a multi-row grid. Instead, the app displays the layout previews in a single, scrollable row.

| Expected | Actual |
| - | - |
| <img width="300" alt="Screen Shot 2021-11-22 at 18 21 35" src="https://user-images.githubusercontent.com/1898325/142940567-eb8accd5-d4e4-467f-ba1a-4e383d34beea.png"> | <img width="200" alt="Screen Shot 2021-11-22 at 18 20 06" src="https://user-images.githubusercontent.com/1898325/142940589-6ff8ed57-184a-4ae9-ad57-db60800ec3ff.png"> |

_Note: Other UI fixes, such as layout preview images not rendering, will be addressed in other issues such as https://github.com/wordpress-mobile/gutenberg-mobile/issues/4274._

**To Reproduce**

The app must be ran from the Gutenberg Mobile feature branch, `add/tiled-gallery-block`:

1. Add the Tiled Gallery block
2. Tap the settings button
3. Tap the "Gallery style" row
4. Notice the layouts that are shown in a single, scrollable row instead of a multi-row grid as shown in the designs.

**Expected behavior**
Layouts render in a multi-row grid layout.

**Comment by guarani** [comment]
@kyleaparker, could we leave this out of the first shippable version of the Tiled Gallery block? It seems like it would be an enhancement, not a bug as such.

**Comment by kyleaparker** [comment]
@guarani yes an enhancement sounds good, I don't think this is critical to shipping 👍

**Comment by guarani** [comment]
Thanks @kyleaparker!
