### ISSUE TITLE
The Tiled Columns layout does not respect image aspect ratios

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4305]
**Describe the bug**

When previewing the Tiled Columns layout of the Tiled Gallery block, the site's front-end is showing all images square. Instead, images aspect ratios should be respected (i.e. if an image is rectangular, it should still be rectangular on the site's front-end).

**To Reproduce**

<details>
<summary>Setup to test from the main apps</summary>
<p>
<ol>
<li>Run the packager from the <code>add/tiled-gallery-block</code> branch: <code>npm run start:reset</code></li>
<li>Run either of the main apps (WPiOS or WPAndroid)</li>
<li>Open a new post in the main apps and expect the editor to load from the running packager</li>
</details>

Then:
1. Add a Tiled Gallery block with a few images that use different aspect ratios
2. Switch to the Tiled Columns layout
3. Preview the post
4. Notice the images are all squares

**Expected behavior**
Image aspect ratios should be reflected accurately on the site's front-end.

**Screenshots**

_Note that because the aspect ratios are not respected, the images are laid out differently (different number of images per column) on mobile and web._

| Correct (Web) | Incorrect (Mobile) |
| - | - |
| <img width="1000" alt="Screen Shot 2021-11-26 at 16 08 51" src="https://user-images.githubusercontent.com/1898325/143622705-5e3df272-274a-485c-9903-be104f331a2a.png"> | <img width="1000" alt="Screen Shot 2021-11-26 at 16 00 30" src="https://user-images.githubusercontent.com/1898325/143622772-17e0ef82-1923-446a-9a19-bc6fada3efc2.png"> |

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 15
 - Version: Current `add/tiled-gallery-block` branch

**Comment by guarani** [comment]
This could be caused by the block context that was added for the Square layout. Or by the hard-coded 100x100 dimensions we need to remove (tracked in another issue).

**Comment by fluiddot** [comment]
@lmischner since the Tiled Gallery block is not available to users yet, I think we could remove it from the Maintenance Week's board.
