### ISSUE TITLE
Jetpack Tiled Gallery: 'Problem displaying block' error when used in Reusable block 

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#4309]
**Describe the bug**

When attempting to use a Reusable block that contains the Jetpack Tiled Gallery block in the apps, a `problem displaying block` error pops up.

**To Reproduce**
Steps to reproduce the behaviour:
1. First, in a web browser, go through [the steps to create a Reusable block](https://wordpress.com/support/wordpress-editor/blocks/reusable-block/#create-a-reusable-block). 
2. Add the Tiled Gallery block to your new Reusable block and save your changes.
3. Next, open the app on iOS or Android and navigate to the site where you create the Reusable block.
4. Go through the steps to create a new post and add the Reusable block to it.
5. Observe the `problem displaying block` error.

**Expected behaviour**

I expected it to be possible to view and edit the Tiled Gallery within the Reusable block.

This expectation comes from the fact it's possible to edit other supported blocks within the Reusable block in the apps. For example, I also tested using the Contact Info and core Gallery blocks, which worked as expected.

**Screenshots**

<img src="https://user-images.githubusercontent.com/2998162/143611130-2c569ca6-89e3-4048-9ffd-b9bb121eca5e.png" width="50%"/>

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android version 12
 - Version: Jetpack Tiled Gallery feature branch.

**Comment by guarani** [comment]
Assigned low priority because we don't foresee Tiled Gallery being used in reusable blocks often.
cc @SiobhyB @illusaen

**Comment by mchowning** [comment]
> Assigned low priority because we don't foresee Tiled Gallery being used in reusable blocks often.

What would you think about marking this as a medium since it is a "broken" flow, and we have the medium option in mobile-gutenberg @guarani ?

**Comment by guarani** [comment]
I agree with moving it to Medium 👍  Since we've moved this to Phase 2 that should be enough to signal that it's not a priority for Phase 1B.
