### ISSUE TITLE
Tiled Gallery Block: Verify contrast between text and background in dark mode

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#4310]
While working on https://github.com/Automattic/jetpack/pull/21884, I spotted that the contrast between the `Tiled mosaic` label and the background was off in dark mode:

<img src="https://user-images.githubusercontent.com/2998162/143862397-0e051e20-69a6-4c91-86fb-54abb1ca5297.png" width="50%">

I haven't been able to reproduce the issue since creating the PR, but it'd be good to do some more testing to double-check whether there are cases where this is reliably reproducible in dark mode or if it was an edge case. It'd also be good to do more testing in dark mode to see if there are any other issues.

**Comment by guarani** [comment]
Closing in favor of https://github.com/wordpress-mobile/gutenberg-mobile/issues/4276 where I've updated it to include this dark mode issue.
