### ISSUE TITLE
iOS - Scrolling behavior hides the caret when tapped at the beginning of a very long text

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#432]
Scrolling behavior hides the caret when user taps at the beginning of a very long text. This happens because KeyboardAwareScrollView always focuses at the end of the selected react element. Let's dig in some more to make it scroll to the cursor instead.

![ezgif com-video-to-gif-4](https://user-images.githubusercontent.com/5032900/50338682-2938df80-0526-11e9-8a4a-cd038922ec85.gif)

**Comment by koke** [comment]
Related to #427

**Comment by SergioEstevao** [comment]
I'm no longer able to reproduce this on iOS so I'm closing this ticket.
