### ISSUE TITLE
Heading block :  split and merge causes empty paragaph and new lines during operation

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/gutenberg-mobile#4322]
**Describe the bug**
While testing the writing flow, specifically, [splitting/merge list block](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) I noticed that the when the block was being split one of the Paragraph blocks created had no hint and the newly created block with the second half of the split content had a new line. 

**To Reproduce**
1. Go to a post/page.
2. Add a Heading block.
3. Perform the split and merge.
4. Notice that a paragraph without a hint is created and new lines are added to the blocks. 
5. 5. Also notice how merging does not behave as expected.

**Expected behavior**
Splitting and merging should not cause any inconsistent behavior. The content should be split in half and there should be no changes to text or structure as a result. 

**Screenshots**

https://user-images.githubusercontent.com/1509205/144172500-c5418ab1-7fbf-467c-9a4c-ed1bcf4ff266.mp4

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL
 - OS: Android 12
 - Version 18.8 ( [Release 1.67.0](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4289) )

**Additional context**
This only takes place on Android. The behavior functions as expected on iOS.

**Comment by SiobhyB** [comment]
@hypest and I did some more testing, Stefanos confirmed this can be replicated with a really old version of the app (17.8) as long as the OS is updated to Android 12. I also replicated on version 18.6 of the app. It doesn't appear reproducible on Android 11.
