### ISSUE TITLE
Button Block: Alignment Options

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/gutenberg-mobile#4327]
**Is your feature request related to a problem? Please describe.**
The Button block does not offer the ability to set alignment, but this is available within the browser.

**Describe the solution you'd like**
Add an alignment option within the Button block's … menu.

**Additional context**
4563549-zd-woothemes

**Comment by thabotswana** [comment]
It looks like we do have alignment options when selecting the parent Buttons block

https://user-images.githubusercontent.com/35628116/148081243-19d3692a-4d79-4da5-b11b-52275b4052d4.mp4

We can close this issue
