### ISSUE TITLE
Android - Scrolling behavior hides the caret when tapped at the ending of a very long text

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#433]
Scrolling behavior hides the caret when tapped at the ending of a very long text. This happens because Android always focuses at the beginning of the selected element. Not sure if this is perceived as a real bug on Android platform but it is worth digging in some more.

![ezgif com-video-to-gif-5](https://user-images.githubusercontent.com/5032900/50338979-1ffc4280-0527-11e9-8689-ccfa49ffa9fb.gif)

**Comment by maxme** [comment]
I can't reproduce that one (Tested on an emulator on a real device with wpandroid alpha-223), when I tap at the bottom of a paragraph, the cursor is placed at the end of the paragraph and the view is centered on the bottom.
