### ISSUE TITLE
Tiled Gallery: Design Review

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#4335]
## Design Review Request

👋  @kyleaparker and @iamthomasbishop, as we're closing in on a shippable version of the Tiled Gallery block, we're at a point where we'd like to get a design review. Installable builds are up for each app and we'd be keen to hear any feedback or areas for improvement. Thanks in advance! 🙇‍♀️ 

## Installable Builds

* Android: https://github.com/wordpress-mobile/WordPress-Android/pull/15619#issuecomment-979373126
* iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/17618#issuecomment-985423423

## Additional Notes

* We used inner blocks to pull in images to the gallery, which makes our implementation different from the original design i.e. the image block's built-in controls/settings icons are used.
* For phase 1b, we'll only be introducing the block to simple WordPress.com sites. It'll be released to Atomic and Jetpack sites in future phases.
* A listing of all known open issues can be found on the project board: https://github.com/orgs/wordpress-mobile/projects/104/views/9
* The current ETA for phase 1b is January 14th, which takes into account the higher-than-usual number of AFKs throughout the holidays.

**Comment by guarani** [comment]
> A listing of all known open issues can be found on the project board: https://github.com/orgs/wordpress-mobile/projects/104/views/9

👋 @kyleaparker and @iamthomasbishop, while the above project board covers the issues we plan on fixing before shipping this block, you might run into issues that we've triaged and determined best left for a later release. These can be found by switching to the "Open issues" tab of that project board, under the "Phase 2" section.

**Comment by kyleaparker** [comment]
> 👋 @kyleaparker and @iamthomasbishop, as we're closing in on a shippable version of the Tiled Gallery block, we're at a point where we'd like to get a design review. Installable builds are up for each app and we'd be keen to hear any feedback or areas for improvement. Thanks in advance! 🙇‍♀️

Thank you, I'll test this today or tomorrow!

**Comment by kyleaparker** [comment]
I've done a first pass ✅  It's coming together really well but I came across a few issues. Sorry if I mention issues that are already logged, I tried to cross check with the board but I may have overlooked some. 

1. Looks like there is some extra padding at the top of the empty block, this should match the padding on the left and right edges
<img width="450" alt="Monosnap 2021-12-08 21-26-26" src="https://user-images.githubusercontent.com/712873/145323159-ab39bf96-0ae8-4a14-8b86-33374b56f53a.png">

2. The block settings icon shouldn't appear until after the media is inserted (this is how it works on the gallery block)
3. Should we be center aligning by default?
4. It looks like we are supporting unlimited columns, but none of the gallery styles are working including circles (this may still being worked on) 
5. The rounded corners setting didn't do anything for me
6. There is no way to reorder images when they are small (the arrows disappear) 
<img width="434" alt="Screen Shot 2021-12-08 at 9 29 23 PM" src="https://user-images.githubusercontent.com/712873/145323429-99a8b1b5-269b-4be1-b9c0-0d5bd9cdb03a.png">

That's all for now!

**Comment by SiobhyB** [comment]
Thank you for the review @kyleaparker! 🙌 

> 1. Looks like there is some extra padding at the top of the empty block, this should match the padding on the left and right edges
> 2. The block settings icon shouldn't appear until after the media is inserted (this is how it works on the gallery block)

I've gone ahead to create issues for these at https://github.com/wordpress-mobile/gutenberg-mobile/issues/4376 and https://github.com/wordpress-mobile/gutenberg-mobile/issues/4377 🙇‍♀️ 

> 3. Should we be center aligning by default?

The web centre aligns by default, too, and my sense is that it's preferable to match up with the web where possible. Do you have any strong feelings or other thoughts about this? If so, I'd be happy to create a separate issue for further discussion/discovery.

> 4. It looks like we are supporting unlimited columns, but none of the gallery styles are working including circles (this may still being worked on)
> 5. The rounded corners setting didn't do anything for me

The styles and rounded corner settings should work **but** the in-editor previews aren't implemented as part of this phase of the block, I wonder if that maybe caused some confusion here? Are you seeing changes after previewing the post itself?

The lack of in-editor previews is unintuitive and I can imagine users getting confused. I've created a separate issue for discussion over at https://github.com/wordpress-mobile/gutenberg-mobile/issues/4378. 

I'm seeing changes applied as expected after previewing a post, which is what led to my above thoughts, but let me know if my assumptions are wrong here and changes aren't being applied for you even after previewing/viewing posts. 

> 6. There is no way to reorder images when they are small (the arrows disappear)

The max number of columns shown in the inline preview is going to be set to a max of two for portrait mode and four for landscape, this is to bring the block in alignment with how the Gallery block works and will address this as a side effect. That work is being tracked at https://github.com/wordpress-mobile/gutenberg-mobile/issues/4285.

**Comment by kyleaparker** [comment]
>The web centre aligns by default, too, and my sense is that it's preferable to match up with the web where possible. Do you have any strong feelings or other thoughts about this? If so, I'd be happy to create a separate issue for further discussion/discovery.

That's fine as is, I was just confused because gallery isn't centered by default (on the web either) and I was curious why it's different. 

>The styles and rounded corner settings should work but the in-editor previews aren't implemented as part of this phase of the block, I wonder if that maybe caused some confusion here? Are you seeing changes after previewing the post itself?

Thanks for opening the issue, it will definitely cause confusion. I don't think people will expect to open the preview to see the change. 

> The max number of columns shown in the inline preview is going to be set to a max of two for portrait mode and four for landscape, this is to bring the block in alignment with how the Gallery block works and will address this as a side effect. That work is being tracked at #4285.

👍

**Comment by SiobhyB** [comment]
Thanks again Kylea, I'll go ahead to close this issue in favour of the other open issues, but feel welcome to reopen if I've missed anything that's pending.
