### ISSUE TITLE
Restrict Tiled Gallery block to Simple sites

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4336]
This issue tracks the need to disable the Tiled Gallery on Atomic and Jetpack sites.

The first shippable iteration of the Tiled Gallery will support Simple sites only. A later release will add support for Atomic and Jetpack sites.

**Comment by SiobhyB** [comment]
Closing and marking as done as this has been done as part of the PRs for the main apps, at https://github.com/wordpress-mobile/WordPress-Android/pull/15619 and https://github.com/wordpress-mobile/WordPress-iOS/pull/17618.
