### ISSUE TITLE
iPadOS 15 - Gaps shown around floating toolbar when using external keyboard

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/gutenberg-mobile#4370]
**Describe the bug**
On iPadOS 15 the operating system's keyboard toolbar does not span the full width of the screen when an external keyboard is being used and the on-screen keyboard is hidden.

**To Reproduce**
Prerequisites: iPad running iPadOS 15 with an external keyboard connected (the Simulator will also work).

1. Start a new Post
2. Type text in a Paragraph Block

**Expected behavior**
A gap is not shown between the Gutenberg Mobile bottom bar and the bottom of the screen.

**Screenshots**

https://user-images.githubusercontent.com/2092798/145683894-682e3c9a-1d91-43b2-9aa1-1f9474f89836.mp4

**Smartphone**
 - Device: iPad Pro
 - OS: iPadOS 15
- Version: WordPress iOS 18.8 / 1.67.0 Mobile Gutenberg

**Additional context**
- This can be more distracting when the device is in Dark Mode
- We could research if there's an Apple API that let's us configure the bar to span the full width (like in iPadOS 14)

**Comment by hypest** [comment]
Marked as "medium priority" (instead of "low") as this is a broken window that lowers the perceived level of quality of the editor.

**Comment by twstokes** [comment]
Awesome work @geriux - thanks for taking care of this! 🎉

**Comment by geriux** [comment]
> Awesome work @geriux - thanks for taking care of this! 🎉

Thanks for reporting it @twstokes!
