### ISSUE TITLE
iOS: Image and Video blocks don't filter their media types on Albums view

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/gutenberg-mobile#4371]
**Describe the bug**

- When selecting "Choose from device" on an Image block, videos are still visible and counted on the Albums view
- When selecting "Choose from device" on an Video block, images are still visible and counted on the Albums view

**To Reproduce**

Steps to reproduce the behavior for images:
1. Ensure at least one image and one video exist in the Photos app and that the WordPress app has appropriate access (configure access to Photos in iOS Settings -> WordPress). It's simplest to allow access to All Photos.
2. Start a new Post and add an Image block
3. Tap "Add Image".
4. Tap "Choose from device".
5. Observe that thumbnails of videos are shown as well as the count.
6. Observe that when tapping on "Videos" the message "You don't have any media." is shown.

Steps to reproduce the behavior for videos:
1. Ensure at least one image and one video exist in the Photos app and that the WordPress app has appropriate access (configure access to Photos in iOS Settings -> WordPress). It's simplest to allow access to All Photos.
2. Start a new Post and add an Video block
3. Tap "Add Video".
4. Tap "Choose from device".
5. Observe that thumbnails of images are shown as well as the count.
6. Observe that when tapping on "Recents" only videos are shown.

**Expected behavior**
- When adding images from the device, video thumbnails nor counts are shown
- When adding videos from the device, image thumbnails nor counts are shown

**Screenshots**

https://user-images.githubusercontent.com/2092798/145691732-efb7d4bd-0d68-4446-9496-24373393bbb2.MP4

**Smartphone**
 - Device: iPhone 12
 - OS: iOS 15.1.1
 - Version: WordPress iOS 18.8 / 1.67.0 Mobile Gutenberg

**Comment by twstokes** [comment]
- https://github.com/wordpress-mobile/WordPress-iOS/pull/17670

**Comment by hypest** [comment]
Thanks for the report and the fix PR @twstokes! Is this a regression?

**Comment by twstokes** [comment]
> Thanks for the report and the fix PR @twstokes! Is this a regression?

I don't believe so @hypest, I'd noticed it during testing.

**Comment by hypest** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/17670
