### ISSUE TITLE
Block color picker: Custom theme colors and gradients aren't shown for Simple Sites

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/gutenberg-mobile#4387]
## Describe the bug
On Simple Sites running a theme with a custom color palette (e.g. Seedlet), the custom colors aren't being shown when using a block with a color picker.

Thanks to @geriux's observation, this appears to be an issue on the backend and doesn't affect self-hosted or Atomic sites.

Failing tests: [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/editor-theme.md#tc003), [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/editor-theme.md#tc004)

## To Reproduce
1. Set Seedlet as the theme for a Simple Site (note: if switching the theme be sure to restart the WordPress app)
2. Create a new Post in the WordPress app
3. Add a Button block
4. In the block settings choose "Text color" or "Background color" to open the color picker

## Expected behavior
Custom colors to be shown.

<img src="https://user-images.githubusercontent.com/2092798/146587560-a3a6c01b-f747-4d69-a5d8-4e43896d7635.jpeg" width="250px" alt="Screenshot of expected behavior - theme colors are shown." />

## Actual behavior
Default colors are shown.

<img src="https://user-images.githubusercontent.com/2092798/146587642-8c96e569-8cc2-411b-bd9f-1309cafdcb16.PNG" width="250px" alt="Screenshot of actual behavior - default colors are shown." />

## Smartphone
 - Device: iPhone 12, Pixel 4a
 - OS: iOS 15, Android 11
 - Version 18.9 apps / 1.68.0 GB mobile

**Comment by hypest** [comment]
Trying to understand if there's something to be done on this one, @geriux , should we consider some UI to better inform the user of what's going on to avoid confusion perhaps, if the user is expecting the custom colors to be offered? Alternatively, is this a bug to forward to the WPCOM folks, or are we planning to do the necessary fixes ourselves?

**Comment by geriux** [comment]
This was handled in D74538-code. This functionality now works on production 🎉

**Comment by fluiddot** [comment]
Now that the issue is solved, I've also opened [this PR](https://github.com/wordpress-mobile/test-cases/pull/109) to remove its reference from the manual test suites.
