### ISSUE TITLE
Remaining untranslated strings after improving the translation pipeline

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4432]
Although most of the strings are now translated after introducing improvements in the translation pipeline, we identified the following strings that remain untranslated and would require further investigation:

- ~~`Order by` (only referenced in the Search block)~~ _Already translated._
- ~~`Newest to oldest` (only referenced in the Search block)~~ _Already translated._
- ~~`Oldest to newest` (only referenced in the Search block)~~ _Already translated._
- ~~`One` (only referenced in the Layout Grid block)~~ _Will be translated as a native-only string._
- ~~`Two` (only referenced in the Layout Grid block)~~ _Will be translated as a native-only string._
- ~~`Three` (only referenced in the Layout Grid block)~~ _Will be translated as a native-only string._
- ~~`Four` (only referenced in the Layout Grid block)~~ _Will be translated as a native-only string._
- ~~`Angle`~~ _Already translated._
- ~~`Solid`~~ _Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4479._
- ~~`Gradient`~~ _Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4479._
- ~~`Linear`~~ _Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4479._
- ~~`Radial`~~ _Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4479._

### Only missing on Android
- ~~`Set as Featured Image`~~ _Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4464_.
- ~~`Remove as Featured Image`~~ _Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4464_.
- ~~`X-Axis Position`~~ _Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4484._
- ~~`Y-Axis Position`~~ _Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4484._
- ~~`Describe the purpose of the image. Leave empty if the image is purely decorative.`~~ _Fixed in https://github.com/WordPress/gutenberg/pull/38115._
- ~~`Add a new block at any time by tapping on the + icon in the toolbar on the bottom left.`~~ _Fixed in https://github.com/WordPress/gutenberg/pull/38115._

**Replace featured image popup:**
- `Featured Image Already Set`
- `You already have a featured image set. Do you want to replace it?`
- `Replace`
- `Cancel`
**NOTE:** These strings will be fixed when tackling https://github.com/wordpress-mobile/WordPress-Android/issues/15822.

**Featured image updated notice messages:**
- `Set as featured image`
- `Removed as featured image`
**NOTE:** These strings will be fixed when tackling https://github.com/wordpress-mobile/WordPress-Android/issues/15822.

**NOTE:** These strings are already translated, however, for some reason are not being included when the editor is initialized. The issue might be related to the way we pass the translations coming from the main apps to the editor.

**Comment by fluiddot** [comment]
Most of the strings, except the only missing ones on Android, are not translated because they're not included in Gutenberg's GlotPress project ([reference](https://translate.wordpress.org/projects/wp-plugins/gutenberg/)). However, they are in the GlotPress project of WordPress ([reference](https://translate.wordpress.org/projects/wp/5.8.x/en-gb/default/)). It's not clear to me why although those strings are referenced in Gutenberg are only included in the WordPress GlotPress project 🤔 .

**Comment by fluiddot** [comment]
When testing on Android, I spotted more untranslated strings:

**Replace featured image popup:**
- `Featured Image Already Set`
- `You already have a featured image set. Do you want to replace it?`
- `Replace`
- `Cancel`

**Featured image updated notice messages:**
- `Set as featured image`
- `Removed as featured image`

Looks like this is related to a potential issue on WordPress-Android so I opened the following ticket https://github.com/wordpress-mobile/WordPress-Android/issues/15822.

**Comment by jhnstn** [comment]
I just found another missing string. It seems to be the same whitespace issue found in #4464 
The string in question is https://github.com/WordPress/gutenberg/blob/72730e0f326df43e761f5d29759b89a4bec3dd58/packages/block-library/src/image/edit.native.js#L493

**Comment by fluiddot** [comment]
The following strings are now translated, looks like they were missing from the Gutenberg GlotPress project (as it was mentioned in [this comment](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4432#issuecomment-1005967214)) and recently reintroduced:

- `Order by` (only referenced in the Search block)
- `Newest to oldest` (only referenced in the Search block)
- `Oldest to newest` (only referenced in the Search block)
- `Angle`

<details><summary>Click here to see screenshots</summary>

|   |   |   |
|---|---|---|
| <img src=https://user-images.githubusercontent.com/14905380/149764660-91374a3a-80d7-4565-8ee9-d00b104f91e3.png> | <img src=https://user-images.githubusercontent.com/14905380/149764667-b4ac74fa-6cdf-460d-914d-160262af6a39.png> | <img src=https://user-images.githubusercontent.com/14905380/149764676-b334f60e-858e-49c5-a650-859590b50a8b.png>

</details>

**NOTE:** On the first tests related to the translation files optimizations made a month ago, these strings were missing ([reference](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4366)). Now running the `i18n:update` command only warns about one missing string `Draft saved`, however, this string is not really being used but only referenced in a used file by the native version.

**Comment by fluiddot** [comment]
The following strings will be translated after applying the fix of https://github.com/WordPress/gutenberg/pull/38026:
- `Solid`
- `Gradient`
- `Linear`
- `Radial`

**Comment by fluiddot** [comment]
Most of the strings are already translated after merging different fixes, the remaining ones related to the replace featured image popup and Featured image updated notice messages will be addressed in https://github.com/wordpress-mobile/WordPress-Android/issues/15822. So we can close it and follow up on these strings on the referenced issue.
