### ISSUE TITLE
Disable Tiled Gallery layouts except for the Square layout

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4445]
The Tiled Gallery will only include the Square layout in its first iteration, so all other layouts should be hidden from the block's UI. Also, Tiled Gallery blocks that use non-Square layouts should not load in the editor (the UBE should be displayed instead, just as with any other unsupported block).

**Comment by guarani** [comment]
I assigned High priority on this because it's essential we disable other layouts (anything except Square layout), since Phase 1B is scoped to the Square layout only.

**Comment by SiobhyB** [comment]
We've changed course and are now going to keep the block behind a dev flag (with other layouts active). As such, this issue can be closed.
