### ISSUE TITLE
Sanity Test - 1.69.0 - File Block > Hide Download Button

### ISSUE THREAD

**Issue by ttahmouch** [wordpress-mobile/gutenberg-mobile#4505]
**Describe the bug**
I'm currently unsure if it matters whether or not I have an `Atomic` site or a `Jetpack` site selected, and I think I experienced this issue on both, but I am consistently seeing an issue on the `Atomic` site that if I select the `Block Settings` I see the `Hide Download Button` toggle until I press `Link Settings`, and then I can no longer get it to return to the action sheet. It will only show the subset of actions from the `Link Settings` in the action sheet when I press the `Block Settings` button. When `Hide Download Button` is available it does work correctly.

[Sanity Tests](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4438#issuecomment-1016634668)

**To Reproduce**
- [x] File block - Show/hide download button (Block Settings only) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/file.md#tc010)

**Expected behavior**
Pressing Link Settings should not suppress Block Settings from displaying in the action action.

**Smartphone (please complete the following information):**
iPhone 13 Pro Max (15.1.1)

[Screenshots](https://user-images.githubusercontent.com/3058263/150990387-1214ea09-3107-4645-90a4-c96c32811bdc.MP4)

**Comment by hypest** [comment]
I don't seem to be able to reprocude on iPhone 6s (15.1), WPiOS v19.0 on a pressable Jetpack site.

> until I press Link Settings

Not sure if you are referring to the link settings via the cog-wheel menu or directly from the toolbar @ttahmouch 🤔 . Can you share the lists of steps or a video perhaps? Thanks!

**Comment by ttahmouch** [comment]
> I don't seem to be able to reprocude on iPhone 6s (15.1), WPiOS v19.0 on a pressable Jetpack site.
> 
> > until I press Link Settings
> 
> Not sure if you are referring to the link settings via the cog-wheel menu or directly from the toolbar @ttahmouch 🤔 . Can you share the lists of steps or a video perhaps? Thanks!

I went to try to record a video yesterday and my generated `Jetpack` site was deleted. I created a new one, and forgot what the default password for those is for `wp-admin`, and then I remembered that I had already recorded a video for this. So I'm still going to try to reproduce it today if I can. When I tried to reproduce it with an `Atomic` site yesterday on `19.0.0.5` if I remember correctly, I also could not. So there's a chance that I somehow put the app into a weird state when originally testing, or there's some nondeterminism at play.

It's hard to see in the video but the first couple times I press the `🔗` and then I press the `⚙` for the remainder, @hypest .
https://user-images.githubusercontent.com/3058263/150990387-1214ea09-3107-4645-90a4-c96c32811bdc.MP4

**Comment by hypest** [comment]
> So there's a chance that I somehow put the app into a weird state when originally testing, or there's some nondeterminism at play.

Gotcha. Yeah, let's see if you can reproduce again and move forward from there. Thanks!

**Comment by ttahmouch** [comment]
> > So there's a chance that I somehow put the app into a weird state when originally testing, or there's some nondeterminism at play.
> 
> Gotcha. Yeah, let's see if you can reproduce again and move forward from there. Thanks!

I could never get the thing to reproduce even with a `Jetpack` site. So I don't know how I got it into that state during sanity testing. I'd recommend we close this defect. Do you agree?

https://user-images.githubusercontent.com/3058263/151622261-776d3523-2f7a-493f-b244-33bed860f152.MP4

**Comment by hypest** [comment]
> I'd recommend we close this defect. Do you agree?

+1, feel free to close!
