### ISSUE TITLE
Missing images and incorrect order of images in Gallery block

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#4514]
**Describe the bug**

Originally reported in 4667625-zd-woothemes. The user reported that some of the images added to the Gallery blocks are not displaying in the app's editor, even though they look fine on the actual site. They also mentioned the images were "shuffled" with other images from their device that have never been uploaded to the site.

Some other details shared by the user:

> The Blog contains about 30 Blocks - only Text and Images (resized to 2 MPixels each as configured in the settings). Currently the published page is still ok, but the editor cannot show all added images in the blog anymore (all over the blog, not only the last block.)
This problem already existed half a year ago with an even bigger blog, which even caused the app to switch the blog images randomly.

> And when
updating the website, the images just even been shuffled with any other
images from my device (which never have been added to the blog!)

**To Reproduce**

I wasn't able to reproduce this but I saw a mismatched order of the images in the app's editor in SSP.

Steps to reproduce the behavior in SSP:
1. Log in to the WPAndroid app in SSP.
2. Go to My Site > Posts and open the "Scheidegg Winter 2022" post.
3. Compare the order of the images in the Gallery blocks with the post URL (password-protected) linked in the ticket note.
4. Noticed some of the images are displayed in different locations than the actual post.

**Screenshot taken on the actual post**

![Markup on 2022-01-26 at 14:32:14](https://user-images.githubusercontent.com/40906847/151115850-56a86960-d69e-4a1a-894d-d26adb17b9b2.png)

**Screenshot taken from the app's editor**

![Markup on 2022-01-26 at 14:32:35](https://user-images.githubusercontent.com/40906847/151115894-f8334f6c-483d-457a-9f4f-5198be7eef4c.png)

The users also provided some screenshots in the ticket with missing images in the app's editor.

**Expected behavior**

The user expects the app's editor shows all of the images added to the post in the correct order.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20FE
 - OS: Android 11
 - WPAndroid: 18.8

* Note: SSP performed with Pixel 4 (Android emulator), Android 10, WPAndroid 19.0

**Comment by hypest** [comment]
Thanks for the ticket @reginabally ! 

> Noticed some of the images are displayed in different locations than the actual post

To verify my understanding, looks to me that the _order_ of the images are matching between the editor and the post output on the site, but it's just some images that are laid out in a different grid position, right?

I think the native mobile editor will always just use the simple 2-column grid anyway though. To confirm, @mkevins, is that what's expected on native mobile?

**Comment by mkevins** [comment]
> is that what's expected on native mobile?

Indeed, the gallery on mobile will display the images in a simple grid: up to 2 columns when the viewport is narrow, i.e. portrait, and up to 4 columns when the viewport is wider, i.e. landscape. The number of columns displayed is limited, but the actual number of columns set for the gallery can be larger.

Regarding this issue:

> They also mentioned the images were "shuffled" with other images from their device that have never been uploaded to the site.

To clarify, were these other images not uploaded, or just not added? @reginabally is the following the relevant quote?

> And when
updating the website, the images just even been shuffled with any other
images from my device (which never have been added to the blog!)

The reason I'm wondering is that there were issues in the past (apparently rare, but possible) with colliding media ids which caused some images to appear in place of other ones, but these were always images that were in the media library (and thus had ids), but not necessarily added to any post or page.

**Comment by reginabally** [comment]
@hypest @mkevins Sorry for my late reply. I was on AFK last week.

> To verify my understanding, looks to me that the order of the images are matching between the editor and the post output on the site, but it's just some images that are laid out in a different grid position, right?

I didn't compare every image in the gallery blocks but if we look at the last row of images in the screenshot I took from the app's editor after I scrolled to the end, the three images highlighted from the screenshot below (taken from the actual site) do not show up.

![151115850-56a86960-d69e-4a1a-894d-d26adb17b9b2](https://user-images.githubusercontent.com/40906847/152753693-0fa49475-7771-4946-883e-4356348497c6.png)

> To clarify, were these other images not uploaded, or just not added? @reginabally is the following the relevant quote?

Yes, both are relevant. My understanding from these two quotes is, they saw images on the app's editor that have never been uploaded to the post.

**Comment by hypest** [comment]
About the last 3 images that seem to not become visible in the mobile editor, I confirmed that that's the case, although not consistently missing. Trying to switch to another app and then back to the editor causes a refresh and sometimes some of the last 3 images do appear.

I will investigate deeper.

**Comment by thesacredpath** [comment]
Another report here: 34464769-hc

Re-adding the images fixes the issue, but this user has a lot of posts with galleries and a majority of them seem to be broken. All are showing properly on live site, just not in the editor.

Note that this is occurring in the browser editor for this user. Took the site AT fully as it was simple Business in hopes that would fix the issue, but it did not.

**Comment by hypest** [comment]
Update: I manged to try the `react-native-fast-image` lib on the Android gutenberg-mobile demo app. It doesn't crash and it loads all the images so far. I will need to test it out more on WPAndroid this time, and then see if it integrates well on the iOS side as well.
