### ISSUE TITLE
Remove "REPLACE BLOCK" case indicator and sheet title from Block Picker

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#452]
As discussed, the behavior is changing and so we should reflect that in Gutenberg mobile.
See related discussion in https://github.com/wordpress-mobile/gutenberg-mobile/pull/445#issuecomment-450102887

**Comment by hypest** [comment]
Just to be clear, I'm not suggesting (in https://github.com/wordpress-mobile/gutenberg-mobile/pull/445#issuecomment-450102887) to remove the title completely. Instead, have it always be "ADD BLOCK" as per the original designs and not have a "REPLACE BLOCK" case.

**Comment by mzorz** [comment]
>  Instead, have it always be "ADD BLOCK" as per the original designs and not have a "REPLACE BLOCK" case.

I realized and renamed the issue to reflect that a few minutes ago 😄
