### ISSUE TITLE
Try to replace layout-based logic with something more idiomatic for block holder border styling

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#455]
Let's revisit this due to comment https://github.com/wordpress-mobile/gutenberg-mobile/pull/440#issuecomment-450104759 Wel'll try to replace layout-based logic with something more idiomatic.

**Comment by pinarol** [comment]
I looked into Media Queries but as far as I understand we need to have some static constraints to be able to use them. Currently, it doesn't seem possible to know the width of the block holder until its layout is done. Because the layout calculation is very dynamic, especially for iOS. For example we make use of readableContentGuides to automatically set left right paddings for blocks in iPad devices, we even don't state that it is iPad, system already knows the limits of readable area of the current device. And also there's the safe area thing, it is also a different reason to have left right paddings around blocks. 

In the current solution we only re-render if the boolean result of `window width > block width` changes, this can only change if we go between portrait and landscape in _some_ devices, and changing the device orientation will cause a re-render anyway. So it looks harmless to me from this point.

Could I be missing something? I can really use your help on this. Thanks! @hypest

**Comment by hypest** [comment]
> Currently, it doesn't seem possible to know the width of the block holder until its layout is done

Why do we need to not the width of the block holder? The current mobile designs assume that the block will always take up all the available _width_ of its container.

I might be missing context here but, it's should be a responsibility of the container to set its content area, adding paddings or margins when needed. All of those should be known based on the device/mode/state, before the block needs to render at all. What am I missing?

**Comment by SiobhyB** [comment]
I don't believe this issue is actionable any more, as we don't currently have a `BlockHolder` component and I wasn't able to locate the code introduced in https://github.com/wordpress-mobile/gutenberg-mobile/pull/440. I assume that various refactors over the year have resolved this issue, but please re-open if I'm missing something.
