### ISSUE TITLE
[Drag & Drop blocks] Fetch and share blocks layout size and position coordinates

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/gutenberg-mobile#4601]
## Description 

In preparation for the drag & drop functionality, we need to store the layout and position data of the blocks within the block list. This will be used for calculations when moving and dropping a block.

Most likely this will be stored in the block list context where we already store the main scroll reference.

**Comment by hypest** [comment]
> store layout and position data

Assuming layout also refers to block heights, [this PR might become useful](https://github.com/WordPress/gutenberg/pull/31144). In it, I was keeping the block heights in the block-list and then [computing the block offsets from heights](https://github.com/WordPress/gutenberg/pull/31144/files#diff-753322c95666679508eecb52371e38647190768c3198f16c1dc312a57c5b0e41R173-R186).

**Comment by geriux** [comment]
Thanks for sharing Stefanos! 🙇  I'm using `onLayout` as well in https://github.com/WordPress/gutenberg/pull/39089 but storing the data in the block list context instead.
