### ISSUE TITLE
Images in wpios' Reader are not sized correctly

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#467]
When creating a post in gutenberg-mobile that has some images, the reader tries to resize them in such a way that it fits the viewport. Currently, it seems that the mobile block editor doesn't provide the proper markup to let the wpios Reader succeed in the resizing.

This is only a wpios issue as the wpandroid Reader seems to be able to resize the images.

See these posts in the Reader to verify:

Post written on wpios: https://stefanosuser.wordpress.com/2019/01/07/two-images/
Post written on the web: https://stefanosuser.wordpress.com/2019/01/07/two-images-web/
Post written on wpandroid: https://stefanosuser.wordpress.com/2019/01/07/two-images-android/

**Comment by koke** [comment]
From @rachelmcr:

> After some additional testing, I think there might be something else happening in the Reader. I just managed to trigger the same issue with a post created in Aztec, so it turns out it isn’t a Gutenberg thing — I’ll test further and report it as a Reader issue

Maybe we can close this one?

**Comment by hypest** [comment]
@koke , my impression is that comment by Rachel was for a different thing, some extra space appearing above the post in the Reader. Are you sure it includes this ticket too?

**Comment by rachelmcr** [comment]
> that comment by Rachel was for a different thing, some extra space appearing above the post in the Reader. Are you sure it includes this ticket too?

Yes, sorry for the confusion — with that comment I was only referring to extra space appearing above the post. Based on my testing, this image size issue only occurs with posts created in mobile Gutenberg.

**Comment by koke** [comment]
I moved this to https://github.com/wordpress-mobile/WordPress-iOS/issues/10867 since I don't think there's anything we need to change in gutenberg-mobile
