### ISSUE TITLE
[Integration test] Separator block

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#4681]
The separator block was recently refactored in https://github.com/WordPress/gutenberg/pull/38428, which led to some "false positive" failures in [the block insertion UI test (part 2)](https://github.com/WordPress/gutenberg/blob/8a204c8d03e340b7431595a84a441e7cdf14b289/packages/react-native-editor/__device-tests__/gutenberg-editor-block-insertion-2.test.js). These failures were addressed in https://github.com/WordPress/gutenberg/pull/39636.

As it looks like there will be further changes to the separator block in the future, it'd be valuable to add integration tests to catch issues like these before code's merged.

**Comment by geriux** [comment]
We recently added an integration test for this block in https://github.com/WordPress/gutenberg/pull/46583 should we close this issue?

**Comment by SiobhyB** [comment]
@geriux, great, thanks! I'll go ahead to close this. :)
