### ISSUE TITLE
Improve code block to support scroll to caret

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#469]
We want code block to have scroll to caret abilities just like Paragraph and Heading blocks. Desired behavior can be seen [in this PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/461). Currently Android supports this kind of behavior on system level so this is just necessary for iOS. We can make it possible by simply using RCTAztecView( see rich-text.js ) instead of react native's text input.

**Comment by SiobhyB** [comment]
Closing as this is fixed now that the code block was refactored to use `RichText`. The block itself is still hidden behind a dev flag, but there is a separate GitHub issue related to enabling it.
