### ISSUE TITLE
Implement the post title in RN.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/gutenberg-mobile#472]
## Description:

Implement the post title in RN.

This task involves:

- Implementing the logic in `gutenberg-mobile` to use the post-title component from `gutenberg`.
- Create a matching PR in the apps to remove the native title.
- Make sure edits to the title are properly saved by the apps.

**Comment by koke** [comment]
We already had an issue for this in #372. Can we combine both and make sure we address all the items there? It's fine to break up in multiple tasks/PRs, I just want to make sure we don't forget all those items in #372.

**Comment by hypest** [comment]
372 was superseding this one but was not specific of the implementation change (moving the title into RN). We decided to keep both, rename 372 (already done by Koke) to capture the writing flow details it originally was created for.

**Comment by diegoreymendez** [comment]
Completed.
