### ISSUE TITLE
[Drag & Drop blocks] Disable text editing when long-pressing a block in favor of drag & drop gesture

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4720]
## Description

On iOS when long-pressing over a text block, instead of enabling dragging mode it initiates text editing. This is not the expected behavior as the drag & drop gesture should override focusing on text input. On Android, this issue can't be reproduced as it matches the expected behavior.

**UPDATE:** This issue can also be reproduced on Android.

https://user-images.githubusercontent.com/14905380/161079926-877c8433-f5f2-4284-9d53-969e0708cb85.mov

**Comment by hypest** [comment]
I wonder, if initiate-drag has precedence over text editing/selecting, what's the expected user flow when they do want to select some text? 🤔

**Comment by fluiddot** [comment]
> I wonder, if initiate-drag has precedence over text editing/selecting

The idea is that the dragging has precedence over text editing unless the text is already being edited. Similarly, when editing text, the dragging gesture will be disabled to prevent conflicts.

> what's the expected user flow when they do want to select some text? 🤔

It would be similar to what we currently have:
1. Select a text block.
2. Select text.

I think regarding this user flow, the dragging gesture shouldn't impact.
