### ISSUE TITLE
[Drag & Drop blocks] Vertically align the dropping insertion point when is over the dragged block

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4721]
## Description

Following https://github.com/WordPress/gutenberg/pull/39891#pullrequestreview-927431464, it would be great if the dropping insertion point is centered when is displayed in the position of the block being dragged.

<img src=https://user-images.githubusercontent.com/14905380/161055754-a23148e9-0cef-4dd2-b8e3-694ab70230a0.jpeg width=350>

**Comment by geriux** [comment]
Since this issue was opened, the UI when dragging a block changed a little. Now the block is not collapsed so I think this issue is no longer valid:

<kbd><img src="https://user-images.githubusercontent.com/4885740/164229939-b2b3be2f-d9e1-46f5-a99e-7baed0b56acd.png" width="300" /></kbd>

What do you think @fluiddot?

**Comment by fluiddot** [comment]
Good point, although not sure what should be the behavior for the insertion point when dragging over the original position of the block. If we vertically align it, that could be an issue when the block is too large, so probably we could keep the current approach. Alternatively, we could also show the insertion point after the block, as currently it's only shown before it.

https://user-images.githubusercontent.com/14905380/164245267-29a76992-9fed-4fea-adc6-0d19e3039995.mp4

**Comment by geriux** [comment]
>Alternatively, we could also show the insertion point after the block, as currently it's only shown before it.

That's a great sugestion! Something like this?

https://user-images.githubusercontent.com/4885740/164434780-c2015eea-2cf4-4422-97a1-2952f1db7839.mov

**Comment by fluiddot** [comment]
> > Alternatively, we could also show the insertion point after the block, as currently it's only shown before it.
> 
> That's a great sugestion! Something like this?

Exactly 🤩, thanks for tackling it 🙇 .

**Comment by geriux** [comment]
Yay, awesome! I'll work on the PR!

**Comment by geriux** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/40510
