### ISSUE TITLE
[Drag & Drop blocks] Automatically select the dropped block if it's not previously selected

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4741]
## Description

Related to [this feedback on the drag & drop feature](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4691#issuecomment-1088038628), when the user drags a block that is not selected, it should be automatically get selected after it's dropped.

**Comment by hypest** [comment]
A bit late to comment on this but, when the drag-vs-select flow will be fixed, it will mean that auto-selecting the dropped block will make it hard to drag it again in sequence, right?

An example to make what I say more clear:
1. With no blocks selected, long-press a paragraph block to begin dragging it
2. Move it to a new place
3. Either dropped it in the wrong place or changed your mind and need it elsewhere
4. Long-press again to drag it
5. ❓ what should be the behavior here? Should the long-press engage the drag-and-drop flow or should the paragraph text start to be selected?

Perhaps the focus/selection should not change on drop? cc @iamthomasbishop

**Comment by iamthomasbishop** [comment]
> what should be the behavior here? Should the long-press engage the drag-and-drop flow or should the paragraph text start to be selected?

@hypest I see what you're saying and I'm kind of on the fence but I think there might be a fine-tuned middle ground. My gut tells me that folks will tend to either _edit the block in-place_ or _select a diff block_ after a drag/drop action but at the same time, it would be nice to also have that long-press gesture available at that moment. 

I wonder if it'd make sense to leave the block in the in-between state upon drop? What I mean is, the block would be visibly in a selected state (blue outline, inline controls) but importantly the **text area would not be focused initially**. 

So after dropping the block, the user can either: 

- Single-tap on text area to give it focus, or 
- Long-press to activate drag & drop (same behavior as when no blocks are selected, but the block would already be outlined).

Does that make sense, or is there something I'm missing? It can be a bit hard to visualize these micro details in text format, and iOS/Android have slightly different text selection models so we might want to try it in a test build.

**Comment by mchowning** [comment]
> So after dropping the block, the user can...Long-press to activate drag & drop (same behavior as when no blocks are selected, but the block would already be outlined).

When I was (briefly) trying out this feature, I did find that it a bit tricky to repeatedly move the same image block to find the right spot for it. I think that would have felt much more natural with ^this^ behavior, so a 👍 as far as I'm concerned.

**Comment by hypest** [comment]
> So after dropping the block, the user can either:
>
>   * Single-tap on text area to give it focus, or
>   * Long-press to activate drag & drop (same behavior as when no blocks are selected, but the block would already be outlined).
>
> Does that make sense, or is there something I'm missing?

Thanks @iamthomasbishop , it does make sense to me as it leaves the block in a long-press-to-drag enabled mode.

The only thing that now makes me wonder a bit is that we are differentiating between "selected and caret-focused" and "selected but no caret-focused" modes. Obviously, the former will have the big virtual keyboard visible while the latter won't, but I'm not sure if the two modes will be that discernible to the user. Instead, I'd assume that if I see the blue border on a block then it's selected, and long-press will activate text selection no matter what. 🤔

I understand that the "no matter what" actually conflicts with the plan to have the long-press gesture activate drag when the edit area is not focused, not text selection. 🤔

**Comment by iamthomasbishop** [comment]
> I'm not sure if the two modes will be that discernible to the user

I think in that case the visibility of the software keyboard would make it pretty clear that input is allowed. It'd be less obvious in cases where the user is using a hardware keyboard, although even in those cases there is typically a UI that is visible when you're in that "input-able" mode.

> Instead, I'd assume that if I see the blue border on a block then it's selected, and long-press will activate text selection no matter what.

I see what you're saying, @hypest. Do you think it would help to increase the delay/timeout before activating drag & drop so that the user has more of an opportunity to utilize the default system behavior?

Side-note: here are the diffs in terms of what happens when you long-press on a standard (system) text area...

- **On Android** (Android 12, Pixel 4): long-press typically _selects a word_
- **On iOS** (iOS 15.3.1, iPhone 13 Pro): long-press on a bit of text typically _places the cursor_ at that position

**Comment by fluiddot** [comment]
I see your points here, my premise when implementing the feature is that the long-press gesture on blocks always enables the dragging. However, there's an exception for text blocks, when entering in text editing (i.e. the text input gain focus), the dragging is disabled for all blocks, including the unselected. This allows enabling the default behavior for long-press gestures within the text input (as Thomas pointed out in [this comment](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4741#issuecomment-1100265144)), and also helps with preventing conflicts with the scroll, which is controlled by both the dragging (the user can scroll while dragging) and the text editing (automatically scrolls the content to keep the caret is always visible).

Regarding the selection behavior when dropping a block, I'd like to note that the block gets automatically selected but not focused in case it's a text block. This allows the user to decide whether to edit the text by tapping on the content or keep dragging by long-pressing over the content.

Let me share an example to clarify the mentioned flows:

https://user-images.githubusercontent.com/14905380/163803948-a983a2fe-4680-4d67-82db-8439543b54b5.mp4

**NOTE:** _The video capture was extracted from [the PR](https://github.com/WordPress/gutenberg/pull/40406) that introduces the latest changes into the feature._

**Comment by hypest** [comment]
I think that it's cool to go with selecting text on long press when editing is activated, and default to dragging-n-dropping when text blocks are not caret-focused, and then we take it from there.
