### ISSUE TITLE
[Drag & Drop blocks] Multiple touches are being tracked while dragging a block

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/gutenberg-mobile#4754]
**Describe the bug**
Multiple touches are being tracked while dragging a block making it possible to have dragging direction and speed changes due to unintentional touches.

**To Reproduce**
1. Start dragging a block;
2. Using another finger/hand palm
3. Notice that the chip moves to an intermediate point possibly changing dragging direction and speed.

**Expected behavior**
Only the first touch should be tracked while dragging a block.

**Evidence**

https://user-images.githubusercontent.com/42008628/163242588-bc3d27db-1580-48db-a0c6-ac1628d637ff.mp4

**Smartphone:**
 - Device: Android, iPhone, iPad.

**Comment by fluiddot** [comment]
I think we could tweak the gesture configuration and limit the number of fingers to activate it. Looks like there's a property named [`maxPointers`](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/pan-gesture#maxpointersvalue-number) that could help us to address the issue.

There's another property ([`averageTouches`](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/pan-gesture#averagetouchesvalue-boolean-android-only)), only supported in Android, that might be also interesting to check, as it might be related to the case where having two fingers, the touch position is averaged.

**Comment by geriux** [comment]
Closing since it was fixed in https://github.com/WordPress/gutenberg/pull/40519
