### ISSUE TITLE
https://books.apple.com/us/book/biology-2e/id1413413708

### ISSUE THREAD

**Issue by ghost** [wordpress-mobile/gutenberg-mobile#4766]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please add a type label to this issue. e.g. '[Type] Enhancement'
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Please add a feature label to this issue. e.g. 'Stats'</td>
    </tr>
  </tbody>
</table>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a>
</p>

_Originally posted by @peril-wordpress-mobile[bot] in https://github.com/wordpress-mobile/WordPress-Android/issues/15982#issuecomment-1045323467_

**Comment by fluiddot** [comment]
I'm closing this issue as it doesn't contain any information.
