### ISSUE TITLE
[Drag & Drop blocks] Long-press no longer starts drag if text previously edited

### ISSUE THREAD

**Issue by lmischner** [wordpress-mobile/gutenberg-mobile#4775]
**Describe the bug**
After using the long-press gesture in a text block to move the cursor, subsequent long-press gestures on other blocks (regardless of type) results in edit action rather than dragging.

The issue resolves itself if you then try to drag the original text block prior to dragging other blocks.

**To Reproduce**
1. Open any text-type block
2. Long-press and move cursor
3. Long-press on any other block (any type)
4. Note that see relevant edit options.

**Expected behavior**
Long-press should trigger dragging unless editing a text block.

**Evidence**
https://user-images.githubusercontent.com/103850310/164130187-eaa2fc4e-0337-4ed3-819a-cfabc70a00b7.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 15.4.1

**Comment by fluiddot** [comment]
Closing this issue as it was addressed in https://github.com/WordPress/gutenberg/pull/40480.
