### ISSUE TITLE
[Drag & Drop blocks] Disable long-press gesture in Media blocks

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4784]
## Description

Long-pressing on the media to replace it will be removed in favor of the Drag & drop functionality, users will still be able to replace media by tapping on the upper right button or via the toolbar replace option.

Affected blocks:
- Cover
- File
- Image
- Media Text

**Comment by geriux** [comment]
This was handled in https://github.com/WordPress/gutenberg/pull/40651
