### ISSUE TITLE
[Drag &amp; Drop blocks] Investigate Sentry report: Assertion failed: object-&gt;ctx_ == ctx_

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4785]
## Description

**Sentry issue:** https://sentry.io/share/issue/5070bdca207a4c4c93af5e2123e5653c/

After upgrading the Reanimated library in the version `17.2.0 (19.5)` ([reference](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4615)), we're getting some crash reports related to that library. So far, it's not clear what's causing it, per the error message, looks related to some kind of conflict due to using different runtimes.

**Error message:**
```
Don't try to clone an object backed by a different Runtime
```

**Comment by fluiddot** [comment]
_Metrics collected on April 26th:_
- 0,11% of users affected in `19.5.0.4`
- 0,07% of users affected in version `19.6.0.6`

**NOTE:** Looks like the issue is impacting fewer users in the recent version 🤔.

I'm going to set medium priority to this issue since this is not affecting too many users and we were not able yet to reproduce it.

**Comment by geriux** [comment]
This issue is happening in older versions of the app <= 22.9 and no other reports have been reported in recent versions so I'll close this issue. Most likely recent React Native and Reanimated upgrades might have addressed it.
