### ISSUE TITLE
[Drag & Drop blocks] Dragging chip remains visible when the app goes to the background (only iOS)

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4802]
## Description

The drag & drop functionality keeps the chip component visible when the app goes to the background and then resumed.

This could be solved by listening to the app state changes via the [`AppState` API](https://reactnative.dev/docs/appstate), and canceling the dragging if it goes to the inactive state.

**How to reproduce it:**
1. Start dragging a block.
1. While moving the block, make the app go to the background by swiping up the screen with another finger.
1. Resume the app and observe that the dragging chip is still shown and can't be dragged unless long-pressing on a block.

**Comment by fluiddot** [comment]
Closing this issue as it has been addressed in https://github.com/WordPress/gutenberg/pull/40519.

**Comment by fluiddot** [comment]
_(Sorry for closing the issue by mistake 😅 )_

**Comment by geriux** [comment]
This was handled in https://github.com/WordPress/gutenberg/pull/40729
