### ISSUE TITLE
[Drag & Drop blocks] Crash on Android when having only one block and dragging

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4806]
## Description

The editor crashes when trying to drag a block if the post/page only contains that block.

**How to reproduce it:**

1. Open a post/page.
1. Add one block (it's important that the content is just one block).
1. Long-press on the block to start dragging.
1. Drag the block around and observe that the editor crashes.

**Comment by geriux** [comment]
This was handled in https://github.com/WordPress/gutenberg/pull/40689
