### ISSUE TITLE
[Drag & Drop blocks] Block can't be dragged if it's added by replacing a Paragraph block

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4807]
## Description

Probably related to the changes introduced in https://github.com/WordPress/gutenberg/pull/40480. 

When a block is inserted by replacing a Paragraph block, the dragging gesture is disabled for that block while remains selected. However, this only happens after inserting the block, as the dragging works after selecting a different block and selecting the inserter block again.

**How to reproduce it:**

1. Open a post/page.
1. Add a Paragraph block and select it.
1. Tap on the ➕ button to insert a block.
1. Insert any block.
1. Observe that the inserted block replaced the Paragraph block.
1. Long-press over the inserted block.
1. Observe that the dragging is not available.

**Comment by geriux** [comment]
I'm also investigating an issue on Android where the return key doesn't work for the first block

https://user-images.githubusercontent.com/4885740/166475295-f995841c-924b-4928-aff5-51f4347aec17.mov

**Comment by geriux** [comment]
This was addressed in https://github.com/WordPress/gutenberg/pull/40788
