### ISSUE TITLE
[Drag & Drop blocks] Add drag & drop help guide in Help & Support screen

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4840]
## Description

Add a guide for explaining to users how the drag & drop blocks feature works. This implies expanding the information provided in the "Move Blocks" section of the Help & Support screen.

<img src=https://user-images.githubusercontent.com/14905380/167442571-7f9243a6-7140-42f3-9b65-6922c6e7927d.png width=300>

### Design sketch
![Image from iOS](https://user-images.githubusercontent.com/14905380/167878216-28562b9b-cc59-4f95-9a35-78011b042600.jpg)

**Comment by fluiddot** [comment]
@iamthomasbishop now that we'll provide a new way for moving blocks, I'm wondering if we could update this section of the Help & Support screen to reflect the new feature.

Could you help us with the designs of this part? Thanks 🙇 !

**Comment by geriux** [comment]
As an example this is the image indicating the arrow buttons:

### Light

<img src="https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/editor-help/images/move-light.png?raw=true" />

### Dark

<img src="https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/editor-help/images/move-dark.png?raw=true" />

It'd be nice if we could have it with the same dimensions for both light/dark and the `@2x` and `@3x` sizes.

Thanks!

**Comment by fluiddot** [comment]
Thanks @geriux for adding the images 🙇 , in case it helps, [this is the folder](https://github.com/WordPress/gutenberg/tree/trunk/packages/editor/src/components/editor-help/images ) where we have all the images included in the "Help & Support" screen.

**Comment by fluiddot** [comment]
Closing the issue as it was addressed in https://github.com/WordPress/gutenberg/pull/40961.
