### ISSUE TITLE
Keyboard hiding and reappearing after adding 10+ blocks

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/gutenberg-mobile#4864]
**Describe the bug**
Originally reported internally in pbMoDN-3vb-p2?c=6739#comment-6739  there is a regression in the block list where the keyboard will start hiding and reappearing after adding 10+ blocks.

**To Reproduce**
- Open the app
- Start adding blocks, using the return key to create new Paragraph blocks.
- Add more than 10 blocks.

**Expected behavior**
The keyboard shouldn't hide and it should stay visible after each Paragraph block is added.

**Screenshots**

https://user-images.githubusercontent.com/4885740/168773954-9fefaab8-5149-4032-a06b-df59dc5e0b88.mov

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro (Simulator)
 - OS: 15.4

**Comment by fluiddot** [comment]
I'd like to note that the keyboard hiding and reappearing issue was already happening on Android and could be reproduced just by adding a Paragraph block (independently of the number of Paragraph blocks added). However, it's less prominent than the issue outlined here for iOS.

**Version `19.7.1`:**

https://user-images.githubusercontent.com/14905380/168807892-f01d5f26-9e7d-46e0-8179-0724ef2b28f5.mp4
