### ISSUE TITLE
[iOS] Media & Text Block: Keyboard covers the text field after rotating from Landscape to Portrait

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/gutenberg-mobile#4894]
**Describe the bug**
When using a Media & Text block, the keyboard obstructs the view of the text after rotating from Landscape to Portrait.

**To Reproduce**
1. Portrait mode
2. Add Media & Text block to a post
3. Add an image
4. Type some text
5. Rotate to Landscape mode
6. Rotate back to Portrait mode
7. ❌ Notice that the keyboard goes on top of the text field and the text is not visible.

**Expected behavior**
When rotating from Landscape to Portrait, Media & Text block should look exactly like it looked before rotating to Lanscape. Keyboard and text field should both be visible.

**Screenshots**

https://user-images.githubusercontent.com/42008628/170294682-73919502-0fde-4186-ab6a-b0cc2f9de2e9.mov

**Smartphone:**
 - Device: iPhone 13
 - OS: iOS 15.4.1

**Comment by hypest** [comment]
Thanks for opening this ticket Tiago! Let me ask to verify: in the video capture, it looks like the editor keeps scrolling to above the text field even after you repeatedly try to scroll down, right? In other words, auto-scrolling keeps "fighting" you, right?

**Comment by tiagomar** [comment]
That's correct @hypest! It was me trying to scroll the text field into view. =)
