### ISSUE TITLE
Crash on the editor when closing it

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/gutenberg-mobile#4918]
**Describe the bug**
A [new issue on Sentry](https://sentry.io/share/issue/160a7b6fc5aa49cc8c625699deb14bc9/) started to increase with the latest `19.9` release generating a crash on iOS when the editor is closed.

This is related to the Reanimated library, used in the newly introduced feature Drag & Drop blocks.

**To Reproduce**
1. Install the `19.9` WordPress iOS version
2. Open the editor
3. Quickly close the editor
4. Repeat until the app crashes

**Note**: Sometimes it happens after the second try or a few tries more. It variates and there's no exact way to reproduce it the first time.

**Expected behavior**
The app shouldn't crash when closing the editor.

**Screenshots**

https://user-images.githubusercontent.com/4885740/171444962-f785dab2-9b5c-4f98-8e90-3f25064694bf.mov

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 15.5

**Comment by fluiddot** [comment]
Closing the issue as a fix was released on both version `19.9` and `20.0` via a hotfix and betafix.
