### ISSUE TITLE
Is `RNFastImage` required for iOS apps?

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/gutenberg-mobile#5025]
Hey folks 👋 

Forgive the noob question, but is `RNFastImage` required? I don't see it used anywhere 🤔

When I say "I don't see it used anywhere" I mean that the output of `find Pods -type f -print0 | xargs -0 grep -li RNFastImage` in WordPress iOS doesn't return anything other than config files. Likewise, [a GitHub search on this repo only returns the JSON podfile](https://github.com/wordpress-mobile/gutenberg-mobile/search?q=RNFastImage).

I have little knowledge of how React Native works and what it expects as available at runtime, so maybe I'm missing something obvious here. 😅 

For extra context, I stumbled upon it while auditing our dependencies and noticing an outdated one that comes across because of `RNFastImage`. See https://github.com/wordpress-mobile/WordPress-iOS/issues/19043#issuecomment-1183933852

Thank you for your input 🙇‍♂️

**Comment by derekblank** [comment]
Timely question! @geriux is leading an initiative to add FastImage, so it is included in these PRs:
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/4989
- https://github.com/wordpress-mobile/WordPress-iOS/pull/18995

We're working to merge the remaining iOS-related PRs:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/18997
- https://github.com/wordpress-mobile/WordPressKit-iOS/pull/529

This may explain why you're seeing it referenced right now, but if you note anything that seems unusual with the dependency arrangement, please let us know too. I'll update https://github.com/wordpress-mobile/WordPress-iOS/issues/19043#issuecomment-1183933852 with some further context on RNFastImage itself.

**Comment by geriux** [comment]
> When I say "I don't see it used anywhere" I mean that the output of find Pods -type f -print0 | xargs -0 grep -li RNFastImage in WordPress iOS doesn't return anything other than config files. Likewise, [a GitHub search on this repo only returns the JSON podfile](https://github.com/wordpress-mobile/gutenberg-mobile/search?q=RNFastImage).

That's because pretty much all of the dependencies are used in the [Gutenberg repo](https://github.com/WordPress/gutenberg/search?q=%3CFastImage).

**Comment by fluiddot** [comment]
I think that for most of the Pods listed [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/23ae9e7bfe2d92ecd861a1995434190090609f69/Podfile#L103-L146), we'll have a similar case where we won't really see any reference in the WPiOS code because, as @geriux mentioned, they are mainly used in Gutenberg and imported as native modules in the JavaScript environment.

**Comment by mokagio** [comment]
Thanks folks! I thought it would be something like that but didn't go as far as checking Gutenberg 🤦‍♂️ 

I opened https://github.com/wordpress-mobile/WordPress-iOS/pull/19047 to add a note about this in `Podfile`, I can see myself going through this dance again in the future.
