### ISSUE TITLE
List Block V2: Prefilled word "list" isn't greyed-out

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#5098]
**Describe the bug**
When adding a new list item, the word "List" appears, but isn't greyed-out.

**To Reproduce**
1. Make sure you're using Gutenberg 13.8.2, and enable List block v2 in Experiments.
2. Create a new post, and add a list block.
3. Add a few items, noting that each time you add one, the word "List" is prefilled before you start typing. Note that the word "List" is not grey or in any way distinguished from text you have entered.

**Expected behavior**
I expected the prefilled word "List" to be greyed-out, indicating it's not real text.

**Screenshots**

![Screenshot_20220816-104711_Jetpack (1)](https://user-images.githubusercontent.com/15107387/184833343-53d2ae05-d23a-4acb-8c32-785f6ccb64b6.jpg)

**Smartphone (please complete the following information):**
Tested on Samsung Galaxy S21, Android 12, WPAndroid 20.5-rc-1

**Comment by fluiddot** [comment]
Thanks for reporting this @thehenrybyrd 🙇.

I agree that might be confusing to the user that the placeholder is not greyed-out, as it looks like real text. I've set High-priority on this issue as it might disrupt the writing flow experience when the List block V2 will be enabled.

cc @geriux @derekblank in case you could take a look, thanks!

**Comment by geriux** [comment]
> cc @geriux @derekblank in case you could take a look, thanks!

I think @derekblank is already checking it out, but if not, let me know and I will take a look. Thanks!

**Comment by fluiddot** [comment]
> I think @derekblank is already checking it out, but if not, let me know and I will take a look. Thanks!

Great, thanks for the update! @derekblank feel free to assign yourself to the issue in case you're currently tackling it.

**Comment by fluiddot** [comment]
Closing this issue as it was addressed in https://github.com/WordPress/gutenberg/pull/43353.
