### ISSUE TITLE
Compile and target Android API 31

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/gutenberg-mobile#5181]
Parent #https://github.com/wordpress-mobile/WordPress-Android/issues/16062

As part of the migration of WP Android to Android 12, the `targetSdkVersion` on the dependent libraries can be updated to 31. The [Wordpress Android](https://github.com/wordpress-mobile/WordPress-Android) had a `targetSdkVersion` of 30 which now has been updated to 31 in this PR - https://github.com/wordpress-mobile/WordPress-Android/pull/17153. So in order to keep the `targetSdkVersion` to be consistent with the apps, this change needs to be taken up. 

**UPDATE:** The following Android dependencies need also to be updated to Android 12:

#### Dependencies from forked repositories (published to JitPack)
- [react-native-gesture-handler](https://github.com/wordpress-mobile/react-native-gesture-handler/pull/23)
- [react-native-reanimated](https://github.com/wordpress-mobile/react-native-reanimated/pull/19)
- [react-native-prompt-android](https://github.com/wordpress-mobile/react-native-prompt-android/pull/9)
- [react-native-linear-gradient](https://github.com/wordpress-mobile/react-native-linear-gradient/pull/7)
- [react-native-slider](https://github.com/wordpress-mobile/react-native-slider/pull/12)
- [react-native-video](https://github.com/wordpress-mobile/react-native-video/pull/20)

#### Dependencies from NPM packages (published to S3 via [`react-native-libraries-publisher`](https://github.com/wordpress-mobile/react-native-libraries-publisher))

**UPDATE:** The following libraries are external so we won't be updating them for now.

- ~~react-native-get-random-values~~
- ~~react-native-reanimate~~
- ~~react-native-safe-area-context~~
- ~~react-native-screen~~
- ~~react-native-svg~~
- ~~react-native-webview~~
- ~~react-native-masked-view~~
- ~~react-native-clipboard~~
- ~~react-native-gesture-handler~~
- ~~react-native-fast-image~~

**Comment by fluiddot** [comment]
Setting this task as a high priority as we should include it in the next WP-Android release 21.0.

_Internal reference:_ p1664442201957959-slack-C6UJ0KRKQ

**Comment by fluiddot** [comment]
I noticed that some of the forked repositories we have in Gutenberg, [which are Android dependencies to the project](https://github.com/WordPress/gutenberg/blob/a6c43fb9df3168246430aa85ee0beb7ac58c59ce/packages/react-native-bridge/android/react-native-bridge/build.gradle#L67-L79), have `targetSdkVersion` set to `30`:
- [`react-native-gesture-handler`](https://github.com/wordpress-mobile/react-native-gesture-handler/blob/wp-fork/android/build.gradle#L60): `targetSdkVersion = 30` ❌ 
- [`react-native-linear-gradient`](https://github.com/wordpress-mobile/react-native-linear-gradient/blob/wp-fork/android/build.gradle#L11): `targetSdkVersion = 30` ❌ 
- [`react-native-prompt-android`](https://github.com/wordpress-mobile/react-native-prompt-android/blob/wp-fork/android/build.gradle#L11): `targetSdkVersion = 30` ❌ 
- [`react-native-reanimated`](https://github.com/wordpress-mobile/react-native-reanimated/blob/wp-fork/android/build.gradle#L94): `targetSdkVersion = 30` ❌ 
- [`react-native-slider`](https://github.com/wordpress-mobile/react-native-slider/blob/wp-fork/src/android/build.gradle#L11): `targetSdkVersion = 30` ❌ 
- [`react-native-video`](https://github.com/wordpress-mobile/react-native-video/blob/wp-fork/android/build.gradle#L10): `targetSdkVersion = 30` ❌ 

I understand that we'd need to update them too as we're doing with other libraries, @AjeshRPai wdyt?

**Comment by AjeshRPai** [comment]
@fluiddot  Thanks for the ping and noticing the `targetSdkVersion` on the other libraries. 🙇🏼 

>I understand that we'd need to update them too as we're doing with other libraries, @AjeshRPai wdyt?

Yup, we'd need to update them as well.
