### ISSUE TITLE
Stop media upload button is missing in iOS Picker

### ISSUE THREAD

**Issue by derekblank** [wordpress-mobile/gutenberg-mobile#5254]
On the React Native 0.69 upgrade branches, the Stop upload button for Media Uploads is missing in the iOS picker.

- https://github.com/wordpress-mobile/gutenberg-mobile/pull/5193

**To Reproduce**
- Tap on the Image block placeholder or edit button in the toolbar
- Tap option ‘Choose from device’ and choose an image
- While the upload is in progress tap on the image thumbnail

**Expected Behavior**
The Stop upload button should be visible:

![Image](https://user-images.githubusercontent.com/643285/199659396-a2515182-10ed-494b-a7d0-af01301ea9a2.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.6.1
 - Build: [pr19326-b696f88
](https://github.com/wordpress-mobile/WordPress-iOS/pull/19326#issuecomment-1252700810)

**Comment by geriux** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/19573
