### ISSUE TITLE
Investigate issues with React Native Gesture Handler `2.5.0`

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/gutenberg-mobile#5255]
**Describe the bug**
While upgrading to React Native `0.69.4` we tried to update the library React Native Gesture Handler to version `2.5.0` but we encountered issues **on iOS** where the editor would freeze while using it.

**To Reproduce**

I didn't find the exact steps to reproduce but while using the editor in general you could easily get it to feeze.

- Open the editor
- Add some blocks
- You might be able to reproduce by:
  - Rotating the device a few times
  - Try to add editing different Paragraph blocks and edit their content
  - Add a Columns block and update its settings by adding/removing columns and rotate the device a few times while doing so.

**Expected behavior**
The editor shouldn't freeze

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro and iPhone 14 Simulator
 - OS: iOS 16,1
 - Version React Native Gesture Handler version `2.5.0`

**Additional context**
I tried a few approaches like memoizing Drag & Drop components, avoiding re-renders, and updating the `Gesture` code using the latest improvements like using [activateAfterLongPress](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/pan-gesture#activateafterlongpressduration-number) instead of manually activating it.

[These are the changes](https://github.com/software-mansion/react-native-gesture-handler/compare/2.3.2...2.5.0) between the version that currently works `2.3.2` against `2.5.0` I also tried the latest release `2.8.0` but it'd still freeze the editor on iOS.

Maybe by checking the commits introduced, we could spot the culprit of the issue.

**Comment by fluiddot** [comment]
Marking the issue as a High priority as eventually, we would need to upgrade the RN Gesture Handler library to version `2.5` or greater and this will be a blocker.

**Comment by fluiddot** [comment]
Closing this issue as we updated `react-native-gesture-handler` to a newer version than `2.5.0` as part of the RN upgrade 0.71 ([reference](https://github.com/WordPress/gutenberg/commit/c2957aa08de7e574d030f167ed8c5731c89e37af)) and we haven't encountered this issue.
