### ISSUE TITLE
Move Gutenberg Editor Unsupported Block Editor Tests to the main apps

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/gutenberg-mobile#5321]
Due to the constant failures of the Gutenberg Editor Unsupported Block Editor Tests **on Android**, we are disabling them in Gutenberg, we will keep the iOS test for now.

Currently, this test only checks for the WebView to be visible and nothing else, on Android it fails often. Let's move this test to the WordPress/Jetpack app improving the actual test with real test sites and assertions.

The test in Gutenberg was disabled in https://github.com/WordPress/gutenberg/pull/46542 for Android only.

**Comment by dcalhoun** [comment]
Noting that the relevant test was relocated to `gutenberg-mobile` in https://github.com/wordpress-mobile/gutenberg-mobile/pull/5969.

**Comment by dcalhoun** [comment]
Removing the high priority label for this test case as I do not believe expanding the automated test is worth of such a priority in comparison to user-facing features and bug fixes. 

Additionally, we have organized a larger effort (p9ugOq-3Rb-p2) to automate the manual tests we have in place for the mobile Gutenberg project. With that, my recommendation is closing this issue to consolidate tracking of our automated testing strategy to one location. 

If others disagree, please feel free to reopen this issue or reinstate the label, sharing your perspective. Thanks!
