### ISSUE TITLE
Block options title shows "undefined" instead of block type

### ISSUE THREAD

**Issue by lmischner** [wordpress-mobile/gutenberg-mobile#5337]
**Describe the bug**
When I open the 3 dot menu for a block, the type of block no longer shows in the menu's title (where it used to say "<block type> block options" it now says "undefined block options"). If I opt to transform the block, it similarly shows "transform undefined to" instead of "transform paragraph to".

**To Reproduce**
1. Access JP or WP in either iOS or Android
2. In a post, tap the 3 dot menu on a block
3. Note menu title does not indicate what type of block it is
4. (You can also tap "Transform block" and see the menu title behavior there as well)

**Expected behavior**
I'm not sure when exactly it broke, but it shows the correct behavior in 21.2:
![Screenshot_20221220-131945](https://user-images.githubusercontent.com/103850310/208750610-6dcdfaa1-6db8-49f8-992f-a019973e5c12.png)

**Screenshots**
![Screenshot_20221220-131737](https://user-images.githubusercontent.com/103850310/208750621-3f8b52ad-c2cc-43c4-ac23-019769ad5dda.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 and iPhone XS
 - OS: Android 13 and iOS 16.0
 - Version 21.4-rc-2

**Comment by derekblank** [comment]
Linking the Gutenberg companion issue for reference: https://github.com/WordPress/gutenberg/issues/46673
