### ISSUE TITLE
Bottom Sheet / Image Settings Visual Refinements

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#535]
Per discussion with @etoledom regarding our progress on the updated "neutral" Bottom Sheets that will be housing Image Block Settings, I wanted to jot down some notes regarding recommended visual refinements. But first, some useful context:

## Related Issues

* Image Setting – Link To: https://github.com/wordpress-mobile/gutenberg-mobile/pull/534
* Image Setting – Alt Text: https://github.com/wordpress-mobile/gutenberg-mobile/pull/531

## Current State

Here's a screenshot of what the current developed state looks like:

<img width="300" alt="screen shot 2019-02-04 at 1 09 04 pm" src="https://user-images.githubusercontent.com/9772967/52207547-0f591f00-287e-11e9-84f8-be0a7b551c3d.png">

## Proposed Design

Here's the proposed design – nearly identical to what @etoledom has here 👏

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/1200432/52225421-e92c8280-286f-11e9-9b0d-f3ffd3a4868c.png">

## Proposed Refinements to Dev

- [x] Remove the `:` from “Link To”. **(in-progress)**
- [x] Force title case for the row titles (`Link To`, `Alt Text`, `CSS Class`, etc). _(This is a point of difference between HIG and Material, but I’d prefer to use title case.)_
- [x] Truncate long text strings in the middle instead of at the end of the line.
- [x] Make last row’s border-bottom full-width.
- [x] 24pt margin between the top of sheet and start of the table. ([example](https://user-images.githubusercontent.com/1200432/52217821-dbbacc80-285e-11e9-9c32-54a8f7915c9a.png))

**Comment by etoledom** [comment]
Closed via https://github.com/WordPress/gutenberg/pull/13855
