### ISSUE TITLE
Fix Jetpack Build issues

### ISSUE THREAD

**Issue by jhnstn** [wordpress-mobile/gutenberg-mobile#5357]
We are currently stuck with [Jetpack@cbd96](https://github.com/Automattic/jetpack/tree/cbd961392fa3879909077b2ba4eb6cb3abd19fcc) due to [this changeset](https://github.com/Automattic/jetpack/pull/27937).

The issue is with how Metro JS attempts to bundle Jetpack with the newly introduced imports [here](https://github.com/Automattic/jetpack/blob/50158fb1d0f95b326abf7e37d491cd964ae4ee6b/projects/js-packages/shared-extension-utils/src/hooks/use-analytics.js#L1)

**Comment by jhnstn** [comment]
@geriux tried fixing the imports via the metro config in [this PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5345/files): 

1. Point metro to use the `config` package index file in `jetpack/projects/js-packages/config/src/index.js'
2. Mock the `jetpack/connection` module

He also fixed an issue with how we are loading up pnpm to install jetpack. I had previously used npx to do the pnpm install but that is no longer working with some of the Jetpack monorepo packages. Not sure why that stopped working but installing pnpm globally seems to work locally and on CI

**Comment by jhnstn** [comment]
I tried fixing the imports in Jetpack itself in [this PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5356) which uses [this Jetpack branch](https://github.com/Automattic/jetpack/compare/rnmobile/fix-build?expand=1)

1. The `config` package sets the `exports` field in the package.json to set the main entrypoint. This does not work with Metro JS. I added the `main` field to point to `./src/index.js` and that fixes the module resolution. Per the [node docs](https://nodejs.org/api/packages.html#main) adding a `main` field will not have an impact on the `exports` 
2. I noticed that the issues from the `connection` package were due to some odd SCSS build issues. The Jetpack changes that started the build issues uses just one module from the `connection` package, so in theory we don't need any of the connection components. I tried adding `projects/js-packages/connection/index.native.js` so we can export only what is needed. 

These changes allowed me to bundle fine locally but looks like the CI is still having issues.

Not sure if we are back to `pnpm` issues or if changing up the connection package index is causing the issues.
I vaguely remember seeing similar failures back when we added `bin/install-jetapck.sh` to fix the prior pnpm problems.

**Comment by fluiddot** [comment]
Setting a High Priority because this issue blocks updating Jetpack in Gutenberg Mobile. This is a critical blocker as we won't be able to incorporate new changes from the Jetpack repository until is fixed 😬 .

**Comment by fluiddot** [comment]
@geriux @jhnstn I assigned you to this issue as I know that you've been recently working on it. Feel free to share the last update to keep track of its progress, and let me know if you plan to keep working on it. Thanks!

**Comment by geriux** [comment]
Currently, we are waiting for a review in https://github.com/Automattic/jetpack/pull/28154 from a Jetpack team member, they requested changes and it looks like @jhnstn addressed them but the CI checks are still pending. @jhnstn Do you know why they're stuck? If not let's ping the team to get some help. Thank you!
