### ISSUE TITLE
Serializer

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#54]
We’re currently using the serializer code but calling it block by block. I believe this is just because our initial mocks use “fake blocks” that the serializer doesn’t know how to handle, but this might still be problematic with the unsupported block. Let’s use the serialize function with the block list directly and see what needs to be done so it handles unsupported blocks gracefully.

Estimated: 8

**Comment by hypest** [comment]
App supports serializing unsupported blocks now and doesn't differentiate between blocks, closing this.
