### ISSUE TITLE
iOS: “Add New Block” indicator not visible when using Inserter

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#543]
Note: this is iOS-only as far as I can tell.

When the Inserter sheet is open, the “add new block” indicator is not visible.

Screenshot (iOS – indicator not visible):

![ff488303-1f4c-45fe-bd08-b230ef6c248c](https://user-images.githubusercontent.com/1200432/52320982-dca34980-2997-11e9-906f-ac8170a273c5.jpeg)

Screenshot (Android – indicator visible):

![cbbece4d-b18f-42b6-960d-fe45b007bfc7](https://user-images.githubusercontent.com/1200432/52320969-d0b78780-2997-11e9-9056-99d48b06756b.jpeg)

**Comment by koke** [comment]
I can see this working on iOS now 🎉
