### ISSUE TITLE
Refine inner block margins

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#547]
Inner block paddings are a bit loose right now, let's make sure these are refined.

## Block Anatomy

By default, every block type (including Title) contains internal padding of 12pt top/bottom and 16pt left/right.

#### Static

<img width="620" alt="image" src="https://user-images.githubusercontent.com/1200432/52358801-47876b80-29fe-11e9-8956-5f346ec1f06e.png">

#### Focused

When a block is focused, we show the inline toolbar (44pt height) and collapse the margin-bottom, like so:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/1200432/52358900-6f76cf00-29fe-11e9-9b2d-f59ec5c8c44e.png">

## Currently 

(proper paddings indicated with green, improper in red)

Android:

![image](https://user-images.githubusercontent.com/1200432/52362272-cd5ae500-2a05-11e9-8e3d-152108c08537.png)

As you can see, left/right paddings on Android are 👍 , however top/bottom paddings are a bit off.

iOS:

![ios](https://user-images.githubusercontent.com/1200432/52362263-c6cc6d80-2a05-11e9-9efe-aeb6231db43b.jpg)

## Punch-list

**Both Platforms**

- [ ] Ensure padding-top is always 12 (static + focused)
- [ ] Remove padding-bottom when block is focused

**iOS**

- [ ] Ensure padding on left/right sides is 16pt

**Comment by iamthomasbishop** [comment]
Previous, related issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/393

**Comment by SergioEstevao** [comment]
@iamthomasbishop I update the margins here, one of the issue we where having is that the text container had a minimum height of 50px so when we had a single line on it we were still getting 50px of height to it making it look to have bigger margins. Here is a screenshot with some extra colors:
![simulator screen shot - iphone xr - 2019-02-20 at 11 05 29](https://user-images.githubusercontent.com/651601/53087717-b46f2b00-34ff-11e9-81ff-8d210837a847.png)

**Comment by iamthomasbishop** [comment]
Pulled this into Sketch to double check, and all of these margins look aligned _perfectly_.

![image](https://user-images.githubusercontent.com/1200432/53102055-94843b00-34f0-11e9-9fc3-922625b52e4b.png)

Thanks for taking care of this @SergioEstevao !
