### ISSUE TITLE
Remove all focus when tapping in empty canvas or hide keyboard button

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#552]
## Expected Behavior

When I tap on the `hide keyboard` button or an empty part of the canvas (outside visible blocks), I expect that all blocks would be un-focused.

## Current Behavior

* When tapping the `hide keyboard` button or on an empty part of the canvas, the keyboard hides and the caret is hidden, but the block stays in a focused state.

## Video

https://cldup.com/JYYcSZyTfm.mp4

**Comment by koke** [comment]
I tested on both platforms and the hide keyboard button correctly dismisses focus. Tapping on an empty area doesn't but it hardly happens with the available space (maybe on iPad).

I think I'd like to close this for now, and move the conversation to #358 and figure out tapping on empty areas there.
