### ISSUE TITLE
Embed block not persisting input in HTML mode

### ISSUE THREAD

**Issue by derekblank** [wordpress-mobile/gutenberg-mobile#5527]
**Describe the bug**
When editing an Embed, YouTube, or Vimeo block in HTML mode, any input is not persisted, and disappears when hitting Publish.

**To Reproduce**
1. Create a new post using the mobile editor
2. Add the Embed-, Vimeo-, or YouTube-block to the page with a valid video URL
3. Switch to HTML mode using the Options menu (three dots, top right)
4. Edit the HTML, e.g.: add a custom `class` attribute of the parent element, e.g.: `<figure class="test-class-123 ...">`
5. Press Publish
6. Note any custom HTML input that was just added is not saved, and disappears before the post is published

**Expected behavior**
Custom HTML input would persist when editing as HTML mode.

**Screenshots**

https://user-images.githubusercontent.com/643285/222637060-d8df2415-4116-4ccb-85c0-5998deb39629.mov

**Smartphone:**
 - Device: iPhone SE 2022
 - OS: iOS 15.6.1
 - Version: 21.7.2

**Additional context**
Related Gutenberg issue: https://github.com/WordPress/gutenberg/issues/41813

**Comment by fluiddot** [comment]
Closing the issue as it has been fixed in https://github.com/WordPress/gutenberg/issues/45540.
