### ISSUE TITLE
Upload - Handle failed uploads

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#5566]
## Description

Implement the same logic we have in the Video block for the case when an upload fails. The functionality should match the test cases we have for other media blocks:

- [TC001 - Insert video from device (failing)](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/video.md#tc001)
- [TC002 - Insert video from device (stop)](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/video.md#tc002)
- [TC004 - Close/Re-open post with an ongoing video upload](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/video.md#tc004)
- [TC005 - Close post with an ongoing video upload](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/video.md#tc005)

**Comment by fluiddot** [comment]
@osullivanchris I think we haven't included this flow in the designs (XHD8UklCpQe10CX2Zz1zBo-fi). I'm considering following the exact same flow as we have in the Video block, but let me know if you rather do it differently. Thanks!

**Comment by osullivanchris** [comment]
@fluiddot I didn't look at these cases but I'm ok with using what we have in the Video block for now.

**Comment by fluiddot** [comment]
This issue has been addressed in https://github.com/Automattic/jetpack/pull/29511.
