### ISSUE TITLE
Post List: VideoPress blocks should not show the video url in the post list

### ISSUE THREAD

**Issue by jhnstn** [wordpress-mobile/gutenberg-mobile#5601]
The post list in the native apps is showing the video source url : 

![Image](https://user-images.githubusercontent.com/744755/228336693-c9214e48-9e63-4a08-97c4-1b37349df6c7.png)

The posts with a core video block are empty in the post list:

![Screen Shot 2023-03-29 at 10 19 46 AM](https://user-images.githubusercontent.com/744755/228568734-8cc609b1-3f93-4ea8-be25-32455d9a9276.png)

**Comment by fluiddot** [comment]
I'm wondering whether we should consider this issue as a non-blocker. It's not ideal but it's not disrupting the block experience, WDYT?

cc @jhnstn @SiobhyB

**Comment by jhnstn** [comment]
This feels borderline blocking. While it's not broken it is ugly, especially when compared to the core video block behavior.
So no on blocking but I think we should address it soon.

**Comment by fluiddot** [comment]
> This feels borderline blocking. While it's not broken it is ugly, especially when compared to the core video block behavior.
> So no on blocking but I think we should address it soon.

Ok, let's keep it in then in the list of pending tasks 👍 .
