### ISSUE TITLE
Add underline option for text-based blocks

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#562]
## Context

Core Gutenberg doesn't have an option for `underline`, but considering the usage data, there is some value in adding it to the style options alongside bold, italic, and strikethrough.

In Aztec, `underline` is consistently in the top 10, and its usage is roughly double that of `strikethrough`.

## Proposal

Add `underline` button to Quick Toolbar on text-based blocks such as Heading, Paragraph. I would add this right before the `strikethrough` option.

<img width="252" alt="screen shot 2019-02-07 at 10 22 28 am" src="https://user-images.githubusercontent.com/1200432/52425783-546d9300-2ac2-11e9-96fa-93fd45b1d369.png">

Either of these icons could be used:

* Dashicons: https://developer.wordpress.org/resource/dashicons/#editor-underline
* Material: https://material.io/tools/icons/?icon=format_underlined

**Comment by koke** [comment]
[More on core's decision to not implement underline](https://make.wordpress.org/core/2016/10/28/editor-changes-in-4-7/):

> The underline and justify buttons have been removed from the bottom row. Underlining is a bad practice as readers can confuse it with links (bad accessibility), and it does not insert a semantic element. Justifying has uneven browser implementation, and in many cases is bad for readability. Keyboard shortcuts for both will keep working.

And extra discussion in https://core.trac.wordpress.org/ticket/27159

I have mixed feelings about the decision, but I don't think I can stand behind mobile diverging from core in something like this that it's hardly specific to mobile, so I'm closing this for now.

**Comment by iamthomasbishop** [comment]
I also have mixed feelings, but certainly understand the rationale. Closing for now sounds good to me.

**Comment by iamthomasbishop** [comment]
@koke I noticed that core re-added the underline style recently. Do we want to re-open this and consider adding it to mobile?

**Comment by koke** [comment]
It is there but kind of hidden in an overflow menu. 
<img width="317" alt="Screen Shot 2019-06-20 at 22 42 27" src="https://user-images.githubusercontent.com/8739/59880187-b4e3d980-93ac-11e9-9b4c-1b549469df34.png">

I haven't found any discussions as to why the change happened, but I was sold on the original idea of not doing it. I'd be curious to know more about why and how people are using it.

**Comment by iamthomasbishop** [comment]
Same. The rationale of not including it made sense, but perhaps market demand won out 😆 I think it's probably just an expected thing.

**Comment by hypest** [comment]
Gutenberg on the web still seems to has it so, re-opening this ticket.

**Comment by hypest** [comment]
Decision on which part to implement for this feature: https://github.com/WordPress/gutenberg/pull/17483#issuecomment-535989589

**Comment by designsimply** [comment]
We do still get requests for an underline option for text from apps users. I am not sure yet whether it would be helpful to create a new issue to track such requests, so I will leave the latest request here for now.

> The app is great, but it lacks some features that should have become intuitive in the blogging process: 1. Underline under writing […]

<sup>4-star review - Sep 18, 2020 at 11:28 PM - Galaxy On Nxt, WPAndroid 15.7-rc-3, Android 7.0</sup>
<sup>(internal reference: play-store-feedbackid=gp:AOqpTOFwoqUWzFnguYgKjf8J7PtrHbtwz2PdvUIgV_1lrD-OKnxA1b1ZMZt6_sYj9ncV7uZMSlJJ4OaC8x1xG2V6)</sup>

I saw in https://github.com/WordPress/gutenberg/pull/17483 that we attempted to add an underline option in WPAndroid at one point but it was removed at the request of the core WordPress & Gutenberg developers. I think what has happened is that it has effectively been removed everywhere except on WordPress.com web. If we were to consider changing this again, or if we want to track requests for it, we might consider adding the option in the app for WordPress.com only which would create feature parity with both WordPress core and WordPress.com. 

Mobile Web WordPress.com|Mobile Web WordPress Core|WPandroid 15.8-rc-1 Aztec
---|---|---
![Screenshot_20200921-114252](https://user-images.githubusercontent.com/1119271/93802127-479ea400-fc00-11ea-971e-c6fece7777ac.png)|![Screenshot_20200921-114152](https://user-images.githubusercontent.com/1119271/93802128-48373a80-fc00-11ea-837c-c119e1a4047a.png)|![Screenshot_20200921-112814](https://user-images.githubusercontent.com/1119271/93802129-48cfd100-fc00-11ea-8bec-54192c8b8ed9.png)

Either way is ok with me, and mainly I would like to know how you would like to receive feedback about this as we continue to receive user requests asking for an underline option through app reviews and elswhere.

**Comment by erricgunawan** [comment]
> ... would like to receive feedback about this as we continue to receive user requests asking for an underline option ...

Just got feedback from 3736130-zen:

> Stop disabling keyboard shortcuts such as underlining. Make formatting easier.

I couldn't find where else to report this for now (or if it's still needed to be reported). 

Happy to be redirected to the more appropriate place.
