### ISSUE TITLE
Player: Add custom controls on Android

### ISSUE THREAD

**Issue by jhnstn** [wordpress-mobile/gutenberg-mobile#5646]

**Comment by jhnstn** [comment]
The touch events on Android are spotty. 
As an MVP leverage the VideoPress player events to add custom controls.

**Comment by fluiddot** [comment]
@jhnstn since we find a workaround to enable touch events on Android, I'm wondering if we could close this issue, WDYT?

**Comment by jhnstn** [comment]
yup!
