### ISSUE TITLE
Update Gutenberg toggle copy

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#567]
We should review the whole setting, but some things that might not be ok for release:
- The 💣 emoji
- The monkeys 😭
- It says (A8C)
- Let's not call it "experimental", it sounds too scary. "Preview" might be a better term

Let's use

> Use Block Editor  [x]
> Edit new posts and pages with the block editor

- [x] iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/11044
- [x] Android: https://github.com/wordpress-mobile/WordPress-Android/pull/9208

**Comment by koke** [comment]
Current:

![img_d4c2c8a0a03f-1](https://user-images.githubusercontent.com/8739/52430629-d4b5e780-2b06-11e9-9448-6c42cab35853.jpeg)

**Comment by koke** [comment]
I think the simplest option is to use "Use block editor for new posts"
@iamthomasbishop I don't know if we want any extra explanation below, but this should be consistent with the messaging in https://github.com/wordpress-mobile/WordPress-Android/issues/9034 and https://github.com/wordpress-mobile/WordPress-iOS/issues/10869

**Comment by iamthomasbishop** [comment]
> I think the simplest option is to use "Use block editor for new posts"

This makes sense to me as well for the row label.

We might want to change the footer text slightly to something more like "early preview" rather than "an experimental version", considering it's pretty stable – just not full-featured.

**Comment by iamthomasbishop** [comment]
Also on iOS, we might want to use Title Case for the label: "Use Block Editor for New Posts".

**Comment by koke** [comment]
It's not a preview though, just the first version 😉 
I still feel a need to set the right expectations, but also I think very few people would stumble into the setting by accident, and we can set those expectations in the release notes and announcement posts.

Maybe we can use the footer to highlight that they can still switch back to Classic on any post from the editor menu?

**Comment by iamthomasbishop** [comment]
> It's not a preview though, just the first version

🤦‍♂️ Duh. My wires are crossed.

> Maybe we can use the footer to highlight that they can still switch back to Classic on any post from the editor menu?

Yea that makes sense.

**Comment by koke** [comment]
Just to summarize here the discussion from #565, we're going with:

> Use Block Editor  [x]
> Edit new posts and pages with the block editor.
