### ISSUE TITLE
VideoPress block: Ensure settings persist after previewing a post on iOS

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#5677]
**Describe the bug**

At the moment, if you tweak the settings on a VideoPress block, those settings get lost if you preview the post on iOS.

**To Reproduce**

1. Having a VideoPress block with a video.
2. Change some of the settings that will be synced (e.g. title).
3. Tap on the three dots button.
4. Tap on Preview.
5. Close the preview.
6. Open the block settings and observe that the settings changes were discarded.

**Expected behavior**

The settings should persist locally after previewing.

**Additional context**

As of https://github.com/Automattic/jetpack/pull/30131, VideoPress settings are only synced when a user manually saves a post. Ideally, previewing a post wouldn't trigger a sync (as the post isn't necessarily saved). However, if there isn't a straightforward way to persist the settings locally, we could consider syncing the settings.

There are also some cases where settings may be lost in both the app and the web. In order to remain in alignment with the web, these issues will be discussed separately in the following places:

* https://github.com/Automattic/jetpack/issues/30237
* https://github.com/Automattic/jetpack/issues/30233

**Comment by SiobhyB** [comment]
Updating the title to reflect that settings are also lost following a replacement:

https://user-images.githubusercontent.com/2998162/233365109-dacdd5c4-3f05-41cd-9fd7-f31b2f139b87.mov

**Comment by SiobhyB** [comment]
Noting here that the case for whether settings should persist or be reset following a replacement isn't clear cut. Native is currently in alignment with the web in resetting following a replacement, and there could be an argument to this being preferred. I've created an issue at https://github.com/Automattic/jetpack/issues/30233 for further discussion. The app will remain in alignment with the web in how we handle this. As such, I removed the replace flow from this PR's title and description.

**Comment by fluiddot** [comment]
> **Switch to HTML mode**

I tested the web version and noticed that this issue is also happening. In fact, I found a bug that prevents some of the block settings to be modified via the HTML editor (https://github.com/Automattic/jetpack/issues/30237).

**Comment by SiobhyB** [comment]
@fluiddot, thanks for catching that! I've updated this GitHub issue to reflect that this known bugs/issues are being discussed in separate GitHub issues. The scope of this specific issue has now been reduced to the preview issue on iOS.

**Comment by fluiddot** [comment]
> @fluiddot, thanks for catching that! I've updated this GitHub issue to reflect that this known bugs/issues are being discussed in separate GitHub issues. The scope of this specific issue has now been reduced to the preview issue on iOS

@SiobhyB Now that the scope of this issue has been reduced, do you think we could close it as https://github.com/wordpress-mobile/WordPress-iOS/pull/20571 has been merged?

**Comment by SiobhyB** [comment]
Sounds good, closing.
