### ISSUE TITLE
Custom gradient is not selected when opening the background color

### ISSUE THREAD

**Issue by jhnstn** [wordpress-mobile/gutenberg-mobile#5726]
**Describe the bug**
Custom gradient is not selected when opening the background color

**To Reproduce**
Follow [Custom Color TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/color-settings.md#tc005)

**Expected behavior**
The last expected behavior of the test should pass.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13
 - Version 22.3-rc-1

**Additional context**

**Comment by dcalhoun** [comment]
Is this report duplicative of https://github.com/WordPress/gutenberg/issues/42017?

**Comment by jhnstn** [comment]
> Is this report duplicative of [WordPress/gutenberg#42017](https://github.com/WordPress/gutenberg/issues/42017)?

It is indeed. Thanks @dcalhoun
