### ISSUE TITLE
Proposal: Add ability to style text and add link in Image caption

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#574]
## Expected Behavior

As a user, I'd expect to be able to style text and add a link on a caption.

## Current Behavior

We (mobile GB) don't currently offer any controls for customizing the style or linking on the caption.

Core GB currently offers an inline toolbar that looks like this:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1200432/52431543-09f21380-2ace-11e9-916e-2db5601702f2.png">

## Proposal

In the long-term we might want to explore a similar "floating" solution to Core's, but in the short-term I think it'd make sense to utilize the Quick Toolbar surface. Thinking of the caption as a "child" of the image block, I think we could approach it in this way:

* Remove the Image Block-level controls (Edit aka "pencil" icon)
* Show style controls (`bold`, `italic`, `link`, `strike`, `underline` if we add from [this](https://github.com/wordpress-mobile/gutenberg-mobile/issues/562))

<img width="389" alt="image" src="https://user-images.githubusercontent.com/1200432/52432109-3ce8d700-2acf-11e9-9143-b5d084f498c4.png">

**Comment by koke** [comment]
As we move to RichText, let's also test #590 and see if that gets fixed

**Comment by mchowning** [comment]
I am looking into this issue now.

**Comment by mchowning** [comment]
> As we move to RichText, let's also test #590 and see if that gets fixed

Also worth taking another look at #829

**Comment by etoledom** [comment]
Closed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/975
