### ISSUE TITLE
Red screen on shift + ENTER in title.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/gutenberg-mobile#580]
## Description:

While the caret is in the title, pressing shift + ENTER brings up a red screen.

Steps to reproduce:

1. Open a new post.
2. Place the care on the title.
3. Press shift + ENTER.

A red screen will come up.

Reported here: https://github.com/wordpress-mobile/WordPress-iOS/pull/10969#pullrequestreview-201589639

**Comment by koke** [comment]
I tried this today and could not reproduce anymore 🎉
