### ISSUE TITLE
Update RELEASE-NOTES in the apps with a general note about Gutenberg

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#584]
Instead of changing `RELEASE-NOTES.txt` for each individual change, let's make sure we add a note before the release

**Comment by koke** [comment]
@SergioEstevao @marecar3 assigning to you since you'll be wrangling the release, just so you're aware of it. Let's chat next week about what to add exactly

**Comment by hypest** [comment]
Do we have a text copy to use?

How about:
`First public release of the new, native Block Editor`

**Comment by koke** [comment]
Actually, we don't want a mention of this on the App Store release notes, so this should be good to close 😅
