### ISSUE TITLE
Remove third-party dependency on react-native-hsv-color-picker

### ISSUE THREAD

**Issue by derekblank** [wordpress-mobile/gutenberg-mobile#5847]
**Is your feature request related to a problem? Please describe.**
The react-native-hsv-color-picker library is an unmaintained forked third-party dependency that uses no native resources, and is only used in one Gutenberg file (the [native color picker](https://github.com/WordPress/gutenberg/blob/291a19595115cd9b8277d0ca30b2f0ad34dd2168/packages/components/src/color-picker/index.native.js#L5)). The library is small enough that it could be implemented directly within our code as part of the native color picker (or as a native color picker utility).

Removing the third-party dependency would simplify future React Native upgrades. 

**Describe the solution you'd like**
1. Take the source of react-native-hsv-color-picker and incorporate it as part of the [native Gutenberg color picker files](https://github.com/WordPress/gutenberg/tree/291a19595115cd9b8277d0ca30b2f0ad34dd2168/packages/components/src/color-picker).
2. Convert the code from a class to a function component in the process, and modify any library code that would better suit the project.
3. Remove the third-party react-native-hsv-color-picker package dependency and delete the repo. 

**Describe alternatives you've considered**
Continue to use the forked third-party library as-is, or use the original react-native-hsv-color-picker library as a non-forked dependency.

**Comment by fluiddot** [comment]
Thanks for opening the ticket @derekblank 🙇 ! I also considered this when reviewing the dependencies for the React Native upgrade. It shouldn't be too complex to implement a picker similar to what we have in https://github.com/lukewalczak/react-native-hsv-color-picker/blob/master/src/HsvColorPicker.js.

**Comment by derekblank** [comment]
Just a heads up -- I've started working on this issue during downtime in between other tasks.

**Comment by derekblank** [comment]
Resolved in https://github.com/WordPress/gutenberg/pull/53329.

**Comment by fluiddot** [comment]
Now that we no longer use the forked repository https://github.com/wordpress-mobile/react-native-hsv-color-picker, I'm going to archive it.
