### ISSUE TITLE
Image Caption gets cut off instead of overflowing to new line

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#590]
Instead of overflowing to a new line, the caption is getting cut off.

Screenshot:

![screenshot_20190212-124120](https://user-images.githubusercontent.com/1200432/52659721-9e3fea00-2ec3-11e9-8923-a2bb8c29ed15.png)

**Comment by koke** [comment]
I'm leaving this on bug fixes, but it's likely to be taken care of by #574

**Comment by etoledom** [comment]
Fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/975
