### ISSUE TITLE
Align text-label wording on block placeholders

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#592]
## Currently

**When starting a new post**, the first placeholder block has a text label that says `Start typing or press (+) to add content`.

**When you add additional blocks**, those text labels say `Add text or type / to add content`.

## Proposal

Considering we don't currently provide slash commands, the second message isn't appropriate in our editor. 

I propose that we show 1 consistent message – `Start typing or press (+) to add content`.

This is related to: 
https://github.com/wordpress-mobile/gutenberg-mobile/issues/549

**Comment by SergioEstevao** [comment]
@iamthomasbishop do you want "Start typing..." or "Start writting..." and can we keep the unicode character for now?

**Comment by iamthomasbishop** [comment]
It should probably be "writing", considering we support various input methods (voice, Pasting, etc). Good catch.

I think @koke was working on the Unicode thing, so that should be fixed soon.
