### ISSUE TITLE
Android: Placeholder Text alignment on RTL 

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#593]
The placeholders should be aligned right on RTL layouts:

![android_rtl](https://user-images.githubusercontent.com/9772967/52696925-8d00e700-2f70-11e9-91a6-ed5d35303bf3.png)

**Comment by etoledom** [comment]
Related iOS fix for a similar problem:
https://github.com/wordpress-mobile/gutenberg-mobile/pull/591

**Comment by hypest** [comment]
It happens that on Android, the text alignment generally follows the locale of the text so, when for example displaying English text the alignment is left even if the global language/locale is set to a RTL one. That's what the stock ReactNative components seem to follow on Android and it's acknowledged here as well: https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html#limitations-and-future-plan

> Text alignment behaviors differ in iOS and Android
>
>  *  In iOS, the default text alignment depends on the active language bundle, they are consistently on one side. In Android, the default text alignment depends on the language of the text content, i.e. English will be left-aligned and Arabic will be right-aligned.
>  *  In theory, this should be made consistent across platform, but some people may prefer one behavior to another when using an app. More user experience research may be needed to find out the best practice for text alignment.


In the meantime, I tried out the work in https://github.com/wordpress-mobile/gutenberg-mobile/pull/585 and have verified that when the  placeholders are translated, the RTL texts do render as RTL. So, it seems there's no work needed on the Android side to change the bahavior.

Closing this ticket as "wont fix" and we can re-open if needed.
