### ISSUE TITLE
Story block: Upload progress is not displayed after close/re-open a post with an ongoing upload

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#5947]
**Describe the bug**
After close/re-open a post with an ongoing upload in a Story block, there's no visual indication that an upload is in progress.

**To Reproduce**
* Follow testing instructions from test case: [TC005 - Close/Re-open post with an ongoing Story upload](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/jetpack/story.md#tc005)

**Expected behavior**
The upload progress should be shown after close/re-open a post.

**Screenshots**

https://github.com/wordpress-mobile/gutenberg-mobile/assets/14905380/f1767d36-76fd-4308-946d-70232587f670

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android 13
 - Version 22.7-rc-1

**Additional context**
N/A

**Comment by SiobhyB** [comment]
Closing following the Story block's removal in https://github.com/wordpress-mobile/gutenberg-mobile/pull/6568.
