### ISSUE TITLE
[Android] Bottom Sheets: Inset table rows with icons to 72dp keyline

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#597]
On Android bottom sheets, we should inset table rows with icons to the 72dp keyline.

## Current (iOS + Android)

<img width="375" alt="screen shot 2019-02-13 at 1 38 53 pm" src="https://user-images.githubusercontent.com/1200432/52738684-c8ada800-2f94-11e9-94e4-f0209573f6f8.png">

## Proposed on Android

<img width="360" alt="screen shot 2019-02-13 at 1 39 51 pm" src="https://user-images.githubusercontent.com/1200432/52738720-e11dc280-2f94-11e9-8ef0-f76bd56e8c48.png">

**Comment by etoledom** [comment]
Closed via https://github.com/WordPress/gutenberg/pull/13855
