### ISSUE TITLE
Keyboard automatically resigns and becomes active in an infinite loop

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/gutenberg-mobile#6002]
**Describe the bug**
Keyboard automatically resigns and becomes active in an infinite loop without any user interactions.

**To Reproduce**

Can't provide these. I've been simply adding one block type after another to monitor the memory usage. At some point, I saw two "Start typing..." blocks at the bottom and the keyboard started doing it.

**Expected behavior**
n/a

**Screenshots**

https://github.com/wordpress-mobile/gutenberg-mobile/assets/1567433/deed2932-1a7e-4488-805a-3fc5728b34c0

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.5.1 (c)
 - Version `trunk` from the commit https://github.com/wordpress-mobile/WordPress-iOS/commit/8f1a857c2207a5d189956b688e2151bfea41afb6

**Additional context**

**Comment by kean** [comment]
I managed to stop it be pressing (+) a few times.

**Comment by kean** [comment]
I managed to reproduce it again without doing anything special; just added a "preformatted" block.

**Comment by kean** [comment]
I was able to reproduce it again without doing anything special. I was just adding more blocks.

Here are some more videos to demonstrate what's happening. I'm not performing any interactions. I managed to close it 
and save the draft, but only after some struggle because the confirmation alert also kept jumping up and down.

https://github.com/wordpress-mobile/gutenberg-mobile/assets/1567433/f28edeae-5aeb-4725-afc4-372e0b25711b
https://github.com/wordpress-mobile/gutenberg-mobile/assets/1567433/7755997b-c3b6-449c-ac69-eb8bb5bc994e

**Comment by twstokes** [comment]
Thanks @kean for reporting this!

It would be worth us testing on or after [`1614edc`](https://github.com/wordpress-mobile/WordPress-iOS/commit/1614edc7ece69f3630737eb13d4747c60f8bd6c5) where we merged the [React Native upgrade](https://github.com/wordpress-mobile/WordPress-iOS/pull/20956) to see if anything acts differently. 🤔

**Comment by geriux** [comment]
Hey @kean 👋 we are currently working on a fix for this, would you mind t[esting this build](https://github.com/wordpress-mobile/WordPress-iOS/pull/21209#issuecomment-1658561718) when you have a chance to see if it fixes it for you? Any feedback would be appreciated, thank you!

**Comment by kean** [comment]
Hey @geriux, thanks for addressing it so quickly. I tested it, and after adding hundreds of blocks, it's still going strong with no issues. It feels snappier too; maybe it's just me.

<hr/>

Unrelated:
- It would be nice to entirely eliminate the keyboard jumps when adding new paragraphs
- "Start writing..." placeholders looks like [regular text](https://github.com/wordpress-mobile/gutenberg-mobile/assets/1567433/a8671199-791b-4175-be5f-188d4d3f4a03); it would be nice to make them gray

**Comment by geriux** [comment]
Thank you for testing! Happy to see that it fixed the issue for you! And that it feels snappier 🎉 

>It would be nice to entirely eliminate the keyboard jumps when adding new paragraphs
>"Start writing..." placeholders looks like [regular text](https://github.com/wordpress-mobile/gutenberg-mobile/assets/1567433/a8671199-791b-4175-be5f-188d4d3f4a03); it would be nice to make them gray

Those are great suggestions! 

Hopefully, we'll be able to avoid hiding/showing the Keyboard in the future when we improve the current implementation we have with Aztec.

As for the placeholder, I'll create an issue to track it. Thanks again!
