### ISSUE TITLE
[iOS] Using the keyboard suggestions removes spaces

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#603]
When you use the predictive keyboard on iOS, sometimes there aren't spaces between words

![predictive-text](https://user-images.githubusercontent.com/8739/52862722-347b4680-3136-11e9-8580-cd01c3c4fc5d.gif)

**Comment by etoledom** [comment]
Adding to this:
After a suggestion is inserted and there are no space added, you can try press the space button. This will unexpectedly delete de last letter of the inserted word instead of adding the space.

**Comment by pinarol** [comment]
Let's check if this also fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/693
