### ISSUE TITLE
Tablet layout visual refinements

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#604]
This issue covers various refinements related to layout/alignment.

Visualization for reference:

![image](https://user-images.githubusercontent.com/1200432/52881651-c3826180-312a-11e9-9532-c16c97c0231e.png)

## Punchlist

- [ ] User should be able to scroll by dragging anywhere on canvas
- [ ] ~Center column container should have max-width of 580, which provides a nice readable balance/line-length~
- [ ] ~Block boundaries should extend beyond center column by 16 on each side (inner block 580 to edge of container)~
- [ ] Quick Toolbar should extend to edges of canvas

Note: Upon further inspection, the container-width might be dependent on readable-margins, so this is probably fine as-is. At least on iOS, when I change the OS-level font-size the container width adjusts (I didn't realize I had my OS-level setting to lower than default). However, the font-size doesn't actually adjust in the editor – I will create another separate issue for this.

**Comment by etoledom** [comment]
Related: https://github.com/wordpress-mobile/gutenberg-mobile/issues/473
