### ISSUE TITLE
[iOS] Make blocks full-width on narrow viewports, split-view

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#607]
Discovered when testing split-view on iPad.

![27b68670-7d80-4a2f-8784-87fbabfebe0c](https://user-images.githubusercontent.com/1200432/52921291-37fc0280-32db-11e9-980b-70827d43d26d.jpeg)

In theory, all blocks should be full-width on < ~580, depending on readable content-widths and dynamic type sizes.

**Comment by koke** [comment]
@etoledom do you think we can fold this into #473 and close this one?

**Comment by etoledom** [comment]
Yes, and #473 is finished so we can close that one too. I'll test split view again to see if it's working correctly.

**Comment by etoledom** [comment]
In the latest develop it's working well! 🎉 

![IMG_0037](https://user-images.githubusercontent.com/9772967/55585900-07a3e280-5728-11e9-96d3-b18f280109f0.png)

It is also adjusting properly when it's expanded:

![IMG_0038](https://user-images.githubusercontent.com/9772967/55585960-24401a80-5728-11e9-9782-3f612fd4efc2.png)

Let's say this was closed via #769
