### ISSUE TITLE
Social Icons block - Appender and buttons alignment

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/gutenberg-mobile#6140]
**Describe the bug**
It appears the buttons and the appender of the Social Icons block are adding extra padding that affects the alignment of the content.

**To Reproduce**
1. Open the editor
2. Add the social icons block
3. The icons and the appender have extra paddings

**Expected behavior**
Social icons and the appender should be aligned.

**Screenshots**
Before|After
-|-
<kbd><img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/4885740/dc49bf9b-7d51-48c6-be8a-d087c2f8f3b2" width="250" /></kbd>|<kbd><img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/4885740/916aff68-6e26-4a21-9f67-c53bff20d96b" width="250" />

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.4
 - Version: Upcoming beta using Gutenberg Mobile `1.103.0`

**Additional context**
N/A

**Comment by dcalhoun** [comment]
I believe this was introduced with https://github.com/wordpress-mobile/gutenberg-mobile/pull/6133. I am unsure what amount of padding is expected on the buttons or container, but I agree the icons and appenders should be aligned. Thank you for capturing this issue. cc/ @derekblank

**Comment by geriux** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/54100
