### ISSUE TITLE
[iOS] Empty paragraph not removed when inserting a different block

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#626]
To reproduce:

* Create a new post
* Write a paragraph, press enter
* Tap + and add a heading

A heading block is inserted but the empty paragraph block stays in place

Tested with WPiOS develop (https://github.com/wordpress-mobile/WordPress-iOS/commit/e0f869274f967af3679e581559ff94e0feb1b67c) pointing to gutenberg-mobile develop (8ed6cb17b3443c45562c0eef410d97de4f3d0c55)

**Comment by diegoreymendez** [comment]
I'm closing this as this was apparently fixed at some point last week.
