### ISSUE TITLE
[Android] Heading block shows no formatting at first

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#627]
To reproduce:

1. Create a new post
2. Insert a heading block
3. Type some text

Initially the text has normal paragraph formatting. Toggling the h2/3/4 buttons sets the right format.

Tested on WPAndroid develop (https://github.com/wordpress-mobile/WordPress-Android/commit/03e8d84a1bb698354f73e6934432de60dcf7f431) pointing to gutenberg-mobile develop ([8ed6cb1](https://github.com/wordpress-mobile/gutenberg-mobile/commit/8ed6cb17b3443c45562c0eef410d97de4f3d0c55))

**Comment by marecar3** [comment]
Fixed.
