### ISSUE TITLE
Moving title to top bar

### ISSUE THREAD

**Issue by paaljoachim** [wordpress-mobile/gutenberg-mobile#634]
Hey

In the regular version of Gutenberg we are working on this issue:
Add Block: Title
https://github.com/WordPress/gutenberg/issues/11553

One of the thoughts is moving the title to the top bar. Then creating a Title Block the user can add directly to the layout if they want the title visible on the page/post.

I am thinking about the mobile view. Perhaps you could share some thoughts about it directly on the above issue? Thanks.

**Comment by koke** [comment]
Thanks for the heads up, we really appreciate it. I mentioned this to @iamthomasbishop since I think he's the right person to join that conversation. I'm closing this issue and we can continue there.
