### ISSUE TITLE
Default and paragraph placeholders don't match

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#637]
I missed this when reviewing #616, but the default block placeholder shows at a slightly different position than the paragraph placeholder so it moves the first time you tap on it.

Also, the border makes the text go up/down 1px when it gets and loses focus.

![placeholders](https://user-images.githubusercontent.com/8739/53175440-39377300-35ec-11e9-942f-50eb618d53ba.gif)

cc @iamthomasbishop @SergioEstevao

**Comment by iamthomasbishop** [comment]
Not sure if it's 100% related, but potentially related to the other issue that @pinarol and @etoledom are working on [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/622).

I really wish we had access to `box-shadow` bc it would solve the shifting issue with a few lines of code 😪

**Comment by SergioEstevao** [comment]
@koke was this on the latest on develop? Just tested and while I see the 1px moving up I don't see the big gap when moving from post placehoder to paragraph placeholder...

**Comment by koke** [comment]
Yeah, WPiOS develop (3be1df9ebf) with the Podfile pointing to my local checkout with develop (bdf0202) and running metro

**Comment by pinarol** [comment]
> the border makes the text go up/down 1px when it gets and loses focus
this will be fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/622

But the issue about '_default block placeholder shows at a slightly different position than the paragraph placeholder so it moves the first time you tap on it_.' is different
