### ISSUE TITLE
Change background-color on Image placeholder block

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#640]
Currently the background color on the Image Block during placeholder state looks like:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1200432/53188633-70495c80-35cb-11e9-9804-c9497514a323.png">

Its background is a neutral gray, where it should be `$gray-lighten-30` aka `#E9EFF3`, like the unsupported blocks:

![img_1989](https://user-images.githubusercontent.com/1200432/53188815-be5e6000-35cb-11e9-83a1-df69218657d4.jpeg)

Also noticed that the icon color – can we change that to `$gray-dark` aka `#2e4453`?

**Comment by iamthomasbishop** [comment]
Also noticed that the icon color – can we change that to `$gray-dark` aka `#2e4453`?

**Comment by marecar3** [comment]
Done : https://github.com/WordPress/gutenberg/pull/14033/files
