### ISSUE TITLE
Introduce a visual indicator to inform users when the editor is in an offline state

### ISSUE THREAD

**Issue by derekblank** [wordpress-mobile/gutenberg-mobile#6405]
![Image](https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/c9e86170-2698-4f94-a8dd-ea5f62e98bb2)

**Comment by derekblank** [comment]
Connectivity status requirements: boolean connected/disconnected.  Dependent on:

- https://github.com/wordpress-mobile/gutenberg-mobile/issues/6409.

**Comment by dcalhoun** [comment]
Completed by https://github.com/WordPress/gutenberg/pull/56934. The user-facing feature is currently hidden behind a dev flag.
