### ISSUE TITLE
Editor appearance not displaying light/dark mode correctly in Android for certain themes

### ISSUE THREAD

**Issue by derekblank** [wordpress-mobile/gutenberg-mobile#6431]
**Describe the bug**
On Android for certain themes using custom colors, the Editor does not display text in light mode correctly. 

**To Reproduce**
1. Activate the [Russell theme](https://wordpress.com/theme/russell) using the [OS UI Light Mode](https://support.google.com/android/answer/9730472?hl=en)
2. Create a post and type text into a paragraph block
3. Observe that text is white and matches background
4. Switch to Dark Mode
5. Observe that Editor remains in Light Mode, while the rest of the UI switches to Dark Mode

**Expected behavior**
Editor should display light/dark mode colors correctly in Android (compare against iOS functionality for correct behavior). 

**Screenshots**
<table>
<tr>
<td>
<video src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/4ef7ce4e-f43c-496e-92a3-141dd6dac6e9" />
</td>
<td>
<img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/37cbbf54-bf5e-425e-9c43-db39c1b4ecc7" />
</td>
</tr>
</table>

**Smartphone (please complete the following information):**
 - Device: Tested on a Samsung Galaxy S20 FE
 - OS: Android 16
 - Version 23.7

**Comment by dcalhoun** [comment]
👋🏻 @geriux I _think_ I may still be encountering this issue with the Geologist theme with Jetpack iOS 23.9.0.1. Would you be willing to see if this issue occurs for you as well? 

1. Disable dark mode. 
2. Enable the Geologist theme. 
3. Launch the editor. 
4. ⚠️ An unexpected, illegible black text is rendered atop a dark theme background color for the editor canvas. 

<details><summary>Screenshot</summary>

![Unexpected, illegible black text is rendered atop a dark theme background color for the editor canvas](https://github.com/wordpress-mobile/gutenberg-mobile/assets/438664/3df83023-db64-4b0d-a333-8f133513b168)

</details>
