### ISSUE TITLE
Quickly toggling network connection can result in paused uploads which may not be retried

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/gutenberg-mobile#6511]
As referenced in p1704467407176419-slack-C063XEQAM8X, it is possible to have paused uploads that one cannot retry. 

## Steps to Reproduce

1. Disable network connectivity. 
2. Add media blocks and attach media. 
3. Toggle network connectivity on and off every 1–2 seconds for a few times. 

## Expected Outcome
Any paused media will retry once a network connection is available — either automatically or when manually selected by tapping the media. 

## Actual Outcome
It is possible for paused media to no longer be able to retry — both automatically or manually.

**Comment by dcalhoun** [comment]
Once you find yourself in this unexpected state, the inability to retry a given media appears to happen for both automatic and manual (tapping an image) retries.

They share [logic for initiating a retry](https://github.com/wordpress-mobile/WordPress-iOS/blob/45df974b617176157830d78dae4df217364ed5ba/WordPress/Classes/Services/MediaCoordinator.swift#L64-L75), so maybe there is a bug or improper usage of `automatedRetry`.

Alternatively, we may need to hunt down where a race condition occurs.

**Comment by dcalhoun** [comment]
Possibly only tangentially related: I noticed that, after attempting to "Preview" a post in this state, the post may display the local thumbnail. It will, unsurprisingly, be empty in the preview. Tapping the problematic image can also open an empty "Media Options" Action Sheet. 

It is possible that this experience is achievable in the latest release already, and the automatic retries merely make it more reproducible. 

<details><summary>Screen recording</summary>

https://github.com/wordpress-mobile/gutenberg-mobile/assets/438664/7928ed9e-2d94-4ccf-b7a9-c919549e6128

</details>

<details><summary>Screenshots</summary>

<img width="200" style="float: left; margin-right: 1rem;" alt="empty image element within gallery" src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/438664/d7d98c80-936e-4544-a05d-dc3330ca1e88" />
<img width="200" style="float: left; margin-right: 1rem;" alt="empty media options" src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/438664/bd90a3ab-a312-4a2d-88ad-3e303ed8db24" />
<img width="200" style="float: left; margin-right: 1rem;" alt="unexpected local src" src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/438664/85dfef1e-22e6-4caf-994d-da152da7039d" />

</details>

**Comment by derekblank** [comment]
> They share [logic for initiating a retry](https://github.com/wordpress-mobile/WordPress-iOS/blob/45df974b617176157830d78dae4df217364ed5ba/WordPress/Classes/Services/MediaCoordinator.swift#L64-L75), so maybe there is a bug or improper usage of automatedRetry.

@dcalhoun I logged out the values of [this conditional block](https://github.com/wordpress-mobile/WordPress-iOS/blob/7b65cbcf32675f1697b79748015b02a6ac516367/WordPress/Classes/Services/MediaCoordinator.swift#L67-L71) in MediaCordinator.swift when uploading media offline, and it does seem that the race condition lies within `automatedRetry`.

When uploading media, and connecting/reconnecting somewhat rapidly (2 - 3 seconds between switches), this is the output of the logged values:

```
Automated Retry: 5 media objects to upload
Automated Retry: 0 media objects to upload
Automated Retry: 5 media objects to upload
Automated Retry: 5 media objects to upload
Automated Retry: 5 media objects to upload
Automated Retry: 0 media objects to upload
Automated Retry: 5 media objects to upload
Automated Retry: 0 media objects to upload
```

In this case, I was attempting to upload a Gallery with five Images. The number of media objects to retry oscillates between `5` and `0`, before eventually settling on `0` for good. It's worth noting that the `automatedRetry` condition is always invoked -- I did not observe a value logged from the `else` statement (i.e., `Failed media: ...` in this debugging patch):

<details>
<summary>Debugging patch</summary>

```diff
diff --git a/WordPress/Classes/Services/MediaCoordinator.swift b/WordPress/Classes/Services/MediaCoordinator.swift
index 849d2e1308..b073d27802 100644
--- a/WordPress/Classes/Services/MediaCoordinator.swift
+++ b/WordPress/Classes/Services/MediaCoordinator.swift
@@ -66,8 +66,10 @@ class MediaCoordinator: NSObject {
 
         if automatedRetry {
             mediasToUpload = Media.failedForUpload(in: post, automatedRetry: automatedRetry)
+             print("Automated Retry: \(mediasToUpload.count) media objects to upload")
         } else {
             mediasToUpload = failedMedia
+            print("Failed media: \(mediasToUpload.count) media objects to upload")
         }
 
         mediasToUpload.forEach { mediaObject in
```
</details>

Possibly the oscillating values for `mediasToUpload` may have to do with [this line](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/Services/MediaCoordinator.swift#L64), where they are being filtered by `remoteStatus == .failed`:

```
let failedMedia: [Media] = post.media.filter({ $0.remoteStatus == .failed })
```

It appears that "paused" uploads are still considered `.failed` remotely, while the "local" Gutenberg status is `.paused`. See [syncUploads](https://github.com/wordpress-mobile/WordPress-iOS/blob/79e311c045afe84b3ebd9c6861fe06c47a80f48e/WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift#L89-L97) for an example:

```
func syncUploads() {
    for media in post.media {
        if media.remoteStatus == .failed {
            gutenberg.mediaUploadUpdate(id: media.gutenbergUploadID, state: .uploading, progress: 0, url: media.absoluteThumbnailLocalURL, serverID: nil)
            let finalState: Gutenberg.MediaUploadState = ReachabilityUtils.isInternetReachable() ? .failed : .paused
            gutenberg.mediaUploadUpdate(id: media.gutenbergUploadID, state: finalState, progress: 0, url: nil, serverID: nil)
        }
    }
}
```

This is just a hypothesis, but perhaps we need to move this conditional (and any others like it) more upstream to be a true discrete `paused` status. I looked into the `remoteStatus` and `automatedRetry` logic and it seems fairly complex in terms of its surface area, so I think adding a fully discrete `.paused` status here is out-of-scope. 

Perhaps we could instead focus on the `automatedRetry` filter code to exclude `failedMedia` that have been marked paused. Possibly, something like this (where `gutenbergUploadStatus` is very much a psuedocode placeholder):

```
let failedMedia: [Media] = post.media.filter({
    $0.remoteStatus == .failed && $0.gutenbergUploadStatus != "paused"
})
```

At the moment, I believe this conflict between failed and paused is the race condition, but I encourage you to pursue other leads if you have further hunches. Neither of these potential solutions seem very appealing, and full caveat for the above: this may not actually be where the race condition occurs, just the result of my initial findings. I'll continue investigating, and capture any other areas where `automatedRetry` code may be modifying media to retry.

**Comment by derekblank** [comment]
Just noting some other areas to investigate where the race condition may be occurring:

- [`failedForUpload`](https://github.com/wordpress-mobile/WordPress-iOS/blob/7b65cbcf32675f1697b79748015b02a6ac516367/WordPress/Classes/Extensions/Media%2BBlog.swift#L71-L76)
- [`failedMediaForUpload`](https://github.com/wordpress-mobile/WordPress-iOS/blob/7b65cbcf32675f1697b79748015b02a6ac516367/WordPress/Classes/Extensions/Media%2BSync.swift#L12-L26)
- Any other instances of [`automatedRetry`](https://github.com/search?q=repo%3Awordpress-mobile%2FWordPress-iOS%20automatedRetry&type=code) where the `[Media]` model is being modified. 😓
