### ISSUE TITLE
Add whitespace to bottom of canvas

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#656]
It feels a little cramped at the end of the post (after the last block). Let's add a slight bit of margin at the end of the canvas to afford a little breathing room. We can try 24px as a start to see how that looks/feels.

**Comment by SergioEstevao** [comment]
This looks solved on the latest version, can you double check @iamthomasbishop

**Comment by iamthomasbishop** [comment]
> This looks solved on the latest version

@SergioEstevao That's correct, I think this was solved when we added the "invisible empty block" at the end of the canvas.
