### ISSUE TITLE
Image placeholder moves out of its bounds once we tap on it

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#661]
**Steps to reproduce**

Open a post that has at least 1 image block
See that there's a placeholder in the image block until it's downloaded
Tap to the placeholder
It moves out of its bounds

![img_0237](https://user-images.githubusercontent.com/5032900/53261388-ec839300-36e4-11e9-91c8-6f7201e887b6.PNG)

**Comment by marecar3** [comment]
https://github.com/WordPress/gutenberg/pull/14066

**Comment by hypest** [comment]
Fixed with #663
