### ISSUE TITLE
Error in image block for one of the "About" page templates

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#6610]
**Describe the bug**

After selecting one of the "About" page templates when creating a new page, there is an error visible in the image block.

**To Reproduce**
1. In the Jetpack app, tap the + icon in the lower right and select the option to add a new page.
2. From the list of available layout options, choose the **About** layout with the circular image at the top.
3. View the layout in the editor.

**Expected behavior**

I expected all elements of the layout to be visible, with no errors.

**Actual behavior**

The image block displays a "Problem displaying block" error.

**Screenshots**

<img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/2998162/dc6fc9b1-6622-4db4-85a8-780fcbf6b8c0" width="50%" />

**Smartphone (please complete the following information):**
 - Device: Pixel 6 / iPhone XR
 - OS: Android 14 / iOS 17.3 
 - Version 24.2

**Additional context**

The error is not a regression in 24.2, I tested on an older version (23.9) and confirmed it's reproducible there.

**Comment by tiagomar** [comment]
Just that Tapping to recover works on both platforms.

Original HTML:
```
<!-- wp:image {"width":150,"height":150,"sizeSlug":"medium","linkDestination":"none","align":"center","className":"is-style-rounded"} -->
<figure class="wp-block-image aligncenter size-medium is-resized is-style-rounded"><img src="https://dotcompatterns.files.wordpress.com/2021/02/pexels-photo-1674752-e1611678857421.jpeg?w=300" alt="" style="width:150px;height:150px"/></figure>
```

Recovered HTML:
```
<!-- wp:image {"sizeSlug":"medium","linkDestination":"none","align":"center","className":"is-resized is-style-rounded"} -->
<figure class="wp-block-image aligncenter size-medium is-resized is-style-rounded"><img src="https://dotcompatterns.files.wordpress.com/2021/02/pexels-photo-1674752-e1611678857421.jpeg?w=300" alt=""/></figure>
```

The recovered block seems to have just removed `width` and `height`, would that indicate a template issue?

**Comment by SiobhyB** [comment]
@tiagomar, thank you for digging in! Yes, we'd just need to update the original markup that's being used. I've noted here that I'll plan to look into this tomorrow morning, if no one beats me to it: p1707242684329719/1707242406.209419-slack-C06G6C1P70R

**Comment by SiobhyB** [comment]
This has now been fixed for both platforms.
