### ISSUE TITLE
[Android] Paragraph placeholder half-visible before block stabilizes

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#666]
The paragraph (and heading and post-title) blocks are too short before the block stabilizes its height, making the placeholder look half-cut.

See the glitch (thanks @marecar3 for capturing a video of the bug):
![late_measure](https://user-images.githubusercontent.com/1032913/53292869-46ae5200-37d2-11e9-9ebb-045df207c453.gif)

**Comment by marecar3** [comment]
Update: Tested` gutenberg-mobile` **v1.1.1** against `WPAndroid` and we still have some problems with Heading block.

![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/28219092/54844387-2d070a00-4cad-11e9-8578-bff952b984aa.gif)

**Comment by marecar3** [comment]
I think that we have solved this problem, so I will close this issue.
