### ISSUE TITLE
Support HTML anchors

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#6674]
**Is your feature request related to a problem? Please describe.**
Several core blocks support HTML anchor, which can be edited on the web but not in the mobile native version. 

**Describe the solution you'd like**
Following the web implementation, display the block setting in the blocks that support it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fluiddot** [comment]
**User report:** p1708754889891169-slack-C06AJCED8EN

**Comment by dcalhoun** [comment]
This seems to relate to and might duplicate https://github.com/WordPress/gutenberg/issues/28363.

**Comment by fluiddot** [comment]
> This seems to relate to and might duplicate https://github.com/WordPress/gutenberg/issues/28363.

Ah true, I'll close it and mark it as duplicate. Thanks @dcalhoun for the call out 🙇 !
