### ISSUE TITLE
App becomes unresponsive when loading large posts

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#672]
Steps to reproduce:

1. Create a Gutenberg post on the web with Gutenberg demo content using a variety of blocks.
1. Add about 10,000 words.
1. Try to open the post in Gutenberg in the app.
1. If you can open the post, try scrolling.
1. If the post gets closed, re-open and try scrolling again.
1. If you can open the post and scroll, then try editing any block.

<strong>Result:</strong> triggered the ANR dialog trying to open the post in Gutenberg in the app.

/hat tip @rachelmcr for the original report at https://github.com/wordpress-mobile/WordPress-Android/issues/8628.

(internal ref: p4a5px-2iV-p2)

I tested and confirmed with Pixel 3, Android 9, WPAndroid alpha-153 (11.9 alpha) using a self-hosted site running WP 5.1 and Gutenberg 5.1.1.

<img src="https://user-images.githubusercontent.com/1119271/53361916-27104a00-38f6-11e9-917d-651d2a8759d5.png" width="270" alt="screenshot_20190225-120818">

**Comment by designsimply** [comment]
Noting that I also tested with WP Internal 11.9.0.20190226 on iPad Mini 4 (WiFi) (iPad5,1) iOS 12.1.4 and I was able to open and edit the same large post (10000+ words plus several types of blocks) without the iOS app crashing but the delay is very long and there's not spinner or indicator that you can't interact with the app while it's loading or updating so it seems like the app becomes stuck but it's really just taking a long time to process the post. ([2m59s](https://cloudup.com/cSmPnG2zyFd))

I don't think an extra issue is needed for this, but if you'd like to see one created just let me know!

**Comment by hypest** [comment]
Thanks for reporting the iOS side case too @designsimply ! I might actually be a different issue but, let's keep things simple for now and investigate first before opening a different ticket. @SergioEstevao , will you be able to have a look and investigate what's the main culprit for the long opening time on iOS? Let's try to find out if the delay lies in the native side (before the RN editor starts) or inside the RN code, cool?

**Comment by SergioEstevao** [comment]
@designsimply can you link to the original sample content, for us to copy/paste? We probably can build a unit test around this.

Another question did you try to open the same post using our current Aztec editor?

**Comment by hypest** [comment]
> can you link to the original sample content

If I remember correctly from a past convo with @rachelmcr , I recreated such a post by copy pasting the Gutenberg demo content on a site of mine. Here's the one I use @SergioEstevao : https://stefanosuser.wordpress.com/2019/01/07/long-demo-post/

**Comment by designsimply** [comment]
<blockquote>@designsimply can you link to the original sample content, for us to copy/paste? We probably can build a unit test around this.</blockquote>

I used two sources of sample content combined to one post:

1. [Gutenberg Demo Post](https://github.com/dmsnell/gutenberg-document-library/blob/master/library/demo-post.html)
1. [Lipsum generator](https://www.lipsum.com/) (enter `10000`, select "words", click Generate Lorem Ipsum)

There are also two real-world sample posts that were used during performance testing in Gutenberg that you might consider as well:

1. https://github.com/WordPress/gutenberg/issues/11782#issuecomment-438213916
1. https://github.com/WordPress/gutenberg/issues/10418#issuecomment-436431030

<blockquote>Another question did you try to open the same post using our current Aztec editor?</blockquote>

I did! And I didn't have any stability problems with Aztec.

**Comment by designsimply** [comment]
@SergioEstevao @hypest I just tested again with WPAndroid alpha-155 (11.9 alpha) and a crash did not happen again for the demo + lorem ipsum content but crashes keep happening when I try with this sample content: https://gist.github.com/florianbrinkmann/4e9e4d23eaefb8b23484badddd848196

**Comment by hypest** [comment]
https://github.com/wordpress-mobile/WordPress-Android/pull/9370 got merged and that one should help start the editor faster than before. The editor will still take some time to fully parse and render the post but, the android app won't be unresponsive at least.

**Comment by hypest** [comment]
App no longer becomes unresponsive per se. Large posts can still impose a delay until the post is rendered and editable, but that'd be a different issue. Let's close this issue and perhaps open a different one if the delay is still a problem. WDYT @designsimply ?

**Comment by SergioEstevao** [comment]
For reference, I uploaded the content that @designsimply used to one of my websites using the browser, and even on the laptop the browser struggled to open the post, and even after the post was open, it was very slow to type.
So there is an underlying problem with Gutenberg performance on long posts.

**Comment by hypest** [comment]
Good point sharing that experience @SergioEstevao . Can you get in touch with @youknowriad too to perhaps report it to the Gutenberg repo too? Thanks in advance!

**Comment by designsimply** [comment]
Related: https://github.com/WordPress/gutenberg/issues/11782 and https://github.com/WordPress/gutenberg/issues/14079

I think we can close this in favor of https://github.com/WordPress/gutenberg/issues/14079 since you have made an update in https://github.com/wordpress-mobile/WordPress-Android/pull/9370 and you have also identified that it is an underlying problem with Gutenberg itself. Thank you for looking into this since Gutenberg Mobile is launching this month as an opt-in for the first time.
