### ISSUE TITLE
Block Editor: autocomplete eating last character

### ISSUE THREAD

**Issue by folletto** [wordpress-mobile/gutenberg-mobile#674]
This is a very odd bug, but might point at some issue somewhere else so might make sense of reporting it. 

1. Create a new post with the block editor
2. Focus on the existing first paragraph block
3. Start tapping the autocomplete words in sequence (which means: don't type, just fill out using the autocomplete feature).

You'll notice that every 2 words the space is eaten. 

For example this is what I get:

> Strawberrymango rollsare amazingand thefood isgreat

There's a related bug: if a word is autocompleted, then a character is added, it eats the last letter. For example:

1. Type "banan"
2. Tap "banana" to autocomplete
3. Tap "." to add a full stop
4. It deletes the final letter: "banan."

**Comment by koke** [comment]
Related to #603, looks like the same issue

**Comment by folletto** [comment]
Yes. Closing this one.
