### ISSUE TITLE
Link: After adding link, cursor moves to start of linked text

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#679]
When I add a link, I expect the cursor to be placed at the end of the linked text. Instead, it's placed at the start of the linked text.

This is especially disruptive when I'm adding a link while typing (as opposed to adding links to text I've finished writing), since I have to tap to move the cursor to the end to continue typing.

To reproduce:

1. Add a paragraph block.
2. Tap the link icon in the toolbar.
3. Enter a URL and link text.
4. Close the link sheet.

Observed in Gutenberg on both WPiOS and WPAndroid:

![2019-02-27 14 59 10](https://user-images.githubusercontent.com/8658164/53504437-dfcaba80-3aa9-11e9-86b4-4ccabe712ee2.png)

**Comment by designsimply** [comment]
Noting https://github.com/WordPress/gutenberg/issues/7980 because it's a relevant discussion about what to do with the caret after a link is inserted on the web side.
