### ISSUE TITLE
Proposal: Autofill link URL field with link in clipboard

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#680]
I'd like to propose that when adding a link, Gutenberg autofill the link URL field with the clipboard contents when the clipboard contains a URL. (This is a feature of Aztec that I really appreciate.)

The user flow is to open the browser or other app, copy a URL, and insert it as a link in the editor. Autofilling the link URL field means the user does not have to deal with long tap and paste actions to insert the URL — it "magically" appears in the link sheet when they create the link.

**Comment by SergioEstevao** [comment]
@rachelmcr I know is not exactly the same thing, but do you know if you copy a link and then paste it over a text selection the link will be applied to the text?

**Comment by rachelmcr** [comment]
Ah, I didn't know that worked! I just tried it and it works very nicely — but even though I do that action all the time on the web I didn't expect it on mobile, so it seems hard to discover.
