### ISSUE TITLE
Youtube block (Embeds)

### ISSUE THREAD

**Issue by Tug** [wordpress-mobile/gutenberg-mobile#682]
We can implement a Youtube block using an Embed

**Comment by chipsnyder** [comment]
@mchowning @hypest Should we move this to the `Mobile Gutenberg` board since I think the embeds project is being taken care of by one of your teams.

**Comment by ceyhun** [comment]
Closing in favor of https://github.com/wordpress-mobile/gutenberg-mobile/issues/3278 and https://github.com/wordpress-mobile/gutenberg-mobile/issues/3276
