### ISSUE TITLE
'RNTAztecView/RNTAztecView.h' file not found

### ISSUE THREAD

**Issue by IslamRustam** [wordpress-mobile/gutenberg-mobile#6825]
**Describe the bug**
Launching project in xcode fails due to 'RNTAztecView/RNTAztecView.h' file not found, Could not build Objective-C module 'RNTAztecView'

**To Reproduce**
1. Install @wordpress/react-native-aztec, @wordpress/react-native-bridge
2. Run app in XCode

**Expected behavior**
App should launch without errors

**Screenshots**
<img width="753" alt="Screenshot 2024-04-23 at 14 03 38" src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/71266873/b562ef88-0ede-45d6-9833-83793c0ac6e7">

**Smartphone (please complete the following information):**
 iOS Emulator

**Additional context**
I'm trying to embed aztec text input into my application, not running it in gutenberg-mobile

**Comment by geriux** [comment]
Hey there 👋 

>I'm trying to embed aztec text input into my application, not running it in gutenberg-mobile

If you wish to use Aztec in a Text Input, you should use [AztecEditor-iOS](https://github.com/wordpress-mobile/AztecEditor-iOS) directly.

Let us know if that addresses your issue. Thanks!
