### ISSUE TITLE
Spacer block

### ISSUE THREAD

**Issue by Tug** [wordpress-mobile/gutenberg-mobile#684]
Add support for the spacer block.

Experiment for cross-platform.

**Comment by hypest** [comment]
Note to selves: We will use the Spacer block as the testbed to develop better-than-today's solutions for doing styling and layout.

**Comment by iamthomasbishop** [comment]
This work will obviously need to be done to offer baseline support for a Spacer block, but I also just made a proposal (#998) for bringing Spacer capabilities to the Separator block which would essentially make the Spacer block a very limited version of the Separator block.

**Comment by pinarol** [comment]
I am closing this one to avoid confusion about Separator & Spacer dependency. We have a new issue to add the Spacer block: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1428
