### ISSUE TITLE
Gallery block

### ISSUE THREAD

**Issue by Tug** [wordpress-mobile/gutenberg-mobile#685]
Add support for the gallery block

**Comment by thehenrybyrd** [comment]
Great to see this! 
Galleries are definitely a popular request, so I'm excited to see we're thinking about implementing them in Mobile Gutenberg.

**Comment by thehenrybyrd** [comment]
Had another request for this today in #2026434-z
Also wanted to loop in our iOS issue to show previous requests: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/938

**Comment by thehenrybyrd** [comment]
Two iOS reviews mentioned wanting galleries today, so wanted to make sure those are noted here.

**Comment by SiobhyB** [comment]
We had a request for galleries in 13995631-hc. The user was pretty dismayed at the fact the option's missing from the app.

**Comment by thehenrybyrd** [comment]
Another request in #2212017-zen.

**Comment by rachelmcr** [comment]
I know this is on the roadmap but wanted to note that a beta tester (using WPAndroid 13.7-rc-1) just requested the gallery block.

**Comment by mkevins** [comment]
FYI there is some ongoing work on this being tracked here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1416

**Comment by mkevins** [comment]
:tada: Implemented and closed with: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1416
