### ISSUE TITLE
Video block

### ISSUE THREAD

**Issue by Tug** [wordpress-mobile/gutenberg-mobile#687]
Add support for Video block

**Comment by pinarol** [comment]
TO DO:

- [ ] (First iteration)Make a basic video block that can upload & show media (from WP media library)
- [ ] Add unit-tests for touched areas( both image and vide block )
- [ ] Add support for Video settings
- [ ] Enhance video block to show videos with better aspect ratio rather than a fixed one
- [ ] Try and look for ways to make it cross platform

**Comment by pinarol** [comment]
**Note about video playing differences between platforms**

We have limitations on react-native-video level. Having control buttons(like play, pause etc) in the video block are messing up the layout on iOS, so I had to hide them and add our own play button which opens the video on full page. Once the video opens full page then there's no problem about control buttons. A bit of a technical insight: I think this is the line responsible for it, they are setting the frame (as a workaround for some issue) when controls=true
https://github.com/react-native-community/react-native-video/blob/c30f246f5694452f4f081ff30ac4523dfd89f41d/ios/Video/RCTVideo.m#L593
And by doing that they are messing up the y position of our page. 

On the other hand on Android the full page preview just doesn’t work, the method call does nothing. But control buttons do work correctly. The video can play inline.

So now, we have different user experiences in both platforms in terms of video playing. If we want to make this equal in the future we'll need to either solve one of this: 

1. Android the full page preview doesn’t work
2. iOS controls=true messing up the layout

**Comment by hypest** [comment]
The block has been released for both platforms. Closing this.
