### ISSUE TITLE
Audio block

### ISSUE THREAD

**Issue by Tug** [wordpress-mobile/gutenberg-mobile#688]
Add support for Audio block

**Comment by thehenrybyrd** [comment]
I talked to a user this morning who's planning to podcast from the WPiOS ap. I know we're adding blocks as we go and this one will arrive in time, but I wanted to drop a note to say we're looking forward to it! :)

**Comment by annacmc** [comment]
Had a user who wants to upload Voice Recording audio from the WPiOS app. Dropping a note in here to add support for it!  (int ref #2538352-zd)

**Comment by designsimply** [comment]
The inability to upload audio was noted recently in an app review:

> One thing that WP needs is a good uploader, compared to YouTube, Google, etc, it is very hard to upload things on the website using a slow internet connection. Any little drop out and the whole upload fail. An app like this could help but I just discovered that audio can't be uploaded from the app.
> 
> <sup>2-star app review by Tom Richards - 6/11, 4:38 AM - WP Android 13.8 Samsung Galaxy Note8 Android 9</sup>

**Comment by reginabally** [comment]
Another request in a WPiOS app review:

> For the podcasters on wordpress, the Audio in the Add Media editing block is a must.

**Comment by reginabally** [comment]
> I hope that the block editor can support more web version blocks, such as audio blocks.

Date of app review: Oct 11, 2020, 10:02
Device: Huawei 华为畅享8e
App version: WPAndroid
App version code: 933
App version name: 15.9-rc-2

**Comment by jd-alexander** [comment]
I will be closing this issue since the Audio block has been built and shipped.
