### ISSUE TITLE
[iOS]Caret goes to a wrong place when tapped to space

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#693]
This issue occurs when we tap space while caret has a space on left of it:

![caret-position-on-space](https://user-images.githubusercontent.com/5032900/53580815-b333a300-3b7c-11e9-99b8-179b7ee2f583.gif)

**Comment by etoledom** [comment]
Fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/694
