### ISSUE TITLE
Placeholder is missing on Heading block

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#707]
In order to fix an issue https://github.com/wordpress-mobile/gutenberg-mobile/issues/627 .
We have intentionally created an issue with missing placeholder on heading block.

This issue is created because we need the heading block to start with the `<h>` tag, but when that happens then Aztec loses its placeholder.

**Comment by hypest** [comment]
We will need to come up with a robust sollution for this one this time. Most probably a solution that will make Aztec more flexible on how it determines when/how to show the placeholder.

**Comment by koke** [comment]
Also we should prioritize this before block work, since I believe this will break in a similar way on any non-paragraph text block

**Comment by marecar3** [comment]
Fixed in this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/739
