### ISSUE TITLE
Introduce a Logger to send logs to parent apps

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#710]
Let's come up with a logging mechanism to use inside the RN app.

So far, we're using `console.log()` statements to print out messages to the JS debugger (if attached) or the parent app's ReactNative logging mechanism. While useful while developing locally, we'd ideally want to mimic what the main WP apps do and be able to log messages that are persistent across app runs and are even pushed online to services that we can inspect remotely.

The main apps already have a logging mechanism in place (Crashlytics/Fabric) so, it makes sense to try and wire up to that.

**Comment by hotchemi** [comment]
Update: base PR(https://github.com/wordpress-mobile/gutenberg-mobile/pull/746) is merged and remaining task is to fix wp-iOS to address API interface change.
ref: https://github.com/wordpress-mobile/gutenberg-mobile/pull/746#issuecomment-478108948

**Comment by hotchemi** [comment]
I suppose this issue is ready to close 🙇

**Comment by hypest** [comment]
Completed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/746 and https://github.com/wordpress-mobile/WordPress-iOS/pull/11380.
