### ISSUE TITLE
[Android] Lag when saving long posts in the HTML mode

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#713]
Originally reported [here](https://github.com/wordpress-mobile/WordPress-Android/pull/9370#issuecomment-470355885).

There is a brief moment in which the HTML editor seems to be hanging there, unresponsive. To reproduce:

1. Use the content in (it's basically the demo Gutenberg content pasted several times) https://selfhostedmario.mystagingwebsite.com/2019/03/welcome-to-the-gutenberg-editor/
2. open in Gutenberg in wpandroid
3. tap on the overflow menu icon and choose HTML mode
4. modify the content (don't break any blocks, for example just add some text within the pre-existing text in some paragraph block)
4. tap UPDATE or, tap BACK after modifying 
5. observe the lag.

**Comment by designsimply** [comment]
Adding some links to sample data which can be used for testing large posts:

1. [Gutenberg Demo Post](https://github.com/dmsnell/gutenberg-document-library/blob/master/library/demo-post.html)
1. [Lipsum generator](https://www.lipsum.com/) (enter `10000`, select "words", click Generate Lorem Ipsum)
1. https://github.com/WordPress/gutenberg/issues/11782#issuecomment-438213916
1. https://github.com/WordPress/gutenberg/issues/10418#issuecomment-436431030
