### ISSUE TITLE
Lag when switching between block and classic editor on long posts

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#714]
Originally reported [here](https://github.com/wordpress-mobile/WordPress-Android/pull/9370#issuecomment-470355885).

Switching to Classic editor makes the app hang (ANR) for a bit until everything is loaded and then it works alright (scrolling fast and all) but you do have to wait a fair 10-15 seconds for the thing to be responsive. It hangs, goes black for a second, appears (but you can't scroll or anything) and have to wait.

Here's the Post used (it's basically the demo Gutenberg content pasted several times) https://selfhostedmario.mystagingwebsite.com/2019/03/welcome-to-the-gutenberg-editor/

For the record, using the content mentioned here [wordpress-mobile/gutenberg-mobile#672](https://github.com/wordpress-mobile/gutenberg-mobile/issues/672#issuecomment-469740405) on Aztec makes it take a long time to load and be responsive, same as with the aforementioned Gutenberg post when switching and opening it on the Classic Editor.

On Aztec, switching to HTML mode and trying to add / modify text there is super slow.

**Comment by designsimply** [comment]
Adding some links to sample data which can be used for testing large posts:

1. [Gutenberg Demo Post](https://github.com/dmsnell/gutenberg-document-library/blob/master/library/demo-post.html)
1. [Lipsum generator](https://www.lipsum.com/) (enter `10000`, select "words", click Generate Lorem Ipsum)
1. https://github.com/WordPress/gutenberg/issues/11782#issuecomment-438213916
1. https://github.com/WordPress/gutenberg/issues/10418#issuecomment-436431030

**Comment by drspaceboo** [comment]
Looking into this issue in WordPress-Android I have found that the majority of the time taken when switching to the "classic editor" is caused by Aztec. I have logged an [extensive issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/800) in that repository highlighting some areas to look into for performance improvements.

I would advise closing this issue as it doesn't look like this is primarily related to Gutenberg-mobile.

**Comment by hypest** [comment]
👋 @drspaceboo , thanks for diving into this one! Reason this ticket was originally created here was for better tracking within [the gutenberg-mobile GitHub project](https://github.com/wordpress-mobile/gutenberg-mobile/projects/1) and because it refers to the whole flow of switching editors on the fly. Switching editors on the fly encompasses another slow process (the saving of data) and perhaps more reasons so, I'd recommend we keep this ticket open anyway. When we fix the Aztec slowness side we can update this ticket too. How's that sound?

**Comment by drspaceboo** [comment]
Makes sense to me 💯

**Comment by KokkieH** [comment]
We have a user report of this issue in https://en.forums.wordpress.com/topic/wordpress-android-app-3/

**Comment by hypest** [comment]
"Switch to classic" [has been removed](https://github.com/wordpress-mobile/WordPress-Android/pull/14334) for some time now so, closing this ticket. Happy to reopen if it still holds for some flow. Thank you all!
