### ISSUE TITLE
Pexels and Giphy search not available form image block

### ISSUE THREAD

**Issue by hlashbrooke** [wordpress-mobile/gutenberg-mobile#720]
I'm using the alpha-155 version of the Android app, but I doubt this is specific to any platform or version.

When setting a featured image on mobile you have the option to search the Pexels free photo library for an image (which is great), but that option isn't available when adding an image with the image block. I'm not sure if this is intentional or not.

Steps to reproduce:
1. Add an image block
2. Click the 'choose image' link
3. Notice the lack of an option for using the Pexels library

**Comment by koke** [comment]
As we do this, let's make sure we also bring in Giphy and the "Other apps" file picker on iOS

**Comment by frosty** [comment]
+1 from me – I was writing a post yesterday and missed the Other Apps option. I had to import the file in the Media Library section, and then hop back into the editor to pull it into the post.

**Comment by marecar3** [comment]
Added @etoledom on this one as we need iOS support when it's available.

**Comment by hypest** [comment]
Reopening since the iOS side of the implementation is still pending.

**Comment by designsimply** [comment]
From a 4-star review "Need help 4" by Buddah216 – Nov 5, 2019 Version 13.5

> Can we no longer access GIPHY’s through WordPress? I’m working on my blog post and noticed, that I no longer can add GIPHY’s.
