### ISSUE TITLE
Enter on Heading block creates another Heading block.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#734]
**Issue**: Pressing enter on a Heading block, it creates another Heading block.
**Expectation**: Pressing enter on a Heading block, should create a Paragraph block. Same as on any other "split-able block)

![heading](https://user-images.githubusercontent.com/9772967/54214591-cc2a4580-44e6-11e9-951f-cc5e3a72dda8.gif)

**Comment by Tug** [comment]
Related https://github.com/WordPress/gutenberg/pull/10382
