### ISSUE TITLE
Get aligned with web about caret position in case of transforming a text into link

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#737]
We already aligned ourselves with web about caret positioning after adding a link with this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/716

However there's a possibility that things can change for web also. There's an ongoing convo inside this issue and I am opening this one just to make sure we are getting aligned with that:  https://github.com/WordPress/gutenberg/issues/7980

Having said that, the only flow that might be affected is the flow where we transform an existing text into a link. So this is expected to be a small change.

**Comment by hypest** [comment]
This ticket is not currently worked on so, clearing the assignee field to denote that.

**Comment by jhnstn** [comment]
Closing since the issue being tracked in Gutenberg was resolved with no changes made https://github.com/WordPress/gutenberg/issues/7980#issuecomment-484122563
