### ISSUE TITLE
WPiOS: Bold and Italic is (sometimes) not rendered.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#738]
On WPiOS, when opening a new empty post with gutenberg, with the app just lunched, the bold and italic formatting is not rendered rendered.

This will break the Bold and Italic buttons on the Paragraph block, and will show the title and the heading blocks without bold.

I noticed that this issue "fixes itself" when a bold text is displayed in the UI, like in the posts list, reader or opening Aztec (as in the video).

[Video showing the problem](https://cloudup.com/cPgeNSea08s)

This issue has been difficult to reproduce. So far just me (@etoledom ) and @iamthomasbishop have been able to see it.

**Comment by koke** [comment]
I could reproduce this as well on the latest WP Internal (12.1.0.20190328)

**Comment by SergioEstevao** [comment]
I no longer can reproduce this on iOS so I'm closing this.
