### ISSUE TITLE
[iOS] Display Custom Taxonomies in Post Settings v12.0.0.1 beta

### ISSUE THREAD

**Issue by alextheberge** [wordpress-mobile/gutenberg-mobile#748]
I have a custom taxonomy on my self-hosted Wordpress site called "person" that shows up correctly in Gutenberg's panels in my site's back end as well as in the wordpress.com editor. 

Unfortunately it doesn't show up on the iOS 12.0.0.1 beta version. Am I missing a setting?

Here is the code: 
`
function person_taxonomy() {

	$labels = array(
		'name'                       => _x( 'People', 'Taxonomy General Name', 'text_domain' ),
		'singular_name'              => _x( 'Person', 'Taxonomy Singular Name', 'text_domain' ),
		'menu_name'                  => __( 'People', 'text_domain' ),
		'all_items'                  => __( 'All People', 'text_domain' ),
		'parent_item'                => __( 'Parent Item', 'text_domain' ),
		'parent_item_colon'          => __( 'Parent Item:', 'text_domain' ),
		'new_item_name'              => __( 'New Person Name', 'text_domain' ),
		'add_new_item'               => __( 'Add New Person', 'text_domain' ),
		'edit_item'                  => __( 'Edit Person', 'text_domain' ),
		'update_item'                => __( 'Update People', 'text_domain' ),
		'view_item'                  => __( 'View People', 'text_domain' ),
		'separate_items_with_commas' => __( 'Separate people with commas', 'text_domain' ),
		'add_or_remove_items'        => __( 'Add or remove people', 'text_domain' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'text_domain' ),
		'popular_items'              => __( 'Popular People', 'text_domain' ),
		'search_items'               => __( 'Search People', 'text_domain' ),
		'not_found'                  => __( 'Person Not Found', 'text_domain' ),
		'no_terms'                   => __( 'No People', 'text_domain' ),
		'items_list'                 => __( 'Person list', 'text_domain' ),
		'items_list_navigation'      => __( 'Items list navigation', 'text_domain' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => false,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
		'show_in_rest'				 => true, 
	);
	register_taxonomy( 'person', array( 'post', ' attachment' ), $args );

}
add_action( 'init', 'person_taxonomy', 0 );`

Any ideas why this isn't working on the iOS app's post settings?

Thank you,
-Alex

**Comment by hypest** [comment]
👋 @alextheberge , thanks for reaching out!

The mobile apps don't currently have support for custom taxonomies, and that's the reason they don't show up. We don't have any current plans to work on that so, can't offer some better insight on the matter.

Especially in this case of site settings, the work so far relied on just using whatever the host app (WPAndroid, WPiOS) is offerring, without adding any special support in the case of Gutenberg-mobile. We might start to look at what Gutenberg itself has to offer via its JavaScript implementation and adopt it down the road. We're just not there yet.

Sorry if this answer wasn't too helpful.

**Comment by rachelmcr** [comment]
For reference, we're tracking custom taxonomy support as an enhancement in the WordPress for iOS app in https://github.com/wordpress-mobile/WordPress-iOS/issues/6753 and in WordPress for Android in https://github.com/wordpress-mobile/WordPress-Android/issues/63.

**Comment by alextheberge** [comment]
Thank you for your response @hypest I just saw the previous inquiry from two years ago on this issue that @rachelmcr shared. I'm guessing that this is a _very_ difficult implementation if it's been this long with no addition of this feature. What this means for me, or anyone else using custom taxonomies, is the iOS app is great up to the point of drafting posts, but not publishing from the app. It's a shame one of the worlds most used CMS's doesn't have native support for custom taxonomies in their own app. The other custom implementations seem to work fine, eg. post types. I guess I don't understand why this isn't a priority. I'll keep an eye out in the meantime.

**Comment by hypest** [comment]
Closing this ticket since the feature is not actually related to the editor itself but to the post settings which are wrangled by the parent apps, and the related tickets have already been mentioned in https://github.com/wordpress-mobile/gutenberg-mobile/issues/748#issuecomment-473262864.
