### ISSUE TITLE
[Android] Unselected block has text field with active focus

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#749]
**Steps to reproduce:**

1. Open WPAndroid
2. Create a new post in it
3. Create Image block and pick some image
4. Create paragraph/heading block
5. Start writing in created block
6. With backspace remove all content from the block

**Actual result** -> Formatting toolbar buttons are missing and the text field is still in the focus
**Expected result** -> Formatting toolbar should be presented while the text field is in the focus

**Note:** I couldn't reproduce the same scenario on WPiOS

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/28219092/54385290-a29b2680-466c-11e9-830d-49d0c34e0e50.gif)

**Comment by daniloercoli** [comment]
I think this is a duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/345 and it should be fixed by this PR here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/733

**Comment by marecar3** [comment]
Hey @daniloercoli, yes you are right I have checked it's duplicated issue.
Closing this one.
