### ISSUE TITLE
[Android] HTML mode - Inertial scrolling is gone on the content text view

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#766]
Since https://github.com/wordpress-mobile/gutenberg-mobile/pull/755 the main content text view lost inertial scrolling feature. (Scroll momentum is gone).

To replicate the issue just open a long post (in `wp-android`, since HTML mode is not available in demo app), switch to HTML mode, and try to scroll the content. [Here](https://cloudup.com/c60oBwEiJ3B) is a video of the problem. 

This other video instead shows the old version of the app with inertial scrolling https://cloudup.com/ckcs33vd-BP

**Comment by pinarol** [comment]
Closing since there's a duplicate issue https://github.com/wordpress-mobile/gutenberg-mobile/issues/768
