### ISSUE TITLE
"Add new block" fails after first use

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#783]
The `+` button to add new block works once, but does not work on subsequent button presses. This issue was discovered on the Android Emulator, and has not been reproduced on a real device (attempts were made, but the issue was not encountered).

**Steps to reproduce:**
* Press the `+` button and choose new paragraph block
* Write some text
* Press the `+` button again and choose a new paragraph block

**Result:**
A new paragraph block is not created. The focus changes to an already existing block.

**Screenshot:**
<img src="https://user-images.githubusercontent.com/8507675/54969087-b463be80-4fc8-11e9-9dd8-a80df264217f.gif" width="360">

**Comment by mkevins** [comment]
After testing this issue further, I have discovered that the `+` button to create a new paragraph block fails when a Heading or Paragraph block is focused, but succeeds when a Page Break block or Code block is focused.

Also, it seems that using `+` to add either a Page Break block, or a Code block, succeeds, regardless of which block type had focus when tapping `+`.

Some other discoveries:
* If a heading block is created, with no text, and focus is changed to another block, the heading block remains. I'm not certain this is the desired behavior.
* When a Page Break block is created while a textual (Heading, Paragraph, or Code) block has focus, the Page Break block becomes the active block, but a (blinking) caret remains in the previously focused textual block, but the keyboard becomes hidden. I'm not certain this is the desired behavior, but if so, I think the keyboard should remain visible. Presently, it appears as though both blocks have focus simultaneously.

**Comment by mkevins** [comment]
The recent upgrade (React Native to 0.59, React to 16.8.3) seems to have a source map issue, which has made it difficult to use the JS remote debugger. I am temporarily resorting to a bisection method to try to isolate the changeset that may have introduced this issue. I will test this issue manually using the following steps:

1. Place the cursor at the end of the "**Hello World!" block
2. Press the `+` button and add a new Paragraph block
3. Observe success or failure
4. Mark hashes / tags below with a [*] for success, and [ ] for failure

**Progress:**
- [ ] 2f145b

**Comment by daniloercoli** [comment]
Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/857
