### ISSUE TITLE
Paragraph block is prematurely removed on backspace event

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#807]
When all text is deleted from a paragraph, the block is removed prematurely. This issue has been encountered on Android Emulator, but may not occur on a physical device.

**Steps to reproduce:**
* Place caret at the end of the "**Hello** World!" paragraph (after the '!')
* Press [backspace] 12 times

**Expected result:**
The (empty) paragraph block remains focused, with the placeholder text ("Start writing...") visible.

**Actual Result:**
The paragraph block is removed. The focus changes to the previous block.

This behavior is mentioned in #699, and may be related to #783.

**Screencast:**
<img src="https://user-images.githubusercontent.com/8507675/55461477-e1067e80-5637-11e9-9173-8120a86f2b7e.gif" width="360">

**Comment by koke** [comment]
I can confirm this happens on WPAndroid alpha-160

**Comment by koke** [comment]
I've seen a crash that seems related:

1. Create a new post
2. Tap the link button and enter some url and text
3. Close the link UI
4. Press backspace enough times to delete the whole link
5. Crash

I've seen it happen with other combinations of typing and links, but this were steps where I could reproduce consistently.

Tested on WPAndroid alpha-160

**Comment by marecar3** [comment]
Hey @mkevins, thanks for the feedback!

Behavior from this issue is fixed in this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/756 as part of this issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/699

I will add you as a reviewer in the PR so that you can check if everything is working alright.

**Comment by koke** [comment]
So is it fine to close this as a duplicate?

**Comment by marecar3** [comment]
Closing this one in favor of #699

**Comment by mkevins** [comment]
> Hey @mkevins, thanks for the feedback!
> 
> Behavior from this issue is fixed in this PR: #756 as part of this issue: #699
> 
> I will add you as a reviewer in the PR so that you can check if everything is working alright.

Thanks @marecar3 ! I wasn't 💯 sure if the two issues would be solved by the same PR, so I split out this issue. Glad that the PR solves both! I'll test it out.

**Comment by mkevins** [comment]
I just tested it (on the Android emulator), and it indeed solves the problem. Thank you!

**Comment by marecar3** [comment]
Thanks @mkevins !
