### ISSUE TITLE
Prettier not being used consistently

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#816]
The [README](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/README.md) states that this project uses prettier to enforce our code style, but if you run `yarn prettier` on the develop branch there are currently >30 files that are changed.

This seems like a problem because:
- We are not getting the benefits of a consistent code style across the project
- New developers to the project who run prettier as the README directs may think that all of the changes means there is an issue with their project setup.
- Developers will either (1) avoid running `yarn prettier` when they make changes because of the large number of unrelated style changes they will need to separate out from their intended changes or (2) will run `yarn prettier` and commit those changes, resulting in PRs that are very hard to review because of the unrelated style changes.

A few options come to mind for what we can do to handle this:

1. **Drop our usage of prettier.** I am not a fan of this because I think there is a lot of value in having a consistent code format that no one has to think about. With that said, this is the easiest solution to implement and would slightly simplify the project. Also, we **[just](https://github.com/wordpress-mobile/gutenberg-mobile/pull/7)** added prettier, we can't give up this soon! :-)
2. **Add a [git hook to the project that runs prettier automatically](https://prettier.io/docs/en/precommit.html).** I have worked on another project that has taken this approach and it has worked well. It does make me feel a bit weird when there is something that changes my code automatically, but I have not seen any issues with it since prettier seems to be a very solid tool.
3. **Have our CI reject PRs that are not 'pretty'.** This does the most to make sure that all committed code is pretty, but it will also add some friction to the development process. (push change -> build failed because you forgot prettier -> run prettier -> push prettier changes -> get PR comments, and repeat).

It appears that Option 3 was the intended path when prettier was added to the project by @maxme since one of the commit messages is "[Add style check command (to be used in travis)](https://github.com/wordpress-mobile/gutenberg-mobile/pull/7/commits/e439b3f48259c34c1e0b72eac2665d3f6cb3c8aa)". Maybe this decision was already made and we just need to update our build job on Travis. Of course, we could do both Options 2 & 3, so that prettier is automatically run and if you somehow manage to skip the git hook then Travis will catch it.

Once we've picked an option (assuming we don't pick Option 1), we also need to do a PR that just catches the project's code style up.

**Comment by hypest** [comment]
Related PR where we removed the automated formatting check: https://github.com/wordpress-mobile/gutenberg-mobile/pull/43

I'd actually be wonderful if we manage to re-enable Prettier checks!

**Comment by hypest** [comment]
Regarding which path/option to follow, I'd favor No3 (CI checks) and additionally encourage people to install a precommit (or prepush) git hook to run checks.

**Comment by mchowning** [comment]
@hypest In light of the migration to gutenberg (and the linting rules that come with it), and the fact that we haven't really been even using prettier in gutenberg-mobile, it seems like we may just want to drop our usage of prettier. What do you think?

**Comment by maxme** [comment]
+1000 for having automated style checking and eventually automated style formatting. In our case if we can't keep `prettier` due to style incompatibilities, we should adopt gutenberg style and use the same style/formatting tool in this repo.

**Comment by hypest** [comment]
> it seems like we may just want to drop our usage of prettier

Not sure what will be the benefit of dropping it @mchowning . Can you expand?

Also, it seems that as we speak lots of code that used to live in this repo has migrated to the Gutenberg repo (which is good) but we can't be sure yet that it will not grow back.

I'd prefer if we make the integration more robust and let it be, protecting any code changes that will happen here. Happy to change my mind on this!

**Comment by mchowning** [comment]
Thanks @hypest and @maxme !

>Not sure what will be the benefit of dropping it @mchowning . Can you expand?

My thinking was that because:

1. We haven't been enforcing prettier (and therefore we haven't been using it);
2. There are only 9 js files left in `mobile-gutenberg`'s src/ directory; and
3. We will be moving everything from gutenberg-mobile to gutenberg

it wasn't worth devoting effort to updating gutenberg-mobile to comply with prettier and updating our CI to start enforcing it. But, based on your response @hypest :

>it seems that as we speak lots of code that used to live in this repo has migrated to the Gutenberg repo (which is good) but we can't be sure yet that it will not grow back

it sounds like I was mistaken about #3 (moving everything to gutenberg). In light of that, it makes sense to update our CI to enforce prettier. I don't like this state where we have prettier set up and we say in the README that we use it but it's not generally being used and it's not enforced, so I'll look into getting this added to CI first thing after HACK week.
