### ISSUE TITLE
Links UI: Place the caret at the end of a link breaks the Link inserter UI once opened

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#817]
Originally reported [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/740#issuecomment-476664914).

**Issue**
Positioning the caret at the end of a link, and opening the Link Inserter UI, shows the `Link Text` field empty. Other fields are filled correctly.

Steps to repro:
- Add a link
- Move the caret at the end of the link
![Screen Shot 2019-03-26 at 15 11 27](https://user-images.githubusercontent.com/518232/55003922-905ca900-4fd9-11e9-9b66-f511348bc4b4.png)
- Tap the link Button again...(See `Link Text` is empty in the UI)
![device-2019-03-26-151146](https://user-images.githubusercontent.com/518232/55004062-d154bd80-4fd9-11e9-803a-8d7deb757245.png)

- Instead if you move the caret in the middle of the link, and open the link UI again, it has all the details filled in:
![device-2019-03-26-151207](https://user-images.githubusercontent.com/518232/55004151-fb0de480-4fd9-11e9-8ba4-caf8697318fc.png)

**Comment by jhnstn** [comment]
I'm unable to reproduce this specific behavior and the original report has been closed.
