### ISSUE TITLE
Formatting button can't be unchecked in some cases

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#834]
For https://github.com/wordpress-mobile/gutenberg-mobile/issues/823#issuecomment-480270751

Originally reported by @koke / @daniloercoli  in #823 

I have been able to reproduce here on a Pixel 2 with Android 8.1, videos below

- This one with Aztec `1.3.24` https://cloudup.com/cIbT5WVb8jx
- This other one with previous version (Aztec `1.3.23`) https://cloudup.com/ccmM4X67uuJ

(did these tests to make sure it was not due to introduction of [clickable URL spans PR ](https://github.com/wordpress-mobile/AztecEditor-Android/pull/793) which was the only difference from one version to the other)

Steps to reproduce:
1. start writing
2. activate bold, write more
3. activate italic, write more
4. activate strike through, write more
5. deactivate one of the buttons and write
6. eventually, the button will get highlighted again.
If it doesn't happen on the first block, it happened for me 100% of times on the second block at least.

**Comment by SergioEstevao** [comment]
I tested this with the latest version on develop, using a very slow device and it's no longer happening.
