### ISSUE TITLE
Editor crash when undoing at list end

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#836]
(First reported in https://github.com/wordpress-mobile/gutenberg-mobile/issues/208#issuecomment-480246421 by @mkevins)

Undoing the newly added list item produces a red-screen.

Steps to reproduce:

1. Add a new list block
2. Type in few chars in the first line item and hit Enter to start a new item
3. Type in some more chars
4. Hit the "Undo" toolbar button
5. 💥

![55630821-f0352a00-57f9-11e9-89e4-60885927ff2f](https://user-images.githubusercontent.com/1032913/55639418-016a4080-57d2-11e9-91d5-2bdc3680dfc5.gif)

**Comment by mchowning** [comment]
I believe this issue has recently been fixed. I was seeing this issue on Android before I merged in the latest today, but post-merge I am not able to recreate it anymore.

**Comment by hypest** [comment]
Indeed, I cannot reproduce it, at least on a29bec31. Closing this.
