### ISSUE TITLE
Pasting inline text into a link splits the link apart

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#839]
**Describe the bug**

When pasting text in the middle of a link, the link is split (pasted text is not part of the link).

This makes it impossible to quickly change the link text via copy/paste.

**Steps to reproduce**

1. Select some text and create a link.
2. Copy some small inline text.
3. Place cursor within the link and paste.

***Expected behavior:***

Pasted text becomes part of the link.

***Actual behavior:***

Pasted text is not part of the link, and the link is split in two pieces.

**Screenshot:**

<img src="https://user-images.githubusercontent.com/8507675/55695550-6903d400-59fc-11e9-9b50-8c974a8ac260.gif" width="360">

**Note:**

This issue was found in Gutenberg (https://github.com/WordPress/gutenberg/issues/11571) and already has a fix there: https://github.com/WordPress/gutenberg/pull/14815 . It may be possible to port some / all of the code changes in this PR to `packages/block-editor/src/components/rich-text/index.native.js` to fix the same issue on mobile.

**Comment by cameronvoell** [comment]
Fixed via https://github.com/WordPress/gutenberg/pull/14815 and https://github.com/WordPress/gutenberg/pull/19190. (See the video in https://github.com/WordPress/gutenberg/pull/19190)
