### ISSUE TITLE
[iOS] Editor becomes unusable after moving selection in paragraph block.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#843]
[Video showing the issue](https://cloudup.com/c1vWeZ-lAFx)
Tested on 12.2 (WP Internal)

Steps:
- Have a paragraph block with text.
- Double tap on a word to select it.
- Long tap until you can drag the selection.
  - If you are having troubles with this, try to select a longer word (or more words) so the selection is bigger, and long press in the center of the selection.
- Drag the selection anywhere else in the paragraph block.
- Release and behold.

**Comment by mkevins** [comment]
FWIW, I was not able to reproduce this on Android (emulator).

**Comment by etoledom** [comment]
Thank you @mkevins !
Android device also works fine (Tested on current WPAndroid Beta)
WPiOS v12.0 also works fine.
