### ISSUE TITLE
[Android] List Block Ordered list number indicators don't respect alignment 

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#846]
The prefix numbers in a long ordered list are not keeping their alignment and they jump around.

Note: doesn't seem to happen when using the virtual keyboard but does happen when using an external one (example: Vysor).

1. Do a long list (> 10 items in the list)
2. Try to add a new item at the end of the list
3. Notice that number indicators < 10 don't respect alignment until you type something in the item
![list-android](https://user-images.githubusercontent.com/518232/55627332-349ad880-57ae-11e9-8837-2bd7f76b459f.gif)

**Comment by hypest** [comment]
This is not too important to block today's cut so, moving it to the next milestone.

**Comment by hypest** [comment]
Moving to next milestone.

**Comment by koke** [comment]
Tested on WPAndroid 12.4-rc-3. I only see the glitch when going from 9 to 10 items, but not afterwards. Closing this unless someone else can reproduce
