### ISSUE TITLE
Video block (first iteration)

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#855]
Make a basic video block that can upload & insert media.

**Some technical subtasks**

- [x] Extract MediaUpload component from image block ( similar to what web has )
- [x] Extract MediaUploadProgress component from image block ( to be used by video block also )
- [x] Enhance MediaPlaceholder component to support different media types ( similar to what web has )
- [x] Add video block
- [x] Add a sample video block to Example app content

**Example App work**

- Integrate react-native-video library to example apps
   - [x] Android
   - [x] iOS

- Update example apps due to bridge changes and make it compile
   - [x] Android
   - [x] iOS

- Update example apps to mock media upload behavior
   - [ ] Android
   - [x] iOS

- Update example apps to mock media upload failed behavior
   - [ ] Android
   - [x] iOS (added listening to long press gesture to mock failure of upload)

- Update Example apps to mock video selection of WordPress media library ( just pass a valid video url when that option is selected )
   - [ ] Android
   - [x] iOS

**WPiOS and WPAndroid work**

- Integrate react-native-video library 
   - [x] WPAndroid
   - [x] WPiOS

- Update apps due to bridge changes and make it compile (new filter parameter)
   - [x] WPAndroid
   - [x] WPiOS

- Use the new `filter` parameter passed through bridge to filter down media shown to user from Device
   - [x] WPAndroid
   - [x] WPiOS

- Use the new `filter` parameter passed through bridge to filter down media shown to user from WordPress Media library
   - [x] WPAndroid
   - [x] WPiOS

- Use the new `filter` parameter passed through bridge to decide what type of media to capture if user selects 'take media'

   - [x] WPAndroid
   - [x] WPiOS

- After the upload is completed request the video's VideoPress URL from remote (by using the videopressGUID) and pass the VideoPress URL to the media upload update event. This is a url in this format: https://pinpin.blog/wp-content/uploads/2019/04/sample_video.mov

   - [x] WPAndroid
   - [x] WPiOS

**Comment by pinarol** [comment]
WPiOS PR: wordpress-mobile/WordPress-iOS#11454

**Comment by marecar3** [comment]
WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/9644
