### ISSUE TITLE
More block

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#859]
We have a working implementation, but split/merge doesn't work.

We need to decide if we use RichText, or fix #324 to add split/merge support to PlainText

**Comment by thehenrybyrd** [comment]
Had a request for the more block today in #2057785-zen
Looking forward to it! :)

**Comment by hypest** [comment]
Following up on a conversation over Slack, @iamthomasbishop has suggested that a shippable "v1" of the `more` block could be one that its "Read More" text is readonly. That is, we don't offer the ability to edit the message the block will display.

We could then iterate on that block to offer the full editable writing experience.

**Comment by rachelmcr** [comment]
> We could then iterate on that block to offer the full editable writing experience.

Are we tracking this as a planned second iteration somewhere? This came up while I was beta testing the `more` block today and I expect it will come up as a request from users once the block becomes available.

**Comment by iamthomasbishop** [comment]
I’m not 100% sure on the status of this, but another option – if we’re experiencing difficulties with the dynamic on-canvas input – could be to put a “label” setting in the block settings/inspector. On-canvas editing is probably preferred, but if this is any easier, it would be a fair middle-ground, imo.

**Comment by hypest** [comment]
Opened a follow up ticket: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1211
