### ISSUE TITLE
Image Block: add an option for changing the image size

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#877]
I expected to be able to change the image size settings but cannot.

Steps to reproduce:

1. Add an image block and add an image to it.
1. Open the image settings.
1. Look for a way to change the image size between Thumbnail, Medium, Large, Full Size.

**Result:** there is not an option to change the image size.

<img src="https://user-images.githubusercontent.com/1119271/56239974-7ef24400-604f-11e9-8f45-c64453b9ad25.png" height="480" alt="Screenshot_20190416-135605"> <img src="https://user-images.githubusercontent.com/1119271/56237700-dee5ec00-6049-11e9-9ae7-62856f07a76a.PNG" width="270" alt="IMG_2578">
<p style="clear:both;"><sup>Tested with WPAndroid alpha-164 (12.2 alpha) on Pixel 3 Android 9 and WP Internal 12.2.0.20190412 on iPhone 6S iOS 12.2.</sup></p>

Related past work: https://github.com/WordPress/gutenberg/pull/13728 reverted in https://github.com/WordPress/gutenberg/pull/13750.

<p style="clear:both;"><sub>(internal reference: p4a5px-2mW-p2)</sub></p>

**Comment by hypest** [comment]
Superseded and worked on in https://github.com/wordpress-mobile/gutenberg-mobile/issues/1329, closing this.
