### ISSUE TITLE
Caret / focus position when adding page break block

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#882]
When writing on a paragraph block, then inserting a page break, the page break block is selected but the caret is still blinking on the paragraph block.

Steps to reproduce:
1. start a new draft post on WPAndroid
2. start writing on a paragraph block
3. insert a page break
4. observe the selected block changes to the page break block, but the caret is still blinking on the paragraph block you were typing in.

**Comment by hypest** [comment]
Not happening for me on https://github.com/wordpress-mobile/WordPress-Android/commit/8f9af22f045d6863f16b30adff74d186fafeb812 with a Android 9.0 Pixel 2 XL. Closing and we can reopen if still happening.
