### ISSUE TITLE
Hitting return twice doesn't escape List block + create next one

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#899]
Scenario :

1. Create a list block
2. Insert text in the first row
3. Tap on Enter (the second row will be created)
4. Tap again on Enter

![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/28219092/56446120-c89c9200-62ce-11e9-8f4a-e00cca1c01ea.gif)

Result: Nothing will happen
Expected: List Block should be broken

**Comment by hypest** [comment]
Fixed with #928 .
