### ISSUE TITLE
Undo removes whole List Block

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#900]
Scenario :

1. Add a List block
2. Create few rows with content
3. Click on UNDO button

**Result**: All content will be removed
**Expected:** Only last added/changed row should be removed

**Comment by hypest** [comment]
Moving to next milestone.

**Comment by hypest** [comment]
Not seeing this happen on v1.8 (the least)... The list items are removing one by one on Undo. Closing but, feel free to open again if still occurring.
