### ISSUE TITLE
Remove duplicated imagepipe okhttp3 depdendency from RN gutenberg bridge

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#904]
As RN core already have  same `com.facebook.fresco:imagepipeline-okhttp3` dependency 

https://github.com/facebook/react-native/blob/758eb9fa7bba1d1a14fd8c8870e2a00ad3a31809/ReactAndroid/build.gradle#L316

There is no need to have it into `gutenberg-mobile` project.

**Comment by hypest** [comment]
Moving to next milestone.
