### ISSUE TITLE
Improve Screen Reader support for Separator block.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#910]
Currently it's not recognized by Screen Reader.

Selected and Unselected:
- Read block type.
- Read selection state.

Selected:
- Access toolbar buttons.

**Comment by koke** [comment]
Removing my assignment for now, as I'm not sure when I'll be able to pick it up

**Comment by etoledom** [comment]
Fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/937
