### ISSUE TITLE
Improve Screen Reader support for Block Picker.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#915]
- The buttons content can be more friendly. (i.e. "Paragraph block. Button")
- Needs to set the `button` role.
- Mention that the block picker is scrollable.
- Give a hint when the picker is presented (currently it says nothing).

The Bottom Sheet accessibility improvements are marked separately on #914

**Comment by etoledom** [comment]
Closed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/935

**Comment by etoledom** [comment]
Closed the wrong one by mistake 🙏

**Comment by SergioEstevao** [comment]
@etoledom is this still an issue on the current builds?

**Comment by etoledom** [comment]
@SergioEstevao - Yes, it's still an issue. And now we also have to mention that it is scrollable.

**Comment by SergioEstevao** [comment]
Thanks for checking @etoledom , will move to the new project.

**Comment by guarani** [comment]
> And now we also have to mention that it is scrollable.

Just noticed one edge case where the block picker isn't scrollable; when the inner paragraph block of a "Media & Text" block is focused, and you tap the (+) block insterter button. This opens the block picker with only 4 blocks (Paragraph/Heading/List/Button), so no scroll.

**Comment by etoledom** [comment]
> This opens the block picker with only 4 blocks (Paragraph/Heading/List/Button), so no scroll.

This sounds like expected behaviour to me.

If the bottom-sheet content is smaller than the maximum height, then we are disabling scroll to avoid unwanted bouncing. That's my understanding 🤔

**Comment by guarani** [comment]
That's right, I was just looking through this issue when I noticed this edge case and noted it down for future reference.
