### ISSUE TITLE
Improve AztecWrapper RN TalkBack support.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#918]
From https://github.com/wordpress-mobile/gutenberg-mobile/pull/916 we noticed that TalkBack on Android will focus on RichText without the need of activating it (with double tap).

This is contrary to what the Accessibility [documentation says on React-Native pages](https://facebook.github.io/react-native/docs/accessibility.html#accessible-ios-android), and it's different to how TextInput behaves.

The behavior expected from the Screen Reader is to select the item, and focus on it when the user double taps.

It's much appreciated if an Android expert could investigate this issue and help us find a solution.

https://cloudup.com/c-ROMCxSTX3

**Comment by SergioEstevao** [comment]
@mchowning can you give a look to see if this is still happening?

**Comment by mchowning** [comment]
I still see the behavior in the video where dragging your finger over paragraph blocks automatically focuses and makes the text editable, which I confirmed is different from the behavior of a plain `TextInput`. 

FWIW, if you swipe left and right to cycle between elements, then you do have to double-tap to edit the text. So it seems to be working properly with swiping left to right to cycle through selecting different items, but not when you drag your finger to select an item.
