### ISSUE TITLE
Editor crashes on merging blocks

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#921]
Steps to introduce:

Open the editor and change the content as:
```
<!-- wp:paragraph -->
<p><b>Hello</b> World!</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>part two</p>
<!-- /wp:paragraph -->
```

Switch to visual mode and try to merge 2 blocks
Following crash occurs:

```
Cannot read property 'multiline' of undefined

Array.MERGE_BLOCKS
    effects.js:93:62
Object.dispatch
    refx.js:37:38
Object.mergeBlocks
    index.js:191:32
ComponentWithDispatch.proxyDispatch
    index.js:94:4
BlockHolder._this.mergeBlocks
    block-holder.js:156:3
RichText.onBackspace
    index.native.js:332:3
RichText.proxiedMethod
    createPrototypeProxy.js:44:29
AztecView._this._onBackspace
    AztecView.js:72:4
Object.invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:93:9
invokeGuardedCallback
    ReactNativeRenderer-dev.js:318:30
```

**Comment by hypest** [comment]
This is an important issue and we'll continue working on it on the next milestone. In the meantime, for v1.4 we have "extracted" from Gutenberg the code that causes the breakage by using a branch off Gutenberg's `master` that doesn't include it. See  https://github.com/WordPress/gutenberg/pull/15399.

Bumping this to the next milestone.

**Comment by etoledom** [comment]
Fixed via :https://github.com/wordpress-mobile/gutenberg-mobile/pull/949 (🎉)
