### ISSUE TITLE
[Android] List Block - Incorrect cursor position when splitting list item after space

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#929]
When splitting a list item at a point where the cursor is preceded by one or more spaces, the cursor will be moved "forward" when positioned on the new list item line. The number of characters it is moved forward will be equal to the number of spaces that preceded the cursor when the list item was split. 

I believe this is occurring because [we do not update the caret position in `rich-text` when spaces will be trimmed by Aztec](https://github.com/WordPress/gutenberg/pull/15021).

![output](https://user-images.githubusercontent.com/4656348/56706421-ead54c00-66e2-11e9-8fab-d80135b0b367.gif)

⚠️ I do not have access to an iOS device, so I cannot verify whether this is an issue on iOS (seems unlikely though).

### Scenario 1
1. Create new List Block
2. Enter two words separated by a space ('one two')
3. Position the cursor at the beginning of the second word ('one |two'), so that there is **one** space preceding the cursor.
4. Press Enter
5. Observe that the cursor is positioned between the 1st and 2nd characters in the new list item ('t|wo'), instead of at the beginning.

### Scenario 2
1. Create new List Block
2. Type 3 letters, 4 spaces (the second space will create a period), and 3 more letters. ('abc.  
 def').
3. Position the cursor between the second and third space ('abc.  | def'), so that there are **two** spaces preceding the cursor.
4. Press Enter
5. Observe that the cursor is positioned between the 2nd and 3rd characters in the new list item ('de|f'), instead of at the beginning.

**Comment by iamthomasbishop** [comment]
I was also seeing this (or something similar) happen on the Android alpha, where if write a list of a few items, then go to any previous `li` and hit enter, the new `li` created includes the last character from the previous `li`. Noted here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/897

**Comment by hypest** [comment]
Fixed by #928 .
