### ISSUE TITLE
Post Title stay focused after new image block is added 

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#932]
**Steps to reproduce:** 

1. Enable Block Editor
2. Create new Post
3. Insert new Image block 

![ezgif com-video-to-gif (12)](https://user-images.githubusercontent.com/28219092/56781747-2f7be880-67b2-11e9-9775-2e2367e9f440.gif)

**Result:** Post title stay focused
**Expected:** Post title shouldn't be focused

cc: @hypest, @etoledom, @koke

**Comment by hypest** [comment]
Moving to next milestone.

**Comment by etoledom** [comment]
I was able to reproduce this issue on iOS too:

This seems to happen only for the very first block added to an empty post, when the block added doesn't autofocus.

That might give some clues.
