### ISSUE TITLE
Toolbar: Horizontal scroll persists when switching blocks

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#934]
When editing a block with more items in the toolbar than fit on the screen, the toolbar can be horizontally scrolled to see/select the items that are not visible. This scroll position does not reset, however, when switching back to another block that does not have so many toolbar items. This results in the leftmost toolbar items (add block, undo, redo) being off the left of the screen.

This was tested on Android with a Pixel 3. I am not able to test whether this is an issue on iOS.

![toolbar_scroll_1](https://user-images.githubusercontent.com/4656348/56808241-ff0e6b80-67fe-11e9-97f9-fbe3c4a427ef.png)

Arguably, this might be desired behavior when switching between two blocks of the same type (i.e., you select heading block #1, scroll the toolbar all the way to the left, then select heading block #2, and the toolbar buttons stay in the same position), but it seems like a clear bug in a case like this where the toolbar items are so different.

## Steps to Reproduce
1. Open demo app
2. Select a heading (such as "What is Gutenberg?")
3. Scroll toolbar to the left so that the strikethrough icon is visible on the right.
4. Select a paragraph block (such as "Hello World!")
5. Observe that the toolbar is scrolled to the left and the left-most icons are off the left of the screen.
6. Tap a toolbar item and the toolbar's scroll position will snap back so that the add block button is now visible on the left.

![output](https://user-images.githubusercontent.com/4656348/56808035-87404100-67fe-11e9-8632-63de0caccaec.gif)

**Comment by mchowning** [comment]
Upon further testing, it appears this is only an issue on Android.

**Comment by hypest** [comment]
Not sure if you're actively working on this one @mchowning , if so, better to move the ticket to the "In Progress" column in the project board, otherwise let's un-assign the ticket. Thanks!

**Comment by mchowning** [comment]
Moved to "In Progress"
