### ISSUE TITLE
Fix our i18n process

### ISSUE THREAD

**Issue by Tug** [wordpress-mobile/gutenberg-mobile#939]
Internationalization is broken since Gutenberg moved away from [`babel-plugin-makepot`](https://github.com/WordPress/gutenberg/tree/master/packages/babel-plugin-makepot). 

Indeed, build files for each packages in gutenberg is now used as input for glotpress to generate pot files. This means our assumption that mobile native strings in the gutenberg repository will be picked up automatically was wrong.

We need to fix this and either:
1. have gutenberg include our strings 
2. include those in our `gutenberg-mobile.pot`.

Solution 2. is probably more realistic as it will induce less friction with the WordPress core and Gutenberg projects but will bring us one step back in terms of automating translations for gutenberg-mobile.

See related discussions:
https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/
https://make.wordpress.org/core/2018/05/01/javascript-internationalization-the-missing-pieces/
https://wordpress.slack.com/archives/C04KRK0KA/p1525791742000720
https://meta.trac.wordpress.org/ticket/3876

**Comment by swissspidy** [comment]
Let me know if I can help with the i18n part in Gutenberg, WordPress core, or WordPress.org.

**Comment by hypest** [comment]
Not sure if you're actively working on this one @Tug , if so, better to move the ticket to the "In Progress" column in the project board, otherwise let's un-assign the ticket. Thanks!

**Comment by Tug** [comment]
👍 Unassigned
