### ISSUE TITLE
Simplify media insertion flow

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#946]
## Problem

As of right now, the process of adding an image block (and soon additional types of media) is a bit cumbersome. I'd like to make improvements to the media selection part of the flow, but for now at very least we can simplify by skipping the placeholder step or combining it with the location options sheet.

_Note: I'm not sure if any additional design is needed, but if so I can pull together a blueprint._

## Current Flow

![image](https://user-images.githubusercontent.com/1200432/57026490-990b5500-6bff-11e9-9df5-5981fc739da7.jpeg)

1. Tap `(+)` (inserter) – this shows the Block Library sheet
2. Tap `Image` to add Image block placeholder to canvas
3. Tap on block placeholder to trigger sheet
4. Tap on an option to choose location
5. Select image to upload
6. Image gets added to canvas, uploads, succeeds/fails

## Proposed Flow

![image](https://user-images.githubusercontent.com/1200432/57026509-a1639000-6bff-11e9-8f42-3d9b294643f9.jpeg)

1. Tap `(+)` (inserter) – this shows the Block Library sheet
2. Tap `Image` to add Image block placeholder to canvas –  _trigger media location sheet_. _Note: the placeholder could still display on the canvas, behind the sheet_, and be dismissed if the user backs out of the process by tapping `Cancel`.
3. Choose location
4. Select image
5. Image added to canvas, uploads, succeeds/fails

## Note on Future Improvements

I'd like to replace the location-choosing sheet with an improved media selection sheet, similar to Aztec – but for now, let's at least make this improvement as it will benefit some of the next blocks we're building (Video, for example).

**Comment by hypest** [comment]
> Note: the placeholder could still display on the canvas, behind the sheet, and be dismissed if the user backs out of the process by tapping Cancel.

I'd add that if we indeed leave the placeholder be visible (behind the sheet) then we should probably avoid adding it to the undo history. So, in case user cancels the insertion and hits "Undo" afterwards it wouldn't cause the block to re-appear.

While at it though, can we perhaps envision cases where the user would intentionally want to leave the block in its placeholder state? Say, something like preparing a post/page or template and setting some image wouldn't be desirable? Perhaps we can add a "Leave empty" option to the media options sheet to cater for that?

**Comment by iamthomasbishop** [comment]
> I'd add that if we indeed leave the placeholder be visible (behind the sheet) then we should probably avoid adding it to the undo history. So, in case user cancels the insertion and hits "Undo" afterwards it wouldn't cause the block to re-appear.

@hypest I agree w/ this. If I exit the insertion mid-flow, it'd essentially clear the block and roll back to right before I tapped to add the block. 

There might be a case where the user wants to leave the media clear and come back to it later, especially if we ever allow the user to save a post/page as a custom template/layout, but we might want to think of it from the other side -- we could treat it similarly to the Cover block, where you can "clear" an applied background image. In other words, we would shorten the flow for insertion as described in this ticket, but we could also allow the user to "clear media" in addition to the existing options to "edit" and "replace". 

Here's the cover block for example:

| **With media** | **Media cleared** |
| --------------- | --------------- |
| <a href="https://user-images.githubusercontent.com/1200432/90437913-c7cd6900-e098-11ea-9677-df431efceb07.jpeg"><img src="https://user-images.githubusercontent.com/1200432/90437913-c7cd6900-e098-11ea-9677-df431efceb07.jpeg" width="375"></a> | <a href="https://user-images.githubusercontent.com/1200432/90437927-d1ef6780-e098-11ea-9c8b-86bf2f3495d3.jpeg"><img src="https://user-images.githubusercontent.com/1200432/90437927-d1ef6780-e098-11ea-9c8b-86bf2f3495d3.jpeg" width="375"></a> |
