### ISSUE TITLE
List shows an empty editable extra line

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#954]
Tested on WPiOS with 1.4: https://github.com/wordpress-mobile/WordPress-iOS/pull/11628

1. Add a list
2. Notice there's an extra line at the bottom
3. If you tap on it you can write

![RPReplay_Final1556894057](https://user-images.githubusercontent.com/8739/57144701-e800e800-6dc1-11e9-83f0-43c25d3952df.gif)

The resulting HTML:

```html
<!-- wp:list -->
<ul><li>One</li><li>Two</li></ul><p>what</p></ul>
<!-- /wp:list -->
```

cc @SergioEstevao

**Comment by SergioEstevao** [comment]
So I investigated this issue and the reason we have this extra line is that the LayoutManager in iOS doesn't draw a line unless there is a character on it, so for us to have a bullet on an empty list we need to add an extra character to make it visible.
While in the Aztec editor wasn't an issue, on the blocks where each block is a separate Aztec TextView we will end up seeing a lot of empty line at the end of the list blocks.

**Comment by koke** [comment]
👏 👏 👏 Thanks for figuring out this one, it was really bugging me 😁
