### ISSUE TITLE
Splitting a list block sets the wrong list type

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#955]
Tested on WPiOS with 1.4: wordpress-mobile/WordPress-iOS#11628

1. Add an ordered list and write several items
2. Put the cursor in the middle of it and press enter twice
3. The list is split, but the second half is a bullet list instead of numbered

![RPReplay_Final1556895413](https://user-images.githubusercontent.com/8739/57146054-bd645e80-6dc4-11e9-96b7-4dee3740c601.gif)

**Comment by etoledom** [comment]
Tested this again and it seems to be working well now.
