### ISSUE TITLE
Undoing a list split removes the content

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#956]
Tested on WPiOS with 1.4: wordpress-mobile/WordPress-iOS#11628

1. Create a list
2. Type a few items
3. Put the cursor in the middle and press return twice to split the list
4. Tap undo

Instead of reverting to the previous list, the split content disappears

![RPReplay_Final1556895683](https://user-images.githubusercontent.com/8739/57146809-7ecfa380-6dc6-11e9-94e0-3bb35b59df5e.gif)

**Comment by koke** [comment]
Possibly related to #900. There's definitely something odd going on with lists and undo. It's hard to describe but try to undo/redo as far back as you can, and at some point part of the history is lost

**Comment by etoledom** [comment]
I was able to reproduce this same bug on web.

![split_and_undo](https://user-images.githubusercontent.com/9772967/57151084-58166a80-6dd0-11e9-84de-c8e3f2ae55dc.gif)

**Comment by koke** [comment]
I think this is https://github.com/WordPress/gutenberg/issues/8882, being worked on in https://github.com/WordPress/gutenberg/pull/14765. Closing in favor of that one.
