### ISSUE TITLE
Poster and Video being displayed at same time

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#965]
Currently, react-native-video has a bug about the poster, if you set a poster url then this happens: react-native-community/react-native-video#1509

**Comment by hypest** [comment]
Seems [fixed upstream](https://github.com/react-native-community/react-native-video/issues/1509#issuecomment-504644832) and we should update our fork to include the fix.

**Comment by SergioEstevao** [comment]
@marecar3 are you still seeing this? Or the updates to react-native-video fixed the issue?

**Comment by marecar3** [comment]
> @marecar3 are you still seeing this? Or the updates to react-native-video fixed the issue?

Hey 👋 @SergioEstevao, thanks for asking. 
I am not 100% sure but I think that we are not using poster in our case.

**Comment by jhnstn** [comment]
Adding a poster is not currently an option in Gutenberg Mobile. Gutenberg Calypso allows adding a poster to the video block but I was unable to verify if that might cause an issue due to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152
