### ISSUE TITLE
Video block - UI/UX Enhancements

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#966]
This issue is opened to track @iamthomasbishop 's comments on [this PR:](https://github.com/wordpress-mobile/gutenberg-mobile/pull/854)

https://github.com/wordpress-mobile/gutenberg-mobile/pull/854#issuecomment-490546887
https://github.com/wordpress-mobile/gutenberg-mobile/pull/854#issuecomment-490624053

@marecar3 has already started to work on these and we believe it'd be easier to track on a separate issue/PR. 

Please note that Video block won't be available publicly even if we merge https://github.com/wordpress-mobile/gutenberg-mobile/pull/854, there's a code piece on the PR that prevents that(similar to code block). We'll be doing these enhancements along with other bug fixes before making video block publicly available. 

- [x] Media blocks are difficult to select
- [x] Error state design differences
- [x] Uploading state design differences

I added new items here to address the rest https://github.com/wordpress-mobile/gutenberg-mobile/issues/687#issuecomment-482011555

**Comment by marecar3** [comment]
Thanks @pinarol! :)
