### ISSUE TITLE
Add GIF badge to GIFs in editor

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#968]
In Aztec, we showed a [GIF] badge over the top of .gif's – let's add that, and in the process set ourselves up for future badge re-use :)

Here's what it looks like on a variety of backdrops:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/1200432/57489545-f183c780-727b-11e9-96f2-ed1b4d1a9c8e.png">

## Specs:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/1200432/57489286-23485e80-727b-11e9-8871-95ac69c32119.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/1200432/57489308-39eeb580-727b-11e9-97f1-fe3cb8008066.png">

* **Positioning:** 10px from top left corner
* **Background color:** `#1A1A1A` 50% alpha
* **Border-radius:** 6px
* **Internal Padding:** 3px 6px
* **Font-family:** Sans-serif
* **Font-size:** 14px
* **Font-weight:** Semi-bold
* **Text-transform:** Uppercase
* **Background Blur (iOS):** 5pt

**Comment by kmdupr33** [comment]
Linking [updated styles](https://zeroheight.com/226850145/p/11878e/b/793b21/i/6492732) that @iamthomasbishop linked to in #gutenberg-mobile.

**Comment by SergioEstevao** [comment]
@iamthomasbishop I just implemented animated GIFs for the GB editor on the WPiOS app: https://github.com/wordpress-mobile/WordPress-iOS/pull/14238

On Android the GIF already plays while on the GB editor.

Do you think we still need the GIF badge if the editor plays the animation?

**Comment by iamthomasbishop** [comment]
> Do you think we still need the GIF badge if the editor plays the animation?

@SergioEstevao Yea, I think the badge should always be displayed, even while it's animated.

**Comment by hypest** [comment]
Looks like the badge is not displaying in various cases of the Gallery Block or a Media&Text block so, reopening this ticket to track.

**Comment by thehenrybyrd** [comment]
Related, we have this older issue for Image Gallery: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1715

**Comment by hypest** [comment]
👋 @illusaen , since you recently worked on adding the GIF badge, can you have another look to see how to have all types of image blocks display it? Thanks!
