### ISSUE TITLE
 Failed upload image state missing after reopening the post

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#978]
### Steps to reproduce the behavior
1. Open the app
2. Enable block editor - gutenberg
3. Create a new post
4. Start upload image from device
5. Turn on AirPlane mode during the upload
6. Publish the post
7. Open Post List -> you will see that it's marked as failed upload
8. Open the post

### Expected behavior

The post should show the image and retry upload button

### Actual behavior

The post shows only the image without an option to re-upload it.

**Web look:** 
<img width="912" alt="Screen Shot 2019-05-13 at 12 13 31 PM" src="https://user-images.githubusercontent.com/28219092/57637624-e5e51900-7579-11e9-8454-14ca0075eaef.png">

**iOS app - Post List**

![image1-1](https://user-images.githubusercontent.com/28219092/57637851-686dd880-757a-11e9-84f8-eb859b3ef531.png)

**iOS app - Post**

![image2](https://user-images.githubusercontent.com/28219092/57637875-7b80a880-757a-11e9-8aae-5dd4d876db2c.png)

**Android :** 

![android](https://user-images.githubusercontent.com/28219092/57639997-488ce380-757f-11e9-9aa4-27e6e93cdd10.png)

**Comment by SergioEstevao** [comment]
Tested this on iOS with the current release version 14.8 and it now shows a retry placeholder on the image that can be pressed to resume the upload.
