### ISSUE TITLE
Items within the add new block modal can be slight shifted if label is long

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#984]
Items within the add new block modal can be slight shifted (see the last row in the picture below) if the label is too long. 

![device-2019-05-16-103504](https://user-images.githubusercontent.com/518232/57839767-9136dd80-77c7-11e9-81c7-b0da0b032c93.png)

**Comment by SergioEstevao** [comment]
This is now solved, the name can break to a second line and the alignment of the icon is kept.
