### ISSUE TITLE
Add description/title to Image selection sheets

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#986]
This won't be as big of an issue when we change the `pencil` (replace) icon eventually, but in the meantime, we should add some descriptive titles to the top of the bottom sheet, for some added clarity in the flow.

Replacing an Image:

<img width="2271" alt="image" src="https://user-images.githubusercontent.com/1200432/57861828-efaa8e80-77bc-11e9-84b0-7827bbed2295.png">

For each platform, I'm hoping we can:

* iOS: add as a top row description to the ActionSheet
* Android: add it as a standard list item – text label color is `$gray-darken-10` instead of `$gray-dark`

This could also apply to initial image selection:

<img width="2296" alt="image" src="https://user-images.githubusercontent.com/1200432/57861762-d1dd2980-77bc-11e9-9a73-d38af03ca6d9.png">

**Comment by hypest** [comment]
Removing the milestone marker since we nowadays only add PRs to milestones.

**Comment by SergioEstevao** [comment]
@iamthomasbishop do you think the new icon for replacing image is enough? Or do you think we still need to add the extra information on the top of the action sheets?

**Comment by iamthomasbishop** [comment]
We should probably have a description at the top of the sheet, as I don’t think the icon is always sufficiently clear.
