### ISSUE TITLE
Remove extra inner padding on text blocks

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#992]
Since we last solved these issues looks like there might have been a regression in one of the last releases. There is some extra padding applied inside the body of text blocks (paragraph, heading, etc). It's slightly different between platforms:

## iOS

There appears to be a slight bit of additional **left/right** padding. It's hard to tell if there's also extra padding on top/bottom edges of the blocks, so we should double check. Same thing applied to the title (only on iOS).

![57C57374-7663-41BD-A8BE-C42B558C371A](https://user-images.githubusercontent.com/1200432/57902415-a72bb900-782e-11e9-9419-afce359b4d65.jpeg)

## Android

It looks like extra **top/bottom** padding, but left/right looks aligned properly.

(Note: title block looks to have proper padding.)

![681D53FD-67D9-4486-AC30-6F1AD68F289F](https://user-images.githubusercontent.com/1200432/57903062-ead3f200-7831-11e9-89a6-546abf2030a3.jpeg)
![060C26AF-EDB5-4240-80BF-26C73DBED080](https://user-images.githubusercontent.com/1200432/57903063-ead3f200-7831-11e9-8281-85909fe06533.jpeg)

## Note

All blocks have inner padding of **12 top/bottom, 16 left/right**, so the total vertical spacing between blocks is always 24.

**Comment by koke** [comment]
Removed the 1.5 milestone, let's only use milestones for PRs

**Comment by iamthomasbishop** [comment]
Sounds good, apologies!

**Comment by maxme** [comment]
On Android, I did a quick sanity check - loaded the a test post with the block editor in the Layout inspector. Then I took a screenshot with Material Grid and added the layout inspector over it. Here is the result of this:

<img width="651" alt="Screenshot 2019-11-08 at 13 48 50" src="https://user-images.githubusercontent.com/40213/68477835-b49a8c80-022e-11ea-8709-c843cbed1e18.png">

From this screen shot:
- It looks like we have a margin on each block.
- And some padding on each text "area" (title / heading / paragraph).
- The block toolbar (up / down - trash buttons) height looks good.

I think that removing the padding on text area would fix this problem on Android. I'll investigate more to check where this is coming from (RichText component? Aztec? glue code?).

**Comment by koke** [comment]
There might be some related changes in #1379, or at least I was discussing block margins there yesterday

**Comment by maxme** [comment]
Note: I found a source of extra padding in the example app, I was able to remove it, but apparently there is a different issue in the wpandroid integration.

![out](https://user-images.githubusercontent.com/40213/68482554-1f9d9080-023a-11ea-9b07-0fbfcb53163e.png)

**Comment by maxme** [comment]
By setting adding `aztecText.setPadding(0, 0, 0, 0);` in the `ReactAztecManager.createViewInstance()` call, I'm able to remove the padding on RichText in wpandroid integration:

<img width="567" alt="Screenshot 2019-11-08 at 15 24 31" src="https://user-images.githubusercontent.com/40213/68483603-2927f800-023c-11ea-83e1-92bf6f4541bd.png">

But for some reason when using bigger font in a RichText (see the heading block in this screen shot) there is some extra vertical white space which is not a padding. See here:

<img width="893" alt="Screenshot 2019-11-08 at 15 25 10" src="https://user-images.githubusercontent.com/40213/68483871-963b8d80-023c-11ea-9499-516098c14ce1.png">


Note: I also checked the `ReactAztecText` wasn't wrapped in another padded view.

**Comment by maxme** [comment]
This extra vertical white space is probably coming from heading rendering code in Aztec. For reference here is the screenshot of the Aztec version of this post. 

![Screenshot_1573223538](https://user-images.githubusercontent.com/40213/68484205-1feb5b00-023d-11ea-9e3a-2ce2cb01e04d.png)

**Comment by maxme** [comment]
I confirm the heading issue must be fixed on the Aztec side. It's currently not parametrized, but it can be. I'll update Aztec, do a new release and then update the PR here.

![out](https://user-images.githubusercontent.com/40213/68489476-765d9700-0247-11ea-965e-d672e787fac1.png)

(I removed the vertical space in the "after" screenshot)

**Comment by iamthomasbishop** [comment]
Interesting notes above. @maxme. Do you know what the line-heights are set to for headings? I wonder if that has something to do with the additional optical spacing. For example, here's what the measurements of a Heading 2 block look like (22px font-size 28px line-height:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/1200432/68618549-35f05a00-048f-11ea-8707-10af61a18c46.png">

For reference, here is the type scale I'm following (`font-size`/`line-height`):

* H1: 24/32 (~1.33)
* H2: 22/28 (~1.27)
* H3: 20/26 (1.3)
* H4: 18/22 (~1.22)
* H5: 16/20 (1.25)
* H6: 14/18 (~1.29)
* Paragraph: 16/24 (1.5)

If we need to, we can define a standard formula/ratio and stick to it. FWIW, I propsed a refinment to the base (paragraph) alignment, but the headings need to be a little bit tighter, so they could be set to something between to 1.2 or 1.4. IIRC, there is also a difference in how Android and iOS handle line-height equivalents, so I wonder if we might need to define this differently for each platform.

Inspecting core GB, it looks like some headings use a line-height of 1.8 and some use 1.4 – not sure if they're following a scale or not.

**Comment by maxme** [comment]
> Do you know what the line-heights are set to for headings? I wonder if that has something to do with the additional optical spacing

The [line-height implementation](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/widget/TextView.java#L5659-L5682) is defined in the Android `TextView` (we use it as the base class for Aztec). And we set these values [here](https://github.com/wordpress-mobile/AztecEditor-Android/blob/94afefaaa8b0687a19b049a4f46d610585e4a7df/aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt#L369-L378) for all text in an Aztec instance. 

We could change that for each block but I'm not sure that's what you want (line-height and block padding are different things. `line-height` is the parameter that drives the vertical space between 2 lines when a long heading line is wrapped). 

I'll take screenshots with long lines after updating the headings padding in Aztec and check if that's what we want.

**Comment by hypest** [comment]
This ticket looks closed by @mchowning but I only see Android side work on it. Aren't there still some iOS side adjustments that are pending?

**Comment by iamthomasbishop** [comment]
@hypest Looking at the latest internal beta, we seem mostly good on iOS, except the title seems to suffer the same issue that I mentioned above.

<a href="https://user-images.githubusercontent.com/1200432/76649620-177a9800-652f-11ea-8c43-10787c69fce0.jpeg"><img src="https://user-images.githubusercontent.com/1200432/76649620-177a9800-652f-11ea-8c43-10787c69fce0.jpeg" width="375"></a>

Also realized that the Separator block also isn't quite wide enough ([screenshot](https://cloudup.com/cBtSgLzZ5zt)), so I'll report that separately.

**Comment by etoledom** [comment]
I also created a ticket for the Post Title issue on iOS to keep this one closed.

**Comment by maxme** [comment]
> Aren't there still some iOS side adjustments that are pending?

I'm pretty sure @SergioEstevao made some adjustments on the iOS side, I couldn't find the PR though.
