### ISSUE TITLE
Change image/video caption placeholder text color to $gray

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#996]
The current placeholder text color on captions is using a desaturated gray color – which is different from the other instances (paragraph/heading/list placeholder text). Let's update that to align w/ the other instances, which I believe is `$gray`.

(This issue applies to both Android and iOS, IIRC)

Note: we'll be updating to a new color palette in the near future, but we don't yet have that work slated, so let's do this in the meantime.

Related: https://github.com/wordpress-mobile/gutenberg-mobile/issues/549

**Comment by maxme** [comment]
I guess this was fixed already. The color for image caption placeholder `Write caption...` is already `gray: 87a6bc` (like in the heading placeholder).

**Comment by iamthomasbishop** [comment]
I think you're right about the Image block placeholder text, so maybe this issue is out-of-date and it's just the video text label color. On the latest internal beta, it looks like the Video block is using a neutral gray. Here's a side-by-side of what I"m seeing, for reference:

![caption-color](https://user-images.githubusercontent.com/1200432/61636581-ea0d7100-ac63-11e9-9a2b-d58150d854cd.jpg)

**Comment by maxme** [comment]
Ah! I haven't tested on video, thought it was the same code 🤦‍♂ - I'll fix that, thanks for pointing it.

**Comment by iamthomasbishop** [comment]
Maybe it should be 😄 Thank YOU for fixing this!
